---
lang: es
format: 
  html:
    page-layout: article
---
# La huella del 21 de febrero {.unnumbered}
---

A las tres fuerzas que erosionan la gobernabilidad, identificadas en el análisis de diciembre de 2015 [^1], se agrega ahora el notable debilitamiento de la convocatoria y la credibilidad gubernamental, objetivado en su derrota del 21 de febrero.

Este descenso es producto de la interminable seguidilla de hallazgos que indican o prueban una constante falta de honradez en el desempeño de la administración del país, que van desde la falta de veracidad de los altos funcionarios, incluyendo al presidente, hasta la opacidad y las dudas que provocan mil millonarias contrataciones directas para la ejecución de obras públicas.

El último referendo constitucional, realizado por iniciativa y decisión exclusiva del MAS, establece una marca imborrable que influirá decisivamente en los acontecimientos, lo que obliga a quienes se interesan por el quehacer social y político del país a esforzarse para descifrar sus resultados y las tendencias que abre.

## El certamen de la corrupción 

Durante el primer cuatrimestre del año casi había dejado de hablarse del gran desastre ocasionado en el Fondo campesino por su directorio de dirigentes y los ministerios representados en esa instancia. Mientras que las noticias que tenían origen en los desmanes y desfalcos en esa institución financiera ocuparon por aproximadamente un semestre los titulares noticiosos en 2015, este año han pasado a segundo plano, si es que sencillamente no se han borrado, opacadas por las novedades relacionadas con los negocios que se entrevén alrededor de una cantidad todavía desconocida de contrataciones directas (sin licitación) ejecutadas por las autoridades [^2].

Es probable que la situación no hubiera alcanzado tal intensidad si Morales Ayma no aparecía en el centro del entramado, a partir de la denuncia que lo vinculó con la gerente de una de las compañías chinas beneficiadas con la adjudicación de contratos directos para ejecutar algunas grandes obras públicas.

El foco informativo se ha trasladado a este escándalo, al que se culpa de haber causado la derrota de la reforma constitucional que debía abrir paso a una nueva reelección de los dos primeros mandatarios en 2019.

Predomina actualmente en el tratamiento noticioso el enfoque sobre la relación sentimental y familiar de los involucrados, giro que también seduce a la oposición política [^3]. Sin embargo, paulatinamente ha empezado a abrirse espacio el tema de las cantidades y modalidades en que se ha adjudicado la mayor parte de obras públicas a cargo del gobierno central.

De todas maneras, se ha instalado como una corriente de opinión en pleno desarrollo la idea de que la corrupción a gran escala y profundamente arraigada en el conjunto de la administración estatal forma parte existencial del régimen. La suma de denuncias previas, incluyendo redes de extorsión, contrataciones sobrevaluadas y fallidas, negocios en empresas estatales y un largo etcétera, se han condensado en estas semanas y adquieren una nueva fuerza y significado luego de que la estrategia para la reelección se estrellara contra la determinación democrática de los electores.

A diferencia de lo que ocurría antes, los últimos hechos quiebran la invulnerabilidad gubernamental y la del presidente. Son permanentes las denuncias de que el poder público se utiliza en favor de intereses grupales e individuales, continua y metódicamente, reforzando la percepción no solo de problemas que se multiplican, sino de que se está en una fase de descomposición.

## El aguinaldo no alcanzó 

Entre las medidas con que el frente oficial se preparó para ganar o ganar el referendo plebiscitario que montó para el segundo mes de este año, tenía un puesto muy destacado el pago del aguinaldo adicional al que obliga la ley cuando el crecimiento del producto interno nacional supera el 4,5%.

La administración estuvo insistiendo en que durante la gestión 2015 se habría superado un crecimiento del 5% del PIB, pero el reciente 4 de mayo publicó la información de que se habría alcanzado el 4,83%, en contraste con las cifras de organismos internacionales [^4], que se quedan en 4,3 o 4,4%. Para esta gestión se pronostican cifras parecidas.

Las décimas de diferencia con la gestión pasada tenían durante la campaña un significado mucho más grande que el pago o no del segundo aguinaldo; con ellas se dilucidaba si se mantenía (o caía) el prestigio de la gestión económica, en los términos y alcances definidos por el gobierno nacional [^5].

Los mensajes que predominaron en la campaña se aparcaron en el espacio de transmitir confianza en lo conocido, ratificando que los dos principales mandatarios constituían una carta de garantía para mantener el consumo y los niveles de bienestar y para asegurar una nueva década de enormes inversiones, obras públicas y planes de avanzar, desde una presunta condición de “nueva potencia regional”. Esto hacía indispensable mantener la idea de que se superaría el 5% de crecimiento [^6].

El aguinaldo adicional por sí mismo, aunque solo se brinda a la minoritaria porción de asalariados “formales” [^7] (es decir, debidamente registrados en las estadísticas oficiales y usufructuarios de los beneficios sociales legales), tiene un alto valor simbólico y político porque representa el viraje con el que los gobernantes se aproximaron en 2014 a este sector, que tiene una elevada capacidad de movilización social en las ciudades. Así sellaron el pacto que mantienen con la principal organización que aglutina a los entes federativos y gremiales que los representan: la COB.

En su momento, esa medida, sumada a la política de incrementos salariales y aumento del nivel del salario mínimo, resolvió un creciente alejamiento de los asalariados, que pueden considerarse hoy una especie de columna central de las clases medias urbanas, tanto las tradicionales como las denominadas nuevas o “vulnerables” [^8]. Analistas gubernamentales, y no solo ellos, consideran que la recuperación de terreno perdido por el MAS y su gobierno con esa franja social hasta 2014 se dio gracias a incrementos salariales y al doble aguinaldo, consolidando su gran victoria electoral de ese año.

De allí que, a pesar de haberlo impuesto contra toda resistencia el año pasado —lo que no impidió que perdiera 700.000 votos el 21 febrero [^9] respecto a la votación de 17 meses antes— su derrota causa una confusión tan grande en el oficialismo, que hasta ahora no termina de hilar una explicación única y verosímil de los acontecimientos [^10].

Dicha confusión empezó a expresarse con la idea de “empate técnico”, planteada la misma noche en que se dio a conocer el resultado final con tres puntos de ventaja para el No, y prosigue hasta hoy por un carril que retorna continuamente al supuesto de que el fracaso se debería a un engaño (“del imperio”, “de la derecha”). Esto deja margen a buscar una revancha, una “segunda vuelta” o un “segundo tiempo”, en palabras del presidente, su séquito y la mayoría de dirigentes nucleados en la CONALCAM, quienes, coincidentemente, enfrentan problemas actuales o lo harán en perspectiva cuando avancen las hasta ahora muy lentas o detenidas investigaciones sobre los desfalcos del FONDIOC [^11].

## Lo duradero y lo transitorio

Lo que puede ser más difícil al organizar una información que ayude a hacer inteligibles las causas de lo ocurrido es discriminar y jerarquizar los factores que lo condicionaron, especialmente entre los más profundos, prolongados y gravitantes y los menos. Si se toma a los medios masivos de difusión como guía, muy posiblemente terminaremos convencidos de que el affaire con la novia presidencial, la existencia del hijo y, tal vez, las víctimas del incendio de la alcaldía alteña serían los que inclinaron la balanza.

Un examen más detenido probablemente lleve a otras conclusiones, si se toma en cuenta que, a pesar del trágico balance de seis víctimas mortales, el apoyo a la reelección se impuso en El Alto [^12]. Si a esto se añade el comportamiento marcadamente práctico que rige la lógica del voto en nuestro país, y se suma el enfoque conservador del mensaje oficial (“votar por lo bueno conocido”), la importancia de factores menos mencionados en las noticias, pero más constantes y hondos en la experiencia social, cobra mayor significado.

Así, la desaceleración económica, que impacta sobre la oferta laboral y el precio de los jornales en actividades muy sensibles a la velocidad de rotación del capital (como la construcción) y, con igual rango de importancia —como lo reconoce el vicepresidente en una de sus entrevistas—la desconfianza frente a la permanencia demasiado prolongada de un partido en el control del gobierno y el Estado [^13], junto con la creciente percepción y sensibilidad ante la corrupción, son probablemente las principales causas de la victoria del No.

El affaire con la novia tiene ingredientes sociales y políticos fuertes (súbita conciencia de la presencia china y su creciente peso, alerta inicial sobre la discrecionalidad en la firma de contratos y concesión de grandes obras), pero dichos elementos comienzan recién, lenta y dificultosamente, a abrirse paso. En tanto, la faceta de culebrón e intriga ha estado en primer plano noticioso; sin embargo, son dudosos sus efectos electorales, si se considera el contexto machista, patriarcal y demasiado permisivo ante la omisión de obligaciones familiares [^14] que prima en nuestro medio.

## Recetas para salir del atolladero

Existen, pues, razones para dudar de que los temas privilegiados por los medios y por las redes sociales virtuales hayan alcanzado el rango que privilegia su tratamiento noticioso, Sin embargo, está fuera de discusión que han golpeado frontalmente el aplomo y la capacidad de respuesta e iniciativa que caracteriza a los gobernantes.

Sin ofuscarse tanto como lo ha hecho la diplomacia chilena ante la causa entablada por nuestro país en la Haya, el conjunto de voceros, mensajeros y mensajes oficiales ha perdido la velocidad y contundencia de otros trances. Desde el principal dirigente, pasando por “su secretario” (que es como el jefe de Estado califica al vicepresidente), hasta el último de los ministros, parlamentarios, gerentes y otros que han salido al ruedo en calidad de garantes de la buena conducta e intenciones del presidente, han quedado en situación muy precaria ante el público si se los compara con otras situaciones de emergencia [^15].

Después de todos los balances sobre los resultados del 21 de febrero y de la emergencia comunicativa que trajo el affaire Zapata, el vicepresidente resume una fórmula muy comprimida para remontar el contraste: “Si logramos mantener el crecimiento económico e industrializarnos; si logramos convertirnos en centro energético; y [si seguimos] reduciendo la desigualdad y ampliando la ciudadanía económica para las personas, estaremos en mejores condiciones para afrontar la campaña de 2019” [^16].

Aunque la fórmula parece sencilla, no lo es, como se verá a continuación; es más, puede resultar simplista porque desatiende varias aristas, problemas y fuerzas que se encuentran en plena evolución.

Su primera y mayor debilidad es que reduce todo al plano económico, cuya importancia es enorme, pero definitivamente insuficiente para comprender la realidad en su conjunto. Al final de cuentas, aunque el vice lo olvide, el MAS ganó la primera elección por la esperanza colectiva en transformaciones y no por estímulos económicos.

Y, según avanzan las cosas, son cuestiones políticas, morales, de anhelos y expectativas las que se le está enredando y las que podrían pesar más en su declive, junto al indudable y creciente deterioro que vive nuestra economía a partir del viraje negativo de los precios de las materias primas en el mercado mundial.

Pero, comenzando por el riesgo de un sesgo simplista en el análisis de las autoridades, los planes oficiales para llenar el hueco producido por la caída del precio de exportaciones, con préstamos de la China (entre 7.500 a 10.000 millones de dólares) y el uso de reservas para mantener un plan de inversiones públicas masivas, puede efectivamente funcionar en el corto plazo. Pero si se prolonga la brecha entre el promedio de 10 dólares que se estuvo cobrando por el millón de BTU y los 2,5 que se obtienen ahora, ni siquiera las fuentes extraordinarias serán suficientes; mucho menos si una parte de los recursos se desvían a bolsillos de intermediarios y comisionistas.

La segunda parte del plan oficial consiste en sostener una masiva inversión pública, aplicada a infraestructura y, principalmente, al campo energético, con una inversión de unos 32.000 millones de dólares hasta 2025 para sostener las reservas de hidrocarburos y llegar a generar unos 8.300 MW, que se exportarían en su mayor parte. Pero hay muchas dudas respeto al éxito que pudiera tener lo que los expertos caracterizan unánimemente como un insuficiente y tardío esfuerzo exploratorio.

En cuanto al proyecto de exportar electricidad, los mercados argentino y brasileño pueden absorber fácilmente nuestra oferta, pero el financiamiento presenta grandes interrogantes, mucho más si la recuperación del precio de nuestros actuales productos de exportación es lento o vacilante. Adicionalmente, la construcción de grandes represas implica desafíos ambientales (y respuestas sociales); para responder a ellas se necesita de confianza, convocatoria y credibilidad política, que se están desmoronando. Pero antes, es un serio problema construir nuevas termoeléctricas cuando no se garantizan las reservas de gas para hacerlas arrancar y mantenerlas en funcionamiento.

Antes de poder alcanzar esa gran conversión de nuestras exportaciones, están los muy gelatinosos resultados de inversiones ya realizadas, como las de las plantas separadoras de gases y la de urea y la proyectada de polipropileno, que traen más preguntas que respuestas, principalmente respecto al mercado internacional y, nuevamente, al costo de las plantas.

Pese al recorte de ingresos y recursos, no se ha modificado la priorización de grandes y costosas obras urbanas, con bajo impacto en resolver problemas tales como el transporte masivo y otros, y que simplemente están dirigidas a apuntalar cosméticamente imágenes de “desarrollo”.

En lo cotidiano, los presupuestos de todas las instituciones estatales continúan achicándose; han comenzado los primeros recortes de planillas, y serán mucho mayores en los próximos meses [^17]. Al mismo ritmo, proliferan las protestas de los contribuyentes por el celo excesivo, o el sesgo casi extorsivo, con que se cobran y exprimen tributos, en un desesperado afán por equilibrar las cuentas.

En el gobierno parece olvidarse, finalmente, que una de las principales razones para lanzar y fomentar la aventura del referendo fue tratar de prevenir el coletazo que ya se esperaba por la caída del precio de las materias primas, y legitimar los recortes y ajustes de los que aún no hablan los voceros, pero que ya sobrevuelan el ambiente.

## El campo institucional

El congelamiento y archivo de la reforma estatal, no solo en sus componentes mayores —referidos a la descolonización, al reconocimiento y apertura de espacio a todas las expresiones de pluralidad, al ejercicio de autonomías o al control social—, ha servido de prólogo a espacios de simple regresión, como ocurre con la descentralización y la desconcentración, sofocadas por una concentración creciente del poder y por un deterioro de la siempre maltrecha institucionalidad, como se observa en la administración de justicia. Lo mismo aplica al manejo de los aparatos de seguridad y represivos, unidos al quebrantamiento del respeto a derechos y garantías constitucionales [^18].

El control de dos tercios en el Legislativo no se ha usado para regularizar los altos cargos y gerencias estatales. Los interinatos se mantienen, y cuando toca regularizarlos —como pasa con el próximo nombramiento de Contralor—, proliferan las señales de que los gobernantes privilegiarán la lealtad y la subordinación partidaria por encima de cualquier otra consideración. Lo mismo se presagia con el inminente nombramiento de un nuevo Defensor(a) del Pueblo.

Las “precumbres” y la subsecuente “cumbre” de reforma de la administración de justicia ofrecen un panorama desalentador, porque hasta ahora son solamente una cámara de resonancia del nuevo viraje propagandístico oficial, según el cual será posible una nueva, y esta vez verdadera, “revolución” de la justicia (en palabras del procurador del Estado), simplemente mediante una nueva reforma de la CPE, en que se reemplazará la elección de magistrados por una selección meritocrática, encomendada a los dos tercios de la mayoría oficial que domina el Legislativo. Es decir, los mismo que eligieron a los candidatos que se votaron en las elecciones de magistrados [^19].

Al cabo de dos meses transcurridos desde la realización del referendo —durante los cuales el ala oficial y todos sus adherentes y asociados [^20] no han dejado de reiterar que su derrota ha sido circunstancial y reversible—, la reforma de la justicia se encamina a ratificar su principal vicio: su dependencia absoluta del poder político y económico. Y es que las autoridades no se resignan a perder el brazo de contención y castigo a sus rivales y críticos, ni quieren una administración neutral cuando les toque rendir cuentas de sus actos [^21].

## Escenarios prospectivos

Este último comportamiento se ampara y trata de justificarse, adicionalmente, en las situaciones que se viven hoy en Brasil y Argentina, donde la administración de justicia, ya sea por independencia o por inclinación favorable a los rivales de los aliados internacionales de nuestro gobierno, está mostrando los serios daños que pueden infligir administraciones de similar conducta.

Por todo lo anterior, la tendencia central del proceso en nuestro país fortalece la predisposición defensiva del personal principal del régimen, que endurece su preferencia por la confrontación y la imposición. El resultado de tal sesgo será una reforma de la administración de justicia que preservará el abominable funcionamiento del Órgano Judicial y el Ministerio Público, bajo control absoluto del Ejecutivo y dejando al desamparo a la población que se atreva a recurrir a ellos. La frustración y el sentimiento de derrota moral que tienden a acarrear tal situación pueden ser devastadores.

Los votos adversos que cosechó el régimen en febrero no han alcanzado para persuadirlo de la necesidad de un ajuste, y menos, de un viraje. Por ello, lo que se ve venir en el campo de la justicia, en el nombramiento de autoridades titulares y en el nulo enfrentamiento de la corrupción tiene grandes posibilidades de repetirse en la esfera económica.

Esto significaría continuar privilegiando la política de simular que la desaceleración no nos afecta, manteniendo un programa de grandes inversiones, desvinculado de la necesidad de ajustes en la priorización de obras, sin consenso con los actores económicos y sometido a los sobrecostos de intermediarios corruptos (estatales y privados), con el agravante de un rápido avance del endeudamiento externo, escasamente sustentado en una transformación productiva de envergadura y en un incremento de la productividad nacional.

Ratificando la previsión del análisis previo: “si no se consigue imprimir un cambio significativo en esa dirección, todos los escenarios tenderían a privilegiar la exacerbación de los choques y a incrementar el costo y sufrimiento para todos los actores, excluyendo, quizá, a los más privilegiados.”

Una complicación adicional es que los problemas y enredos del partido dominante y en control del poder tampoco alcanzan para catalizar entre sus opositores una regeneración que les permita asumir que, en tanto no comprendan que necesitan ensamblar una plataforma capaz de atraer a una franja significativa de votantes del oficialismo, sus posibilidades de ganar permanecerán petrificadas. Esto pasa por tener la capacidad de reconocer aquellos elementos económicos, políticos, éticos e intelectuales abandonados por los gobernantes, pero representativos de las transformaciones que la sociedad buscó.

Los proyectos rupturistas o restauradores del anterior orden vigente se han estrellado una y otra vez en las elecciones previas. No existe fórmula unitaria capaz de subsanar la cortedad de vista del sistema partidario tradicional, y el continuo desgaste de gobernabilidad, que ya se ha iniciado, continuará socavando a este gobierno y pasará lo mismo con el que lo suceda, ya sea continuista u opositor.

La falta de recursos se acentuará, con una pugna creciente por el menguante excedente entre sectores sociales e intereses corporativos o regionales, lo que aumentará las tensiones.

Para que la sociedad civil rescate sus reclamos y sus avances democráticos es indispensable recuperar la independencia de las organizaciones acopladas a la maquinaria estatal, hoy por hoy sumidas en una crisis de corrupción y burocratización mayúscula. Indudablemente, ese paso solo pueden darlo las bases de esas estructuras y, por lo tanto, su ritmo y amplitud, tanto como la calidad de los cambios individuales y organizacionales, dependerán de la acumulación previa y la calidad de los actores que se estén formando ahora mismo.

La reflexión sobre las metas incumplidas que fija la CPE, su pertinencia, actualidad y la manera en que se pueden aplicar y proyectar es una posible herramienta para establecer balances y para fijar rutas, etapas y alianzas de esa gran mayoría democrática que animó el proceso constituyente y que vive un distanciamiento creciente de los grupos e individuos que llegaron a conformar la herramienta a la que se confió la conducción del proceso.

::: {style="text-align:right; font-weight: bold;"}
Abril de 2016
:::

## Notas

[^1]: El curso desfavorable de la situación económica internacional y, especialmente, la baja de precios de los commodities; la restructuración de la disposición de fuerzas en el espacio continental y regional y el mantenimiento de un estado de crispación y confrontación de las escenas política y social en nuestro país.

[^2]: “Desde 2006, el Sistema de Contrataciones Estatales (SICOES) reporta 54.583 contrataciones directas, más de la mitad de las cuales fueron impulsadas por entidades del nivel central. Según la base de datos, a partir de 2006 también se realizaron 7.456 contrataciones por excepción, además de 18.641 licitaciones públicas y 153 invitaciones públicas. Del total de contrataciones directas, al menos 27.862 fueron ejecutadas por ministerios, empresas públicas estratégicas y otras entidades de la administración central. Mientras que en 2004 unos 600 mil Bs fueron asignados por contratación directa, en 2014 este monto llegó hasta 19.603 millones de Bs” [el resaltado es nuestro]. Periódico Página 7, La Paz, 13 de marzo de 2016, p. 10.

[^3]: Buena parte de las disputas entre los representantes de la comisión parlamentaria que entrevistó a Gabriela Zapata en la cárcel se debieron a que los opositores pugnaban por preguntarle sobre temas personales, antes que los referidos estrictamente al tema de tráfico de influencias (véase más sobre el tema en Página Siete del 19 de marzo de 2016, p. 2.

[^4]: Véase: [https://n9.cl/j3l2a](https://n9.cl/j3l2a); también: [http://www.imf.org/external/Spanish/pubs/ft/survey/so/2015/CAR042915AS.html](http://www.imf.org/external/Spanish/pubs/ft/survey/so/2015/CAR042915AS.html)

[^5]: Eso significa que crecer al 4,3% en 2015 y en 2016 es un logro notable, al menos en términos “macro” y de estadísticas, en comparación con los rendimientos de toda la región, que ha ingresado en un segundo año de contracción.

[^6]: Aunque con un déficit público del 6,1% y de 953 millones de dólares en balanza comercial.

[^7]: El indudablemente rápido y consistente avance de las relaciones capitalistas que ha ocurrido en Bolivia y en toda América Latina durante la última década se expresa en el continuo aumento del número de asalariados, independientemente de si los nuevos asalariados son “formales” en términos jurídicos. 

[^8]: Gonzalo Colque, director de la Fundación Tierra, critica la manera en que suele caracterizarse y utilizarse la idea de una “nueva clase media”, en el sentido de que categoriza erróneamente a un segmento de la “clase trabajadora”, sin tomar en cuenta la facilidad con que puede regresar a la situación de pobreza de la que estaría emergiendo. Véase: [https://n9.cl/smtch](https://n9.cl/smtch)

[^9]: Votos urbanos en su gran mayoría, y muchos de los asalariados que recibieron el doble aguinaldo.

[^10]: Las justificaciones más constantes las ha proporcionado el vicepresidente: la “ingratitud y la dudosa calidad moral” de un millón de nuevos “clasemedieros”; la unidad y las “mentiras” de la oposición; la influencia de las redes sociales digitales, “manipuladas por tuiteros enviados directamente por el imperio”; la “migración” de dirigentes sindicales a cargos públicos, entre las principales.

[^11]:  Es muy importante destacar que, en las últimas semanas, dirigentes de la CSUTCB —cuya cúpula está muy comprometida con ese desfalco al haber recibido grandes desembolsos— han declarado públicamente que ya no cabe insistir en la reelección; más bien hay que ver los relevos y nuevos candidatos que encabezarán la fórmula masista en 2019.

[^12]: Atribuyo la constante mayoría que mantiene en esa ciudad (aunque con tendencia al descenso) al predominio del “voto identitario”, condicionado por la importante presencia de migrantes y descendientes de migrantes rurales. Ese comportamiento es propio de la franja más firme de electores que encuentran en el presidente del Estado un legítimo e inigualable representante propio desde el punto de vista cultural y de clase: campesino, colonizador y migrante.

[^13]: Es preciso recordar que, como respuesta a que las encuestas más tempranas focalizaban el recelo de los electores ante gobiernos demasiado “largos”, la propaganda oficial desechó referirse al término reelección y puso la máxima presión para que propios y extraños se refiriesen a la “repostulación”. La desconfianza de los electores toca fibras de la memoria larga, como la descomposición del MNR, y en ese sentido puede considerarse como parte de una cultura democrática en proceso de afirmación.

[^14]: Es posible que el impacto y el costo electoral resultado de cuestiones morales y emocionales recién se esté acumulando, ante la cadena de abusos contra la señora Zapata, apabullada por un Estado movilizado para respaldar al presidente hasta en los temas más dudosos. Esto mella aún más la figura de Evo Morales, pues lo muestra como alguien que se esconde detrás de otros, lo que socava el mito de hombre intrépido que ha alimentado por años.

[^15]:  Pese a ello, Morales continúa con una aprobación del 61%, incluso en medio del agitado conflicto de las personas con discapacidad, según la encuesta de la empresa Tal Cual, con una muestra de 1.800 personas en las ciudades del eje e intermedias, realizada la segunda quincena de abril de 2016 y difundida por la red televisiva ATB.

[^16]: Véase: [www.notimerica.com/politica/noticia-vicepresidente-bolivia-asegura-mas-mas-debil-morales-20160307131744.html](www.notimerica.com/politica/noticia-vicepresidente-bolivia-asegura-mas-mas-debil-morales-20160307131744.html)

[^17]: En relación a este tema, la experiencia de la última década ha mostrado una enorme inflación de las planillas públicas centrales y subnacionales y, junto con ella, un deterioro constante de la calidad del empleo, porque se ha virado a contratar “consultores” sin beneficios, sin estabilidad y con derechos laborales recortados. Es una década en que el Estado se ha exhibido como un patrón con los peores hábitos y tics neoliberales en materia de empleo.

[^18]: Concretamente, la de asociación atropellada, con intervenciones estatales subrepticias sobre organizaciones sociales, cuando expresan disenso o protesta, o su división y manipulación; la del hostigamiento de periodistas críticos y la severa discriminación en el reparto de la gran torta publicitaria estatal, así como la multiplicación de causas judiciales contra alcaldes, gobernadores y otros representantes electos de organizaciones opositoras; la de los derechos de pueblos indígenas y contra la Madre Tierra (con la apertura de áreas de reserva), etcétera.


[^19]: Especialistas en la materia que militan en la oposición han expresado críticas a la ruta de la “cumbre” que lleva adelante el Ejecutivo, y han presentado propuestas alternativas para que la decisión de una auténtica reforma incorpore a otros actores además del propio personal de gobierno y dirigentes de organizaciones sociales aliadas (véase: [https://n9.cl/unxag](https://n9.cl/unxag); también: [https://n9.cl/9i1c7](https://n9.cl/9i1c7)).

[^20]: Excepción hecha de la CSUTCB, cuya máxima dirigencia se ha desmarcado de los demás en una sola oportunidad, al afirmar que debe dejar de buscarse “segundas rondas” y que hay que concentrarse en hallar el relevo para la candidatura de 2019.

[^21]: Aunque oficialmente se ha desmentido que en el MAS se esté considerando la posibilidad de aprovechar una reforma constitucional que elimine la elección de magistrados para volver a consultar sobre una nueva reelección, la susceptibilidad se mantiene ante la reiterada alusión a nuevas “vueltas” o segundos tiempos.
