---
lang: es
format: 
  html:
    page-layout: article
---

# Aterrizaje de Trump y despegue de la contraofensiva al 21F {.unnumbered}

El XI aniversario del ascenso del MAS al gobierno se cumplirá apenas tres días después de la ceremonia de transmisión de mando en EE. UU. Así, mientras en el centro imperial se consagra la culminación de un ciclo completo, del "progresismo" de Obama al "ultraconservadurismo" [^ano_2016_3-1] de su sucesor, aquí, aparentemente, la situación mantendrá una inverosímil estabilidad, proyectada hacia el futuro con la ya declarada intención de abrir espacio para la cuarta reelección presidencial.

[^ano_2016_3-1]: El entrecomillado se justifica ampliamente porque, más allá de las imágenes, el gobierno del primer presidente negro deja como herencias tantas flagrantes contradicciones en su caracterización de progresista, como dudas e interrogantes el comportamiento que realmente tendrá o podrá tener el nuevo gobierno norteamericano. La designación de los principales secretarios no deja duda sobre las intenciones regresivas, o francamente reaccionarias, del nuevo presidente, pero queda por delante un período de prueba respecto a la efectiva capacidad de cumplir sus promesas y amenazas en política interna e internacional.

Pero si a Donald Trump puede no serle tan fácil volcar abruptamente la política que su país ha mantenido por casi medio siglo hacia China, aniquilar el Tratado de Asociación Transpacífico (TPP) antes de su nacimiento, construir la muralla con México y expulsar a 11 millones de migrantes, no será ni más sencillo ni más grato para los gobernantes bolivianos remontar la desaceleración, enmendar el deterioro de su imagen en materia de eficiencia administrativa o corrupción o ejecutar cualquiera de las "cuatro vías" [^ano_2016_3-2] (la mitad de las ocho alternativas de las que habló García Linera) que, según cree, estarían a su alcance para neutralizar o burlar los resultados de la negativa popular que obtuvieron el 21 de febrero (21F).

[^ano_2016_3-2]: A saber: i) iniciativa ciudadana para reformar parcialmente la CPE; ii) reforma constitucional aprobada por dos tercios de la Asamblea Legislativa; iii) interpretación constitucional del art. 168 por el Tribunal Constitucional Plurinacional (TCP) y iv) renuncia de Morales antes de cumplir con su actual mandato (véase La Razón del 19 de diciembre de 2016, en su amplia cobertura del congreso del MAS en Montero).

Es tan previsible que el nuevo gobierno estadounidense tendrá serias dificultades para llevar a cabo sus planteamientos, como que la instalación de Trump en Washington complicará todavía más las perspectivas de nuestras actuales autoridades.

La merma de capacidad de estas últimas para sostener la iniciativa y allanar el camino para sus planes ---como única forma de ejecutar la "agenda patriótica", convertida en una especie de curalotodo del conjunto de problemas del país--- se ha confirmado al reducir el relato oficial a una pugna permanente con sus enemigos, quienes tratan de impedir que se abra camino a la reelección presidencial.

## Los cambios en el hemisferio norte

El arribo de Trump a la Casa Blanca consolida el viraje conservador en nuestro planeta, que empezó a manifestarse en Europa y que tiene sus propias manifestaciones en América Latina.

Los resultados electorales de España, las tendencias electorales prevalecientes en Francia, Italia, Austria y el Brexit británico son algunas de las señales que muestran el fortalecimiento de corrientes conservadoras, sean tradicionales o nuevas, como aparente respuesta a la inestabilidad económica y financiera, a la intensificación de ataques yihadistas y al masivo flujo de refugiados que huyen de la guerra en Medio Oriente y del hambre y las guerras en África y otros continentes.

A diferencia de la ola neoliberal de hace tres décadas, varios de los nuevos referentes conservadores reniegan de la globalización y abogan por vías proteccionistas que, hipotéticamente, llegarían a vulnerar, y en el peor de los casos, a anular algunos de los acuerdos comerciales más extensos e importantes vigentes, o en vías de consolidarse, abriendo paso a extendidas guerras comerciales que complicarían notablemente la economía mundializada.

El obligado repliegue económico de los países latinoamericanos, afectados por la finalización del ciclo de superprecios de materias primas, no mejoraría en ninguno de los escenarios que supone el avance de las tendencias económicas y políticas conservadoras del hemisferio boreal.

La presidencia de Trump, que hoy por hoy implica un elevado factor de incertidumbre, tiende a potenciar las dificultades de la región y a crear un entorno cada vez más hostil para los gobiernos etiquetados como "progresistas" que sobreviven en esta latitud. El hecho de que sobre el nuevo presidente estadounidense recaigan sospechas en su país de ser afín con Putin no significa que los gobiernos sudamericanos que simpatizan con el gobierno ruso vayan a beneficiarse de una actitud más complaciente de la nueva administración estadounidense [^ano_2016_3-3].

[^ano_2016_3-3]: Las múltiples y elogiosas menciones a Putin por Trump se complementan con el nombramiento de Rex Tillerson como su secretario de Estado. El nombramiento de este ex máximo ejecutivo de la Exxon, conocido como el "occidental mejor relacionado con el presidente ruso", ha obligado al Partido Republicano a suscribir la iniciativa de los demócratas para investigar si Rusia intervino en el proceso electoral estadounidense mediante ataques de hackers, por ejemplo. Evo Morales, por su parte, escribe literalmente en su tuit: "Saludar triunfo de @realDonaldTrump Esperamos trabajar contra el racismo, machismo, la antiinmigración, por la soberanía de nuestros pueblos". Con los antecedentes de la relación EE. UU.-Rusia, en Bolivia, no hay acuerdo sobre si la temprana salutación del presidente Morales al triunfante Donald Trump se explica por las simpatías internacionales del presidente electo o si, más bien, encierra una dosis de ironía.

Si a la seria y prolongada disminución de inversiones provenientes del hemisferio norte que experimenta Sudamérica ---complicada con la elevación de las tasas de interés decidida por la Reserva Federal--- se le agregan presiones políticas y económicas, puede construirse un escenario bastante peor que el de este año que, según el ministro de Economía, Luis Arce, habría sido hasta ahora el más desventajoso del último decenio.

Lo que no debe perderse de vista es que los presidentes de estirpe y orientación estrictamente conservadora, como Macri en Argentina y Temer en Brasil, no abren una puerta ancha para una mutación política y social, como ocurrió en la era neoliberal, porque la resistencia interna hacia sus políticas muestra, desde el inicio de su gestión, una intensidad y una persistencia que no se vieron el pasado.

El anudamiento de nuevas contradicciones políticas y económicas a escala global fortalece la evolución de una tendencia que eleva los riesgos de estallidos, en un contexto de acelerado desequilibrio ambiental. Este desequilibrio también tiende a incrementarse a causa de los triunfos políticos de fuerzas negacionistas del cambio climático, tanto en EE. UU. como en algunos países europeos, además de un recrudecimiento de reflejos desarrollistas e industrialistas de viejo cuño en prácticamente todos los gobiernos de los países menos desarrollados, independientemente de la inclinación ideológica de sus gobiernos.

De tal manera que el encono político y social tiende a ser opacado por la creciente fuerza y gravitación de la contradicción entre sociedad humana y la naturaleza, sin que los planes multilaterales ensayados y practicados hasta ahora consigan aplacar o modificar esa tendencia.

## Un inmovilismo engañoso

La impresión de que Bolivia pueda quedar al margen de los cambios que se están acumulando alrededor nuestro y más lejos es un típico espejismo. Si bien la obsesión gubernamental de reescribir el pasado impregna la agenda noticiosa y política, alcanzando a crear esa sensación, en realidad se producen continuas modificaciones, frecuentemente de una manera muy rápida.

El congelamiento de la imagen a captarse ---debido a que a fines de este año, tal como a su inicio, seguimos hablando de reelecciones, "repostulaciones" y cuestiones afines, como si el referendo constitucional de febrero jamás hubiese ocurrido---, el resquebrajamiento del bloque de poder, consecuente con el estallido cooperativista minero y la agregación de escándalos y conflictos, ha conducido a una situación antes desconocida, que puede caracterizarse como de agrietamiento estratégico del proyecto hegemónico en el país.

La dirigencia del MAS y sus aliados, que conducen las mayores organizaciones sociales [^ano_2016_3-4] (encabezadas por las "trillizas" campesinas: CSUTCB, Colonizadores y "Bartolinas"), hacen los máximos esfuerzos por tratar de probar que el apoyo del "pueblo" al partido y al proyecto gubernamental sigue incólume, y que lo único que impide verlo es la pérfida manipulación que torció el voto en febrero, cuando las "mentiras" y "calumnias" sobre el presidente, su novia y su hijo desportillaron fugazmente la confianza de una franja de votantes fieles.

[^ano_2016_3-4]: La salida y el reingreso de algunas de ellas, como la COB, simplemente ratifica el predominio absoluto de la dinámica corporativista que impregna las relaciones entre el gobierno y la dirigencia de estas organizaciones. Así, la COB amenaza con no respaldar las iniciativas para la reelección, incluido el intento de "anular" el referendo de febrero, si los gobernantes no hacen concesiones a sectores asalariados.

Según esta interpretación, repetida a diario, ni la desaceleración económica ---con sus cada vez mayores impactos sobre las actividades económicas en general, el empleo y los ingresos---, ni los indicios y evidencias de corrupción y arbitrariedad, ni la explosión de escándalos que van desde los choques internos hasta las muertes que llegan a ocasionar, consiguen afectar el crédito del presidente, su partido y sus asociados.

Sin embargo, los sondeos y encuestas revelan que este año la credibilidad del jefe de Estado ha descendido, sin recuperarse a continuación, como había ocurrido invariablemente en todos los años anteriores. En concordancia, la aún imbatible fortaleza electoral del MAS enfrenta su peor y más continuo enflaquecimiento en términos de intención de voto.

El hecho de que la cúpula masista sienta que se juega la vida en demostrar que no hubo error al convocar al referendo, que la convocatoria de Evo Morales está intacta y que, por lo tanto, se justifica cualquier camino para volver a llevarlo a la cabeza de la candidatura partidaria, no ha sido suficiente para lograr que la sociedad lo crea, aunque el flujo noticioso avance y se retuerza alrededor de ese eje único.

## Chepete-Bala: Proyecto tóxico y quimérico

Si el enfrentamiento entre gobierno y cooperativistas en agosto alertaba sobre los límites de los acuerdos y alianzas de conveniencia, que permitieron construir el agregado corporativo sobre el que se apoya el gobierno, el surgimiento de dos conflictos, aparentemente de menor rango, pondrá a prueba los planteamientos de largo alcance con los cuales ha venido justificando su vigencia y la supuesta necesidad de que se mantenga por un plazo adicional no menor a una década.

El jubiloso anuncio, formulado por el propio presidente el 16 de julio recién pasado, de que la construcción de una represa en el estrecho del Bala sería el inicio de un amplio y raudo proceso de sustitución de exportaciones, que nos permitiría reemplazar los ingresos perdidos por la disminución de los precios del gas y, a la larga, pensar inclusive en reemplazarlos completamente, pudo seguramente aportar cierta dosis de serenidad ante el panorama de dificultades económicas que no dejan de sumarse desde hace dos años.

Esa posible tregua, si existió, llegó a durar muy poco, debido principalmente a la cerrada negativa gubernamental de cumplir su obligación de difundir los estudios [^ano_2016_3-5] en los que basa sus esperanzadoras informaciones. Estas, siempre muy escuetas, afirmaban en un principio que el "proyecto Bala" requería para construirse 6.000 millones de dólares, pero que aportaría 1.250 millones de dólares de ganancias anuales desde que se finalice su construcción, que duraría unos siete años; en otros siete años habríamos pagado su costo.

[^ano_2016_3-5]: A la falta de transparencia se suma la abierta intención de confundir y manipular a la opinión pública cuando, por ejemplo, el presidente y su vice insinúan que el agua de las represas hidroeléctricas sobre el río Beni podría servir para aliviar la escasez de agua potable (véase: <https://n9.cl/zhg1j>, y también: <https://n9.cl/5i9hi>).

De allí en adelante, "el departamento de La Paz y el TGN" contarían con ingresos frescos y de libre disponibilidad. Por ello, cualquiera que se oponga al "proyecto Bala" o lo cuestione era un enemigo innato de La Paz y del país y, como tal, representante de intereses foráneos, seguramente proimperialistas.

La filtración, primero, de la ficha ambiental y, semanas después, del "Estudio de Identificación del proyecto hidroeléctrico El Bala", elaborados ambos por la consultora italiana Geodata, proporcionan un panorama completamente distinto a la optimista versión oficial.

Para empezar, el proyecto que el gobierno se empeña en llamar "El Bala" corresponde a la construcción de una enorme represa a más de 40 km al suroeste de esa angostura, en la desembocadura del cañadón que vincula las serranías del Beu y de El Chepete, por lo que se trata en realidad del componente Chepete, con un costo inicial no de 6 mil millones, sino de casi 7 mil millones de dólares, según el mencionado estudio.

El componente Bala se construiría, eventualmente, unos 20 años (op. cit.) después de concluido el gigantesco embalse de 159 m, que detendría las aguas del río Beni por 6 a 7 meses en el Chepete, para presuntamente generar unos 3.300 KW de potencia, que deberían venderse en algún momento a Brasil. El componente Bala aportaría apenas un 12% adicional a la capacidad de generación del Chepete.

Sin embargo, hasta el día de hoy no hay ninguna negociación o aproximación con el gobierno brasileño que respalde la decisión de exportarle esa importante cuota de energía [^ano_2016_3-6]. Sin comprador seguro [^ano_2016_3-7], con capacidades menguantes de financiar el proyecto [^ano_2016_3-8], los 11 millones de bolivianos que costaría el proyecto de prefactibilidad (estudio de Identificación del proyecto, según la nomenclatura vigente) y los 12 millones de dólares para el estudio a diseño final, encomendado también a Geodata, podrían llegar a servir absolutamente para nada y perderse, como ya ha ocurrido con los estudios que se han realizado para la hidroeléctrica de Cachuela Esperanza.

[^ano_2016_3-6]: El déficit anual de Brasil ronda ahora los 7.500 MW. Según su plan de expansión energética, se irá desplazando hacia la generación eólica, en la que planea invertir más 50.000 millones de dólares hasta 2025. Las licitaciones brasileñas para compra de energía demuestran que estas se adjudican con unos ocho años de anticipación. De modo que si Bolivia quisiera llegar a ser un proveedor de electricidad para 2025, como se define en el estudio de identificación del proyecto Chepete/Bala, los acuerdos tendrían que haberse cerrado este año. El ministro de Energía de Brasil, que visitó al nuestro hace pocas semanas, no mencionó el proyecto Chepete ni una sola vez, y recalcó que el interés brasileño en materia de generación hidroeléctrica se centra en la construcción de la represa binacional Riberao sobre el río Madera.

[^ano_2016_3-7]: Dos intentos bolivianos previos de vender a Brasil electricidad generada lejos de su territorio han fracasado. En 1996 un consorcio privado encabezado por Julio León Prado, principal accionista del Grupo Bisa, ofreció 600 MW generados en una planta termoeléctrica ubicada en Bulo Bulo, obteniendo una expresión de interés, con la condición de que la generadora se traslade a Puerto Suárez. El gobierno actual avanzó aceleradamente con los estudios para construir en Cachuela Esperanza una hidroeléctrica con capacidad de generar unos 900 MW, pero debió desistir porque la parte brasileña expresó que su interés es la hidroeléctrica binacional Riberao, en el nacimiento del Madera. Véase Jorge Molina Carpio (2006), "Análisis de los Estudios de Impacto Ambiental del Complejo Hidroeléctrico del Río Madera: Hidrología y Sedimentos". <https://n9.cl/6m7vv>

[^ano_2016_3-8]: Según el estudio de Geodata, el proyecto sería viable si el Estado boliviano lo financia en al menos el 30% (unos 2.100 millones de dólares); con el 70% de financiamiento externo se calcula que habría que pagar una elevada cuota como costo financiero.

Por lo elevado de estos montos, el exembajador del gobierno de Morales ante las Naciones Unidas, Pablo Solón, ha lanzado la hipótesis de que la sola elaboración de estudios termine convertida en una redituable "industria" para las consultoras que los elaboran y los funcionarios que las licitan o adjudican directamente.

Las principales observaciones que ha merecido hasta ahora el proyecto Chepete/Bala, además de su altísimo costo y su baja e incierta rentabilidad, radican en que afectarían entre cuatro a seis tierras comunitarias de origen (TCO) de un igual número de pueblos indígenas. Estos sufrirían inundaciones y una expropiación de hecho de sus territorios [^ano_2016_3-9], la práctica aniquilación y esterilización del río Beni [^ano_2016_3-10], que concentraría en el embalse desechos tóxicos provenientes de La Paz y poblaciones yungueñas, convirtiéndolo en una gigantesca cloaca que aniquilaría la vida en ese remanso y las 70 hectáreas de bosque inundadas.

[^ano_2016_3-9]: Véase los blogs de 2016 de Daniel Robison: <https://n9.cl/wmt02> y <https://n9.cl/fvkw6>

[^ano_2016_3-10]: Roger Cortéz y Daniel Robison (2016), "Incógnitas tóxicas y verdades ocultas del proyecto del Chepete/Bala" (documento inédito).

Aguas abajo, desde el Chepete hasta la confluencia del río Beni y el Mamoré, por cientos de kilómetros, el río, desoxigenado y privado de los sedimentos minerales que arrastra y que se retendrían en la represa, perdería sus bondades fertilizantes y erosionaría velozmente su curso, afectando, de paso, múltiples acuíferos que se encuentran por debajo de su lecho [^ano_2016_3-11].

[^ano_2016_3-11]: El único daño que reconocen el estudio y el gobierno son los 670 km2 de selva que quedarían anegados, con pérdida parcial de biodiversidad, especialmente especies piscícolas. Las críticas multiplican muchas veces la superficie y el daño ambiental y humano, por el impacto sobre todo el curso del río y la interrupción violenta de ciclos y relaciones de un sistema que abarca múltiples subsistemas.

Lejos de retroceder, el presidente de ENDE ha anunciado que el presupuesto de 8.800 millones de dólares contemplado en la "agenda patriótica", se multiplicaría hasta alcanzar 27.000 millones principalmente para la construcción de megarepresas en áreas boscosas. Sin embargo, nunca ha aclarado por qué los estudios y proyectos apuntan en esa dirección, cuando ENDE ha identificado en las cuencas altas de las cordilleras Oriental, Tres Cruces y Apolobamba un potencial mayor a 14.400 MW (cuatro veces el del Chepete) sin afectar bosques, biodiversidad y territorios indígenas.

## El agua y las nuevas sensibilidades

La escasez de agua que afecta a la sede de gobierno desde noviembre de 2016 puso en evidencia fallas esenciales de la gestión gubernamental y de su ambicioso programa de inversiones a largo plazo [^ano_2016_3-12], llamado "agenda patriótica".

[^ano_2016_3-12]: Los resultados de otras grandes inversiones, como la planta separadora Chaco (más de 300 millones de dólares) o el ingenio de San Buenaventura (265 millones de dólares), entre las principales, son suficiente muestra como para cuestionar tal tipo de megaobras. La planta separadora tiene serias dificultades de abastecimiento de materia prima y el propano que produce se vende a Paraguay a un precio 16% menor que el subvencionado que pagan los consumidores bolivianos de GLP. En San Buenaventura apenas se ha plantado el 8% de la cantidad de caña que el ingenio puede procesar y la expansión de cultivos para alimentar la producción de azúcar compromete suelos tropicales muy frágiles, vecinos al Parque Nacional Madidi. La reciente inauguración de la planta de urea (800 millones de dólares) presenta interrogantes igualmente perturbadoras, ya que la vía férrea que debe trasladar su producción a Montero está lejos de concluirse, y sus costos de exportación amenazan con una absoluta falta de competitividad.

La Paz viene a ser la cuarta ciudad, capital de departamento, que enfrenta problemas de abastecimiento de agua potable, ya que Cochabamba, Sucre y Potosí los sufren, en algunos casos desde hace décadas. Con el ingreso de La Paz y El Alto al círculo de la escasez del líquido vital, se visibilizan los problemas que no han podido superarse en los diez años de gestión del actual gobierno, pese a haber sido lubricados con el mayor flujo de divisas extranjeras de nuestra historia.

Así, los éxitos en materia de disminución de la pobreza, avance de infraestructura y mejora de algunos servicios básicos que exhibe continuamente en su defensa la gestión gubernamental muestran una fragilidad extraordinaria, ya que una amenaza similar pende sobre Santa Cruz, que, debido a la contaminación de sus acuíferos, afronta el riesgo de retroceder en su calidad de vida en el mediano plazo.

Al mismo tiempo, cuando se examina el programa de enormes inversiones de la agenda proyectada por el gobierno hasta 2025, se advierte que fines muy nobles y necesarios, como la transformación de la matriz eléctrica de termo (que cubre más del 70% de la demanda actual) a hidro, o la necesidad de ampliar el abanico de exportaciones, incluyendo la venta de electricidad, quedan completamente desfiguradas por la falta de acuerdos sólidos con posibles compradores (o su inexistencia, más bien), por la selección de los peores espacios geográficos y sociales para construir las generadoras y la sospecha de negocios ilícitos por la priorización de contrataciones directas.

La situación no mejora al considerar otras grandes inversiones, como los teleféricos y trenes eléctricos, que suman más de mil millones de dólares. Son productos muy atractivos para la imagen de las ciudades, pero con poco impacto en la solución de sus problemas de transporte.

La ampliación de la frontera agrícola a expensas de bosques y biodiversidad es también parte central de la mencionada agenda. Por esa vía, lejos de incrementar su adaptabilidad y resiliencia al cambio climático, que avanza implacablemente y más rápido de lo previsto, el país estará lleno de deudas, debilidad y estancamiento económico, con una mayor dependencia política y económica, con mayores dificultades para su transformación económica y social y con una pérdida considerable de fuentes de oxígeno, agua y biodiversidad, ignoradas como las fortalezas principales del país y sacrificadas tras un desarrollismo de perspectivas muy dudosas.

Bajo esa lógica, las anteriormente abundantes reservas internacionales merman muy rápidamente, mientras que los usos para los que se ha programado las que aún restan se asemejan más a "armas económicas de destrucción masiva", dado su alto costo y escaso beneficio para un país que sigue siendo sustancialmente pobre.

Tales problemas se complican mucho más cuando el norte de la gestión gubernamental es abrir la oportunidad de perpetuarse a través de la reelección, manteniendo e incrementando la falta de transparencia y de rendición de cuentas.

## Escenarios

La porfía del aparato oficial de no renunciar a la candidatura de Morales Ayma para la elección de 2019 traslada a la escena política el ánimo de confrontación abierta del MAS y sus aliados, como tendencia política y social principal que irá creciendo a medida que se aproxime el momento de imponer su punto de vista.

No habiendo definido aún por cuál de las "cuatro vías" definidas en el congreso de Montero optará, las señales emitidas hasta ahora apuntan a que se imponga alguna de las que no requieren una votación popular, es decir, la reforma parcial de la CPE por dos tercios de votos de la Asamblea Legislativa, o su interpretación, encomendada al TCP, como cuestión de puro derecho, según la cual el MAS impugnará el número limitado de reelecciones (dos) que la CPE impone, porque "coartaría el derecho del soberano".

La iniciativa ciudadana que entusiasma a la dirigencia de las organizaciones sociales aliadas del oficialismo ---porque permitiría, supuestamente, que cada facción, grupo e individuo pruebe y presuma de su capacidad de convocatoria--- es cada vez peor recibida por la cúpula partidaria, que está al tanto del debilitamiento de la fuerza electoral de su propio jefe máximo y candidato [^ano_2016_3-13].

[^ano_2016_3-13]: La sugerencia del procurador general, Arce Zaconeta ---considerado uno de los principales cuadros jurídicos del gobierno---, de impulsar una reforma parcial que no solo modifique el artículo de la reelección, sino que "se refuerce" con la cadena perpetua contra violadores de menores, planteada por la "cumbre judicial" de 2015, refleja el temor de algunos dirigentes de introducir únicamente la reelección, sin un apoyo o lubricación discursiva y legal, incluso en espacios como el Congreso, donde la orden emitida desde el Ejecutivo se acatará sin demora.

La indignación de los partidos opositores no tiene mayor posibilidad de alterar los planes e intenciones del oficialismo, debido a la debilidad congresal, electoral y de crédito público de estas tiendas políticas. A ello hay que agregar, obligatoriamente, su incapacidad de diferenciarse estratégicamente del desarrollismo gubernamental. Sus diferencias en lo económico y en las relaciones internacionales se ubican en su nítida predisposición a diluir la presencia estatal en el campo productivo y a estrechar lazos comerciales y políticos con EE. UU. y Europa Occidental, alejándose de China, Rusia e Irán; en lo político, buscan ceñirse más estrictamente a la formalidad legal e institucional [^ano_2016_3-14].

[^ano_2016_3-14]: Los partidos con posiciones descentralizadoras y autonómicas, con mayor sensibilidad ambiental, indígena y profemenina, como el Verde y el MSM, apostaron por su extinción al equivocarse rotundamente en sus cálculos electorales para 2014, cuando desplegaron vicios caudillistas y sectarios muy similares a los de los partidos y sindicatos tradicionales.

Las organizaciones sociales independientes, principalmente algunas indígenas, tienen posibilidades de lograr convocatorias a veces extraordinariamente mayores que su dimensión y capacidad organizativa, pero siempre en situaciones concretas y transitorias. En el espacio de la academia, las ONG y gran parte de la intelectualidad, así como en el de los medios de difusión, se mantiene el impacto de las sucesivas y continuas agresiones montadas por el gobierno, aunque aquí y allá aparecen nuevos reductos de resistencia.

En ese cuadro, los mayores enemigos del oficialismo continúan siendo la estrechez económica y de recursos vitales, como el agua y los alimentos, que se sentirá cada vez más asfixiante debido a las expectativas que ha sembrado el triunfalismo gubernamental. En un destacado segundo lugar, el corporativismo de sus asociados seguirá empujando a sus dirigencias a pedir mayores privilegios, disputándolos con otros aliados. Finalmente, pero no de menor riesgo, está el paquete compuesto por la baja calidad de la gestión pública, la corrupción y las divisiones internas del MAS. Sin embargo, es posible que mejoren algunos precios de commodities.

La movilización, indignación y reclamos espontáneos son los más probables adversarios del gobierno, debilitado además por su expectativa y deseo de habilitar a su candidato. Así, la mayor parte de los conflictos por demandas económicas y sociales tenderá a derivar en expresiones que critiquen al continuismo, lo que, a fuerza de repetirse y acumularse, debilitará la potencia electoral oficialista, incluso si logra imponer la candidatura de su jefe máximo.

Lo más novedoso y riesgoso en la perspectiva de los próximos meses es que la cerrada determinación gubernamental de mantenerse a cualquier costo ("hemos llegado para quedarnos", en palabras del presidente) introduzca un sesgo de fuerza y violencia, inducida desde el propio aparato del Estado.

El conflicto del TIPNIS ya inauguró la era de movilizaciones ambientalistas y proindígenas, que pueden ampliarse ante la obstinación por seguir invirtiendo en la lógica de la "agenda patriótica"; esta tendencia se verá dificultada por la pérdida de músculo financiero gubernamental [^ano_2016_3-15]. Nuevas rachas de escasez de agua o crisis producidas por avance de megaobras tenderán a estimular respuestas amplificadas, en las que cabe la posibilidad de que los jóvenes y su actividad en las redes sociales digitales cobre creciente protagonismo.

[^ano_2016_3-15]: Que puede tratar de compensar incrementando la dependencia económica y política de fiadores y prestamistas internacionales, como China.

::: {style="text-align:right; font-weight: bold;"}
Diciembre de 2016
:::

## Notas
