---
lang: es
format: 
  html:
    page-layout: article
---

# Un fallo cardíaco-político y el retorno de un espectro {.unnumbered}

Los frentes de conflicto que el gobierno multiplica, se recargan y ensombrecen, después de que trató de ganar en Santa Cruz, apresando al gobernador. Destaca entre todos la ríspida evolución de la lucha interna del Movimiento al Socialismo, que ahora empieza a manifestarse dentro la dirigencia de organizaciones sociales del campesinado, verdadero corazón de la convocatoria, representatividad y fuerza política y electoral masista, en una fase de intensificación de los tropiezos económicos.

El vuelco adverso de la situación económica se concentra actualmente en la indetenible caída de reservas de moneda extranjera [^ano_2023_1-1] . La iliquidez de dólares crispa notoriamente la situación, al evocar el temido espectro de un retorno inflacionario, después de casi cuarenta años en que la percepción pública asumía que se había superado definitivamente.

[^ano_2023_1-1]: Las llamadas reservas internacionales netas (RIN) indispensables para mantener las voluminosas importaciones y el pago de deuda externa.

El ruido de la división del oficialismo, junto al ensanchamiento de su inclinación represiva -introduciendo cierto toque que va en la huella de Daniel Ortega- puede agotar abruptamente la tolerancia social, como anuncia el aumento los focos de reclamos, protestas y descontento, por ahora dispersos [^ano_2023_1-2].

[^ano_2023_1-2]: Unos cuantos presentan claras pistas de conexión con la fracción evomoralista del MAS.

## La división se extiende a las bases

La franja más fiel y numerosa de la base social del MAS y su prolongado régimen tiene en las organizaciones campesinas, coloquialmente llamadas **Trillizas** [^ano_2023_1-3], su verdadero centro fundacional y columna sustentadora. Hasta hace pocas semanas sus dirigentes optaban por mantenerse silenciosos ante los choques entre las fracciones comandadas por Luis Arce C. y Juan Evo Morales.

[^ano_2023_1-3]: Confederación Sindical Única de Trabajadores Campesinos de Bolivia-Tupac Katari (CSUTCB), la Confederación de Mujeres Campesinas Bartolina Sisa (Bartolinas) y la de Colonizadores (actualmente Confederación de Comunidades Interculturales (CSIB)

El silencio se ha quebrado dentro la CSUTCB y las Bartolinas en las últimas semanas, mientras entre los colonizadores, la franja campesina más poderosa, los roces internos todavía tratan de hacerse pasar como altercados de los colonizadores con campesinos o con indígenas [^ano_2023_1-4]. La paciencia y contención de estos actores ha empezado a rajarse, principalmente por urgencias prácticas, como el cuestionamiento del continuismo de dirigentes, en la CSUTCB [^ano_2023_1-5] , donde el detonante es el reclamo de llevar a cabo el congreso institucional postergado varias veces.

[^ano_2023_1-4]: Los colonizadores fueron originalmente (entre los años 50 a los 90 del siglo XX) familias campesinas que migraban, ocupando nuevos territorios, expulsadas por el minifundio y la decadencia productiva de sus parcelas. Ahora, la búsqueda de nuevos campos de cultivo resulta secundaria, ante una colonización concentrada en expandir el mercado de tierras para uso empresarial, agrícola y ganadero. Los cocaleros del Chapare y gran parte de pequeños y medianos soyeros de Santa Cruz son colonizadores o hijos de colonizadores. Evo Morales es un representante típico de esta franja campesina, cada vez más especializada en la producción agrícola orientada a la exportación (oleaginosas y coca) y fuertemente vinculadas con actividades comerciales.

[^ano_2023_1-5]: Consistente en: poner en primer plano el relato Fue golpe y no fraude, para legitimar el retorno de Morales en 2025, con el apoyo de un aparato judicial, radicalmente corrompido y obediente a las directivas de reprimir cualquier riesgo electoral que amenace el triunfo de su candidatura.

En principio todas ellas, igual que aquellas fracciones de la CIDOB (Confederación Pueblos Indígenas de Bolivia) y CONAMAQ (Consejo Nacional de Ayllus y Markas del Qullasuyu), creadas por el régimen en sus campañas represivas contra los indígenas [^ano_2023_1-6], optaron por observar y callar, con base a reiteradas experiencias sobre cómo la toma explícita de posiciones afecta los privilegios con que el régimen se garantiza su lealtad y sumisión.

[^ano_2023_1-6]: En conflictos como el del TIPNIS, las represiones de cocaleros de Yungas, de comunarios de Mallku Kota, de los guaraníes de Takovo Mora, las marchas indígenas de tierras bajas, desde 2011 en adelante, el abandono estatal de pueblos como los Urus en tierras altas, o los yuracaré en tierras bajas son algunas de las más conocidas.

El problema inmediato que supone para el oficialismo la exteriorización de fisuras en estas organizaciones sociales es que muestran y amplifican problemas en la base campesina que, a la larga, tienen múltiples canales para extenderse a amplios sectores sociales urbanos, originados en las migraciones campo-ciudad de las últimas siete décadas y en la influencia cultural e ideológica que preserva lo campesino sobre estas franjas de población urbana.

Las divergencias en esas y otras organizaciones sociales no han conducido, hasta este momento, que puedan detectarse corrientes o dirigentes individuales que reclamen transparencia, rendición de cuentas, autonomía ante el estado, o una mayor democratización. Mientras no hayan avances en esa dirección, el completo predominio de dirigentes masistas puede extenderse indefinidamente, o hasta que la inestabilidad de la base multiplique los disensos en la cúpula.

## Economía y el fantasma de la inestabilidad y la inflación

La importancia de los problemas dentro las organizaciones campesinas pasa casi desapercibida para otros sectores sociales, pero, en todos se advierten señales de desazón, ante los efectos de la aguda escasez de dólares, inocultable durante este mes, pese a la desaparición de los reportes oficiales del comportamiento de las RIN [^ano_2023_1-7]. Reaparecen en la escena los casi olvidados espectros de la desdolarización y la hiperinflación que en los años 80 del siglo pasado convulsionaron al país y abrieron el período neoliberal que se extendió por veinte años.

[^ano_2023_1-7]: Con la interrupción de informes oficiales del Banco Central durante las últimas semanas, todo lo que se sabe es que se encuentran por debajo de los 3.600 millones de dólares y que, en su mayoría, corresponden al oro físico que no será monetizable hasta que el gobierno consiga convencer al ala parlamentaria evomoralista que apruebe el proyecto de ley del Oro, estancado desde hace varios meses. El Ejecutivo ha tenido dificultades para obtener el visto bueno parlamentario a la aprobación de una parte de unos 800 millones de dólares, correspondientes a créditos internacionales, los cuales no se desembolsan de una sola vez, sino en la medida que avanzan los proyectos financiados con recursos externos.

Hay un consenso manifiesto entre los economistas, incluyendo los críticos de la política gubernamental, sobre que semejante curso está contenido por la amplia preponderancia del uso de moneda nacional en ahorros, depósitos (por encima del 85%) y transacciones en general. Pero, es igualmente compartida la noción de que se requieren con gran urgencia correctivos mayores y más amplios que los ensayados por las autoridades.

La flema que estas intentan aparentar y sus explicaciones de que sólo enfrentamos “ligeros y transitorios desajustes de liquidez de moneda extranjera”, no consiguen disimular el temor que los carcome, porque es demasiado evidente que casi todo el crédito político que llevó a la elección de Arce Catacora y la favorable evolución de sus índices de credibilidad y confianza, en 2021 y 2022, dependen del control de la inflación, con un relativo mantenimiento de poder adquisitivo de ingresos y evolución de precios que supone.

El favorable repunte de las exportaciones [^ano_2023_1-8], después de las cuarentenas por la pandemia, así como una discreta disminución del déficit fiscal y estabilidad del mercado de trabajo cimentaron las expectativas sociales de que el hoy presidente podría capear lo peor de los nuevos malos tiempos.

[^ano_2023_1-8]: Que oficialmente ha alcanzado los 13.600 millones de dólares en 2022, con base al tremendo incremento de exportaciones de oro, los precios de minerales y otras “no tradicionales” que permiten suplir la caída de las exportaciones de gas natural a Brasil y Argentina (ver el apartado de Economía Enel anexo de Notas)

Pero, al verse que el rebote económico favorable de 2021 a 2022 no detiene la continua sangría de divisas por la expansión de las importaciones de combustibles, ni el descenso de producción de gas y condensado, ni el mantenimiento de presupuestos que expanden el gasto y la persistente filtración de grandes recursos desviados y dilapidados, crecen las dudas sobre la presunta aptitud financiera gubernamental y, con ellas, se instala la incertidumbre.

Al carecer de un sólido capital social y político propio, los errores sectarios y represivos que caracterizan al mando estratégico en el que Arce Catacora delega la conducción política (ministerios de Gobierno, Justicia, vocería del jefe de estado y Presidencia-en ese orden) reverberan en todos los ámbitos, se amplifican y retroalimentan el malestar colectivo.

## Desborde de la corrupción

A falta de milagros económicos, el gobierno trata de inventarlos, propagandizando, por ejemplo, una inminente industrialización del litio o alivio casi inmediato del problema de combustibles con plantas de biodiesel. Igualmente, anuncia una futura gran exportación de electricidad al Perú, posiblemente como forma de relanzar el proyecto de megahidroeléctrica del Chepete, inviable por su alto costo económico, social y ambiental y ausencia de predisposición favorable de los supuestos compradores, tanto cuando se insinuaba que sería Brasil y ahora Perú [^ano_2023_1-9].

[^ano_2023_1-9]: No menos de 12.000 MM de dólares (según investigación propia), (impacto profundo y continuo, aguas arriba y abajo del embalse. Sobre la demanda peruana ver [aquí](https://ww1.ratingspcr.com/multi/9616/5592/9962/PE-202112-ELECTRI.pdf).

La predisposición gubernamental a magnificar sus virtudes, igual que la capacidad de manipulación y perversidad que atribuye a sus clásicos enemigos (la derecha y el imperialismo), ha sido compañera fiel de una amplia liberalidad ante la corrupción que inyecta fondos para mantener una amplia clientela ávida de puestos estatales jugosos (donde es posible exprimir a usuarios o contratistas).

Tolerarla abiertamente entre los administradores de justicia garantiza fallos y resoluciones favorables al Ejecutivo, mientras sus contrarios, críticos o disidentes [^ano_2023_1-10] son perseguidos implacablemente. Esta es la razón de fondo que bloquea la reforma del Órgano Judicial, pese al rechazo popular del procedimiento para elegir candidatos judiciales, tal como se manifestó en las dos anteriores elecciones judiciales y su reclamo ante el colapso de la administración de justicia.

[^ano_2023_1-10]: Hasta la muerte, en célebres situaciones como la de Marco A. Aramayo -ex ejecutivo del Fondo Campesino-, la agonía como la del dirigente cocalero yungueño Apaza

El MAS no inventó la corrupción profunda, se limitó a continuar la tradición republicana que hizo del copamiento estatal un forma segura de crear y consolidar nuevas clases o fracciones dominantes, mediante procesos de acumulación originaria cíclica de capital. Hoy, la lucha interna ocasiona una incómoda situación, donde los “hermanos”, amigos o simples correligionarios de ayer, pasan a ser enemigos radicales que, en esta coyuntura, intercambian mutuas acusaciones de conductas ilegales o llanamente criminales en el uso del poder público.

La fracción “renovadora” imputa a los hijos del expresidente Morales; en tanto que los seguidores del expresidente señalan al mayor de Arce Catacora y a su círculo de confianza de lo mismo. Los evomoralistas acusan principalmente al vicepresidente Choquehuanca de socavar la estructura orgánica del MAS y a los luchoarcistas de ser permisivos con el tráfico de cocaína y otros delitos mayores, directamente desde los ministerios de Gobierno y Justicia. En respuesta, los atacados afirman que los reales maestros del delito son sus acusadores [^ano_2023_1-11].

[^ano_2023_1-11]: La corrupción a gran escala, como la que afecta crónicamente a la construcción de caminos, se ha complicado ahora, inclusive con aparición sorpresiva de cadáveres, tal como pasa con la confusa muerte del “testigo protegido”, ocurrida en Miami, dentro del caso de la doble vía Yamparaez-Sucre, centro de las denuncias por millonarias coimas para ejecutivos de la Administradora Boliviana de Carreteras (ABC), Este es un capítulo de una extensa secuela de irregularidades con grandes contratistas chinas.

## Gobernabilidad y gobernanza bajo fuego

Los temores económicos, azuzados por los informes de calificadoras internacionales de riesgo [^ano_2023_1-12] ocupan el primer plano coyuntural, en cuanto a la posibilidad de que se llegue a un desborde del control estatal, ante la mínima señal de que el gobierno pueda embarcarse en medidas de ajuste neoliberal (devaluación, anulación de subsidios, despidos, etc.) o desboque de la inflación.

[^ano_2023_1-12]: Las mismas que se callaron unánimemente ante las grandes señales de desastre financiero en la gran crisis internacional de 2008 (Moodys, Ficht, etc.) y, ahora, ante las señales que anunciaban el derrumbe de bancos en EEUU y Europa.

Juega en la misma dirección el ascenso de la confrontación de las facciones masistas que buscan ampliar su cuota de poder e imponer su propio candidato para la elección próxima [^ano_2023_1-13]. La directa influencia de esa pugna sobre los problemas económicos nacionales, eleva la impaciencia social, inclusive entre sectores porfiadamente fieles al oficialismo, como los campesinos y su área de influencia en otros sectores.

[^ano_2023_1-13]: Tomando en cuenta que la división se ha desencadenado alrededor de la cuestión de ganar anticipadamente la candidatura presidencial, la hasta hoy sólida alianza entre Arce y el vicepresidente Choquehuanca tiene un horizonte de riesgo de resquebrajarse. En el otro bando, la amenaza de fracturas internas estará acompasada por la acumulación de negativos electorales de Morales Ayma.

La oposición de tipo partidista, encerrada en sí misma, presiona por un ajuste estructural tradicional, mientras trata infructuosamente de capitalizar sus acusaciones de que el gobierno se ha hecho dictatorial, de manera tal que en cualquier escenario de virajes bruscos será un sector del MAS que gane la disputa [^ano_2023_1-14].

[^ano_2023_1-14]: Sin que deba descartarse que aparezcan nuevos núcleos de radicalización de derecha, como lo insinuó nacionalmente en 2019 la candidatura de Chi, Y un año después, en Santa Cruz, el triunfo de LF Camacho, con estilo y tras la ruta de Bolsonaro (Brasil) o, de manera más forzada, la que promete Milei en Argentina.

Si la desgastada gobernabilidad continúa recibiendo impactos de desconfianza económica, o se aceleran señales inflacionarias, el régimen tendrá que lidiar con una serie escasez de reservas materiales y morales que frenen su colapso.

## Notas
