---
lang: es
format: 
  html:
    page-layout: article
---

## Popularidad a prueba de fuego {.unnumbered}

Si en 2012, e incluso antes, la oposición partidista denunció la "campaña electoral permanente" que le atribuye al MAS, en este 2013 todos los actores políticos parecen embarcados en prepararse para las elecciones de octubre de 2014 [^ano_2013_1-1].

[^ano_2013_1-1]: Aunque al momento de editar y entregar este material se mantiene todavía la convocatoria para diciembre, lo más probables es que se apruebe la iniciativa del Tribunal Supremo Electoral de adelantarlas dos meses, en previsión de que pudiera darse una segunda vuelta

Por eso, si se busca un asunto que haya dominado la escena informativa en este primer semestre, se impone por volumen e intensidad la confirmación de una nueva reelección de Morales y García.

Incluso en estos días en que el flujo informativo se concentra alrededor del estruendoso forcejeo entre autoridades y la Central Obrera Boliviana (COB), una avanzadilla de francotiradores mediáticos del bando oficial ha estado hostigando a los dirigentes cobistas, afirmando que convocan y organizan la protesta "para lanzar y promocionar publicitariamente al partido" [^ano_2013_1-2], que ha decidido constituir la central sindical imitando los pasos asumidos en 1995 por quienes crearon el "instrumento político", hoy convertido en partido gobernante.

[^ano_2013_1-2]: Véase: <https://uit-ci.org/index.php/2013/03/10/bolivia-gran-congreso-convocado-por-lacob-funda-el-partido-de-los-trabajadores/>

Lo notable de la presente oleada de reclamos callejeros y cortes de ruta es que no se origina en reivindicaciones salariales, puesto que en esta oportunidad se aceptó el 8% de incremento ofrecido por las autoridades, siempre con rezongos de insatisfacción, pero después de una negociación relativamente breve y con menos incidentes callejeros que en otras oportunidades.

## Saldos acumulados

La posibilidad de aglutinar fuerzas y motorizarlas en una escalada importante, como la que se ha observado este mes, con la consigna de aumentar las jubilaciones, puede revelar algunas cuestiones poco analizadas y discutidas por los medios de difusión masiva. Habitualmente, aquí como en otros países, las demandas referidas a jubilaciones convocan casi exclusivamente a jubilados y a sus beneficiarios. Es excepcional la participación asidua y entusiasta de otros grupos, como acontece aquí, excepto cuando se anuncian recortes, que es lo que ha sucedido recientemente en España y en otros países europeos.

Según la masiva campaña propagandística que sostiene el gobierno, en Bolivia los montos cobrados por "cerca del 80% de los trabajadores asalariados se han incrementado con la nueva ley de pensiones" [^ano_2013_1-3] . En contrapartida, la posición de los sindicatos es que "Todo el ahorro del trabajador con más de 30 años de contribuciones continuas no alcanza para cubrir \[pagar\] lo que señala la Ley de Pensiones vigente: una pensión de jubilación equivalente al 60% del referente salarial del trabajador". "El resultado es que las rentas que ofrecen las actuales administradoras de pensiones, casi en la totalidad de los casos, no llegan al porcentaje fijado por ley, sino a un promedio cercano al 40%" [^ano_2013_1-4].

[^ano_2013_1-3]: Vicepresidente del Estado, entrevista-exposición, TVB, 19 de mayo 2013

[^ano_2013_1-4]: La afirmación es del CEDLA, una ONG especializada en temas laborales, y coincide con lo que señalan dirigentes de la COB, federaciones y sindicatos diversos. Véase [http://www. cedla.org/content/2933](http://www.%20cedla.org/content/2933)

Cuanto más reales las afirmaciones oficiales, más difícil de comprender resultaría el movimiento de protesta. Lo cierto es que si se considera el historial de conflictos del país, así como la experiencia ---bastante generalizada--- de que no es fácil agendar el tema de las jubilaciones como tema principal, y menos todavía como el único [^ano_2013_1-5], que es lo está pasando, tiene sustento la hipótesis de que lo que hay por detrás del reclamo explícito es un clima de malestar más o menos generalizado entre grandes grupos de asalariados.

[^ano_2013_1-5]: No me refiero a los jubilados, sino al universo de trabajadores activos contribuyentes, que difícilmente llegan a las calles por una cuestión que empieza a preocuparles cuando se acerca el momento del retiro laboral, según lo han medido múltiples encuestas en países donde se ha encarado reformas de la seguridad social. Al respecto, véase R. Acuña, Fondos de pensiones: Información, educación, cultura previsional y Asesoría entregada a los afiliados, Serie Regulaciones Comparadas, Santiago de Chile: FIAP, 2011.

Se trata, por una parte, de una disminución de la capacidad adquisitiva de los salarios [^ano_2013_1-6], escondida por la subestimación del índice inflacionario que aplica el Instituto Nacional de Estadísticas (INE) y, por otra, de la precarización de las condiciones laborales. Estas condiciones afectan a un numeroso grupo de nuevos empleados públicos, contratados como "consultores" ---y, por tanto, sin ninguno de los beneficios de los trabajadores de planta---, así como a una cantidad considerable de asalariados que trabajan en actividades informales [^ano_2013_1-7].

[^ano_2013_1-6]: Silvia Escobar y Bruno Rojas, Situación de los derechos laborales en Bolivia, La Paz: CEDLA, 2010; también véase Enrique Velazco, Excedente bruto y remuneraciones, La Paz: INASET, 2011.

[^ano_2013_1-7]: CEDLA, op. cit.: 26

Otra importante fuente de insatisfacción proviene de la acumulación de conflictos, muchas veces provocados por el propio gobierno, resueltos a medias y sometidos a treguas forzadas, como ha pasado con los trabajadores de Salud o con los policías. El intento de cercenar una conquista laboral de los primeros inició, por iniciativa de las autoridades, una intensa batalla que ahora atraviesa por un largo paréntesis en el que se realizan "cumbres de Salud", en tanto que los policías se quejan de una desatención crónica de sus reclamos y de un trato despectivo, que contrasta con los privilegios que reciben las FF.AA.

## Redes y enredos

A pesar de que el jefe de Estado cosecha índices de aprobación elevados, es ostensible que la confianza y la credibilidad de la administración están debilitadas por una prolongada sucesión de denuncias y evidencias de corrupción.

Las "barcazas chinas" y la adquisición de maquinaria para Papelbol han estado en vitrina en los meses previos, exhibiendo pérdidas millonarias, pero modestas en comparación con las que se sospecha que han ocurrido con el paquete de 2.400 millones de dólares para contrataciones de Yacimientos Petrolíferos Fiscales Bolivianos (YPFB), cuyo responsable máximo fue apresado accidentalmente.

Sin embargo, este año sobresale el develamiento de una o de un conjunto de redes de extorsión, enclavadas en centros neurálgicos del Estado. Personeros clave del Ministerio de Gobierno están presos bajo el cargo de dirigir dichas redes y beneficiarse con extraordinarios e ilícitos beneficios. Sin embargo, a pesar de su reclusión, exhiben señales de que acceden a información privilegiada [^ano_2013_1-8], y tal vez todavía cuenten con una importante influencia.

[^ano_2013_1-8]: Alude a la denuncia, apoyada en pruebas documentales, de una senadora respecto a que al menos uno de los encausados tenía datos precisos sobre quién sería elegido a la cabeza del Ministerio Público. <http://www.la-razon.com/ciudades/seguridad_ciudadana/Senadora-Gonzales-Fiscal-General-favores_0_1828017242.htm>

Son iguales o mayores las consecuencias de las denuncias contra el fiscal responsable de los llamados casos "terrorismo" I y II, debido a la alta renta política que le significaron al gobierno. La "victoria militar" a la que se refiere la teoría oficial "tras el desbaratamiento del separatismo armado organizado por el grupo La Torre" [^ano_2013_1-9], se fundamenta en la trama que debían dilucidar los mencionados casos judiciales.

[^ano_2013_1-9]: Álvaro García Linera, Las tensiones creativas de la revolución: la quinta fase del Proceso de Cambio, La Paz: Vicepresidencia del Estado Plurinacional, 2011. <https://www.bivica.org/files/tensiones-creativas.pdf>

Las primeras denuncias de que los extranjeros acusados de encabezar la célula armada murieron ejecutados y no en un enfrentamiento se han visto reforzadas por grabaciones de audio, que confirman que los fiscales del caso actuaron al compás de las ordenes políticas del Ejecutivo. Además, proliferan las quejas respecto a que los encargados de la investigación se enriquecieron chantajeando a imputados y sus familias.

## Ruta de una frustación colectiva

La ciudad de Santa Cruz de la Sierra es, con certeza, donde los hechos relacionados con estas redes de extorsión tienen más impacto, porque la mayor parte de las reales y presuntas víctimas de estas mallas político-delictivas radican allá. Sin embargo, los ecos de la decisión del Tribunal Constitucional Plurinacional (TCP) autorizando una nueva reelección del presidente y su vice tienen impacto nacional, y afectan la reforma estatal más allá de los cuellos de botella que hoy la sofocan.

La evaluación de Cusi, el magistrado del TCP [^ano_2013_1-10] que obtuvo la mayor votación en las elecciones judiciales, sobre los efectos de la sentencia que habilita la re-reelección no ha merecido hasta ahora reacciones de voceros oficiales. Sin embargo, estos mismos voceros no ahorraron adjetivos para desautorizar a la expresidenta de Diputados de la gestión pasada, que calificó el fallo como inconstitucional [^ano_2013_1-11].

[^ano_2013_1-10]: "Prácticamente hemos perdido esa cualidad de ser Tribunal, ahora todo el mundo habla mal contra el Tribunal Constitucional, y eso que nos ha costado construir la imagen, pero lamentablemente por una sentencia hemos destruido todo" (Gualberto Cusi, entrevista en radio Fides, La Paz, 16 de mayo de 2013).

[^ano_2013_1-11]: El artículo 168 de la CPE vigente desde 2009 establece que presidente y vicepresidente pueden ser reelegidos una sola vez de manera continua, y su disposición transitoria primera, inciso II, que: "Los mandatos anteriores a la vigencia de esta Constitución serán tomados en cuenta a los efectos del cómputo de los nuevos periodos de funciones".

La exuberante satisfacción oficial ante el pronunciamiento de los tribunos no sopesa el daño que produce el debilitamiento del crédito público del TCP, conquistado por esta instancia con algunas sentencias previas que enmendaron algunos yerros mayores, como la destitución de autoridades elegidas por una simple acusación formal.

Su entusiasmo le impide entender que las señales de un aparato judicial deforme y arbitrario impactan inclusive entre sus más fieles adherentes y, seguramente, contribuyen en alguna medida a alimentar diversas expresiones de protesta, incluyendo la que se ha comentado al principio de este documento.

La sentencia del TCP engrosa el flujo diario de datos que llevan a la población a sentirse desprotegida ante el crimen y las injusticias. Y es que demasiados policías aparecen demasiadas veces asociados con delincuentes o protagonizando delitos ellos mismos, mientras que fiscales y jueces, antiguos y nuevos, no dejan de exhibir su predisposición a inclinarse ante el dinero y el poder.

A ello se suma la pérdida de confianza colectiva que trae la decisión del TCP, que muestra una radical impotencia de este Tribunal para atender la sentida demanda social de construir una administración de justicia imparcial y autónoma.

## Reinado de la aritmética

Es cierto que, a estas alturas, no hay motivo para sorprenderse por el comportamiento del Ejecutivo, ya que, desde la elección de los magistrados a fines de 2011, quedó de manifiesto que había hecho lo posible para asegurarse la sumisión de estas autoridades judiciales electas, tal como antes había dejado claro que replicaría y reforzaría los tradicionales mecanismos de domesticación de los fiscales, indispensables en la hora de montar una persecución judicial a gran escala contra enemigos, rivales, competidores, disidentes o críticos.

La dureza con que actúa en este plano el partido gobernante se apoya, por una parte, en el legado ideológico del sindicalismo revolucionario y de muchas organizaciones de izquierda que se han asimilado al MAS-IPSP. Por otra, posiblemente más importante, en el sentimiento de invulnerabilidad que le reporta una sucesión de victorias electorales, que en apenas siete años se traduce en un 500% de incremento de electores (de los 581.800 obtenidos en 2002 a los 2,8 millones que lo respaldaron en la reelección de 2009) y en la evidencia de que la intención de voto se inclina nítidamente a su favor, frente a la marcada debilidad de sus competidores.

Ese cálculo supone que es automáticamente legal, justo y legítimo cualquier hecho que respalden sondeos o encuestas. La realidad, siempre más rica y compleja, muestra que la preferencia electoral de un ciudadano por una opción válida en un futuro próximo no anula su capacidad de entender que la Constitución prohíbe la reelección continua por más de una vez [^ano_2013_1-12]. Es más, que sus simpatías o inclinaciones electorales no lo privan de experimentar una profunda frustración por el desempeño de la administración de justicia, que se mantiene igual o peor después de varios años de promesas, reformas constitucional y legal, elección de magistrados y otros actos y símbolos de renovación y cambio.

[^ano_2013_1-12]: Tal presunción omite la clara evidencias de la gran selectividad de los electores bolivianos, que en 2005 y en 2010 demostraron que más de un tercio de quienes respaldan al MAS en votaciones nacionales pueden ---inclusive en el mismo día, como ocurrió en diciembre de 2005--- votar por una opción distinta, eventualmente contraria, en los comicios regionales.

La solidez de la convocatoria gubernamental se asienta, en primer lugar, en el profundo sentimiento de identidad cultural y étnica entre el presidente y una porción significativa del electorado [^ano_2013_1-13]:. En segundo lugar, en la simbología del encuentro indígena-no indígena que refleja el binomio que encabeza el gobierno y, en tercer lugar, en un rango igualmente importante, en el récord de cumplimiento de compromisos contraídos con su base social.

[^ano_2013_1-13]: Dicha franja abarca entre un tercio y un 40% de votantes, considerados ---de manera más o menos reservada por dirigentes del MAS--- su electorado cautivo. Está compuesto principalmente por la mayor parte de la población campesina (incluidos, en primer término, todos los colonizadores, y en especial los cocaleros), los cooperativistas mineros y transportistas, junto con una mayoría de pequeños comerciantes y el apoyo de pequeños (pero económicamente poderosos) grupos de empresarios que provienen de estas franjas populares, y que están muy bien representados en el Ejecutivo y Legislativo.

La Asamblea Constituyente y la reforma integral de la CPE, la recuperación del control estatal de recursos naturales, la redistribución de una parte del excedente ---proveniente del alto precio de las materias primas exportadas--- a través de bonos selectivos y subsidios, la sustitución de una porción considerable de ejecutivos y gerentes estatales por personal reclutado de sectores populares, la denuncia y penalización del racismo y la discriminación, la construcción de plantas separadoras de gas, el incremento de la participación femenina en responsabilidades públicas, la interpelación a la dominación regional por EE. UU., la extensión de redes domésticas de gas natural y la política frente a Chile son algunas de estas realizaciones. El presidente Morales y su partido han conseguido con ellas una acumulación política que se mantiene aparentemente intacta, pese:

-   a su intento de aplicar un "gasolinazo" que igualaba los precios de los combustibles en el país con los de la ciudad de Nueva York [^ano_2013_1-14]; al despliegue de miles de conflictos sociales anuales por año;
-   a la represión abierta y sistemática contra movimientos sociales, como los que impugnan en el TIPNIS;
-   a la ruptura frontal entre el relato proambiental del gobierno y su reiteración de prácticas desarrollistas rudimentarias y predatorias;
-   al reparto ilegal y arbitrario de recursos naturales ---incluyendo tierras fiscales y yacimientos mineros--- entre sus allegados.

[^ano_2013_1-14]: Las protestas en diciembre de 2010 impidieron que la medida se consolide.

Sin embargo, la baja de aprobación que se ha dado en los peores conflictos se desvanece en pocas semanas. En este momento, cuando estamos por cumplir los siete años de su primera elección, su aprobación se aproxima a los dos tercios (entre el 59% y el 60% en abril).

En este año han continuado acumulándose evidencias de que el gobierno ha decidido frenar las reformas constitucionales más novedosas, como la descentralización, las autonomías, el control social o una pluralidad económica que vaya más allá del reconocimiento pasivo de que en Bolivia, tal como en muchos otros países, coexiste una diversidad de relaciones económicas.

El ritmo de las estatizaciones ha decaído, pero eso no descarta que pueda decretarse alguna sin anuncio previo, siempre que cumpla con el requisito de lograr buenos réditos electorales.

También se han extendido las rupturas gubernamentales con sectores populares, como los indígenas de tierras bajas y los obreros mineros e industriales (que representan menos de un tercio de todos los asalariados). También se ha desatado una guerra de baja intensidad contra algunas ONG [^ano_2013_1-15] (especialmente con las que han estado trabajando con indígenas y defensa ambiental), lo que ha incrementado la severidad de la reglamentación de su funcionamiento.

[^ano_2013_1-15]: El antioenegismo se relaciona con el hecho de que el gobierno conoce, por experiencia propia, la importante influencia de estas instituciones en un sistema de representación política en el que los partidos comparten su papel y responsabilidades con organizaciones sociales y corporativas, tanto como con instituciones sin fines de lucro. No es por nada que una proporción considerable de ejecutivos gubernamentales han sido reclutados de ONG. Se trata de una suerte de guerra preventiva contra una fuente de incubación de competidores individuales y de referentes para sectores de la opinión pública muy activos.

Entre tanto, se ha consolidado una serena cohabitación con grandes grupos empresariales de las finanzas, con agroexportadores y ganaderos de la zona oriental y con consorcios petroleros y mineros.

La violencia callejera ha avanzado con la incursión de sicarios; hay señales de que grupos criminales extranjeros [^ano_2013_1-16] estarían buscando establecerse en Bolivia.

[^ano_2013_1-16]: Principal, pero no exclusivamente, el Primeiro Comando da Capital brasileño (PCC).

Frente a toda esta situación, la tendencia central es a que, entre tensiones y sobresaltos, el gobierno preserve su capacidad de control y mantenga una importante opinión favorable, apoyado en lo que se ha explicado más arriba, y en el temor, incluso entre algunos que lo desaprueban, a que en su ausencia los problemas se agravarían.

<br>

::: {style="text-align:right; font-weight: bold;"}
Mayo de 2013
:::

## Notas
