---
lang: es
format: 
  html:
    page-layout: article
---
# Aguinaldo extra y guerra anti ONG {.unnumbered}
---

Las autoridades bolivianas mantienen fresca e intacta su capacidad de sorprender y descolocar al público y, especialmente, a sus adversarios, como ha vuelto a probarse con la promulgación del decreto que obliga a todas las empresas legalmente registradas (públicas y privadas) a pagar un aguinaldo adicional al vigente [^1] cada vez que el crecimiento interanual del PIB iguale o supere los 4,5 puntos porcentuales.

Dicha decisión impacta sobre varios campos, y hasta ahora parece superar la capacidad de los críticos para abarcarla en sus múltiples dimensiones. Por lo pronto existe un amplio consenso respecto a que esta disposición, que busca ventajas electorales, incrementará la inflación en una medida difícil de anticipar, y que pondrá en apuros a un amplio espectro de empresas medianas y pequeñas, así como, ciertamente, a muchas ONG, aspecto este último del que me ocuparé más adelante.

En el espacio electoral, el beneficio que espera cosechar la administración masista es el aporte contante y sonante que deberán cotizar muchos de los funcionarios agraciados con él.

## Artillería pesada

Más importante que lo anterior es que este segundo aguinaldo implica un esfuerzo para atender diversas señales de descontento de los asalariados, cuya participación neta en el reparto de beneficios de los ingresos extraordinarios del país ha quedado rezagada en comparación con los empresarios y grupos como cooperativistas, campesinos ricos, comerciantes importadores, transportistas y otros que componen el núcleo principal del nuevo bloque de poder.

La decisión política de endulzar las relaciones con los asalariados se ratifica con la advertencia presidencial de determinar el traspaso obligatorio a manos de los trabajadores de los activos de aquellas empresas que rehúsen pagar el aguinaldo adicional [^2].

Esta amenaza buscaría diluir la noción de que la transferencia neta de los excedentes extraordinarios capturados por el país en estos años de buenos precios de los exportables se ha canalizado principalmente en beneficio del sector patronal, con un retroceso relativo de la participación de los trabajadores, pese a los incrementos salariales y al avance del mínimo salarial [^3]. Si lo consigue, se aproximará a su meta de afianzar el apoyo electoral de trabajadores desencantados con el “proceso de cambio”.

Es muy difícil anticipar la evolución que tendrá el impacto inflacionario de la inyección masiva de recursos que supone el pago del aguinaldo adicional, debido al desconocimiento efectivo de: i) la proporción de asalariados que existe en el 70% o más de puestos de trabajo que oferta la economía informal y ii) las formas en que estos asalariados tratarán de conseguir un beneficio adicional en este final de año, así como la eficacia que tengan sus negociaciones o presiones para conseguir ese propósito.

A mayor eficacia, la inflación será más elevada y se prolongará más tiempo. Lo anterior significa que el saldo favorable o adverso que puede tener electoralmente la medida oficial está aún por definirse.

El gobierno no ignora la variabilidad de una acción que, si bien ha descolocado a sus opositores [^4], genera un margen de incertidumbre lo suficientemente grande como para volcarse en su contra en determinadas circunstancias. Pero sería completamente erróneo suponer que el oficialismo se juega a una sola carta la considerable ventaja que ha acumulado frente a los siete aspirantes que hasta ahora han anunciado su decisión de competir en las elecciones de 2014.

En realidad, el próximo año empezarán a cristalizar los resultados de un ancho abanico de grandes inversiones estatales, entre las que sobresalen la planta de separación (secado) de gas natural, el satélite Túpac Katari, el teleférico para las ciudades de El Alto y La Paz, la planta de urea y amoníaco en Bulo Bulo y varias otras. Este paquete se verá reforzado por el avance o la finalización de decenas de obras camineras, que incluyen la apertura, ampliación y restauración de las principales carreteras [^5].

La perspectiva y el tono desarrollista que ha terminado por afianzarse en el discurso oficial, en detrimento de los matices indigenistas, comunitarios o socialistas, permiten augurar que la campaña para la re-reelección cabalgará sobre un pilar central que reivindicará la gran cantidad de obras ejecutadas, complementado previsiblemente por la ostentación propagandística de los resultados obtenidos en enfrentar la pobreza y la indigencia, así como en la acumulación de ahorro interno y la independencia de las decisiones nacionales frente al imperialismo.

La importancia que la conducción estatal asigna a las inversiones y obras no se reduce a la intensificación geométrica de la propaganda sobre estos temas, sino a la notable promoción que se ha dado a los acuerdos entre el gobierno y la cúpula empresarial cruceña, a tal punto que el mayor publicista oficial ha caracterizado el ingreso del presidente a la feria cruceña (la Expocruz) como la “expresión de la hegemonía revolucionaria”, y el propio mandatario ha reaccionado ácidamente a críticas sobre lo forzado de tal caracterización.

## Cuesta arriba

La oposición política exhibe la misma falta de reflejos y de recursos de siempre, y su mayor muestra de recuperación se restringe a exhibir señales de aglutinamientos parciales, cuya máxima expresión es el Frente Amplio, seguido por el anuncio de agregación de “sectores” que ha publicitado el MSM antes, durante y después de la realización de su congreso.

El lanzamiento de la candidatura del máximo dirigente de esta organización puede interpretarse como una expresión de la limitación de sus posibilidades y de la fragilidad de las adhesiones grupales que proclama haber conseguido, ya que ninguno de tales aliados ha podido proporcionarle siquiera una candidatura vicepresidencial [^6] novedosa.

Algunos medios han interpretado que el hecho de que discursivamente el FA, el MSM y el MDS se inclinen por caracterizar al país como una república y no como un Estado podría ser el punto que permita la confluencia de todos ellos, o de los principales, en una sola fórmula electoral (Página 7, 15 de diciembre de 2013). Dicho pronóstico expresa, seguramente, un elevado voluntarismo y una muy escasa solidez, porque una abstracción teórica y doctrinal tan elaborada no parece tener mayor atractivo para el electorado al que aspira atraer.

Tal y como están evolucionando los acontecimientos, la oposición puede mellar considerablemente la capitalización de lo que hasta hoy parece ser su mayor oportunidad: avanzar en su presencia parlamentaria [^7]. Ninguno de los opositores ha planteado, ni remotamente, ideas novedosas, como la de llevar a toda la plana mayor de los diferentes partidos y frentes al Parlamento y presentar nuevas figuras para candidatos presidencial y vicepresidencial. Estas figuras, eventualmente desconocidas, seguramente tendrían las mismas posibilidades (si es que no mejores) que las de sus jefes para reclutar adhesiones.

Si la oposición continúa descuidando el espacio legislativo, que hasta ahora se muestra como el más promisorio para su disputa con el oficialismo, no solo reeditará el pobre resultado de la acción de sus bancadas (incluyendo la elevadísima tasa de deserciones abiertas y encubiertas). Contribuirá también a fortalecer las ya muy marcadas tendencias continuistas del partido de gobierno, no solamente para las próximas elecciones, sino para varias otras, en una ruta bastante afín a la del orteguismo [^8] en Nicaragua.

## Una guerra privada

Si bien las políticas de máximo control y ajuste sobre las ONG no se restringen a Bolivia, sino que están ampliamente diseminadas en el planeta independientemente de la línea ideológica que ostenten los gobiernos, es bastante claro que nuestro país sobresale en la rigurosidad de las medidas y del discurso público anti ONG de las principales autoridades.

En el análisis de mayo de 2013 de este boletín, se ha examinado el origen del encono oficial contra las fundaciones y organizaciones que desarrollan actividades entre los indígenas y campesinos y en temas de derechos humanos y ambientales [^9]. Además de la sensibilidad “estratégica” de estas áreas, el gobierno es especialmente celoso de las tareas que desarrollan porque sabe, por experiencia propia, el alto potencial ideológico, organizativo, agitador y propagandístico de esas labores.

El gobierno exhibe ante todas ellas igual o mayor susceptibilidad que frente a un partido opositor porque está consciente de que, en un sistema de representación política como el nuestro, algunas ONG,—al igual que sindicatos, organizaciones sociales y corporativas de diversa naturaleza, medios masivos de difusión y otras instituciones— pueden comportarse como instancias informales de mediación y representación política. Por lo tanto, actúa frente a ellas en concordancia.

El pago del segundo aguinaldo amenaza con colocar a varias ONG en una situación de insolvencia insostenible. Esto ha empujado a que la red UNITAS se haya visto forzada a pronunciarse públicamente sobre el tema y sobre la autocensura que prevalece en el ámbito de las ONG en general por temor a represalias del régimen. Esta situación de coyuntura es un claro anuncio de que en los 16 meses próximos de campaña electoral agudizada [^10], hay espacio para que la ya conocida hostilidad estatal frente a las ONG se mantenga e incluso se exacerbe.

<br>

::: {style="text-align:right; font-weight: bold;"}
Diciembre de 2013
:::


## Notas

[^1]: Así tenga un carácter esencialmente retórico, este aguinaldo extra se trata probablemente de la primera propuesta del gobierno que podría caracterizarse como anticapitalista (aunque victimice eventualmente a los representantes más débiles y precarios de este modo de producción).

[^2]: El avance concreto del capitalismo durante estos años se refleja, especial y concretamente, en el incremento de la masa de trabajadores asalariados, independientemente de la “formalidad” o “informalidad” con que se despliegue la compra-venta de fuerza de trabajo. Los cosechadores de coca, los empleados de los comercios “populares” o la masa de cooperativistas, como ejemplos, cobran y viven de un salario, independientemente de que estén o no registrados en las cuentas nacionales.

[^3]: INASET, Ensayos para el Debate, La Paz, julio de 2011.

[^4]: A algunos, como los ex “verdes” y ahora “demócratas”, tan profundamente que su reacción inicial fue adoptar una posición contraria más dura que las asociaciones empresariales, con argumentos absolutamente propatronales. La rectificación de este reflejo se demoró en llegar y el daño electoral en las regiones a las que aspiran extender su influencia tiene grandes probabilidades de ser considerable.

[^5]: No formará parte de este paquete vial la conexión entre Cochabamba y el Beni, a través del TIPNIS, porque está perfectamente claro que el gobierno ha optado por postergar esta pelea seguramente hasta después de las elecciones.

[^6]: En este punto de avance del proceso electoral parece haberse descartado un viraje novedoso, como podía haber sido el que toda la plana mayor de las fuerzas opositoras se postule para puestos en la Asamblea Legislativa. De acuerdo a las tendencias de intención de voto detectadas por las encuestas, este será el principal campo de disputa, y un fuerte asalto opositor al mismo podría plantear serios desafíos a la próxima gestión de los reelectos. La rutinaria y previsible conducta —hacia la que se encaminan las fuerzas opositoras— de ofertar a sus principales figuras como candidatos perdidosos, puede debilitar sus chances de avanzar también en el campo legislativo.

[^7]: Los sondeos muestran la posibilidad de que la oposición pueda llevarse el 40% de las bancas. Las mediciones se refieren a partidos solos, es decir, no a una hipotética coalición única, que —si bien tendría poco o ningún impacto en disputar el gobierno— podría incrementar las posibilidades de elevar la cuota parlamentaria ajena al oficialismo.

[^8]: El Parlamento de Nicaragua ha aprobado en las últimas semanas una enmienda constitucional que permite al presidente Daniel Ortega postularse a la reelección sin límites.

[^9]: Están, por otro lado, las ONG que se desempeñan en otras áreas, pero que son igualmente hostigadas por una razón distinta; es el caso de las que financia la agencia estadounidense USAID.

[^10]: Se trata de dos campañas: para las elecciones nacionales y para las elecciones subnacio- nales para gobernaciones y municipios, hasta marzo de 2015.