---
lang: es
format: 
  html:
    page-layout: article
---

# Guerra externa, fracturas internas {.unnumbered}

La tremenda erupción de una guerra internacional de alto riesgo global, alimentan el retorno el retorno de tensiones y de los temores más atávicos de la humanidad, mientras que en el país han terminado por hacerse inocultables las rajaduras de la maquinaria política nacional más formidable de la que tengamos memoria.

## Es un monstruo grande y pisa fuerte…

La descomunal movilización militar rusa sobre el territorio ucraniano, al ritmo de la justificación putinista que porfía en que se trata de una acción defensiva y a “desnazificar” el gobierno de su vecino y excolonia.

La ilusión del agresor de que se trataría de una excursión relámpago, de días o semanas, ha muerto y, por lo pronto, ha forzado más bien una semi resurrección de la OTAN y le ha abierto la mejor oportunidad de los últimos años a EE.UU. de mostrarse en la escena como líder del capitalismo avanzado y la democracia , en el instante mismo en que su división interna lo carcome sin piedad.

En esta guerra que ha empeorado las serias perturbaciones de los mercados mundiales, en cuanto al bloqueo de circulación de mercancías y consecuente estímulo de la inflación que trajo la pandemia, se repite la regularidad histórica de que son administraciones demócratas, por encima de las republicanas, las más propensas a darle fuelle al belicismo estadounidense y a su industria bélica.

Encarecimiento y escasez de combustibles fósiles, alimentos, acumulación de pérdidas comerciales y ruptura de las cadenas de abastecimiento son los primeros grandes costos económicos que contribuyen a que la bestialidad propia de cualquier invasión, agravada por las noticias de masacres de civiles y crímenes de guerra, incrementen la factura acumulada rusa, ya bastante alta con las sanciones aplicadas por Europa y EEUU.

La condena contra la agresión y el uso de la fuerza no es universal debido a la prescindencia china, sesgada hacia Rusia (según caracterización norteamericana), más el escuálido y respaldo de un puñado de países que han optado por el apoyo franco, o el vergonzante que consiste en abstenerse en los foros internacionales cuando toca censurar la guerra.

El fondo de lo que se juega con la invasión rusa es grande y complejo porque, entre sus fines mayores, apunta a colapsar la hegemonía estadounidense, aprovechando el interés chino en el mismo objetivo y la debilidad relativa de la Unión europea, por su dependencia energética y sus contradicciones internas.

Con la intención de apuntalar su apuesta, Rusia amenaza con la posibilidad de escalar el conflicto, primero, mediante el uso de armas nucleares tácticas, e inclusive, más adelante, su despliegue irrestricto, en caso de que Putin advierta el riesgo de perder completamente el conflicto, momento en el que aparentemente prefiere llevarse al mundo por delante.

## Desacralización y sus efectos

Las sombras que predominan en el telón de fondo global, del cual ni siquiera se ha despejado la posibilidad de que la pandemia pueda rebotar con una gran ola, pese al avance de la vacunación, no ha causado mayores cambios de nuestro tradicional ensimismamiento nacional, que nos mantiene enfrascados en nuestras propias obsesiones.

La mayor huella de los sucesos internacionales se ha limitado a las críticas internas que levanta la diplomacia gubernamental, alineada tras una curiosa lectura ideológica favorable al despliegue bélico pro ruso, contradiciendo nuestra Constitución y experiencia histórica de víctima de agresiones. Llegamos al extremo de que mayor organización corporativa del país ha criticado la tibieza del gobierno por no respaldar con todo a Rusia.

En el plano interno, el rasgo más destacado de estos meses es el reforzamiento de la tendencia al choque abierto entre las facciones internas del MAS. En esta fase, las pugnas han llegado al hasta hace poco impensable grado de que manifieste una impugnación desembozada de las decisiones y la palabra de J. Evo Morales Ayma, como lo que era hasta hace muy poco: la única y última instancia de resolución interna de conflictos.

El sentimiento de orfandad que provocó su escape de 2019 en una significativa y no cuantificada franja de adherentes, ha terminado por hacerse completamente visible, después del apresamiento de Maximiliano Dávila, exjefe nacional de la FELCC. A partir de su captura, en la víspera de Alasita, Morales Ayma se ha sentido obligado a replegarse en el Chapare, restringiendo severamente sus conocidos y frecuentes vuelos al exterior (salió solo una vez a Argentina), atemorizado, aparentemente, por la posibilidad de que la imputación de la DEA contra Dávila, por tráfico de cocaína, pueda alcanzarlo como protector del exjefe policial y esto conduzca a su apresamiento fuera del país.

Críticos como la alcaldesa Copa, un expulsado diputado adicto a Choquehuanca y otros, que se presentan a si mismos como cercanos a Arce C., han arreciado sus críticas contra el expresidente y su séquito de seguidores íntimos, provocando que Morales explote contra los que llama traidores y resentidos, y sintiéndose obligado a continuación de aclarar que su bronca no apuntaría al gobierno del candidato que él mismo designó.

Lo más importante de la agudización de estas tensiones es que las organizaciones corporativas, en especial las campesinas, han sentido incrementarse su poder, al abrirse la posibilidad de que por vez primera les toque el rol de jueces de sentencia en las pugnas internas.

Si se llega a tal extremo, estaríamos frente a un verdadero cambio cualitativo, en el sentido de que, por vez primera desde su fundación, el MAS como coalición (instrumento) de las mayores organizaciones sociales se desplazaría en sentido de darles un sitio protagónico, a costa del eclipse de su caudillo único e incuestionable, hasta hoy.

Es bastante probable que la dirigencia corporativa – y más bien conservadora y poco dada a plantear iniciativas- no termine de enterarse de la posibilidad de apertura de un nuevo ciclo de la única organización política nacional existente. Por el momento, un primer producto de los cambios en la alineación de fuerzas interna del MAS, es el fortalecimiento de la imagen y proyección del actual presidente del estado, según varias encuestas realizadas este año. Esa situación es favorable a promover más modificaciones y alianzas inesperadas.

El límite político inmediato de las proyecciones de Luis Arce es su desarraigo social, propio de una figura sustancialmente tecnocrática, funciona en sentido de volverlo a empujar a que busque refugio en las organizaciones sociales, porque el proyecto de inventarse un partido propio del que dice provenir (el PS1), luce menos viable que hacer aparecer súbitamente el océano de gas que prometió el gobierno de Morales Ayma.

Al mismo tiempo, la oportunidad que se le presenta a la dirigencia de las organizaciones sociales de copar la conducción del aparato, tropieza con dos grandes murallas. El profundo caudillismo de los dirigentes, que los empuja a buscar un jefe político, y el egoísmo sectorial, propio del corporativismo que les dificulta una visión integral de los problemas que les permita formular propuestas que lleguen y muevan al conjunto de la sociedad.

De todas maneras y con la carga de sus contradicciones, el MAS pueda sobrevivirlas, inclusive cómodamente, mientras no se produzca una profunda democratización y renovación de las organizaciones sociales que le dan cuerpo y permanezca vacante la plaza de un competidor serio.

## El primer aprieto

El desempeño de la política económica es, simultáneamente, la mayor fuente actual de satisfacciones y origen de las más grandes amenazas que lo rodean.

De satisfacciones inmediatas, en la medida de que el pragmatismo prevaleciente que inclinó en su favor la balanza electoral, bajo el supuesto de que, era la opción que tenía mayor experiencia y la cintura más hábil ante los conflictos sociales, acepta con rezongos el desempeño anotado hasta hoy.

Con la ayuda del repunte de los precios internacionales de materias primas y, también, con el catastrofismo sin matices de los augurios de especialistas y opositores políticos.

La baja inflación y la volátil recuperación de puestos precarios de trabajo, que se perdieron en la cumbre de la pandemia, hacen que el clima de opinión prevaleciente sea favorable al oficialismo.

Según amplio consenso de los expertos, los límites de esta situación se encuentran en que el endeudamiento se ha acelerado, mientras la capacidad de pago se mantiene básicamente estática, presionando el descenso de las reservas internacionales, que no consigue revertirse, ni con la favorabilidad de los precios internacionales.

No termina de esclarecerse si la aparente indiferencia gubernamental ante las amenazas, que incluyen el poderoso déficit fiscal, se deben a una poderosa fe en nuevas teorías sobre la elasticidad de la capacidad fiscal de endeudarse, o en una ceguera, hija del miedo a escrutar escenarios.

En cualquiera de las opciones, el gobierno mantiene obstinadamente las fuentes formales de pérdida de recursos como son el funcionamiento de empresas fracasadas, igual que las informales, que son el desvío de recursos colectivos a bolsillos individuales y de pequeños grupos, a través de licitaciones y contrataciones fraudulentas.

El inconmovible respaldo a autoridades como el gobernador potosino, el mantenimiento de jefes policiales y militares con antecedentes judiciales por desfalcos, o la denunciada implicación de la familia presidencial en proyectos y contratos de YPFB, no ocasionan ni cambios, o siquiera gestos de enmienda.

Tanta frialdad ante tan grandes problemas obedece, primero, a que no ven asomo de oposición política y electoral, política y, en segundo término, a que tampoco aparecen se articula un reclamo social de peso.

## Policía política y reforma imposible

Pese a su pérdida de fuerza interna, Evo Morales sigue imponiendo la línea que busca fortalecer su imagen (fue golpe, no rebelión popular); mantener la represión selectiva sobre cualquier posible competidor y paralizar a cualquiera con el uso discrecional de la administración de justicia.

En este momento debe lidiar con nuevos problemas porque para mantener dominio sobre la Policía, ha tomado la iniciativa de denunciar protección oficial sobre el tráfico de cocaína y acatamiento de la DEA, tensando así contradicciones de la Policía y con el Gobierno.

El descontrol policial es tan hondo (protección de delitos, redes criminales con fiscales y jueces, etc.), que no le resulta confiable al régimen para conducir la represión y control político selectivos.

Esto ha fortalecido la tendencia de convertir a la administración de justicia en la policía política del régimen, al punto que esto llega a ser una característica propia del proceso de cambio. El problema es que este manejo ha potenciado la quiebra y descomposición judicial a extremos inverosímiles.

El funcionamiento de consorcios entre jueces, fiscales, funcionarios administrativos, peritos y otros ha sido desnudado, una vez más, mostrando algunas de sus peores iniquidades, como el arropamiento de asesinos de mujeres y menores, y de toda laya de traficantes.

Esto se complica aun más con la ineficacia policial para enfrentar la violencia ascendente en el tráfico de tierras, que ya llega al extremo de promover choques no solo entre colonizadores e indígenas, sino entre colonizadores y campesinos.

La misma ineficacia salta a la vista en cualquier acción requerida para frenar las invasiones de la minería ilegal y el potente avance sobre territorios indígenas y reservas naturales. La deliberada impotencia policial se calca en la administración de justicia.

De allá que la credibilidad para intentar cualquier reforma judicial está despedazada de inicio, pero hasta ahora no existe una organización, ni política ni de la sociedad civil que ponga el acento en que el primer paso de cualquier cambio positivo en ese espacio exige restituir la vigencia plena de la CPE y la renuncia del TCP, como ejecutor del golpe que declaró inconstitucional a la CPE y abolió la soberanía popular al desconocer el referendo de aprobación de la CPE (2009) y el 21 F.

Si la acumulación de demandas atrasadas o no escuchadas (reactivación económica y transformación productiva, pacto fiscal, alto al tráfico de tierras, freno a los abusos del poder y la corrupción, entre las más importantes) encuentran un paraguas democrático único (vigencia irrestricta de la CPE-fuera el TCP, por ejemplo) que enfrente la estrategia oficial de reproducción indefinida del poder, existiría alguna brecha para que las quejas se conviertan en iniciativas y recuperación de confianza en las propias fuerzas de la sociedad civil y los sectores populares.
