---
lang: es
format: 
  html:
    page-layout: article
---

# Triunfo anunciado {.unnumbered}

En un análisis previo en el que se consideró las perspectivas del proceso electoral, se dio por hecho el triunfo de la fórmula oficial. Con base a los estudios de opinión sobre intención de voto y aceptación de la gestión de gobierno y principales autoridades, se pensó que era bastante probable que los reelectos consiguiesen una votación porcentualmente más próxima a la que lograron en 2005 que a la de 2009 [^ano_2014_3-1].

[^ano_2014_3-1]: Véase el análisis titulado "Popularidad a prueba de fuego", de mayo de 2013.

Ha sucedido, sin embargo, que los votos del MAS quedaron casi al medio de los que consiguió en ambas oportunidades. Obtendrá cerca de los 2,9 millones de votos a su favor en la anterior elección nacional, si es que se validan el "conteo rápido" y las proyecciones hasta el 15 de octubre. La novedad es que asciende al primer puesto en todos los departamentos, excepto en Beni.

La incertidumbre respecto a si este resultado alcanzará para que controle dos tercios en ambas Cámaras legislativas es, en gran parte, artificial y retórica. Aunque la diferencia fuese uno o dos diputados más que en las anteriores, la experiencia demuestra palmariamente que el MAS domina todas las artes para triunfar en cualquier votación legislativa [^ano_2014_3-2] y, desde luego, y con toda seguridad, en las más importantes.

[^ano_2014_3-2]: Hay que agregar a los antecedentes parlamentarios de la legislatura 2010-2014 las instantáneas conversiones de militantes ajenos, que hasta un día antes de pasarse a sus filas les juraban repugnancia eterna, como la diputada de CN y luego vocera del PDC que pasó a ser una devota oficialista pocos días antes de la elección en Santa Cruz.

Por otro lado, la lealtad de sus votantes ha quedado tan manifiesta que, desde un inicio, anula los intentos de explicar los resultados con razones "técnicas" (diversas modalidades de fraude, publicidad masiva y anticipada, uso de recursos estatales, etc.). En general, esta manera de interpretar los hechos obvia tener en cuenta los factores esenciales de la victoria oficial.

Estos factores decisivos pueden resumirse en: i) aprobación a la gestión económica (control de recursos naturales, redistribución de excedentes, alta inversión pública, descenso del desempleo abierto); ii) identificación cultural y étnica de buena parte de los electores con el jefe de Estado; iii) cumplimiento de la mayor parte de los compromisos electorales previos (nueva CPE, nacionalización, etc.); iv) política exterior no subordinada a EE. UU., propuesta marítima innovadora; y v) apertura y ampliación de derechos y posibilidad de participación política para importantes sectores sociales, anteriormente excluidos o desconocidos por el Estado.

Lo anterior no significa que los electores hayan perdido una capacidad crítica que los lleva a negar los significativos y recurrentes indicios de comisión de delitos, errores y fallas de muchos funcionarios, incluyendo a los de mayor rango [^ano_2014_3-3]. Se trata, más bien, de un comportamiento ampliamente extendido en todo el planeta que se caracteriza por la habitual preferencia por lo conocido, mucho más cuando hay posibilidades de que un cambio pueda venir acompañado de turbulencias económicas y políticas. Esto predispone a pasar por alto las faltas reales o presuntas, especialmente cuando la opción seleccionada compite con propuestas ya conocidas e intrínsecamente desacreditadas en la mayor parte de los casos.

[^ano_2014_3-3]: "Gasolinazo", represión a indígenas, redes de extorsión, gastos fallidos (Papelbol, barcazas, etc.) y excesivos, en una lista preliminar y no exhaustiva.

La franja de los electores esencialmente inmunes a aceptar las críticas, sin importar lo fundadas que estas sean, se reduce probablemente a menos de la mitad de quienes han persistido en favorecer con sus votos al oficialismo; más concretamente, son quienes subordinan su decisión electoral a consideraciones identitarias, antes que a las ideológicas o prácticas [^ano_2014_3-4].

[^ano_2014_3-4]: El escaso peso de lo ideológico en estas elecciones se ha verificado por la alta tolerancia de los electores a "acuerdos inéditos" de casi todos los frentes competidores, sumada al importante porcentaje de quienes respondían en los sondeos preelectorales que su segunda opción de voto era, precisamente, el principal rival de la candidatura que apoyaban (es decir, un votante de UD que votaría por el MAS, y viceversa), según el registro de la encuestadora IPSOS.

La preservación del capital electoral y la consecución plena del conjunto de objetivos de su estrategia en esta fase otorga a los gobernantes una cómoda base para avanzar a su segunda etapa, que consiste en consolidar las posibilidades de preservar el control del Estado como mínimo hasta 2025.

## Impacto en el sistema de partidos

Una de las consecuencias más visibles de los resultados del 12 de octubre es que, mucho más que en los años anteriores, el MAS queda como partido solitario en la escena nacional porque ninguno de los otros exhibe las mínimas condiciones para asegurar su continuidad fuera del ámbito formal.

UD (el segundo en votos) nunca se propuso ser más que un acuerdo circunstancial, y así lo ha recordado uno de sus principales voceros [^ano_2014_3-5], por lo que está en duda su reaparición en las elecciones regionales.

[^ano_2014_3-5]: Véase: <http://www.paginasiete.bo/nacional/2014/10/14/alianza-solo-para-comiciosnacionales-35222.html>

Pero ---dejando para más adelante el análisis de lo estrictamente referido a los partidos--- se corrobora en este punto que el MAS, aparte de haber escalado más allá de su rol previo de partido dominante, concentra hoy en sus manos el control del conjunto del Estado, así como de los principales mecanismos de representación política, formales e informales, incluyendo a las principales organizaciones sociales y corporativas y a buena parte de las empresas y cadenas mediáticas más influyentes [^ano_2014_3-6].

[^ano_2014_3-6]: En su publicación de 2013 Control remoto, el periodista Raúl Peñaranda aporta amplia información respecto al control gubernamental sobre cadenas televisivas, el matutino La Razón y varios otros medios.

Dicha capacidad puede facilitarle la gobernabilidad y el manejo de conflictos que surjan en el desenvolvimiento de su gestión. Sin embargo, en situaciones de crisis declarada, la inexistencia de canales para expresar demandas, descontento o propuestas incrementa las posibilidades de que los conflictos de alta intensidad deriven fácilmente en estallidos [^ano_2014_3-7]. La ineficacia del sistema de representación es una segura incubadora de movimientos sociales (no de organizaciones sociales, con las que se los suele confundir), como hemos observado en la historia de nuestro país, en especial la más reciente.

[^ano_2014_3-7]: La movilización que a inicios de 2010 protestó contra el "gasolinazo" y, finalmente, lo frenó es un típico ejemplo de estallido por falta de ruta de expresión. A los partidos opositores no les dio ni la talla ni la celeridad para responder, mientras que del Parlamento o de las organizaciones sociales controlados por el MAS no llegó a levantarse ni una sola voz sintonizada con la reacción popular.

El debilitamiento del sistema de representación, debido al control que ostenta sobre él el partido de gobierno, se expresará también en pugnas y fracturas internas de sindicatos y otras organizaciones sociales; en algún momento, estas pueden alcanzar el mismo centro monopólico de poder en que se está convirtiendo el MAS.

El incremento de inestabilidad dentro las organizaciones sociales puede dar lugar a su largamente postergada reforma interna, o a un prolongado debilitamiento y mayor pérdida de representatividad.

## Las elecciones que vienen

El hecho de que el MAS sea la única organización política con presencia nacional no le garantiza replicar los resultados de este mes en las elecciones regionales del año próximo. Es lo que nos muestran múltiples y persistentes experiencias previas, según las cuales es probable que experimente una merma de entre un cuarto a un tercio del apoyo que acaba de obtener [^ano_2014_3-8]. Esto, a pesar de haber incrementado su posición de ventaja, ante el debilitamiento extremo de sus rivales.

[^ano_2014_3-8]: Así ocurrió en 2005 con la elección de prefectos el mismo día de la elección nacional, y en 2010, a pocos meses del triunfo nacional de finales del año anterior. La revisión de experiencias previas exhibe el mismo comportamiento, cualesquiera haya sido el partido ganador de la contienda nacional.

Es decir que debe entenderse que el resultado de octubre no se calca automáticamente en las elecciones municipales de La Paz, por mencionar un caso, incluso en la eventualidad de que el MSM pierda su personería jurídica. En el otro extremo, los resultados del Partido Verde [^ano_2014_3-9], con lo inesperados que puedan considerarse, no le garantizan éxito ni donde ha obtenido mejor votación.

[^ano_2014_3-9]: Se arriesga aquí la hipótesis de que la mayor parte del muy significativo apoyo que ha obtenido el PV se debe a la memoria y al sentimiento de alerta que provocó, y que aún despierta, la lucha de los pueblos del TIPNIS y al eco que lograron los pueblos indígenas (expulsados del bloque de poder) en sectores sociales urbanos, así como a la creciente influencia de causas y conflictos por la destrucción y deterioro de la naturaleza y el medio ambiente.

La estrategia oficial se impuso principalmente gracias a que los partidos opositores carecieron, en mayor o menor medida, de la objetividad suficiente para entender que, al no tener chance para ganar el gobierno, podían concentrar fuerzas en la disputa parlamentaria inscribiendo a sus principales referentes en candidaturas para legisladores. Esto, en vez de desgastarse en la disputa por encabezar las alianzas o coaliciones [^ano_2014_3-10].

[^ano_2014_3-10]: Un acuerdo entre el MSM y el PV, encabezado por la candidatura de este último, y con una lista de candidatos a legisladores que incluya al ahora exjefe del MSM, sirve como imagen para especular el giro que pudo experimentar la reciente pugna electoral si los opositores, sin necesidad de aglutinarse en un bloque único, escogían al Legislativo como el principal objetivo y campo de batalla

Las elecciones regionales son un campo de lucha altamente diferenciado del nacional. No se trata de mundos separados, pero está probado que el pragmatismo de los electores llega a lo superlativo en las elecciones regionales [^ano_2014_3-11], por lo cual es altamente probable que en ellas se produzcan nuevos e inesperados acuerdos, trituradores de cualquier frontera ideológica. Más importante todavía es que los electores se muestran muy abiertos y sensibles a la influencia de personas que consideran más próximas y accesibles, como ocurre con una importante proporción de dirigentes regionales y locales [^ano_2014_3-12].

[^ano_2014_3-11]: Factor clave para entender por qué el actual alcalde Santa Cruz de la Sierra correrá con tan grandes posibilidades de reelegirse, con el respaldo del MAS, sin importar todas las acusaciones contra este funcionario en materia de corrupción y agresión contra las mujeres.

[^ano_2014_3-12]: Las votaciones en Beni, Chuquisaca y Tarija muestran una vez más que es más fácil encontrar evidencias de influencia de dirigencias regionales sobre la elección nacional a que los electores obedezcan a quienes eligieron como dirigentes nacionales, si estos tratan de cambiar sus preferencias locales o regionales.

## La agenda que se abre

La completa falta de claridad de la oposición política la privó de apuntar a las grandes falencias del gobierno para cumplir los principales mandatos que recibió. La construcción de una economía plural, la democracia intercultural, la descolonización, la descentralización, la autonomía, la participación, el control social o el vivir bien son a la fecha enunciados o simples frases; su consecución está, cuando no retaceada o congelada, postergada indefinidamente.

El MSM se refirió a estos temas circunstancial y entrecortadamente. No lo hicieron la UD ni el PDC, que representan a la franja electoral más hostil y desconfiada a las transformaciones que se han realizado, y cuyas jefaturas no entienden que la posibilidad de conducir alguna vez el Ejecutivo continuará bloqueada si no se proponen entrar en contacto, relación y cercanía con una porción del electorado que apuesta ahora por el MAS.

Para los reelegidos, los principales retos que deberán encarar son: i) la disminución de ingresos que afrontará el país, a consecuencia de la disminución de precios de los hidrocarburos y minerales; y ii) las pugnas internas de su aparato de sustentación política.

Los organismos financieros internacionales, las consultoras internacionales más publicitadas y algunos de los gurús económicos más frecuentemente citados apuestan unánimemente a que la disminución de precios de las materias primas afectará a todos, y que será muy marcada y sostenida. Sus pronósticos se han estado cumpliendo más lenta y menos intensamente de lo que esperaban; pero incluso bajas menores y no muy prolongadas tienen efectos mayores en economías como la nuestra. Una menor disponibilidad de recursos espolea las luchas sectoriales que conocemos y puede, además, reavivar las aletargadas reivindicaciones de autonomía en todos sus niveles.

Las demandas de igualdad, no circunscrita a movilidad social por mayores ingresos ---como son los crecientes reclamos ante el avance de la violencia contra mujeres y menores---, seguirán creciendo. En este mismo espacio se inscriben las luchas indígenas por ejercer los derechos que les reconoce la CPE, y que les son recortados, cuando no negados [^ano_2014_3-13]. Esta situación puede profundizarse por la posibilidad de que se dé nuevo impulso al proyecto de carretera a través del Territorio Indígena y Parque Nacional Isiboro-Sécure (TIPNIS) y que se lleven a la práctica los anuncios presidenciales de "revisar" la situación de varias tierras comunitarias de origen (TCO).

[^ano_2014_3-13]: La división de la CIDOB y la CONAMAQ, impulsada por el gobierno central, la represión a dirigentes y bases en el TIPNIS y el manejo de las consultas previas son algunos antecedentes de este problema.

En suma, la menor disponibilidad de ingresos dificultará el cumplimiento de varios compromisos electorales, frente a una sociedad más dispuesta a incrementar sus demandas que a resignarlas. Esto incluye una tendencia a que se exacerben querellas corporativas (por ejemplo, cooperativistas contra trabajadores asalariados o colonizadores versus pueblos indígenas), además de reivindicaciones sectoriales y regionales.

::: {style="text-align:right; font-weight: bold;"}
Octubre de 2014
:::

## Notas
