---
lang: es
format: 
  html:
    page-layout: article
---

# Épocas de marchas y contramarchas {.unnumbered}

Se observa un intento de cambio de libreto destinado a centrar la atención pública en una teatral pelea entre centralistas y federalistas, como aparente respuesta a una rudimentaria asimilación por parte del señor Morales Ayma y su equipo de campaña de que la discusión golpe-fraude hartó a la población, como lo prueban tres importantes retrocesos sucesivos a los que han obligado las protestas sociales al gobierno en un lapso notoriamente breve.

Se perfila así el plato fuerte de una operación ideológica y propagandística que tape a los ojos del público que gobiernistas y contrarios políticos comparten la misma falta de proyecto y de respuestas concretas ante el crecimiento de los problemas del país.

## Unidad de contrarios, el campo de lucha ideológica

Después de tres dolorosos recules [^1], la cúpula del MAS decidió, como primera meta, una gran marcha, de una semana de duración, para opacar sus derrotas. Como segunda meta, afianzar el relato de que fueron sus enemigos políticos —como la gobernación cruceña y el comité de ese mismo departamento —quienes dirigieron las movilizaciones que tumbaron sus decisiones y leyes, y no la propia base masista, como efectivamente ocurrió. La tercera meta —aparentemente semiimprovisada durante el avance de la marcha masista— busca perfilar como nueva amenaza a combatir un separatismo disfrazado de federalismo, justo en el momento en que la dirigencia oficialista empieza a notar el desgaste de su enfoque actual para reparar y relanzar cuanto antes la figura de Morales Ayma como próximo
presidente.

La iniciativa de forzar un viraje de la atención colectiva hacia una discusión que contraponga el maravilloso porvenir que nos espera si abandonamos, sin apenas haber comenzado, la construcción de las autonomías con participación y control social, para sustituirlas por un misterioso modelo federalista cuyo contenido desconocen de momento inclusive sus impulsores [^2], ha encontrado, en principio, una disposición muy favorable de los mayores medios de difusión masiva.

Si la operación conjunta de una parte de la oposición con el oficialismo, apoyada por medios de difusión masiva, resulta exitosa, queda asegurado que las redes digitales reforzarán la tendencia. Pero, incluso con tan formidable convergencia, es dudoso que la gente acceda a tomarse una pausa mucho más allá del primer mes de 2022 en el ascenso de las demandas que exigen soluciones para sus más urgentes problemas. Es igualmente incierto que opte por postergarlos para tomar bando (pro o antifederal), como se lo están proponiendo los actores más visibles de la escena política.

La dificultad de colocar la discusión sobre pro y antifederalismo como preocupación central de la sociedad no la hace necesariamente una tarea imposible, especialmente si la sequía de propuestas y proyectos se mantiene tan estática como hasta ahora. Ya hemos visto en otras ocasiones cómo un asunto esencialmente ajeno al interés y comprensión comunes puede llegar a convertirse en un gran paraguas de múltiples reivindicaciones parciales [^3].

En cierta medida, algo parecido ha ocurrido con las marchas contra el paquetazo legislativo que el MAS impuso, en medio del silencio de la oposición parlamentaria o con su aprobación.

La resistencia contra parte de esas normas ha movilizado a siete departamentos, y especialmente a Santa Cruz, copando la escena política. Este accionar se debió a los sectores sociales que detectaron tempranamente cómo la andanada legal masista, planificada primordialmente para anudar el control del poder político y neutralizar a sus oponentes políticos, podría afectar las actividades económicas sumergidas. Tales actividades de subsistencia son las predominantes en nuestra economía, y proporcionan empleo y sustento a la mayor parte de la población.

La resistencia efectiva (siguiendo el ejemplo de los cocaleros de Yungas) que tumbó un proyecto y una ley de ese paquete estuvo a cargo de los transportistas, gremiales, cuentapropistas de toda índole, así como de la franja de cooperativistas mineros que se despegó del oficialismo, comerciantes populares (como los denomina el antropólogo Nico Tassi). Es decir, son los componentes del pilar central, social y electoral sobre el que se apoya el régimen. El único gran sector social ausente de esa protesta fueron los campesinos.

La oportunista adhesión de comités cívicos, coaliciones opositoras y sus dirigentes [^4] trató de mostrarse encabezando el movimiento, aunque iba por detrás. Encontró en la propaganda gubernamental y en buena parte de la cobertura noticiosa el sustento para tal enfoque, simulación e interpretación de los hechos.

Esta burbuja se desinfló vergonzosamente cuando el comité cívico cruceño pretendió extender el paro después de que gremiales, transportistas y otros participantes clave se replegaron cuando el gobierno anunció que abrogaría la Ley 1386.

La demostración más cercana de que estos pactos implícitos de agentes del sistema de mediación y representación política [^5] están lejos de ser exóticos se verifica también en las actitudes y discursos con que distintos voceros políticos encaran el duro enfrentamiento por la tierra que ha explotado en Santa Cruz, en situaciones como las de Las Londras.

Mientras que la acción de grupos armados, secuestros y balaceras son explicadas por la coalición Creemos, la gobernación departamental y organismos cívicos y empresariales como “avasallamientos de propiedades privadas”, el MAS, a través de dirigentes de sindicatos de colonizadores, con oportuno respaldo de funcionarios oficiales, los tipifican como consecuencias de “abusos empresariales”.

La información más difundida sobre estos ríspidos choques que ya han cosechado al menos una muerte omite aclarar que las incursiones sobre propiedades empresariales representan apenas una fracción menor del ensanchamiento ilegal del mercado de tierras —y de la frontera agrícola ganadera—. Esta expansión depende principalmente de la ocupación de tierras fiscales, reservas naturales, territorios. Tal como sucede en Las Londras, donde las tierras en disputa —parte de la reserva forestal de Guarayos— han sido arbitrariamente ocupadas por una familia Barbey (la del presidente de la Confederación de Empresarios de Bolivia, CEPB) como lo reporta el INRA.

Ningún partido o parlamentario individual, ni oficialista ni opositor, ha sacado a relucir este importante dato. Cuando intervienen refiriéndose a los conflictos por la tierra (notoriamente el término territorio casi nunca aparece en estos debates), es para alimentar la imagen de un enfrentamiento entre colonizadores y empresarios, sin mencionar, desde luego, los nexos que existen entre los grandes capos del agronegocio y los dirigentes colonizadores que, desde poblaciones de pequeños y medianos soyeros, orquestan las incursiones, ahora armadas, de ocupación de tierras que terminan, finalmente, en manos de grandes inversores del agronegocio [^6].

Es decir que estamos en una pelea no por tierras de cultivo, sino por superficies con cuya comercialización se especula, con altas ganancias para los avasalladores, o en las que se realiza lucrativas operaciones de agronegocio a expensas de la desertificación de tierras no aptas ni para ganadería ni para agricultura.

En el análisis de agosto de este año ya se advirtió que la última marcha indígena, motivada también por los avasallamientos, tomó un rumbo incierto, precisamente porque su dirigencia prefirió no referirse a la asociación entre grandes empresarios y dirigencia colonizadora para beneficiarse del tráfico ilegal de tierras. Como consecuencia, ni siquiera consideró la posibilidad de esgrimir reivindicaciones de gran potencial estratégico, como el de pausa ecológica, ni una consigna amplia y abarcadora de gran potencial, como es exigir el respeto y cumplimiento irrestricto de la Constitución [^7], que introduce y consagra sus derechos de pueblos indígenas.

## Impotencia común y modelo desfondado

Las rebeliones que están ampliando el déficit de gobernabilidad nacen de la insatisfacción de necesidades básicas de una población que depende, en una proporción que ronda el 80%, de su propia y exclusiva inventiva para crearse empleo y producir sus ingresos. Esa masa social, parte fundamental del porcentaje con que el MAS ganó las elecciones de 2020, pero también de la población que no lo respalda, da señales de fatiga y hartazgo con la agenda de propaganda fraude-golpe y las permanentes noticias de apresamientos y amenazas contra opositores al régimen que ocupan la atención de los principales funcionarios del Ejecutivo.

La oposición parlamentaria, en tanto, reacciona funcionalmente a esta agenda, y calla, o apenas musita, en torno a los grandes problemas que acarrea un presupuesto que mantiene los gastos suntuarios en propaganda y funcionamiento de la presidencia, y que además subsidia empresas improductivas que materializaron los malogrados planes industrializadores de los catorce años. Todo esto, mientras centenares de miles de familias caen nuevamente bajo la línea de pobreza a causa de la desaceleración económica [^8].

Las protestas y movilizaciones que han obligado a cambiar decisiones y leyes ponen de manifiesto que se está agotando la reserva de buena voluntad colectiva que ha beneficiado a la gestión gubernamental, pese al fatalismo que provoca e incentiva el comportamiento del sistema de representación y mediación política.

## Pan y empleo sustituidos por expresiones de optimismo 

Que el MAS y, buena parte del tiempo, la oposición parlamentaria en su conjunto, coincidan en interpretar situaciones de una manera parecida o idéntica, no indica en modo alguno que sus disputas sean falsas o fingidas. Por el contrario, están sumergidos en una tendencia creciente a la crispación y favorable a choques más duros.

La concurrencia ideológica (en el sentido de proyectar una falsa realidad) se origina en que comparten, cada uno desde sus trincheras e intereses, la creencia de que no queda otra que observar con fatalismo el agotamiento del patrón de acumulación que creen insustituible, o cuyo cambio ocurrirá en plazos demasiado prolongados [^9] si de ellos dependiera.

Estos puntos de encuentro no se basan en conspiraciones, sino en la satisfacción de objetivos a corto plazo, como la necesidad de la oposición de aparentar una importancia que no logra —aunque el costo sea una mayor persecución y procesos judiciales contra sus dirigentes—, o la gubernamental de no admitir que lo centrífugo y contradictorio se va imponiendo entre sus filas.

Por otro lado, aunque el régimen aspire a ampliar la influencia económica estatal, mientras que sus contrarios en la Asamblea Legislativa suelan preferir opciones privatistas, ello no garantiza la calidad de los parlamentarios opositores que, con demasiada frecuencia, realizan escrutinios demasiado bastos de las iniciativas de ley enviadas por el Ejecutivo. Esto da lugar a que, unas veces, sean periodistas, y en otras, asesores de organizaciones sociales, en vez de los propios legisladores, quienes descubran los grandes problemas, que pasan fácilmente por su filtro.

El hecho de que el Presupuesto General del Estado (PGE) se haya tramitado con debates legislativos que, a fuerza de rutinarios, se vuelven intrascendentes, conduce a que la oposición —lejos de emplear la poderosa tribuna parlamentaria para demostrar que el PGE es la mayor prueba de que el modelo económico corre al abismo, con la extinción de sus principales fuentes de ingreso— se limite a realizar observaciones secundarias o ininteligibles para periodistas y público general.

Ni el escalofriante déficit de empresas (mal concebidas, diseñadas y conducidas), ni la lenidad oficial para detener en seco la proliferación de comandos e incipientes milicias civiles (a los que más bien encubre o alienta, tal como se descubrió en el conflicto cocalero de septiembre-octubre), ni las raíces de las disputas por la tierra, alcanzan a convertirse en la plataforma de una oposición, resignada a suponer que la única salida a la perpetuación del régimen sean sus peleas internas.

Así, el escuálido crecimiento del PIB, que durante varios años fue fortaleza gubernamental, se ha reducido tanto que no alcanza ni la mitad de nuestro vecino, Perú, que ha ostentado la mayor recuperación.

El crecimiento del PIB en un 9,4% responde principalmente a que se han levantado restricciones, dentro y fuera del país, y a un formidable incremento de precios de algunas exportaciones. Pero esto no alcanza a devolverle los primeros sitiales de años recientes; ahora nos ubicamos en un sexto puesto en Sudamérica [^10].

Pese a los enormes problemas de base (achacados todos, como muletilla, al gobierno interino), ya sea en el nuevo PGE y en general, el gobierno no asume y la oposición no promueve medidas para efectuar correcciones de fondo. Continúa el dispendio en superfluos gastos burocráticos, propagandísticos y de sustento de la tradición patrimonialista y clientelista de la organización política que controla al Estado.

La marcha altiplánica del MAS, que llegó a la ciudad de La Paz el 29 de noviembre, desplegó un caudal de miles de marchistas y una compactación de dirigentes de las organizaciones sociales que componen este movimiento. Sin embargo, todo ello, sumado a la agresividad de las declaraciones y el papel represivo que se hizo jugar a sindicatos afines para disuadir los bloqueos y manifestaciones que obligaron a abrogar la Ley 1486, no alcanza para cubrir las huellas del deterioro interno del bloque social que sustenta al régimen.

Ningún dirigente descontento se atreverá a proponer un ajuste estratégico que se aparte de su actual rumbo de proponer el retorno de Morales como panacea, aunque ello alimente la ingobernabilidad y las posibilidades de que Arce tenga que marcharse antes de la conclusión legal de su mandato.

Las disidencias internas del MAS serán más visibles y tensarán la situación (mucho más que lo que podrían hacer los opositores profesionales), en la medida en que el descontento social tome ímpetu y no quede atrapado en maniobras como la teatral contraposición entre federalistas y unionistas, unidos cuando se trata de enfrentar la quiebra estructural del modelo vigente.

::: {style="text-align:right; font-weight: bold;"}
Diciembre de 2021
:::

## Notas

[^1]: Contabilizados a partir del 5 de octubre último, con la recuperación de la sede de ADEPCOCA por los cocaleros yungueños no afiliados al MAS.

[^2]: Según afirmó el gobernador cruceño, Fernando Camacho. Véase: [https://www.lostiempos.com/actualidad/pais/20211123/gobernador-camacho-no-llevamos-proyecto-imponer-hay-que-sentarse-organizar](https://www.lostiempos.com/actualidad/pais/20211123/gobernador-camacho-no-llevamos-proyecto-imponer-hay-que-sentarse-organizar)

[^3]: Más allá de la coyuntura, están las históricas lecciones de la Guerra Federal de 1899, en la que el bando ganador, los “federalistas” de La Paz, al mando de José Manuel Pando, archivó el asunto después de eliminar a Zárate Willka. La guerra sirvió a unionistas y federalistas para ahogar en consenso la insurgencia indígena (pese a que los aymaras se aliaron los “federalistas”), como lo demuestra Ramiro Condarco en *Zárate, el “temible” Willka”* (La Paz: s/e, 1966).

[^4]: Caracterizados por un cotidiano y sostenido discurso *antinformalidad y antiinformales*, que súbitamente viró 180o grados al respaldar “incondicionalmente” a los movilizados.

[^5]: Se utiliza esta expresión en vez de “partidista” porque la democracia boliviana funciona, desde al menos hace una década, sin partidos políticos, reemplazados, en el caso de la oposición, por endebles y circunstanciales alianzas de siglas, precariamente registradas ante los órganos electorales y, en el oficialismo, por una coalición de organizaciones sociales y corporativistas nucleadas en torno a un reducido pero eficaz núcleo de funcionarios oficiales, encabezados por el caudillo, Morales Ayma.

[^6]: Véase el prolijo trabajo de Gonzalo Colque, de Fundación Tierra, sobre el tema: [https://bit.ly/3mLFt3L](https://bit.ly/3mLFt3L)

[^7]: Con ese enfoque se amplió la posibilidad de que Creemos y la Gobernación cruceña asumieran el papel de aliados protectoras de la Marcha, cuyo impacto se disolvió tras la demanda de reconocimiento de un Parlamento Indígena.

[^8]:  La paciencia y la buena voluntad de la que todavía goza el gobierno de Arce Catacora en la sociedad quedan perfectamente retratadas en la resignación que ha acompañado el anuncio de no pago de segundo aguinaldo, pese a toda la alharaca de avances económicos que hace el presidente, para después informar que el PIB creció menos del 2%. Una actitud similar prima ante el anuncio y avance de nuevas oleadas de la pandemia. Las referencias noticiosas y el respaldo documental de estos y otros temas examinados en este boletín están ordenados en el anexo informativo.

[^9]: Lo señala así el exvicepresidente Álvaro García, quien admite que “el MAS no tiene proyecto” (según su versión, a partir de 2019), negándose a ver que el daño ocasionado por la pandemia y la corrupción ilimitada de su gobierno, del gobierno interino que vino a continuación y del actual. Esto puede remontarse con un cambio de matriz productiva (producción de alimentos sanos, investigación y desarrollo de tecnologías de recuperación de la tierra, incremento sostenido a amplia escala de visitantes interesados en una sociedad basada en la alianza de naturaleza y culturas, cambio de matriz energética, etc.). Véase sus declaraciones, muy pobremente retratadas por los medios, que se han limitado a informar de sus amenazas de continuar con las ya conocidas prácticas de extorsión a empresarios, en: [https://jacobinlat.com/2021/10/12/soy-un-leninista-de-la-nep-2/](https://jacobinlat.com/2021/10/12/soy-un-leninista-de-la-nep-2/)

[^10]: [https://n9.cl/uf6m](https://n9.cl/uf6m)