---
lang: es
format: 
  html:
    page-layout: article
---

# Incendio de bosques y de descontento social {.unnumbered}

El boletín de análisis de abril preveía que el siguiente cuatrimestre (es decir, el que concluye el 31 de agosto) sería “feroz” debido a las pugnas electorales, el avivamiento de demandas sociales y los choques internos en el MAS. Pero no sospechaba que la situación se caldearía al grado al que ha escalado por causas ajenas a los afanes y maniobras de los actores y sujetos habituales.

La guerra de encuestas, el desbocamiento de la corrupción policial, las nuevas tramas chuecas en todos los altos tribunales, las presiones corporativistas, incluyendo los afanes gubernamentales por satisfacerlas o calmarlas, y las ofrendas militares de lealtad no han dejado de intensificarse.

Con todo, cualquier pronóstico empalidece ante el desastre ambiental que suponen los megaincendios que no dan tregua y que, por el contrario, se disparan, mostrando un significativo potencial de afectar la correlación política de fuerzas, la jerarquía de cuestiones que capturan la atención pública y, eventualmente, las tendencias electorales.

## Praderas y bosques en llamas

No exactamente la llanura, sino más bien la superficie ondulada donde predomina el bosque seco de la Chiquitanía, empezó a arder inconteniblemente desde antes de julio. Pasa lo mismo en la Amazonía, el Pantanal y el Chaco.

Los hechos han demostrado que no existía la menor probabilidad de que el Estado respondiera oportuna y eficazmente. Este Estado y sus contrahechas reformas arrastran una sólida y muy estable tradición de prescindencia ante estos problemas. Además, esta respuesta estaba destinada a ser menos eficiente, si cabe, en año electoral y de consolidación de los lazos y compromisos, cada día más íntimos, entre el poder político y los capitales transnacionales que alientan y favorecen los agronegocios [^1].

Este sector dominante, objetiva e incuestionablemente favorecido por la extensión de los incendios, ha actuado como un socio privilegiado de la estrategia sectorial del gobierno para extender las fronteras agrícola y ganadera [^2].

La firma del D. S. 3793 —que autoriza la tala y quema de tierras privadas y comunitarias— el pasado 9 de julio en sede de la Asociación de Ganaderos de Trinidad, Beni, sella y rubrica el conjunto de pasos que han ido acercando al régimen con la franja más activa y agresiva de la burguesía aliada al capital transnacional. Sus avances previos han sido la autorización e impulso de la siembra de grandes extensiones de soja y otros cultivos para producir etanol.

El trabajo constante y minucioso de operadores, como el ministro Romero y el vicepresidente en persona —que ha cultivado una relación continua y vigorosa con representantes de los agroexportadores y ganaderos mediante visitas asiduas a Santa Cruz—, ha rendido resultados remarcables que empezaron a manifestarse hace años [^3], principalmente a través de la conversión de hostilidades entre el gobierno nacional-popular y la oligarquía asentada en el oriente en entendimiento, proximidad y colaboración [^4].

La seguridad que confiere al gobierno el haber sellado alianzas con un sector que, teóricamente al menos [^5], podría contribuir a superar los baches de la caída de ingresos por exportaciones, junto con las prácticas habituales de la militancia masista, han dado lugar, durante la tercera semana de agosto, a la indiferencia y altanería derrochada por los máximos ejecutivos del MAS ante las novedades del incendio.

Así dejó traslucir la actitud del jefe de Estado, cuando, a su regreso de la inspección aérea que hizo sobre la zona de Roboré, rechazó terminantemente la posibilidad de aceptar cualquier ayuda externa para enfrentar el desastre. “Estamos preparados”, afirmó (¡!). Lo mismo cuando defendió y justificó las quemas, al aseverar que las familias pobres de agricultores no pueden prescindir de ellas, o al calificar uno de sus parlamentarios como “ley bendita” la legislación que autoriza las quemas y talas [^6].

Antes de que transcurra una semana, debieron recular ante la indignación popular, que se avivó cuando circularon las dramáticas expresiones de cólera y desesperación de pobladores de la Chiquitanía al reavivarse las llamas y ante los mezquinos esfuerzos gubernamentales para enfrentar la crisis.

La completa concentración del MAS y la plana superior de gobierno en la campaña y los aprestos electorales ha influido para que su respuesta sea más lenta y torpe que lo esperado. Sumidos en esa dinámica, para quienes defienden sus puestos y, en gran medida, sus ingresos y estilo de vida en la cita de octubre, es difícil concebir algo más importante y apetitoso que las cifras estadísticas, los cotilleos, la movilización y los gastos que suponen las elecciones.

Adormecida, o más bien enterrada, la retórica ecologista que les ayudó a acceder al gobierno y controlar el poder, hoy destilan desprecio contra quienes les echan en cara el abandono de todas sus promesas, convertidas en leyes incumplidas y atropelladas continuamente, no solo por el gobierno central, sino prácticamente por todas las instituciones estatales, incluyendo las que están en manos de opositores.

La parálisis opositora ha impedido que ninguna de sus expresiones haya desplegado la sensibilidad, agilidad e iniciativa necesarias para responder a lo que podría convertirse en el más serio flanco electoral del oficialismo.

Se entiende que el exgerente de la CAO y exejecutivo de CAINCO, actualmente a la cabeza de la fórmula Bolivia dijo No (BDN), sea más bien reticente a protagonizar una ofensiva sobre el tema. Son menos fáciles de entender las razones que hacen que Comunidad Ciudadana (CC) no se aplique al máximo en una poderosa contraofensiva que enfrente y revierta la persecución que sufren importantes dirigentes de esa coalición [^7].

La duración e intensidad de las quemas está comenzando a afectar la campaña electoral oficialista, que desde la última semana de agosto despliega una gran ofensiva mediática sobre el tema, pero sin deshacerse de la torpeza y rispidez de sus mensajes. Esto podría contribuir a que la situación marque una inflexión en las tendencias de intención de voto observadas hasta este mes de agosto.

Por encima de si se produce esa alteración, asoman las señales de que ciertas franjas de la población, predominantemente jóvenes (más probablemente los que tienen entre 18 a 25 años) y urbanas, están desplegando reacciones de repudio hacia las autoridades y, en general hacia los políticos profesionales, al observar su irresponsabilidad y desidia respecto a la naturaleza. Dichas manifestaciones no se producían desde la IX Marcha Indígena, en 2013, y deben tomarse como expresión de una nueva actitud frente al cambio climático, que tiene posibilidades de politizarse e irse asentando en la conciencia y la memoria colectivas.

## Más allá de la estupidez o la maldad

Ya no hay manera de ocultar o negar el viraje que ha conducido al gobierno a adoptar como propias las más importantes reivindicaciones y demandas de los exportadores de soya y otras oleaginosas y de los ganaderos más poderosos.

La disminución de los precios y volúmenes de exportación del gas natural y, en segundo lugar, de los minerales, ha tenido en la coyuntura una significativa influencia para determinar dicho cambio. Sin embargo, sería completamente engañoso cerrar los ojos al hecho de que después de la derrota de la ofensiva prefectural-empresarial de 2008, con la ejecución del húngaro-boliviano Rozsá Flores y sus compañeros [^8], gran parte de la cúpula empresarial, y en particular la de los agronegocios, decidió cambiar de estrategia y reencaminar sus relaciones con el gobierno.

La clave de esa operación fueron las coincidencias centrales entre ese poderoso sector económico y los miles de pequeños y medianos productores de soya y otras oleaginosas, que son parte de la ola de colonizadores originarios de la zona andina (o sus inmediatos descendientes) que se asentaron en las tierras bajas del este y el Gran Norte Integrado de Santa Cruz, desde la época de la reforma agraria y aún antes.

Estos agricultores, en su mayoría descendientes de migrantes campesinos, principalmente potosinos, que abandonaron su territorio nativo entre las décadas de 1950 y 1960, encontraron, gracias a un denodado y muy sacrificado empeño, primero un nicho en la producción de la caña y luego de la soya. Ambos productos recibieron un fuerte impulso de empresas agrícolas y del Estado. El auge de estos productos significó una ventana de ascenso social y una fuente de prosperidad para un grupo no desdeñable de estos agricultores [^9].

De modo que comparten prácticamente los mismos intereses con las grandes corporaciones del rubro. Por eso, exigen conjunta y solidariamente que el Estado derribe todas las barreras para el uso de semillas transgénicas y el paquete tecnológico de agrotóxicos que las acompaña. También son entusiastas propulsores y ejecutores de la ampliación de las fronteras agrícola y ganadera.

Tal entusiasmo se justifica, primero, porque el avance de la frontera les permite combinar sus ingresos agrícolas con un impulso extraordinario al mercado de tierra: los nuevos chacos talados y quemados se venden o alquilan, al final de una enmarañada red de participantes, a inversores extranjeros: brasileños, argentinos, colombianos, menonitas, etc. Es una práctica que comparten “democráticamente” los soyeros, independientemente de su tamaño y origen geográfico o étnico [^10].

La concurrencia de estos intereses, que han terminado por hacerse hegemónicos en el bloque de poder que controla al régimen, está en el centro de las explicaciones de por qué y cómo se han impuesto sobre otros componentes del conjunto corporativo del que depende su fuerza y su convocatoria.

No por ello dejan de ser menos patéticos los esfuerzos de quienes componen el núcleo de emisión ideológica y construcción de relatos sustentadores de la hegemonía, como se ve en los esfuerzos realizados por el vice García y el ministro J. R. Quintana, que se aliaron para impulsar, en los años de la VIII Marcha Indígena, la idea de que la resistencia al camino por el núcleo del TIPNIS provenía de ganaderos y madereros (los dos sectores más ávidos de caminos y carreteras) y el “heroico” esfuerzo del vice para demostrar ahora que en Bolivia la relación entre árboles y habitantes es superavitaria en favor de los primeros [^11].

El acuerdo entre las franjas más prósperas de colonizadores y excolonizadores —que controlan las organizaciones de cocaleros (quienes pretenden convertirse en soyeros y ganaderos en el TIPNIS, por ejemplo) y pequeños productores de soya— y la burguesía agroexportadora, es la fuerza modeladora más importante de la orientación estratégica asumida por el MAS. Es también el corazón de su propuesta programática, que tiene su núcleo principal en la ampliación de la frontera agrícola y en la construcción de megarepresas.

## El gran colapso de los tribunales

La parcialización irrestricta del Tribunal Suprema Electoral (TSE) y del Tribunal Constitucional Plurinacional (TCP) con el gobierno se hizo visible y ostentosa por lo menos desde 2014. También se puso de manifiesto que la corrupción de sus miembros fue clave para garantizar que los miembros del anterior TCP respaldaran sin ninguna vacilación la sentencia que justifica la reelección [^12]. De manera paralela, casi todos los miembros del TSE removidos en 2015 tenían una actitud similar ante el gobierno.

El nombre de Pedro Montenegro [^13] se hizo popular por su fuerte presencia noticiosa, originada en disputas y acusaciones internas de jefes y oficiales de la Policía. Al entregarse voluntariamente a la justicia, permitió vislumbrar al público el contorno de una extendida red de contactos y relaciones entre el sindicado —representante del Primer Comando Central (PCC), grupo dominante entre los criminales de Brasil, y a la vez, delegado de la ‘Ndrangheta calabresa [^14]— y altos jerarcas de la Policía y la judicatura.

Las conexiones de este personaje abarcan a jueces, fiscales, jefes y mandos intermedios de la Policía y a operadores políticos de peso. Están tan frescas y vigentes, que han operado rápida y eficazmente para impedir su extradición a Brasil, cuando la justicia ha aceptado condenarlo en Bolivia por un delito menor de falsificación de identidad.

Lo más importante de esta historia policial y política es que el amistoso y popular detenido ha resultado ser el centro de un denso tejido de conexiones con miembros del TCP y del TSJ, cuyo muy alicaído prestigio ha sido golpeado por las revelaciones del caso y por otras más recientes, que señalan la elección fraudulenta de uno de sus componentes. En el caso del Consejo de la Judicatura, las filtraciones descubren la venta de puestos de jueces y otras ilegalidades mayores en audios filtrados a medios de difusión masiva.

Los problemas que representan la corrupción policial y la del conjunto de máximos tribunales (igual que de los intermedios y los de base), incluyendo el Ministerio Público, carecen de respuestas realistas del conjunto de tiendas políticas y de cualquier otra institución. Esto lleva a estar atentos a la germinación de una coyuntura, similar a la que obligó en Guatemala a solicitar apoyo de NN. UU. con la creación de la CICIG [^15], quizás como única forma inmediata de encarar la corrupción y la impunidad.

Los desajustes y las señales de abuso de poder y de corrupción, ampliamente generalizados en toda la estructura estatal, y los gravísimos problemas del conjunto de instituciones sobre las que el Estado ejerce su capacidad coercitiva (judicatura, Policía, FF. FA. [^16], sistema carcelario), junto con el resquebrajamiento de la fuerza persuasiva de su emisión ideológica, empiezan a configurar una crisis política de dimensiones considerables. Si esta confluye con la que se está gestando a partir de los desajustes económicos acumulados, la convulsión social y política puede alcanzar picos no vistos desde inicios del siglo.

## Intención de voto y actores electorales

Varias nuevas encuestas publicadas en el cuatrimestre muestran que hasta inicios de agosto el MAS no había logrado romper la barrera que encierra su intención de voto entre el 25 y el 39% durante los dos últimos años; en segundo término, que todas las categorías que pueden agruparse como indecisos llegan a representar hasta un cuarto de los votantes.

La relativa constancia de esta importante proporción y la respuesta muy constante y mayoritaria de los encuestados que creen que “el MAS ganará” hace pensar en la figura descrita académicamente como la “espiral del silencio” [^17]. De lo anterior se desprende la posibilidad de que una gran parte de quienes manifiestan estar indecisos en realidad ya han decidido su voto, pero prefieren no comunicarlo a los encuestadores.

En la forma clásica de la espiral, los “indecisos” que ya se habrían decidido por la oposición se consideran minoría —debido a la predominante impresión de que “Evo ganará”, que en todas las encuestas se manifiesta por encima del 60%— y temen expresar su decisión. Esto no implica que estén contentos con que Evo ganará; simplemente creen que sucederá “por las buenas o por las malas”.

Pero también podría afirmarse que una porción significativa de los que no saben/no responden estarían conscientes de la enorme cantidad de evidencias y denuncias de abusos y corrupción que pesan sobre el régimen, por lo que se avergüenzan de manifestar abiertamente su decisión de votar por este. Y esta su opción obedece posiblemente a la incertidumbre ante las consecuencias económicas que podría traer el cambio de gobierno [^18].

Algo irrebatible es que la candidatura de CC ha ido perdiendo terreno (o, por lo menos, que la entusiasta adhesión original ha mermado, hasta hacerse también vergonzante), gracias a la omisión de esa fuerza y sus principales candidatos en la coyuntura. La emergencia de nuevas figuras en las listas parlamentarias y sus significativos mensajes localizados no logran quebrar la gran ausencia de las cabezas de fórmula, con lo que la debilidad que percibe el público en una fórmula “indecisa” o “vacilante” se consolida
a favor del régimen.

En todo caso, la coyuntura de los incendios hace más difícil la acumulación oficialista, y favorece la posibilidad de una segunda vuelta. Para la oposición, débil y desconcertada y, en consecuencia, con desventajas notables, sería complicado hacerse cargo del gobierno. Pero, simétricamente, el enorme desgaste de credibilidad que afecta al oficialismo por su comportamiento ante el desastre de los incendios toca una profunda fibra nacional (mal uso o dispendio de recursos naturales) y desgasta notoriamente su legitimidad y credibilidad, en caso de que consiga reelegirse.

En estas condiciones, la disputa por cada voto puede ser extrema, tomando en cuenta que más de la mitad de las diputaciones uninominales se deciden en áreas rurales, donde las posibilidades de un riguroso control ciudadano del recuento de votos y la vigilancia de las actas resulta muy difícil. Algo similar se ha visto en algunos recintos de voto en el extranjero. Este eslabón débil marca la urgencia de subsanar tales deficiencias, que pueden decidir el resultado de la elección.

## Tendencias prospectivas

Las ausencias partidarias, parapetadas detrás de justificaciones electorales, han incrementado el desgaste del 21F como germen de movimiento social, amenazándolo con su extinción. El CONADE y los comités cívicos no alcanzan a cubrir la ausencia de dirección política. Eso no quiere decir que se haya olvidado la injuria del poder estatal al negar y atropellar la decisión democrática, pero empuja a que su reivindicación se canalice hacia otros campos.

La genuina indignación y, por momentos, los estallidos de furia y frustración, abren la oportunidad para articular movilización y organización sobre cuestiones ambientales y el indispensable debate y consideración sobre modelos de desarrollo alternativos, con protagonismo de la sociedad civil, no solo a corto plazo, sino en un horizonte mayor.

La restauración de los bosques quemados, de la biodiversidad, de la vida en la gran superficie afectada, abre un espacio para la acción de redes ciudadanas, ONG y otras instancias civiles, debido a que conecta con preocupaciones universales y con una justificada desconfianza ante el accionar estatal.

El vínculo de estas tareas con una visión democrática genuinamente intercultural, de derechos indígenas y de la naturaleza, con las tareas de rescate y fortalecimiento de la autonomía social y sus expresiones organizadas, así como la justificada desconfianza ante la acción estatal, brinda un ancho espectro para iniciativas y trabajos de alianzas múltiples y de gran riqueza y potencial. Los partidos políticos y las coaliciones electorales de toda estirpe están desconectados de esta realidad, y han demostrado su desinterés e ineptitud para asumirlas.

::: {style="text-align:right; font-weight: bold;"}
Agosto de 2019
:::


## Notas

[^1]: Al respecto, el especialista Carlos Guzmán Vedia opina que “Los incendios, que arrasaron con 500 mil hectáreas en la Chiquitanía, son consecuencia de la política de expansión agrícola que promueve el gobierno y los agroindustriales, ambos sometidos a la agenda global que imponen las empresas transnacionales de la alimentación y agrotóxicos, cerca del 60% del negocio de semillas transgénicas e insumos químicos en el mundo.” Véase el artículo completo se halla en el suplemento “Ideas” del matutino Página Siete del 25 de agosto de 2019.

[^2]: Tanto es así, que en Brasil se ha descubierto una trama entre grandes ganaderos y mercenarios (grileros) que han iniciado quemas a una tarifa de 243.000 dólares por cada mil hectáreas calcinadas, comenzando el llamado dia do fogo (día del fuego). Véase: [https://revistagloborural.globo.com/Noticias/noticia/2019/08/grupo-usou-whatsapp-para-convocar-dia-do-fogo-no-para.html](https://revistagloborural.globo.com/Noticias/noticia/2019/08/grupo-usou-whatsapp-para-convocar-dia-do-fogo-no-para.html)

[^3]: Un recuento preliminar de las cesiones y concesiones legales y reglamentarias está contenido en el informe del periodista Cándido Tancara, donde se señalan, entre las principales: i) la Ley 337, de Apoyo a la Producción de Alimentos y Restitución de Bosques; ii) la Ley 741, “que autoriza el desmonte para pequeñas propiedades para actividades agrícolas y pecuarias”; iii) el 15 de septiembre del año pasado, el presidente aprobó la Ley 1098, de Aditivos de Origen Vegetal, para que Bolivia “ingrese en la era del etanol” y la producción de biocombustibles; iv) el D. S. 3973, que autoriza los desmontes para incrementar la frontera agrícola destinada a las actividades orientadas a la ganadería y agricultura, en Santa Cruz y Beni. Véase el artículo completo en: [https://n9.cl/peyx5](https://n9.cl/peyx5)

[^4]: Véase: [https://n9.cl/4v5np](https://n9.cl/4v5np); [https://n9.cl/ggigr](https://n9.cl/ggigr) 

[^5]: En una proporción muy escuálida, ciertamente, dada su real y escueta productividad. 

[^6]: Un parlamentario masista llamó “benditas” a las normas prochaqueo y proquema, mientras que el gobernador del Beni las ha defendido a capa y espada, igual que representantes de la asociación de ganaderos de Santa Cruz, FEGASACRUZ.

[^7]: Hasta ahora, las ocasiones en que CC ha salido al ruedo a través de su principal candidato son casi exclusivamente aquellas en que Carlos Mesa ha sido directa y personalmente agraviado, o amenazado por el MAS y el gobierno. CC ha emitido un pronunciamiento sobre los incendios, pero muy lejos de lo que la situación amerita, aunque CC es la opción electoral cuyo programa se ocupa más y presenta un mayor número de ofertas sobre el medio ambiente. La falta de congruencia entre esa plataforma programática y acciones e iniciativas concretas da pie para que algunas de las más agresivas críticas a su programa provengan no del gobierno, sino de particulares que se definen como opositores del MAS y eventuales votantes de CC. Véase: [https://n9.cl/l7co5](https://n9.cl/l7co5)

[^8]: En Wikipedia se encuentra una reconstrucción esquemática de esos sucesos: [https://n9.cl/jz9em](https://n9.cl/jz9em)

[^9]: Unas 11.500 familias, según la Cámara Agropecuaria de Oriente (CAO). Véase: [http://agronegocios.com.bo/cao-realidad-de-la-produccion-y-exportacion-de-soya-en-bolivia/](http://agronegocios.com.bo/cao-realidad-de-la-produccion-y-exportacion-de-soya-en-bolivia/)

[^10]: Algunas referencias importantes pueden hallarse en: [https://n9.cl/4hah2](https://n9.cl/4hah2); [https://n9.cl/ezegl](https://n9.cl/ezegl); [https://n9.cl/b2uq0](https://n9.cl/b2uq0)

[^11]: La comparación que hizo entre Bolivia y dos países europeos, en su discurso del 6 de agosto de este año, prescinde de la indispensable referencia a la densidad poblacional de cada país, a la enorme asimetría de superficies, a la latitud geográfica y, especialmente, a lo inútil del esfuerzo estadístico en una época de calentamiento global, en que el valor relativo, incluso de mercado, de bosques, biodiversidad, así como de fuentes de oxígeno y agua, es cada día mayor y, de hecho, inconmensurable.

[^12]: Véase [https://n9.cl/xl8o3](https://n9.cl/xl8o3)

[^13]: Véase [https://n9.cl/abx83](https://n9.cl/abx83)

[^14]: Se sabe que esta asociación delictiva tiene una estructura organizativa y una capacidad económica que la coloca a la cabeza del rango mundial, con ventas de bienes y servicios que superan el PIB de nuestro país. Véase: [https://www.researchgate.net/publication/304703163_›Ndrangheta_mafia_calabresa](https://www.researchgate.net/publication/304703163_›Ndrangheta_mafia_calabresa)

[^15]: Véase: [https://www.cicig.org/que-es-la-cicig/](https://www.cicig.org/que-es-la-cicig/)

[^16]: La sonoridad de las manifestaciones públicas de respaldo de altos jefes militares al régimen deja fuera de cualquier duda el sistemático esfuerzo gubernamental por capturar la buena voluntad de los mandos castrenses. Cada exhibición de lealtad es retribuida con cargos diplomáticos y otros, así como con una benevolencia extrema de los tribunales cuando se ocupan de problemas de corrupción entre ellos o entre exmiembros de la alta cúpula militar.

[^17]: La teoría de la espiral del silencio surge en 1977, propuesta por la politóloga alemana Elisabet Noelle-Neumann, que explica cómo la opinión pública funge como control social, al plantear que *las personas adaptan su manera de comportarse a las opiniones predominantes en su contexto social sobre cuáles conductas son o no aceptables*. Esta conducta tiene su origen en nuestro natural temor al aislamiento, que podría darse si expresáramos opiniones percibidas como minoritarias. Por eso los individuos estamos constantemente “sondeando” el clima de la opinión pública para determinar qué opiniones podemos expresar. *La llamada “espiral”, entonces, es la figura que se dibuja a medida que aquellos que tienen posiciones minoritarias son enmudecidos*, y las opiniones percibidas como mayoritarias aumentan y se vuelven dominantes. Véase: [https://n9.cl/lgskm](https://n9.cl/lgskm)

[^18]: Es notable la casi unanimidad de las encuestas respecto al elevado nivel de confianza de la mayoría de encuestado sobre las perspectivas favorables de la economía del país, así como las altas expectativas de que sus familias se favorecerán de esa tendencia.