---
lang: es
format: 
  html:
    page-layout: article
---

# Verano de fuego {.unnumbered}

Las tendencias que establecidas en el segundo cuatrimestre del año han madurado, configurando una explosión en las relaciones del Gobierno central con Santa Cruz y, al compás de esta, en la interna del Movimiento al Socialismo (MAS) que ha roto todas las cotas anteriores, en cuanto a ferocidad y encono del choque fraccional.

Con ellas, los chispazos de cifras económicas al alza se han extinguido y, como consecuencia del paro de 36 días, de las escaramuzas masistas y de condiciones meteorológicas adversas, las perspectivas económicas de 2023 se han ensombrecido, al mismo tiempo que los conflictos socioambientales se aceleran, intensificados y rodeados de violencia, ya se trate de tierras, avances de la minería ilegal o atropellos contra indígenas.

## Protesta social y prestidigitación política

La abrupta decisión oficial de postergar el Censo de Población y Vivienda por dos años, hasta 2024, le dio a la Gobernación cruceña y a su estado mayor, pertrechado en el comité cívico departamental, la esperada ocasión para convocar a la población, tras la consigna de defenderse de agresiones y postergaciones, anudadas alrededor de la postergación del censo. El Ejecutivo, en vez de apaciguar las aguas, abriendo un diálogo transparente, reconociendo las debilidades del Instituto Nacional de Estadísticas (INE) e inaugurando un espacio de concertación y participación social, entremezcló ofertas de diálogo con amenazas, propaganda agresiva y señales nítidas de que haría todo lo posible para postergar la aplicación de resultados del censo para después de las elecciones nacionales de 2025.

Su enfoque rotundamente electoralista del problema, en el sentido de que se basa en los beneficios que supone le reportaría en las urnas continuar difiriendo [^1], por más de un quinquenio, obligaciones de elevar la coparticipación con el departamento de mayor crecimiento demográfico y de ampliar su representación política, envalentonó a la Gobernación, muy alicaída durante todo este año.

La declaración de paro indefinido reclamando Censo en 2023 tensó las fuerzas locales, pero nunca alcanzó el impulso suficiente para aglutinar a fuerzas de otras regiones, tras una línea de respaldo firme y comprometida. Las organizaciones políticas opositoras la alentaron, pero no quisieron comprometerse con el radicalismo que personifica L.F. Camacho, observando que ni siquiera ha sido capaz de garantizar la cohesión de su propia bancada parlamentaria, diezmada por el transfugio y la deslealtad, desde el primer día en que sus miembros juraron a sus cargos.

Los comités cívicos de otros departamentos que simpatizan con la combatividad del cruceño, carecen de su gravitación social y política y, además, están conscientes de que lo acumulado por Santa Cruz por coparticipación y ampliación de representantes, les pasará factura a la mayor parte de los demás departamentos [^2] , que expulsan población hacia la región que desafió al régimen, después de convocar a un masivo cabildo. Durante el primer mes del paro, el Comité Interinstitucional (gobernación, universidad, comité cívico) [^3] , menguado por la ausencia de la Alcaldía que optó por representar una falsa neutralidad, propia de una alianza apenas disimulada con el MAS, intentó ganar respaldos extradepartamentales. Ante su fracaso, desplegó un sorpresivo y brusco viraje, cuando en el segundo cabildo puso en primer plano consignas propias del conservadurismo cerril de su conducción, como “revisar la relación entre el Estado boliviano y Santa Cruz” (que vuelve a rondar la idea de que ese departamento sería una especie de estado preconstituido), a tiempo de declararse víctima del abandono de los otros departamentos bolivianos.

El cambiazo de objetivos, inconsulto y no se basa en ninguna deliberación social, muta de una consigna mínima (Censo 2023) al maximalismo de los grupos regionalistas más cerrados, en el momento en que se cerró la posibilidad de obtener su objetivo para reemplazarlo por uno menor, representa una fuga hacia adelante, tratando de aparentar un triunfo, al tiempo que contrabandea metas, ajenas a la mayoría de la sociedad cruceña. 

El cambio de estrategia ha sido ruidosamente celebrado por ideólogos de la “Nación Camba”, pero no por la derecha tradicional, más fogueada políticamente, que ha expresado su escepticismo ante el brinco pro federalista, eventualmente independentista, delas Conclusiones del segundo Cabildo (13 de noviembre), como lo expresa el columnista Manfredo Kempff -excanciller de Banzer- y otros comentaristas.

La incuestionable masividad y entusiasmo del cabildo del 13 de noviembre, mayor a la del primero, refleja en principio, mucho más de protesta y hartazgo frente al hostigamiento oficialista, que comunidad de pensamiento con  la dirección política del conflicto (gobernación y comité cívico y, menos probablemente a la representación universitaria) [^4] , dejando claro que es urgente e imperativa la necesidad de investigar rigurosamente la dinámica del largo paro, por lo menos en lo que hace a  su durabilidad, paradójica en términos de los intereses económicos del 80% de los participantes que dependen de actividades económicas de sobrevivencia diaria, cuanto a su textura ideológica y política.

El MAS ha tratado de explicar ambos aspectos, atribuyéndolos a las técnicas de amedrentamiento y coerción usados por el camachismo y grupos de choque de los cívicos, para remachar el paro.  En el mejor de los casos ese abordaje es unilateral porque, aun siendo indiscutible el uso tradicional de esos mecanismos, se balanceó con el despliegue de amenazas y violencia de sectores masistas -en especial grupos relacionados con campesinos, colonizadores, transportistas y pequeños comerciantes- que fortalecían el relato de la dirigencia política del paro, sobre el anticruceñismo del régimen y el MAS. 

Aquí se plantea las hipótesis: 1) que la fuerza del paro radicó en un rechazo social ampliamente extendido a las tácticas intimidatorias del régimen y, desde ese punto de vista, el triunfo que significa la aprobación de una ley que garantiza coparticipación y representación mayores, antes de 2025,  es un avance de recuperación democrática y 2) que el resultado del conflicto tiende a damnificar política y electoralmente, por igual, al MAS y su mayores adversarios, antes que a fomentar una  capitalización política por parte de las fracciones conservadoras y reaccionarias radicales, expresadas en las fuerzas conjuntas del actual gobernador y el comité cívico.

## Guerra de guerrillas en el MAS

Las mayores consecuencias del gran reacomodo social y político que deja la culminación del paro se ciernen sobre el MAS, debido a que aceleró notablemente sus disputas internas, en su calidad de ser la única fuerza política de vigencia y con presencia nacional. Sus contradicciones que empezaron a emerger desde la apresurada salida de Morales/García en 2019, cobraron fuerza, velocidad e ímpetu en el último trimestre para desbordarse en las últimas semanas.

Si todavía en 2021, la actuación del Gobierno se ajustaba a la ejecución de la estrategia impuesta  por Morales Ayma [^5], este último año su rebeldía fue creciendo, al resistir las presiones para cambiar a los alfiles políticos presidenciales (los ministros de Justicia, Gobierno, Obras Públicas, Presidencia y Obras Públicas, según orden de importancia), hasta dejar claro que, con la inspiración y apoyo de ellos, Arce Catacora se siente lo suficientemente crecido para disputar la próxima candidatura, considerada como suya por el supremo jefe del MAS.

Tal sospecha, transformada ahora en certeza, ha desbocado a los participantes que han perdido cualquier recato en ventilar públicamente su desprecio y rencores mutuos. La descalificación, antes aplicada a opositores, críticos y disidentes se ha extendido a sus contrarios internos, súbitamente convertidos en agentes de la CIA, traidores a la patria, corruptos profesionales, aliados de la derecha y una colección creciente de insultos e injurias.

La teórica ampliación de espacio para un juego democrático que aporta la división de bandos parlamentarios está actualmente asfixiada por los chantajes mutuos de las dos fracciones masistas que se acusan de “pactar con la derecha”, lo que las sumerge en una competencia de sectarismo e intolerancia para demostrar que es el otro quien pacta [^6].

Un posible, pero de ninguna manera seguro, límite del recrudecimiento represivo que lo anterior trae es que la ruptura de la bancada oficial va a proyectarse a parcelaciones de la influencia y control de bandos sobre el aparato judicial, la Policía, Fuerzas Armadas y todas las demás instituciones copadas, hasta ahora por un mando unificado.  Lo que estará garantizado es que el aumento de la autonomía relativa de los aparatos estatales hará crecer la ya colosal corrupción y abusos a límites incuantificables.

Por el momento, la ampliación del horizonte democratizante del país está atrapado por el inmovilismo de las mayores organizaciones sociales, domesticadas, afiliadas y componentes del MAS. Su dirigencia, aterrada por la pelea que asola al instrumento político apenas atina a exhortar a la “defensa del gobierno”, al unísono con la apología de la jefatura del partido, pero, ciertamente, la creciente incompatibilidad de esas dos posiciones crecerá rápidamente, empujando definiciones hasta ahora postergadas. Cuando eso ocurra, la rebeldía espontánea de sus base encontrará mayores posibilidades de generar tendencias de mayor apertura y exigencia de rendición de cuentas, a sus propia dirigencia y al aparato gubernamental del que participan habitualmente.

## Adelantos en múltiples frentes

El desenfreno de la lucha fraccional del MAS tiene su expresión más peculiar en la rapidez con que algunos de sus protagonistas han empezado a mencionar la posibilidad de un adelanto electoral, que hasta hace semanas podía percibirse como un invento extravagante. Su sola mención está muy lejos de convertirlo en tendencia dominante, porque sigue siendo ocupando un espacio lateral, pero cobra un nuevo sentido desde que la discusión ha sido puesta sobre la mesa [^7].

El incremento de la ingobernabilidad, traída por los efectos del paro cruceño -incluyendo sus efectos estimuladores de la inflación y depresores sobre el crecimiento económico-, la pérdida de miedo ante el régimen y, probablemente más importantes, la decepción y desmoralización de la masa de sus votantes, afectarán en los próximos meses la jerarquización de tendencias de evolución del país.

Como parte cada vez más importante de esos cambios de tendencia, está el desprestigio social de los grandes pilares corporativos del MAS que son los cocaleros de Chapare, lo colonizadores que avanzan sobre las tierras bajas y bosques y los cooperativistas mineros, cuyas enormes exportaciones de oro, en papel de testaferros de empresarios chinos, brasileños y otros grupos extranjeros, acelera una implacable depredación de fuentes hídricas, biodiversidad y reservas naturales, empezando a impactar en medios de difusión masiva y público general.

Igual que en 2019, Santa Cruz es el escenario principal donde la acción depredadora de los grupos neocolonizadores que expanden frontera agrícola y mercado ilegal de tráfico de tierras. Este se se ha tornado cada vez violento, por la acción de comandos civiles y milicias que avanzan sobre bosques, reservas naturales y territorios indígenas. 

Hasta ahora no se perciben indicios de que la población capte la íntima relación entre la depredación y la agricultura extensiva que está en el núcleo del llamado modelo departamental de desarrollo y su funcionamiento como puente y enlace entre los intereses del gran negocio agroexportador y la base social colonizadora y miniproductora de soya en el departamento.

La suma de la gran agitación agregada en las últimas semanas apura el despliegue del quiebre hegemónico abierto en 2019 y que ha recuperado su impulso, después del paréntesis que trajeron las elecciones de 2020. No hay ni nuevos sujetos o proceso constituyente en marcha, aunque grupos conservadores del orden caído en 2005 se presenten bajo atuendos federalistas o de reclamo de otros cambios administrativos estatales.

## Notas

[^1]: Y donde el MAS ha retrocedido en votación, después de haber logrado 49% en 2014 y retroceder a 34% en 2019 y 36% en 2020

[^2]: Como lo ha expresado el gobernador de Chuquisaca -adversario y víctima judicial del régimen- quien ha anunciado que buscará pactos con otros departamentos para resistir la legítima transferencia de recursos y bancas a Santa Cruz.

[^3]: La sola formación de ese Comité permite ver que, pese a su resurgimiento de 209 en adelante, las solas fuerzas del comité Pro Santa Cruz son insuficientes para convocar y dirigir una movilización unificada.

[^4]: El rector Universitario cobró un papel protagónico, previamente desconocido para ese espacio institucional, debido a que probablemente expresaba no solo a la casa de estudios, sino a fracciones desconfiadas y descontentas con un largo paro, incluyendo a los pragmáticos, como a los grupos empresariales más poderosos del agronegocio y banca, menos inclinados al radicalismo, dada su prolongada y fructífera experiencia en negociaciones t acuerdos silenciosos con el régimen del MAS, desde 2008 hasta actualidad.

[^5]: Consistente en: poner en primer plano el relato Fue golpe y no fraude, para legitimar el retorno de Morales en 2025, con el apoyo de un aparato judicial, radicalmente corrompido y obediente a las directivas de reprimir cualquier riesgo electoral que amenace el triunfo de su candidatura.

[^6]: Con ella, las campañas represivas y de acoso judicial se han intensificado ostensiblemente después del paro.

[^7]: En realidad, se trata de una posibilidad abierta para cualquier gobierno sucesor del que Morales dejó inconcluso, debido a la proliferación de serios y múltiples riesgos para la gobernabilidad, ya desde esa ápoca. 



