---
lang: es
format: 
  html:
    page-layout: article
---
# Derrota en el referendo y maniobras para anularla {.unnumbered}
---

En el semestre transcurrido desde el 21 de febrero, cuando se realizó el referendo constitucional, el gobierno nacional ha enfrentado diversos episodios adversos, que ha proclamado invariablemente como victorias o medios triunfos [^1]. Parece proceder así en parte por el hábito de no reconocer derrotas, en parte por la estrategia que ha ensamblado para neutralizar y revertir el duro fracaso que obtuvo en el último referendo.

En todos los casos resulta relativamente sencillo advertir que la interacción entre la disminución de ingresos y recursos con el ascenso de exigencias y presiones de las columnas corporativas sobre las que se asienta el poder gubernamental, más la aceleración de contradicciones internas y abuso de poder, crean un circuito perverso por el que el partido de gobierno resulta ser el enemigo más constante y eficiente de sí mismo.

Durante los dos últimos meses, cuando las contradicciones sociales y políticas se han caldeado, generando una cuota mayor de sangre y muerte, ese comportamiento se ha intensificado en extremo y ha terminado por obligar al gobierno a tomar decisiones que acelerarán el conjunto de tensiones acumuladas.

## Anclados en una discusíon distractiva

El MAS trató de recuperarse del atolondramiento inicial que se apoderó de él cuando no cabían más dudas sobre la votación del referendo último, intentando montar un contraataque, conducido como una operación de guerra psicológica, que en oportunidades previas le había brindado resultados satisfactorios.

Con ese fin, urdió una narrativa en torno a cargar el fracaso electoral a “una mentira contra el pueblo” (¿¿??), fabricada por “la fuerza del imperio” e instrumentalizada por un “cartel de la mentira” [^2], bajo el “auspicio de la oposición de derecha”.

Este enfoque, ratificado y reforzado durante la presentación de cargos de los fiscales contra Gabriela Zapata, trata de despolitizar al máximo los resultados desfavorables del 21 de febrero, atribuyéndolos a una reacción básicamente emocional del público, ante las “falsas noticias” sobre una oculta relación sentimental del presidente y una “dudosa paternidad” originada en esta.

Durante los 17 días que transcurrieron entre la revelación de la novia, el hijo y la votación, los medios masivos de difusión y la oposición parlamentaria concentraron sus pesquisas y publicaciones, casi exclusivamente, en los aspectos sentimentales y morales, y casi nada en sus consecuencias sobre contrataciones y nexos con empresas chinas.

La posible existencia de tráfico de influencias recién empezó a tomar cuerpo después del 21 de febrero, y la comisión legislativa que examinó los contratos con la CAMC se formó y empezó a funcionar varias semanas después [^3].

Sin embargo, la estrategia de comunicación oficial, deliberada y maliciosamente, funde ambas cosas en un solo acto, tratando de hacer aparecer como que la inexistencia de una criatura procreada por la pareja debería borrar cualquier sombra de duda sobre el manejo de las contrataciones directas. De estas, solo se examinaron seis casos, pero hay centenares que ha ejecutado el gobierno nacional, para no hablar de la gran cantidad de contrataciones que manejan bajo las mismas condiciones los gobiernos subnacionales.

La actuación de los fiscales y de la ministra de Transparencia, al unísono, se concentran en propalar la versión de que la expareja del presidente “no ocasionó ningún daño económico al Estado” y dejan de lado alusiones sobre el problema central, referido a la calidad y transparencia de las contrataciones directas por montos megamillonarios.

Entonces, el primer paso apunta a concentrar toda la atención en lo que la campaña denomina “la mentira original” (“no hay hijo”, por tanto, no se ha favorecido a la exnovia). El siguiente encarga la investigación de los contratos a una instancia subordinada y sometida, cual es el Legislativo, controlado férreamente por el MAS. Por último, se escenifica un enjuiciamiento severo y sumario de Zapata que, con la exclusión de posible daño al Estado, terminaría demostrando que se ha engañado a parte del pueblo.

El resultado esperado es que, al abrir de algún modo el espacio para una nueva consulta, el presidente sería habilitado por el voto de los “engañados-arrepentidos”. Entonces, finalmente podría presentarse nuevamente como candidato en la próxima elección nacional.

El caso se reduciría a que una estafadora habría esquilmado a incautos, nacionales y extranjeros, prometiéndoles favores que no podía cumplir; de este modo, el gobierno obtendría un resonante triunfo. Esta es la impresión que se esmera en dar. Pero el problema radica en que estas conclusiones solo pueden ser asumidas si se olvidan varias piezas clave de lo ocurrido.

## Amnesia selectiva

Para empezar, todo lo que viene pasando en el transcurso del año no hace más que ratificar que la dilución de la credibilidad pública de las autoridades se vincula muy directamente con la desconfianza que promueve el avance de la desaceleración económica [^4], sistemáticamente minimizada por el gobierno. En igual medida, nace de la proliferación de denuncias sobre múltiples tipos de abuso de poder, incluyendo, en primerísimo plano, la corrupción (es decir, el uso del poder público para beneficio de individuos o grupos), antes que la reacción moralista de una fracción del fiel electorado oficialista.

Lo anterior pone una enorme de duda sobre la eficacia del millonario esfuerzo propagandístico para “revelar” un amarre entre el hegemonismo norteamericano [^5], la oposición política y la alianza de medios masivos de difusión con redes sociales virtuales en pacto.

La experiencia histórica demuestra que el intervencionismo de EE. UU. y su deseo de mantener su hegemonía en nuestro continente es una constante, pero que está en proceso de repliegue y declinación desde el 11 de septiembre de 2001, cuando esa potencia dirigió su atención a otras latitudes. De allí que la mayor parte de las veces, y posiblemente todas, en las que el MAS se declara víctima del intervencionismo externo, solo está mostrando impotencia para resolver un problema o usando un recurso propagandístico de victimización.

No es mejor el resultado que le deja al gobierno su contraofensiva, si se analiza el saldo de las “bajas” que ha logrado con su avalancha de acusaciones para barrer con sus críticos, al menos simbólicamente o mediante la emigración forzosa. Y es que de todos a los que señaló y acusó, solo dos han cedido a sus presiones y actos intimidatorios [^6], mientras que los demás, tanto o más estigmatizados o temidos por el oficialismo, se mantienen en lo suyo, igual que los medios y agencias de comunicación acusados de conformar el “cartel de la mentira”.

Le ha ido mejor al gobierno al haber postergado por dos años la caducidad de licencias para radios y televisoras porque, además de las irreprimibles expresiones de alivio de los empresarios de medios masivos de difusión, estos se han comprometido a abrirse más al flujo noticioso de las obras realizadas o emprendidas por el Ejecutivo.

Entre febrero y agosto se verifica el agotamiento de la racha triunfal del oficialismo, que caracterizó a la década cumplida en enero. Desde el referendo hasta el último choque con los cooperativistas y las tensiones que demandan un pacto fiscal, pasando por las disputas con los transportistas y las personas con discapacidad, los costos que ha tenido que asumir para imponer su voluntad son muy altos, y crecen con cada nuevo conflicto.

Pero la peor de las derrotas (por el costo estratégico que impone al país), y la que menor atención periodística y política ha concitado es el reconocimiento —planteado en tono de suficiencia y desafío— de que tenemos por delante cuando menos 20 años de extractivismo.

## Fractura del bloque en el flanco cooperativista

El repliegue casi inmediato de los miles de bloqueadores convocados por la dirección de la Federación Nacional de Cooperativas Mineras (FENCOMIN) después de que se localizó y levantó el cuerpo inerte del exviceministro del Interior Rodolfo Illanes (secuestrado y asesinado por dirigentes cooperativistas), se ha asumido, irreflexivamente, como un presunto triunfo gubernamental.

Amargo y cruento, pero triunfo al fin, según la visión oficialista, obviando que existen demasiadas indicaciones de que el saldo final de los acontecimientos se inclina hacia el otro lado.

Durante las horas previas al asesinato del viceministro, los voceros oficiales reiteraron, de manera uniforme y constante, que la intención oficial era no romper definitivamente con el sector [^7], refiriéndose a guiños y mensajes sobre los alcances de una negociación “flexible” e “inteligente”.

El origen de tan inusual cordialidad con un grupo con el que se está en conflicto radica no solamente en el importante número de socios directos de la FENCOMIN [^8] (y de familias no cooperativistas cuyas actividades giran alrededor de estos), sino en el carácter de ejército paralelo que puede jugar el sector, como lo ha demostrado en diversas ocasiones, y en el 34% que aporta a la producción total de minerales del país durante los últimos años.

Pero más importante que su peso económico, político y electoral es el hecho de que funciona como una válvula de escape a la enorme presión que implica la nunca resuelta escasez de fuentes de trabajo. Por ese motivo, es una auténtica pesadilla para cualquier gobierno la posibilidad de que los malos y precarios puestos de trabajo que proporciona el cooperativismo disminuyan o se esfumen, ya sea por la baja de precios, por el agotamiento de las vetas o por la prolongación de los conflictos sociales.

Lo anterior no debe perderse de vista en ningún momento para entender los inverosímiles equilibrios de las autoridades para no llegar a una colisión frontal con la enorme y poderosa corporación con la que se asoció, y que contribuyó decisivamente a que el modelo plurinacional sea sustituido por un modelo de gobierno corporativista y un bloque de poder basado en las más cohesionadas organizaciones sociales de origen popular (cocaleros, cooperativistas, colonizadores, campesinos, comerciantes importadores de electrónicos y otros bienes de consumo, propietarios de flotillas de transporte, etcétera).

El bloque constituyente incluía a los indígenas, que fueron marginados rápidamente, en medio de una operación política y propagandística que trata, hasta el día de hoy, de negar y confundir las diferenciaciones históricas que se han desarrollado, a partir de la Revolución de 1952, en las poblaciones indígenas del país. Para ello, apelan, por una parte, a identificar al jefe de Estado como indígena y, por otra, a mantener la ficción histórica y sociológica que unifica y disuelve fronteras entre pueblos indígenas y campesinos (nacidos y vinculados ciertamente con esa matriz, pero portadores de una identidad propia que los distingue de aquellos y que es fuente de
choques y contradicciones entre ambos).

La razón principal de la exclusión de pueblos indígenas de tierras bajas, principalmente, y de algunos de la región andina, está causada, en primer lugar, por la consolidación del patrón de acumulación extractivista y rentista, cuya dinámica condiciona y favorece el proceso de centralización y concentración de poder que se da en la última década.

La ruptura con los cooperativistas tiene un origen casi exactamente opuesto, porque no hay ninguna iniciativa estatal para forzar su salida —que es lo que pasó con los indígenas—, sino la mayor elasticidad para favorecer su permanencia [^9]. Sin embargo, lo que los acomodos y acuerdos no declarados ya no pueden resistir es la gran ofensiva cooperativista, originada en la disminución de sus ingresos por el descenso de precios de minerales en el mercado mundial.

Esta declinación de ingresos lleva a la dirigencia cooperativista a tratar de obtener lo que se les había negado con la aprobación de la Ley No 535, de Minería y Metalurgia, promulgada el 19 de mayo de 2014, con la cual, de todas maneras, habían logrado significativas concesiones.

De allí que incluso la denuncia gubernamental —que atribuye un carácter conspirativo a la movilización de los cooperativistas, cayendo completamente en su libreto habitual para explicar y manipular las situaciones de conflicto— pueda haberse quedado corta ante la magnitud de las pretensiones esquematizadas en la “agenda nacional cooperativa”.

Es así como lo entienden investigadores del CEDIB [^10]: el triunfo del pliego cooperativista solo era posible mediante un quebrantamiento abierto de la CPE respecto a la propiedad de los recursos naturales, el control legislativo de contratos y el régimen ambiental, además del desconocimiento de atribuciones del Legislativo y de la recuperación de posiciones en el Ejecutivo. Por ello, en su trabajo, no dudan en caracterizar la estrategia cooperativista como de “toma del Estado”.

Inmediatamente después del secuestro, tortura y asesinato del viceministro del Interior, el gobierno todavía dio muestras de una cierta dubitación. Recién entre el 1 y 2 de septiembre adoptó un franco vuelco, con la aprobación de cinco decretos [^11], algunas resoluciones administrativas y otras medidas que prácticamente desechan las exigencias del pliego petitorio y la movilización cooperativista.

Es difícil discriminar cuánto pesaron las consideraciones estratégicas sobre cortar las pretensiones de cooperativistas y empresas privadas asociadas a ellas, o las de corto plazo, relacionadas con la idea de despejar las dudas que han provocado las omisiones, la negligencia y la falta de transparencia con que respondieron las autoridades a la captura de su colega.

## El fondo y otro risgo de grieta

En otro frente, es necesario no perder de vista —en relación con los problemas y contradicciones del funcionamiento de un gobierno corporativista— los descalabros que ha traído y continúa amontonando el destape de los desfalcos del Fondo campesino (FONDIOC).

El manejo discrecional y opaco de sus recursos sirvió, en un principio, para anudar las relaciones con las corporaciones campesinas, que juegan también como participantes protagónicos del bloque de poder. Sin embargo, el destape del escándalo por la prensa a fines de 2013 obligó a una intervención oficial dos años más tarde.

El lento y laberíntico avance del proceso ha significado en un principio la cárcel para dirigentes de base y dirigentes medios. Más adelante, ha afectado a dirigentes nacionales y a dos exministras. El descontento y la desconfianza que produjo no se ha amortiguado ni un poco con las declaraciones presidenciales que cifran (sin ningún respaldo o prueba) en un máximo de dos y medio millones de bolivianos todo el daño infligido al Estado, ni con que el vice llame “microcorrupción” a los 71 millones de bolivianos y los 102 millones de bolivianos que la Contraloría y la interventora, respectivamente, detectan en sus informes.

Mantener el giro adoptado ante los cooperativistas mineros manifiesta el predominio momentáneo de una tendencia interna que trata de iniciar una nueva fase de la política gubernamental, caracterizada por el predominio de la razón de Estado (más que de institucionalización o de imperio de la ley), para sobreponerse a las presiones corporativas que amenazan con completar un proceso de implosión del esquema gubernamental.

Proyectar la imagen de un Estado fuerte, que se ubica por encima de las demandas de quienes componen el bloque de poder, desconcertaría nuevamente a opositores y seguidores, y podría entusiasmar a la franja de clases medias urbanas que reclaman imponer el orden. Con todo, tiene pocas probabilidades de sostenerse en el tiempo, mucho menos en tanto subsista y se prolongue la coyuntura de escasez [^12] y se mantenga el temor a reiterar pérdidas electorales como la observada en Potosí.

## Una respuesta unívoca

Por ello resulta dudoso que el equipo de gobierno se embarque realmente en una reingeniería política y social que implique abandonar o verdaderamente alterar el molde corporativista vigente, virándolo hacia un esquema bonapartista, que se asienta más en un accionar represivo [^13] que, de aquí en adelante, incluya entre sus víctimas a otros componentes del bloque de poder.

Si bien el descabezamiento de la FENCOMIN favorece que las grandes heridas infligidas al sector permanezcan silenciadas o musitadas en voz baja, no facilita sus relaciones con un régimen cuya apuesta principal sigue siendo la habilitación del actual presidente como candidato para su cuarta reelección. Es un régimen que, por tanto, no puede darse el lujo de una ruptura con una franja tan importante de electores.

La brecha abierta con los cooperativistas va mucho más allá del completo quebrantamiento de sus estructuras organizativas y de la proscripción de su dirigencia, objetivamente comprometida como cómplice en los hechos que culminaron con el asesinato del viceministro. Implica los cinco muertos durante las refriegas, así como el rechazo de sus demandas y una pública y muy extendida estigmatización social que deja como saldo [^14]. El precio de levantar el bloqueo caminero y el posible y prolongado reflujo que afectará a los cooperativistas puede llegar a ser muy alto para la estrategia “reeleccionista”.

Las recientes declaraciones de Evo Morales Ayma, afirmando que se habría resignado a alejarse de la presidencia a la conclusión de su mandato constitucional en enero de 2020, son una pista de que, al menos subconscientemente, el alto mando del MAS empieza a percatarse de que la suma de obstáculos dificulta cada día más ejecutar su estrategia, subordinada a un solo objetivo: permanecer en el control del poder, manteniendo habilitada la carta electoral de su jefe máximo.

Sin embargo, la comprensión de que jugar todo a una sola carta es una equivocación no se abrirá paso fácilmente en el MAS, ya que la suma de intereses, compromisos y cultura organizacional en que se sustenta es demasiado pesada y compleja.

Deconstruirla y sustituirla por un planteamiento diferente que remate en alternativas flexibles necesitaría, por ejemplo, cambiar radicalmente la lógica de imposición de intereses sectoriales (el corporativismo como egoísmo de grupo), para sustituirla por una visión de conjunto. Los plazos parecen demasiado cortos para ese fin que, además, requeriría una radical renovación de las cúpulas corporativas, que han enajenado la autonomía de sus organizaciones por apetitos e intereses cada vez más mezquinos.

Respecto a la cultura que rige la organización interna del gobierno y las relaciones entre este y las organizaciones corporativas de origen popular, se caracteriza por consagrar al máximo dirigente como un ícono intocable e incuestionable. Esto prácticamente anula la selección del mejor reemplazante electoral porque el culto al jefe viene acompañado de celos y sospechas infinitas.

Debido al temor que prevalece entre los aspirantes a aparecer como esa figura, que fácilmente puede convertirse en la figura de un “traidor”, la selección del sucesor tiende convertirse en la búsqueda del peor candidato. Eso puede reavivar la opción “Cámpora” (o Putin) simplificada, en versión boliviana [^15].

La obsesión por mantener el control del Estado mediante el atractivo electoral de su único jefe y conductor reduce las posibilidades de que esta fórmula, que ha funcionado en el pasado, lo haga indefinidamente. Si el MAS continúa aferrándose a ella, en tanto subsistan las condiciones materiales adversas que enfrenta, se arriesga a que, al forzar esa carta, ni siquiera con ella pueda garantizarse una victoria en la próxima elección nacional.

La extrema crispación que puede alimentar la desesperación partidaria por imponer su criterio a una sociedad que se aleja de este se arraiga en un contexto continental en el que la caída de los gobiernos de Argentina y Brasil se acompaña del gran deterioro del venezolano y las dificultades del ecuatoriano; es decir que la malla de soporte internacional más próxima está muy debilitada. Esta correlación adversa se afianza, en tanto que en Europa y Estados Unidos se multiplican las novedades de recuperación de las fuerzas más conservadoras.

## Una renuncia estratégica

La expresión vicepresidencial del 18 de agosto: “Nosotros vamos a usar el extractivismo todavía un par de décadas; si no ¿de dónde vamos a sacar el dinero para mantener los bonos [y] las condiciones de formación intelectual y humana de las personas?” [^16], va más allá de lo circunstancial y se convierte en una llana admisión de derrota estructural, puesto que el cambio de matriz productiva era uno de los más importantes compromisos en el momento de asumir el poder. De hecho, los esfuerzos gubernamentales por cumplir con ese compromiso se anotan como una clara diferencia con las administraciones anteriores [^17], pero resultan tan insuficientes que nuestra economía en su conjunto ha profundizado su dependencia de la extracción y exportación de riquezas naturales.

La escasa relevancia noticiosa que ha recibido y el poco tráfico de debate que ha generado en las redes sociales virtuales demuestran que apenas se ha aquilatado su verdadera importancia como signo de derrota y apocamiento oficial. El hecho de que esta admisión (“no pudimos hacerlo, ¿y qué?”) haya logrado pasar casi desapercibida podría explicarse porque el conjunto de partidos políticos, organizaciones sociales oficialistas o independientes, las universidades, la mayor parte de ONG y otros actores y sujetos, comparten esa resignación del gobierno.

Lo que ha dicho el vice confirma una escasa información y ningún interés por comprender que la magnitud de los retos ambientales globales no deja margen a que nuestra posición sea: “si ellos [los grandes capitalismos del norte] lo hicieron, nosotros no tenemos por qué privarnos de repetirlo”.

Tal tipo de silencios o respuestas imperceptibles da la pauta de que el plan económico gubernamental de largo plazo, que consiste en intentar incrementar la generación eléctrica mediante megahidroeléctricas y plantas termogénicas de ciclo combinado y mediante un mayor avance de la frontera agrícola y ganadera (sacrificando bosques), competirá con fuerza con propuestas similares y menos creíbles de sus oponentes. Y es que el gobierno aún preserva la credencial de estar a la cabeza del crecimiento regional y de mantener un cierto equilibrio al que se aferra una mayoría electoral.

Sin embargo, la recuperación mundial y regional no se ajusta a las expectativas oficiales porque se mantiene el estancamiento de los precios de commodities, principalmente del petróleo. Una coyuntura de escasez prolongada y severa no puede conjurarse con los proyectos de endeudamiento e inversión presentados por el gobierno. Además, la ventaja de asumirse como el generador del incremento de la capacidad y expectativas de gastos de la llamada “clase media precaria”, puede volcarse abruptamente en su contra.

Planes de inversión gigantescos, como los del Chepete/Bala, empiezan a mostrar significativas grietas en su concepción, sostenibilidad ambiental, social y económica [^18]. Toda la generación basada en gas está amenazada por el estancamiento de reservas, y los préstamos para realizar grandes obras urbanas (transporte, principalmente) pueden apresurar el tránsito de desaceleración a crisis. Las cifras gigantes de decenas de miles de millones de inversión pública se tornan cada vez menos sustentables, mucho más al compararlas con las increíbles grandes deficiencias en servicios básicos, salud o educación.

Se ratifica una tendencia central a profundizar confrontaciones y tensiones, a las que se incorpora el riesgo de estallidos de violencia focalizada. Persiste el hecho de que, aunque el debilitamiento interno del MAS llegue a implosionar, eso no constituye a una alternativa por sí misma.

Si el MAS requiere liberarse de su dependencia hacia su jefe, los partidos de oposición están en una situación similar porque el presidente y sus mayores opositores representan, juntos, este momento histórico y los nudos que se aprietan. La renovación partidaria y electoral será insuficiente si las organizaciones sociales no superan la situación de secuestro por la que atraviesan y recuperan su autonomía.

::: {style="text-align:right; font-weight: bold;"}
Septiembre de 2016
:::

## Notas

[^1]: Respecto al último, que es, además, el más serio, el presidente ha proclamado que “ha derrotado un golpe de Estado”.

[^2]: Que sería una especie de consorcio entre medios de difusión masiva, periodistas y activistas, especialmente los de las redes sociales virtuales, tal como lo describió el ministro de la Presidencia en su extensa presentación ante la Asamblea Legislativa el 19 de mayo pasado4. Esta cronología relativiza enormemente el peso del episodio en la conducta de los votantes, y lo incrementa en favor de la desaceleración económica y la corrupción, en especial, pero no únicamente, la del FONDIOC. 

[^3]: De todas maneras, la comisión manejada por el oficialismo detectó problemas en al menos dos de los contratos, mientras investigaciones periodísticas, como las del matutino Página Siete, señalan que el precio del ingenio de San Buenaventura es 160% mayor que el de uno privado, construido recientemente en Santa Cruz, con similar capacidad de producción de azúcar y alcohol. Detecta evidentes contradicciones en la información sobre la rescisión del contrato de la vía ferroviaria Bulo Bulo-Yapacaní y el manejo de las boletas de garantía, además de otros problemas en otros contratos con la corporación china.

[^4]: Encuestas de distintas empresas (Tal Cual, IPSOS, Mori), realizadas entre abril y julio, coinciden en detectar una tendencia a la baja en la aprobación del presidente, que desciende hasta el 52% en julio. Al cabo de una década, conservar una mayoría favorable continúa siendo excepcional, pero contrasta con los registros mucho más altos (rondando el 70%) que ha exhibido el primer mandatario. Las expectativas económicas y las relacionadas con el empleo manifiestan similar comportamiento.

[^5]: La información disponible no permite confirmar, ni descartar, que aparatos de inteligencia norteamericanos hayan intentado sacar ventaja de la situación, pero no desmiente ninguna pieza esencial del affaire Zapata. La actuación del periodista Valverde, que huye al mismo tiempo que da fe de que no existe el hijo cuyo certificado publicó él, y ahora su ruidosa reaparición al publicar videos donde se exhibe parte de la cruel experiencia que terminó con la vida del viceministro asesinado en el conflicto último de los cooperativistas, resulta muy conveniente para las explicaciones conspirativas que usan los gobernantes.

[^6]: Ellos son Carlos Valverde y Wilson García, director del Sol de Pando, quienes se han refugiado en la Argentina y Brasil, respectivamente.

[^7]: Solo como ejemplo,el exministro de Gobierno Moldiz aseveraba en “Diálogo Panamericano” (en radio Panamericana), el sábado 21 de agosto pasado, que “los cooperativistas no van a salir del bloque de poder” y el 31 de ese mismo mes, el vicepresidente se esmeraba en separar la responsabilidad de “unos pocos dirigentes (cooperativistas) de sus bases”.

[^8]: Quienes, sumando a sus peones y asalariados, alcanzarían un número de entre 100 a 150 mil, según las múltiples y dispares apreciaciones que existen al respecto y que podrían involucrar a otras 30 a 50 mil personas en actividades colaterales a la producción de las cooperativas. Es decir que en el escenario más alto representan un potencial de casi medio millón de votos, equivalentes a un 15,7% de los que ha logrado el MAS en su votación más alta (3.173.304 votos, dentro y fuera del país en las nacionales de 2014).

[^9]: Lo que incluye, además de los créditos, cesiones y transferencias de equipos y maquinarias, la transferencia de nuevos yacimientos (Colquiri, por ejemplo), la consolidación de anteriores, una “amnistía” por convenios suscritos entre cooperativas y privados (incluyendo multinacionales) y otra, de facto, por la casi total omisión de las cooperativas en el cumplimiento de regulaciones y obligaciones de mitigación y remediación ambiental, con costos tan altos como la completa contaminación de la cuenca del Pilcomayo y una significativa participación en los problemas de la cuenca endorreica del Poopó. 

[^10]: Se puede bajar el texto completo desde el siguiente enlace: [http://www.cedib.org/wpcontent/uploads/2016/08/TomarelEstadoporAsalto-final.pdf](http://www.cedib.org/wpcontent/uploads/2016/08/TomarelEstadoporAsalto-final.pdf)  

[^11]: En resumen: se revierten al dominio del Estado las áreas sobre las que se suscribieron contratos a riesgo compartido entre mineras cooperativistas y empresas privadas; se revertirán las áreas de cooperativas mineras que no tengan actividad; se verificará el número de asociados, la entrega de información del volumen y valor de producción, y la distribución de los ingresos por cooperativista; se ampara bajo la Ley del Trabajo a los asalariados y peones que no sean socios y, por último, se prohíbe y castiga penalmente el uso de explosivos en movilizaciones.

[^12]: ¿Con qué fuerza puede el gobierno predicar la necesaria subordinación de los intereses particularistas a los generales, cuando en su manejo cotidiano hace exactamente lo opuesto?

[^13]: Se trata de un esquema basado en concentrar toda la autoridad en manos de un jefe, al que se atribuye una condición de genio y de héroe, capaz de comandar la superación de una gran crisis. Se basa en las ilusiones ideológicas de sus seguidores y votantes. Supone habitualmente la neutralización del Parlamento, lo que no es necesario en nuestras circunstancias, dada la completa subordinación de este órgano al Ejecutivo. El cambio radicaría, más bien, en apaciguar la conducción de las organizaciones sociales, con el ejemplo que se intenta dar a través del tratamiento ahora aplicado a los cooperativistas.

[^14]: La preocupación que produce en el equipo de gobierno la ruptura con los cooperativistas ha empezado a expresarse con los llamados públicos a reiniciar negociaciones después de que entreguen a los comprometidos en el asesinato (véase La Razón del 5 de septiembre de 2016).

[^15]: Ya se mencionó en un análisis anterior esa posibilidad, en sentido de que el actual presidente y el vice se presenten en una fórmula en la que intercambien sus cargos. Bastaría con que, luego de las elecciones el candidato a vicepresidente se comprometa a renunciar públicamente a la presidencia para traspasar el mando al nuevo vice (Morales Ayma).

[^16]: Véase: [http://www.la-razon.com/economia/Garcia-extractivismo-produccion-PNUD-Boliviapobreza_0_2547945273.html](http://www.la-razon.com/economia/Garcia-extractivismo-produccion-PNUD-Boliviapobreza_0_2547945273.html).

[^17]: Las plantas de secado de gas natural, la de urea, la de polipropileno y la experimental de litio son sus mayores realizaciones. Sobre cada una de ellas existen observaciones, no solo en cuanto costos muy inflados, sino sobre su eficiencia, rentabilidad e impacto ambiental. Pero incluso superando o descartando todas las críticas, el mismo gobierno reconoce que no modifica la matriz productiva que recibió de herencia.

[^18]: Véase como muestra la ficha ambiental y otras publicaciones en: [https://fundacionsolon.org/category/pacha/el-bala/](https://fundacionsolon.org/category/pacha/el-bala/)