---
lang: es
format: 
  html:
    page-layout: article
---
# Panorama después de las elecciones nacionales {.unnumbered}
---

El cierre del año subraya la importancia de los temas que se vislumbraban como los que marcarán la agenda de inicios de 2015: la disminución de ingresos fiscales; las elecciones regionales y el declive del sistema partidario; las convulsiones del aparato administrador de justicia y el auge de la violencia contra mujeres y menores.

La caída de precios de materias primas, especialmente los del petróleo, que aparentemente puede cerrar el “superciclo” de precios, tiene visos de ser parte de movimientos —algunos explícitos, otros soterrados— dirigidos a reajustar la correlación internacional de fuerzas del período unipolar que benefició a EE. UU. desde la finalización de la Guerra Fría.

Los planes de la potencia para recuperar su autosuficiencia energética y conquistar mercados de exportación, gracias a sus grandes reservas de gas no convencional, y a su más rápida recuperación de la crisis financiera de 2008 en comparación con Europa, tienen una influencia determinante en la reconfiguración de los mercados de materias primas, y ejercen una presión considerable sobre exportadores de petróleo como Rusia, Venezuela, Ecuador y Brasil, entre otros [^1].

Las maniobras de reordenamiento y ajuste de las cuestiones de poder internacional seguirán pesando más que las gravísimas advertencias en torno a que los desequilibrios ambientales [^2] están por alcanzar —si no lo han hecho ya— niveles irreversibles. Al pronóstico de serio retroceso regional económico para el próximo año, ha de agregarse el especial impacto que sufrirán economías como las de Brasil, Venezuela, Argentina [^3] y Ecuador, componentes clave del conjunto de países más respondones a la preponderancia estadounidense en la región.

## ¿Invulnerables?

Cuando se inscriben en ese cuadro, las expresiones y decisiones de nuestro zar económico, el ministro del área, resultan mucho más llamativas y desafiantes ya que, según su interpretación, las previsiones oficiales de que el PIB crecerá en un 5,9% durante el año siguiente se mantendrán tal cual, pese al retroceso internacional de los precios.

Así, con aplomo imperturbable, ha contradicho a algún colega del gobierno y ha tildado de “mezquina” la estimación de la CEPAL [^4] respecto a que el techo de nuestro crecimiento sería un 5,2%. Su principal argumento es que ya en el año 2008 superamos una situación aún más adversa, cuando el barril de petróleo cotizó en 30 dólares, y que “dependemos poco” del sector externo y mucho de la inversión pública y del “dinamismo de nuestro mercado interno”.

Es mucho más que una discusión teórica porque, dependiendo de lo prolongado e intenso que sea el retroceso de precios (de hidrocarburos, minerales, soya), se instalará, o no, una coyuntura de escasez que pondría a prueba la solidez del modelo económico, que exhibe hasta ahora un rendimiento muy favorable [^5] respecto a algunos vecinos, especialmente grandes exportadores de materias primas, como Venezuela, Brasil o Argentina.

La firmeza oficial no ha quedado en las palabras, y su intransigencia en rechazar la postergación del pago del segundo aguinaldo es una clara evidencia de que se ha propuesto mantener su mensaje a toda costa, para también capitalizarlo como un activo para las elecciones de marzo.

Aunque de momento nadie sale a debatir con firmeza y persistencia la posición oficialista —debido, probablemente, a que la duración y profundidad de la caída de precios sigue siendo un enigma, y a que casi todas las veces anteriores los pronósticos pesimistas de expertos y opositores salieron malparados—, hay consenso, incluso entre miembros del oficialismo, respecto a que nuestra presunta inmunidad sufriría, primero, y terminaría resquebrajándose, a continuación, si la baja se mantiene estable o si empeora durante más de un semestre.

## La frontera del dibujo libre

Conocedor de los riesgos que se ciernen sobre el clima de estabilidad —pese al discurso de su principal vocero económico (no contradicho, pero tampoco respaldado por sus superiores)—, el MAS se propone obtener la mayor ventaja posible en la disputa electoral subnacional.

Concurrirá a la cita con los reiterados antecedentes, confirmados por las experiencias de 2005 y 2010, de que sus votos disminuirán hasta en un tercio respecto a lo obtenido en las nacionales [^6]. Será un combate que le presentarán un mínimo de 150 frentes regionales (algunos armados por UN, MDS y PDC) y “agrupaciones ciudadanas”, según ha contabilizado el diario La Razón del 7 de diciembre de 2014.

Para las elecciones de 2015, sus posibilidades de incrementar su control sobre las gobernaciones se concentran en Tarija [^7]; Chuquisaca podría entrar en zona de riesgo si no resuelve las disidencias internas que objetan la reelección del actual gobernador masista. El triunfo opositor en Santa Cruz permanece como tendencia predominante hasta antes del cierre de inscripciones de candidatos.

Con relación a los municipios mayores (La Paz y Santa Cruz) y otras capitales en las que perdió anteriormente [^8] (Trinidad, Tarija y Sucre), las opciones se pintan favorables a la oposición, con posible excepción de Oruro.

En la capital cruceña, el MAS cuenta con una estrategia de contingencia basada en su alianza con el alcalde de Santa Cruz de la Sierra [^9]. Si este se prorroga, como lo prevén todas las encuestas, puede mantener la misma amistosa relación que ha cultivado con el MAS en el último par de años.

Esa posible alianza, ubicada en la centro-derecha —espacio hacia el que se está desplazando el MAS— desagrada tanto al oficialismo como a UN, que se vería en la obligación de empalmarse con ella en condición subordinada. Todo lo anterior es válido mientras la predisposición social mayoritaria siga apostando a la estabilidad y mientras no se produzcan importantes alteraciones económicas (coyuntura de escasez), ni divisiones internas en el MAS y con sus aliados corporativos.

El MAS queda como único partido nacional vigente (con presencia y organización comprobable en todo el territorio del país) que, con la desaparición del MSM y el PV, carece de flanco organizado a su izquierda, mientras que a su derecha ninguna fuerza que carezca de la convocatoria para coaligar a esa franja tiene posibilidades serias de desafiarlo.

La única oposición que puede enfrentar al gobierno en tales circunstancias es una protesta espontánea que logre articular movimientos sociales, al margen de la cúpula sindical y corporativa, integrada en este momento al oficialismo.

Dichas protestas espontáneas, articuladas al margen de las organizaciones sociales cooptadas por el oficialismo, tendrán un margen relativamente estrecho para apuntarse victorias, en tanto persista la situación de reflujo y pasividad que predomina actualmente. Esta situación se ha manifestado en una votación mayoritaria a favor de la estabilidad, con un claro sello de giro al conservadurismo, y totalmente alejada del “giro a la izquierda, por torsión gravitacional de la curvatura del tiempo-espacio”, como especula el vicepresidente del Estado.

Los movimientos sociales autónomos podrán incrementar su potencia en la medida en que las señales de estabilidad se debiliten y la compactación interna del oficialismo se resienta por causas probablemente originadas en disputas de los sectores corporativos y aliados, por el control de excedentes (en una coyuntura de escasez) y/o de recursos naturales (tierras, yacimientos minerales, agua, bosques, etc.)

## Las fisuras

El juicio contra los tres miembros del Tribunal Constitucional que se sustancia en la Cámara de Senadores transcurre en un franco tono de opereta, con protagonistas que, de tan previsibles, resultan caricaturescos. Desmayos e internaciones se combinan con un viraje policíaco del Legislativo, enfatizando la agonía prolongada de la administración de justicia, que no se modificará ni con la defenestración de funcionarios ni con el cambio de mecanismos para elegirlos porque, según opinión casi unánime, las causas son múltiples y profundas.

La torpeza con que el partido oficial presiona a los acusados para que se vayan “por su cuenta” o echados por el Legislativo tiene mayores posibilidades de elevar el clima de incertidumbre, desconfianza y desesperación, que conseguir algún cambio que pueda ir más allá de una domesticación total del TCP. Si a lo anterior se añade la proliferación de acciones violentas y crímenes monstruosos contra mujeres y menores, se tiene una situación que seguirá jaqueando al poder, pero también interpelando al conjunto de la sociedad por el atraso de su reforma intelectual y moral.

Derecho a una justicia justa, pronta e imparcial y eficaces mecanismos de defensa y preservación de mujeres y menores contra la violencia y todo tipo de abusos, son temas que ya circulan en diversos espacios y que nece-
sitan cohesión, organización y respaldo de la mayor calidad posible.

::: {style="text-align:right; font-weight: bold;"}
Diciembre de 2014
:::

## Notas

[^1]: Para referencias, véase: [http://www.blogscapitalbolsa.com/article/4877/proyecciones_ del_banco_mundial_para_los_precios_de_los_commodities_en_2014.html](http://www.blogscapitalbolsa.com/article/4877/proyecciones_ del_banco_mundial_para_los_precios_de_los_commodities_en_2014.html); [https://duck-duckgo.com/?q=a+quines+perjudica+precios+petroleo+el+pais](https://duckduckgo.com/?q=a+quines+perjudica+precios+petroleo+el+pais); [http://www.paginasiete.bo/ideas/2014/12/7/cuan-larga-sera-caida-precio-petroleo-40335.html](http://www.paginasiete.bo/ideas/2014/12/7/cuan-larga-sera-caida-precio-petroleo-40335.html)

[^2]: Véase: [http://www.elpais.com.co/elpais/internacional/noticias/onu-entregara-pruebas-concluyentes-responsabilidad-hombre-cambio-climatico](http://www.elpais.com.co/elpais/internacional/noticias/onu-entregara-pruebas-concluyentes-responsabilidad-hombre-cambio-climatico)

[^3]: Expuesta, además de a una inflación pujante, a las maniobras de los fondos buitre.

[^4]: Véase: [http://www.americaeconomia.com/economia-mercados/finanzas/ministro-de-economia-de-bolivia-pib-superara-proyeccion-de-organismos-int](http://www.americaeconomia.com/economia-mercados/finanzas/ministro-de-economia-de-bolivia-pib-superara-proyeccion-de-organismos-int)

[^5]: Aparece en cambio peor parado, al situarlo en un cuadro comparativo con el conjunto de países de la región, durante la última década, dado que si bien los avances en materia de disminución de pobreza, acceso a servicios y otros índices sociales son incuestionables y merecieron el respaldo político verificado en la última elección, no alcanzan para sacarnos del antepenúltimo lugar de la tabla. Véase: [https://www.undp.org/sites/g/files/zskgke326/files/migration/arabstates/HDR_2011_ES_Complete.pdf](https://www.undp.org/sites/g/files/zskgke326/files/migration/arabstates/HDR_2011_ES_Complete.pdf)

[^6]: En 2010, pese a la mengua de unos 900.000 votos de los que obtuvo en la elección nacional, consiguió ser mayoría en 228 municipios (dos tercios), y ganar seis gobernaciones, pero tragando duras derrotas en los municipios de La Paz, Oruro, Achacachi, Quillacollo y otros a los que consideraba ganados por derecho propio.

[^7]: De momento la disputa entre Carlos Cabrera, candidato masista, y el actual alcalde Montes (proveniente del MIR) parece estar muy cerrada. En Santa Cruz todavía encabeza las preferencias el actual gobernador, pero su victoria está amenazada por la suma de candidaturas (Antelo, Nagatami) que abrevan de la misma franja de votantes que el MDS, encabezado por Costas. 

[^8]: En La Paz el actual alcalde tiene todas las de ganar, inclusive si UN presenta fórmula; pero esa certeza se debilitaría si aparecen más frentes que dispersen el voto opositor. Es este el enclave electoral que preocupa prioritariamente al MAS, porque asume que una victoria clara de la oposición en La Paz ciudad y Santa Cruz departamento, da pie a que la convergencia entre Revilla-Costas-Suárez, insinuada ya en la elección de octubre, siente bases para un frente opositor de mayor peso de los que ha enfrentado estos años.

[^9]: Al que respaldó en el Concejo y otorgó una “cuota parlamentaria” en sus listas de uninominales, a través de la inclusión de Romy Paz y Carlos Subirana, muy allegados a la principal “operadora” política del alcalde. 

