---
lang: es
format: 
  html:
    page-layout: article
---

# Triunfo de la certidumbre y la compulsión reeleccionista {.unnumbered}

Pocas cosas son tan seductoras para el género humano como la certidumbre; así lo percibía y definía hace casi cinco siglos el filósofo inglés Thomas Hobbes (fundador de la ciencia política, en mi modesta opinión).

Cuando tal necesidad de certeza se confunde con un espíritu revolucionario, como aparentemente lo ha hecho el vicepresidente del Estado, se abre un ancho margen para la polémica o para el error, según como se miren las cosas.

El hecho de que "un pueblo izquierdizado en más del 60%" ---como lo diagnosticó el segundo mandatario al analizar las elecciones de octubre pasado [^ano_2015_2-1]--- volcase su preferencia por candidatos ajenos al esquema reinante puede considerarse otro síntoma de que, inclusive en Bolivia, los electores hacen apuestas principalmente basadas en criterios prácticos más que en la exaltación ideológica.

[^ano_2015_2-1]: Álvaro García L. "El nuevo horizonte de época", en el periódico La Razón, La Paz, 2 de noviembre de 2014.

## Estabilidad en tiempos de marea baja

Si a esos datos electorales ---que exhiben el repliegue de una gran franja de votación habitualmente fiel al oficialismo--- se les agrega la actual oleada de conflictos y reivindicaciones sectorializadas, se corrobora lo poco apropiado que resulta hablar de un giro social a la izquierda, ya que falta el espíritu revolucionario, caracterizado imprescindiblemente por banderas y consignas generales (universales), alejadas del gremialismo que ahora prevalece. También está ausente la manifestación transversal entre varias capas y sectores, propia de una conciencia inclinada hacia la izquierda.

## Lo establecido, lo duradero, lo mutable

Mal que le pese a quien le pese, el MAS ha ratificado su consolidación como la única formación política organizada nacional, y su gobierno, como el más poderoso, arraigado y popular en más de un siglo (si no desde el inicio de nuestra misma autodeterminación estatal). Al aproximarnos a la primera década de su vigencia, puede verificarse que tramos importantes del relato masista se han instalado cómodamente en los imaginarios sociales. Esto, a pesar de que otros no menos significativos, como el referido a lo indígena y a la Madre Tierra, se han desmoronado, despedazados por sus propios autores.

Los triunfos electorales oficiales constituyen una tendencia que, aun cuando se relacione tan íntimamente con la fase de prosperidad de nuestro comercio externo, ha alcanzado el rango de una marca propia, con la que el público identifica y distingue a esta tienda política.

Para una importante cantidad de electores, el crecimiento económico, y las obras y flujos redistributivos que lo acompañan, son creación del talento gubernamental. Para esos fieles votantes en los comicios nacionales, la existencia de factores favorables externos no le resta méritos.

El voluntarismo característico de las reuniones presidenciales y ministeriales y la vertiginosa movilidad del jefe de Estado, que cruza nuestro territorio en todas direcciones, además de sus periplos internacionales, premiaciones doctorales, etcétera, son parte de un paquete de "dedicación, abnegación y pasos bien pensados" [^ano_2015_2-2] que apuntan en favor de la gestión gubernamental.

[^ano_2015_2-2]: Esa es la interpretación más ajustada de los altos niveles de aprobación de la gestión gubernamental, casi inquebrantable durante la mayor parte de los tres períodos encabezados por el equipo gubernamental.

Seguramente ni una improbable e imprevista catástrofe borrará este tipo de memoria, cuando se rememore más adelante la gestión gubernamental de 2006 a este año. Pueden ---e indudablemente podrán--- registrarse matices, desde los más fervorosos hasta los más escépticos, pero todos dentro de los márgenes de ese registro.

Más allá de los errores de interpretación y el triunfalismo, son la constancia de votos y lo favorables que se muestran los sondeos cuando se pide al público expresar su opinión sobre el gobierno los que han impulsado al alto mando político gubernamental a unificarse firmemente alrededor de su ya antiguo plan de reelección continua, que venía rondando las cabezas de varios de sus más destacados representantes desde 2006. Ahora, la cúpula masista en su conjunto y la de sus aliadas organizaciones sociales, parece estar compactamente convencida de esta línea, con base en los resultados electorales de diciembre de 2014.

En otras palabras, la sensación de certeza respecto a que el régimen se ha consolidado, y que se basa en datos objetivos, sirve de plataforma a la gran operación para la legitimación y legalización de la reelección presidencial, eventualmente perpetua, como una vía segura para mantener el control del poder público por lo menos hasta 2025.

Puede percibirse que el consenso se articula en torno a la muy sencilla noción de "ahora o nunca", nacida del balance entre tareas por cumplir y adversidades y riesgos. Los resultados de las elecciones regionales, especialmente en La Paz, han sido el revés más duro sufrido por esta estrategia. Sin embargo, hasta el momento se han hecho todos los esfuerzos por superar y olvidar el mal trago, confiando en que tendrá cortas proyecciones.

La apuesta se apoya en dos pilares: i) la consolidación gubernamental ha madurado y no cuenta con adversarios partidarios, ni siquiera a escala de proyecto inicial; y ii) la hegemonía ideológica del régimen tolera perfectamente las deserciones y abdicaciones en las que este ha incurrido en su transición de poder constituyente a poder constituido. Ambos elementos representan lo establecido y durable del proceso, mientras que los estrategas masistas prefieren obviar o subvalorar todo aquello que genera tendencias de modificación, inestabilidad o fractura.

## Realizaciones versus abandono

De las tareas y objetivos que originaron la reforma estatal, son los del área económica los que han alcanzado el más alto nivel de cumplimiento. Esto es visible principalmente en la recuperación del control estatal de riquezas naturales, en el ensanchamiento del rol del Estado en la economía y en una mayor redistribución del excedente a través de un cambio inamovible, de subsidios y bonos focalizados y otras medidas similares.

Las "grandes obras", que ocupan cada vez más espacio en la gestión, pueden inscribirse eventualmente en este rubro, con beneficio de inventario en un balance sobre costos y beneficios (incluyendo los que capturan informal e ilícitamente miembros de la burocracia gubernamental y sus clientelas), que debe incluir precios, beneficios reales, actuales y en proyección.

Los voceros económicos gubernamentales insisten en atribuir todas las ventajas y avances a la presunta vigencia de un modelo económico "social comunitario" y casi ninguna al gran flujo de recursos que proviene de buenos precios de nuestros exportables. Como ya se ha apuntado en ocasiones previas, lo sustancial del cambio de modelo, que efectivamente se ha dado, radica en una combinación exitosa de la nacionalización de hidrocarburos con un monetarismo convencional y una restringida, pero importante, derivación de recursos al gasto social.

Los grandes vacíos económicos se resumen en el práctico abandono de estrategias y políticas para modificar la matriz productiva y la regresión hacia un esquema de crecimiento desarrollista propio de mediados del siglo XX, que no ha podido alcanzar hasta ahora ninguna de sus pregonadas metas de industrialización [^ano_2015_2-3].

[^ano_2015_2-3]: Los mayores hitos que se han conquistado en este rubro se resumen al secado del gas natural; la planta para elaborar urea y una reducida planta experimental de extracción de litio. Ni siquiera los cocaleros, con toda su fuerza y representación en el gobierno, han visto avances en la industrialización de la coca. El gobierno, que ha construido febrilmente carreteras, no garantiza la viabilidad permanente de los caminos que unen Cochabamba y Santa Cruz, por lo que su obstinación en construir la carretera del TIPNIS bien puede interpretarse como un afán de compensar a la población del Chapare, ofreciéndole, de hecho, "soberanía" sobre nuevos territorios de donde se pueda extraer una considerable masa de recursos naturales, abriendo campo a los agronegocios y la ganadería y, principalmente, al mercado de tierras que acompañará la ampliación de la frontera agrícola y económica en general.

En la esfera política, el abandono de la idea de construir un Estado plurinacional es la más visible de las renuncias de la conducción política gubernamental. Esta deserción estratégica se desnuda con la inmovilización de las autonomías [^ano_2015_2-4], que concuerda con la manifiesta propensión a concentrar el poder, que atropella de frente a las generalizadas demandas de mayor descentralización. Esto evidencia que el gobierno rema por recortar y dar marcha atrás a procesos avanzados antes de su llegada.

[^ano_2015_2-4]: Sencillamente negadas y proscritas, como pasa con el ejercicio de los derechos constitucionales para los pueblos del TIPNIS, o reducidas a una discreta modalidad de autonomía municipal para los pueblos que han optado por la vía formal que ofrece la Ley Marco de Autonomías.

Este estancamiento, aunado a la cancelación del ejercicio de control social mediante acuerdos nítidamente prebendales con dirigentes de organizaciones sociales, así como el cierre de vías para cualquier avance de formas democráticas interculturales, ha trastocado la edificación de un Estado plurinacional por la de un Estado "policorporativo", a cuya sombra prospera la acumulación capitalista de fracciones empresariales, nacidas y derivadas de sectores populares [^ano_2015_2-5].

[^ano_2015_2-5]: El anexo de este documento se ocupa una vez más de las contradicciones y de la evolución que ha ido tomando cuerpo en el seno de clases y sujetos sociales populares, especialmente en la ruptura entre indígenas y campesinos, como cuestión central.

La manera en que se han dispuestos decenas de millones de dólares (más de 300 millones, según algunas estimaciones) en el Fondo campesino (FONDIOC), sumada a que la única rotación de cargos es la que se aplica a candidaturas parlamentarias y municipales, a la distribución de diversos puestos burocráticos gubernamentales y a nombramientos de dirigentes de organizaciones sectoriales, así como la condonación de deudas, asignación de áreas de trabajo o, directamente, entrega de yacimientos u otros recursos naturales, es como se aseguran alianzas con las dirigencias de las más importantes organizaciones y estructuras corporativas.

Todas estas flaquezas no han agotado la expansión de la participación política de importantes sectores populares, que expresan de diversas maneras una creciente conciencia sobre el ejercicio de sus derechos; esto amplía objetivamente el espacio democrático. Sin embargo, se mantienen y empeoran formas de presión y proscripción sobre la oposición partidaria organizada [^ano_2015_2-6], así como sobre la disidencia y cuadros sindicales, e inclusive sobre organizaciones sociales íntegras, remisos a disciplinarse ante las órdenes oficiales.

[^ano_2015_2-6]: El deterioro de la antes ya pésima administración de justicia, la domesticación de los tribunales electorales y el desquiciamiento de la Policía ---cuya fuerza se usa con la de las FF. AA. para beneficio oficial, intercambiando estos servicios por una actitud permisiva y laxa respecto a las irregularidades que se verifican en esos aparatos represivos--- es parte de las mencionadas restricciones

El mayor retraso se verifica en la reforma ética e intelectual que prometía el proceso de cambio. El progreso observado hasta ahora queda en una focalización de la atención social contra las expresiones más descarnadas de racismo y discriminación. Pero los avances legislativos para ponerle coto a esta herencia colonial son francamente insuficientes, lo mismo que las casi inexistentes políticas para promover cambios educativos y de relaciones sociales que las modifiquen consistentemente [^ano_2015_2-7].

[^ano_2015_2-7]: De hecho, las agresiones contra mujeres y menores no han dejado de proliferar y empeorar, como en otros países del continente; pararlas es un desafío mayor.

## Tres obstáculos

Vistos la contraposición y el equilibrio entre fortalezas y debilidades, avances, rezagos y retrocesos del proceso y sus cambios, puede corroborarse que la voluntad social prevaleciente sigue inclinándose por la indulgencia ante el régimen. Este y el próximo año serán decisivos para verificar la profundidad y la firmeza de la adhesión y permisividad ante el desempeño del gobierno, en una fase en la que crecerán adversidades que hasta ayer eran débiles o inexistentes.

La mayor de estas pruebas es la situación de estrechez relativa a la que nos conduce el declive de los precios de hidrocarburos y minerales y, secundariamente, de los alimentos (que tienen mejores y más rápidas posibilidades de recuperación que los anteriores). Un vigoroso dueto entre el ministro de Hacienda y el vicepresidente han fortalecido la propaganda en sentido de que las inversiones estatales y el consumo interno nos protegerán de los efectos recesivos importados.

Los importantes recortes de ingresos y, consecuentemente, de las coparticipaciones tributarias, desacreditan tal interpretación y obligan a que se baje el tono, aunque sin dejar de insistir en que, de cualquier manera, permaneceremos fuera de la zona de riesgos mayores.

Adicionalmente, esta primera amenaza para mantener la estabilidad y, consecuentemente, el plan de reelección continua, aumenta con la adopción de recortes presupuestarios, supresión de subsidios y alza del celo recaudador estatal.

Inhibidos en principio de poder recortar las inversiones para obras gigantescas (teleféricos urbanos, carreteras como la del TIPNIS, centralita nuclear) ---ya que tales proyectos cumplen un rol central en viabilizar la estrategia continuista---, los funcionarios responsables del Servicio de Impuestos Nacionales realizan excursiones de cacería para apretar a los contribuyentes habituales y alcanzar a nuevos y reticentes. Con ello buscan amortiguar la merma de ingresos, lo que está provocando el incremento y la aceleración de la segunda amenaza, que consiste en el surgimiento de exigencias corporativas y de diversas formas de presión sobre los precios al consumidor.

La política gubernamental intenta paliar estos efectos con sus planes de grandes obras y realizaciones (a las que debería agregarse la demanda planteada ante la Corte Internacional Judicial de la Haya), entre otras [^ano_2015_2-8]. Todas ellas refuerzan el viraje programático de tipo desarrollista, con un componente nacionalista cada vez más marcado, que se apoya en las declaraciones oficiales de que estaríamos en condiciones de aspirar a un rol de "potencia regional".

[^ano_2015_2-8]: Los significativos éxitos internos que ha conseguido hasta ahora con un enfoque de frente unido y plural, al lado de la estruendosa molestia que embarga, por vez primera desde 1879, a la Cancillería de Chile y a casi todos sus políticos, pueden continuar siendo capitalizados políticamente por el oficialismo (mientras no se supere un cierto límite de sobreexplotación al que se ha estado acercando). Esto, hasta que se resuelva la objeción presentada por Chile, cuando se abrirá otra etapa, que estará signada según cómo dirima la Corte de la Haya estos asuntos.

De ese modo, la propaganda sobre la centralita nuclear [^ano_2015_2-9], asociada a la consigna de "núcleo energético continental", se difunde bajo una modalidad esencialmente emocional e irracional, de orgullo patrio, soslayando el debate sobre cuestiones objetivas, como costos, beneficios, riesgos y ventajas comparativas. Es la misma manera en que el Ejecutivo ha procedido hasta ahora con la carretera por el corazón del TIPNIS.

[^ano_2015_2-9]: La denomino así porque, con un presupuesto de algo menos de 2.000 millones de dólares, su capacidad de generación será muy limitada. Véase: <http://www.cienciayenergia.com/Contenido/pdf/020313_rad_tn.pdf>, p. 40.

Es indiscutible la eficacia de este enfoque y la de los mensajes que genera y acompaña, vistos desde la óptica de los resultados en las elecciones nacionales y desde la agregación persistente de poder que le han consentido montar al MAS. Pero las obras realizadas y proyectadas no permiten contener la seguidilla de presiones corporativas [^ano_2015_2-10] ---el segundo riesgo para la estrategia de reelección--- que se ha desatado como producto de la menor disponibilidad de recursos, y de los ajustes y recortes que se está implementando.

[^ano_2015_2-10]: Las de panificadores, comerciantes de carne y cooperativistas mineros son las que están en curso, junto a movilizaciones regionales en desarrollo o listas para iniciarse, en tanto que se anuncian las de campesinos (probablemente vinculadas a la gran inquietud de muchos dirigentes complicados por el lento avance de las investigaciones sobre el FONDIOC).

La estrechez económica relativa y el crecimiento de las demandas sectoriales-corporativas condicionan una agitación interna dentro del MAS, acrecentando sus fisuras internas, que se perfilan como un tercer escollo que puede cobrar una proyección insospechada. Justo ahora que se requiere mantener y reforzar su monolitismo para acometer reformas institucionales que abran los candados constitucionales o una "vía alternativa" (mencionada pero no explicada por algunos dirigentes campesinos) para legalizar la reelección.

Las reformas institucionales en proceso o en espera (electoral, judicial, de la Policía) tienen un potencial de riesgo suficiente como para conformar más adelante un cuarto frente contra el plan de reproducción del poder constituido. La mediocre y declinante calidad de la gestión, los altos niveles de abuso de poder y otras formas de corrupción ya han desatado, en anteriores coyunturas, explosiones de exasperación social.

La ventaja que hoy representa para el Ejecutivo tener a su disposición a las directivas de las organizaciones sociales puede llegar a serle rápida y gravemente perniciosa, porque la neutralización de los canales formales para transmitir al Estado demandas y reclamos (partidos políticos, sindicatos y otras organizaciones sociales) y el bloqueo de los informales (papel que ejercían las ONG, medios masivos de difusión, organizaciones "cívicas" y otras, hoy notoriamente intimidadas), prácticamente empuja a que la protesta y la demanda social se inclinen por generar movimientos sociales (entendidos como acción directa espontánea). Esta es la modalidad más temida por el gobierno, que conoce íntimamente su alto poder de impacto.

De tal forma que la pérdida de autonomía social que se ha venido alentando metódicamente desde el Estado para fortalecer su poder y capacidad de control político, lo pone en la perspectiva de caer preso de su propia trampa.

Y es que al ejercer no solo el monopolio del uso de la fuerza, sino el de la representación política por la vía de fusión partido-Estado-organizaciones sociales [^ano_2015_2-11], obliga a que reivindicaciones relativamente sencillas de resolverse puedan entrabarse fácilmente y derivar en choques mayores, debido a la pesadez burocrática de un aparato de representación política, agrietado, además, por las querellas de los intereses de los sectores que lo sustentan.

[^ano_2015_2-11]: Lo que el vicepresidente del Estado llama "Estado integral", en una acepción propia suya y muy alejada de la categoría de Gramsci, que trata de utilizar como justificación.

La búsqueda de recuperación de autonomía social y las demandas de autonomías territoriales, incluyendo las departamentales, que esta vez pueden empezar a hacer palanca desde lugares no tradicionalesv [^ano_2015_2-12] o convencionales, ocupará un espacio creciente en los siguientes meses. Si dicha tendencia cobra vigor, puede modificar notablemente la faz de los conflictos en el país.

[^ano_2015_2-12]: Como podría ser el departamento de La Paz, donde la autonomía obtuvo un respaldo llamativo, por encima del 78%, en el referendo de 2009 (por encima de lo que obtuvo en Santa Cruz en 2008 en su referendo departamental), y triunfó este año el candidato a gobernador de Sol.bo, cuyo programa puso énfasis precisamente en la autonomía. Las objeciones que el hoy gobernador ha presentado para modificar el proyecto de estatuto (apenas formalmente autonómico y, en el fondo, rutinariamente centralista) aprobado el año pasado por su Asamblea Departamental controlada por el MAS, muestran, por su debilidad ---aunque ciertos opositores pueden sensibilizarse y tratan de incorporar estas demandas---, que ninguna corriente representada electoralmente ha reflexionado lo necesario para encabezar estas demandas y lograr el desarrollo de todo su potencial.

::: {style="text-align:right; font-weight: bold;"}
Junio de 2015
:::

## Notas
