---
lang: es
format: 
  html:
    page-layout: article
---
# Elecciones regionales: Primer desmarque aymara {.unnumbered}
---

Unos resultados electorales regionales portadores de significativas señales sociales, junto con serias inconsistencias institucionales de los organismos electorales; explosión de evidencias incriminatorias de dirigentes que administran fondos públicos, en un contexto de enfriamiento del dinamismo económico y las iniciativas de reforma judicial, son los componentes más visibles del momento actual boliviano.

## Lo previsible y lo nuevo

La predisposición social de entusiasmarse con las competencias electorales se ha impuesto nuevamente, por encima de un cierto tedio, y prevalecen campañas rutinarias y poco novedosas, tanto en contenido como en forma.

A pesar de que las líneas generales de lo que finalmente ocurrió el 29 de marzo han reiterado fenómenos conocidos, también se han manifestado conductas y tendencias sorprendentes que manifiestan un alto potencial de generar modificaciones y giros.

Por el momento, el foco de la discusión que desarrollan públicamente los principales voceros políticos —tanto del gobierno como de sus oponentes— se ubica en un inútil tira y afloja sobre temas redundantes y generalmente engañosos sobre quién será el triunfador absoluto de los comicios o sobre el presunto vuelco masivo de las preferencias electorales.

Respecto a los elementos que podían anticiparse al día de la votación, bien vale rescatar algunos puntos, desarrollados en el análisis de diciembre de 2014, es decir antes de la campaña y de la selección final de candidatos:

> *Conocedor de los riesgos que se ciernen sobre el clima de estabilidad —pese al discurso de su principal vocero económico (no contradicho, pero tampoco respaldado por sus superiores)—, el MAS se propone obtener la mayor ventaja posible en la disputa.
Para las elecciones de 2015, sus posibilidades de incrementar su control de gobernaciones se concentran en Tarija [^1]; Chuquisaca podría entrar en zona de riesgo, si no resuelve las disidencias internas que objetan la reelección del actual gobernador masista. El triunfo opositor en Santa Cruz permanece como tendencia predominante hasta antes del cierre de inscripciones de candidatos.*

El MAS queda como la única formación política nacional vigente (con presencia y organización comprobable en todo el territorio del país) que, con la desaparición del Movimiento sin Miedo (MSM) y del Partido Verde (PV), no tiene un flanco organizado a su izquierda, mientras que a su derecha no existe organización alguna con la convocatoria suficiente para coaligar a esa franja electoral y, por lo tanto, no le significa desafío alguno al régimen.

A pesar de que era posible anticipar con mucha certeza los principales resultados, tanto partidos políticos como medios masivos de difusión insisten en sobredimensionar el significado y las consecuencias de la merma de votos para el partido de gobierno. Dicha actitud se niega a reconocer que este descenso es la regla en nuestro país, al mismo tiempo que desconoce la ya tradicional inclinación de los electores bolivianos a diferenciar entre sus preferencias en los distintos escenarios [^2].

Los resultados de estas elecciones regionales (autonómicas) no muestran una deserción brusca y masiva de votantes hacia la oposición, como porfían nuevamente hoy algunos de sus representantes. Tampoco ninguna de sus victorias locales o departamentales convierten automáticamente a esos triunfadores en rivales, a escala nacional, de la única organización política presente y vigente en el espacio nacional.

¿Puede inferirse de lo anterior que no existe ninguna importante modificación social y política? No, porque aunque la correlación general de fuerzas no ha cambiado, ni se ha alterado la tendencia central vigente —que concede amplia ventaja al partido oficial—, sí han surgido nuevos fenómenos y tendencias capaces de alterarlas en un plazo mediato.

Los más destacados han sido descritos en la prensa como la “rebelión aimara que venció al líder indígena” [^3], en alusión al origen étnico de Félix Patzi y Soledad Chapetón, triunfantes en el departamento de La Paz y en el municipio de El Alto. Dado el peso que tuvo y aún conserva el relato etnocultural con que se autoexplica y legitima el régimen, no puede subestimarse la importancia simbólica y práctica de la triple derrota oficial (incluyendo la de la ciudad de La Paz), aunque no se limita a este espacio.

En estos distritos, el presidente jugó a fondo su capacidad de convocatoria y autoridad, ordenando y exhortando a que no se vote por sus opositores, de manera que, aunque no lo reconozca, dio a estos comicios un carácter plebiscitario que no satisface sus expectativas.

De allí que la reacción oficial ante sus derrotas en La Paz, igual que ante la muy ceñida disputa que se ha verificado en Chuquisaca, es sensiblemente ácida y agresiva, ya que, aun cuando no lo reconozca abiertamente, entiende que reflejan un estado de ánimo sensible o irritable de sectores clave de un electorado considerado particularmente leal al MAS. El hecho de que lo hubiesen respaldado en las asambleas expresa que los vínculos entre representantes y representados están vigentes, pero la rebeldía para acatar las “instrucciones” y amenazas en la elección de autoridades ejecutivas deja claro que no existe una supuesta incondicionalidad.

Por la anterior razón, las explicaciones que solamente toman en cuenta el encanto y atractivo de los candidatos —o su género, como ha pretendido el jefe de Estado— son insuficientes, y omiten consideraciones respecto a la opinión del votante sobre la calidad de gestión y propuesta, y a su capacidad de tomar decisiones que pesan en el balance democrático de poderes y fuerzas.

## La corrupción, actor electoral y político

Ha sido el mismo presidente quien ha puesto en la agenda de debate el tema de la corrupción, al afirmar que la derrota de los candidatos masistas, especialmente para la gobernación de La Paz y el municipio alteño, se explicaría por esa causa [^4].

No queda claro si esta admisión implica algún grado de conciencia sobre la penetración de las prácticas corruptas en la administración pública, o si simplemente se trata de descargar responsabilidad ante las campañas y acusaciones de “medios de difusión y partidos enemigos”, sin reconocer el problema.

En principio, la inclinación sería por la segunda hipótesis porque, además de que no existe ninguna reacción o respuesta para encarar la corrupción, el partido gubernamental ha defendido a ultranza a los acusados (especialmente a su candidata a gobernadora por La Paz), y continúa oscilando entre la pasividad y el encubrimiento ante el destape de masivos malos manejos en el Fondo de Desarrollo para los Pueblos Indígena Originario Campesinos (FONDIOC) [^5], al que en adelante nos referiremos como Fondo campesino, debido a que fueron las organizaciones ese sector, y no las indígenas, las principales beneficiarias de sus recursos (de aproximadamente el 80%).

La Contraloría General ha elaborado un informe de supervisión que abre el cauce a develar irregularidades, pero lo ha hecho después de la persistente publicación de denuncias desde 2013 y al registro de por lo menos una muerte atribuida al intento de impedir que se esclarezca alguna de dichas denuncias [^6].

Más allá del peso efectivo que pudieron tener las acusaciones contra candidatos (que también existieron en las elecciones de 2014, con grandes escándalos sobre las redes de extorsión, jefes policiales aprehendidos en el exterior, etcétera, etcétera), o la actuación de tribunales electorales nacional y departamentales (corruptos en el sentido de usar su poder para beneficiar a un determinado grupo), el caso del Fondo campesino toca directamente los métodos y rutinas utilizados desde el Estado para relacionarse con dirigentes de organizaciones sociales.

No hay suficiente información para sostener categóricamente que la permisividad y benevolencia ante muchas y reiteradas acusaciones y hechos —que prueban múltiples actos corruptos en diversos espacios estatales controlados por el MAS— sufra un cambio. Es abrumadora la evidencia de que dirigentes de organizaciones sociales, coaligadas con el gobierno, disponen de una enorme o irrestricta discrecionalidad para manejar fondos públicos (además de su ventajosa posición para acceder a candidaturas y cargos de la administración gubernamental).

No se trata, ciertamente, de una novedad, pero las cifras pueden llevar a pensar en una reacción de alarma y rechazo ante uno de los ejes de una política estatal que se caracteriza por fomentar de prácticas corporativistas abiertas, y que se ha ido fortaleciendo en este sentido [^7].


El abuso de poder y la apropiación de fondos y recursos públicos para beneficio de grupos, entre los que destacan partidos políticos y organizaciones sociales y corporativas (parte más o menos formal del sistema de representación política), está explotando en todo el continente. Involucra tanto a gobiernos “nacional populares” (Brasil, Argentina, Nicaragua, Venezuela), como a “neoliberales” (México, Perú, Chile). Es un factor que puede volver a cuestionar frontalmente a gobernantes de todo el continente, incluyendo al nuestro, como ya ocurrió hace varios años.

## Blindajes y límites

De cualquier manera, los contrastes en las elecciones regionales no alcanzan por sí mismos a representar un riesgo para un partido que ha desarrollado una auténtica maestría electoral, y que se aproxima a cumplir una década de control casi absoluto del conjunto de los aparatos de Estado. Además, muestra sólidas credenciales históricas que justifican su fortaleza; ya antes ha revertido otros retrocesos, y podría hacerlo nuevamente.

Incluso con los elementos novedosos que se han identificado más arriba, incluyendo el desaliento que puede traer la derrota en La Paz y el serio riesgo en Chuquisaca para los posibles planes de organizar un referendo que autorice una relección, las amenazas podrían conjurarse si no convergieran con una disminución de ingresos fiscales y con la proliferación de choques entre fracciones internas del MAS.

Sobre lo primero, y después de sostener obstinadamente que la caída de precios de materias primas no nos afectaría, el ministro de Hacienda ha admitido que las expectativas de crecimiento se han reducido casi un punto porcentual para este año [^8].

Resulta insustancial que este funcionario atribuya dicha disminución a “la baja tasa de inversión” de la empresa privada, cuando todos los países latinoamericanos están reajustando sus presupuestos y previsiones por el fin del superciclo de precios de las materias primas, y que en la “Cumbre de las Américas” —que tiene lugar en estos días— las voces de alarma por este motivo se hayan multiplicado.

Los resultados económicos —que acumuló incuestionablemente el modelo económico ecléctico[^9] practicado en el país— nos brindan un margen de defensa y alivio netamente superiores al de varios otros países del continente. Sin embargo, no alcanzan a constituir el blindaje del que se han jactado los responsables del área.

Los saldos de caja no ejecutados en años anteriores y el respaldo de las reservas internacionales alcanzan para contrarrestar choques durante este año, pero si las tendencias internacionales no se revierten, los efectos adversos crecerán y se magnificarán por los hábitos de la demanda corporativista.

La vigencia de este riesgo se complica con las fisuras en el aparato político oficial, que se han manifestado en estos meses. Algunos de los rivales más peligrosos que ha enfrentado electoralmente el MAS provienen de sus propias filas; pueden precipitarse nuevos desgajamientos debido tanto a la agudización de contradicciones, como a las revelaciones sobre lo que pudo haber pasado con los fondos del Fondo campesino.

En suma, la escasez (de ingresos y recursos) y las divisiones pueden establecer otro marco ambiental-político y darle una distinta proyección a los avances del mosaico opositor, que deberá resolver su carencia de proyecto, estrategia y estilo para poder crear algún riesgo tangible a su contendiente.

## Los temas postergados

Mientras se ven indicios de que las reformas de la administración de justicia y de la Policía, opacadas y pospuestas en la coyuntura de elecciones, retornarán a la escena, es cada vez más probable que se sume a ellas la demanda de que se extienda también al Órgano Electoral, cuya credibilidad decae a saltos en cada nueva elección [^10].

La oferta presidencial y de otras autoridades respecto a que se abrirá una fase de consulta y deliberación para encarar la reforma de la justicia —sobre la que escasean propuesta de cualesquiera de los actores e interesados— ha quedado flotando. Queda pendiente verificar si se materializará como recuperación de la iniciativa oficial o si se impondrá como producto de la suma de aberraciones que infaliblemente cometen jueces, fiscales y otros funcionarios del ramo.

Al lado de esta cuestión central, se vislumbra la posibilidad de que las demandas de descentralización y avance de las autonomías vuelvan a perfilarse en el horizonte.

A diferencia de años anteriores, cuando la exigencia de autonomías departamentales esgrimidas por tradicionales grupos de poder regionales ocupaba el centro de ese campo de lucha, se abre la opción de que nuevos actores, desde otros espacios territoriales y políticos, demanden la recuperación y el ensanchamiento de los avances descentralizadores congelados o perdidos. Asimismo, que exijan el cabal cumplimiento del ejercicio autonómico establecido en la CPE, ahora retaceado y asfixiado por leyes, procedimientos y actitudes estatales, que han fortalecido la concentración del poder y el manejo de recursos.

::: {style="text-align:right; font-weight: bold;"}
Abril de 2015
:::

## Notas

[^1]: Según el avance actual del cómputo, la disputa entre Carlos Cabrera, candidato masista, y el actual acalde Montes (proveniente del MIR) parece estar muy cerrada. En Santa Cruz todavía encabeza las preferencias el actual gobernador (Rubén Costas), pero su victoria está amenazada por la suma de candidaturas (Antelo, Nagatami) que abrevan de la misma franja de votantes que el MDS.

[^2]: Además de lo ocurrido en 2010, en 2005 muchos votantes de Morales para la presidencia se inclinaron por Pepe Lucho Paredes para la Prefectura de La Paz, y por otros muchos en varios distritos. Lo mismo sucedió en elecciones anteriores con otros partidos que gobernaban al país. No es menos sugestivo que menos de seis meses después de asumir la conducción del Ejecutivo y ser portaestandarte de la bandera de la Asamblea Constituyente, el MAS obtuviese tres puntos porcentuales menos en la elección de asambleístas constituyentes en 2006.

[^3]: Fernando Molina, periódico El País, España, 1o de abril de 2015.

[^4]: “Lamento mucho que en La Paz hayamos perdido las elecciones. Pienso que ha habido acusaciones, especialmente en la ciudad de El Alto, y en el departamento, muy fuertes en temas de corrupción. Si eso es verdad, quiere decir que el pueblo paceño ha dado voto castigo a la corrupción”, afirmó el jefe del Estado (La Razón, 31 de marzo de 2015).

[^5]: La ministra de Desarrollo Rural y presidenta del Fondo campesino arguye que ella no participó, y que tampoco podía frenar la aprobación de recursos porque estaba en minoría frente a ocho directores (dirigentes de organizaciones sociales) que determinaron el desembolso de más de 1.300 millones de bolivianos, en muchos caos depositados en cuentas personales. De estos desembolsos no existe respaldo documental, según el Contralor, o existe, pero “desordenado y disperso”, según la interventora nombrada por la ministra. Esta última no ha explicado por qué no impugnó esos procedimientos y la falta o debilidad de respaldo documental en los cinco años que encabeza el Fondo campesino.

[^6]: “Jacobo Soruco Cholima, dirigente campesino de la comunidad 26 de Julio del municipio de San Javier de la provincia Cercado del departamento del Beni, fue asesinado por denunciar proyectos ‘fantasmas’ y la malversación de recursos del Fondo de Desarrollo Indígena Originario Campesino (FONDIOC), aseguró el secretario general de la Confederación Sindical Única de Trabajadores Campesinos de Bolivia (CSUTCB), Joel Guarachi” (ERBOL, 23 de octubre de 2014). 

[^7]: El más reciente ejemplo de esas prácticas está en la transferencia de recursos financieros a cooperativas mineras, uno de los grupos corporativos más fuertes, ampliamente beneficiados anteriormente con transferencia de recursos naturales (yacimientos), equipos y maquinaria. Los medios acaban de informar que “El ministro de Minería y Metalurgia, César Navarro, informó el lunes que las cooperativas habían solicitado ampliar los préstamos del Fondo de Financiamiento para la Minería (FOFIM) y que se estaba proyectando ‘unos 100 millones de dólares para los próximos tres años’. El TGN desembolsará 100 millones de dólares al FOFIM para canalizar préstamos a las cooperativas mineras ante los precios deprimidos de minerales en el mercado internacional” (periódico El Diario, La Paz, 10 de abril de 2015).

[^8]: La pérdida de “no más de 40 a 60 millones de dólares” para todo este año —que presagiaban ese ministro y el vicepresidente— por la disminución del precio del petróleo, se triplica en solo un mes. Según el INE, en enero de 2015 los ingresos de divisas por la venta de combustibles ascendieron a 385,66 millones de $US, es decir 182,64 millones de $US menos que los 568,30 millones de $US registrados en 2014 (periódico Página Siete, La Paz, 4 de marzo de 2015).

[^9]: Me refiero a la combinación de avance estatal en la economía y en las políticas redistributivas con una marcada ortodoxia fiscalista y monetarista, que se ejecuta en Bolivia desde el gobierno a partir de 2006.

[^10]: No es que se haya generalizado la sospecha de fraude, sino que se ha puesto en evidencia —con inhabilitaciones de candidatos y la aplicación parcializada de normas, como principales ejemplos, siempre en beneficio del partido gubernamental— la falta de idoneidad y la sumisión de este incompleto poder estatal.