---
lang: es
format: 
  html:
    page-layout: article
---

# Enfermedad y bloqueos {.unnumbered}

Los estertores del bloqueo que pedía la inamovilidad de la fecha electoral y el exceso de testosterona en los tours fotográficos de Evo Morales Ayma se conjugan para golpear, con dureza nunca vista antes, el monolitismo del MAS, agrietándolo en más de un frente. En la banda opuesta, los peores pronósticos sobre el comportamiento del gobierno interino empalidecen frente las conductas de sus componentes clave.

Más allá de las fallas de unos y otros, las prácticas políticas nacionales, que nunca se caracterizaron por su pulcritud y sutileza, se han sumergido en el pantano más rudimentario de una campaña electoral, tan tóxica como la epidemia del coronavirus.

Superados oficialmente casi 120 mil contagios y las 5.000 víctimas fatales, con el mayor déficit continental de pruebas diagnósticas, los rastrillajes de las grandes ciudades aportan evidencias irrefutables de que los informes del Ministerio de Salud cubren menos de la mitad de los casos de contagio [^1].

Con el bloqueo y antes de él [^2], Bolivia ha enfrentado la pandemia con el paupérrimo sistema de salud heredado y con la mediocridad y estulticia de una administración dedicada a promocionar su candidatura y a desviar recursos que debían 
dedicarse a aliviar la enfermedad.

## Poderes en pugna

La tónica predominante en los últimos meses es la del choque abierto entre el Ejecutivo y el Congreso. La llamada pacificación de fines del año pasado, apresuradamente edificada sobre los cadáveres acumulados en Sacaba, Montero y Senkata, fue posible gracias al agrietamiento de la hasta entonces inconmovible estructura orgánica, alineada detrás del pétreo mando de Juan Evo Morales Ayma.

Hoy los actores políticos exhiben un desconocimiento de las nociones elementales y de las más básicas tácticas para encarar y resolver problemas. La especialidad de los operadores-protagonistas de la escena es generar conflictos y su maestría consiste en empeorarlos.

Los violentos episodios durante y después de la escapatoria de Morales y García, con el alto costo de la propagación y el agravamiento de enfermedades y de muertes entre la población inocente y ajena al conflicto, se detuvieron mediante la frágil tregua pactada en el Legislativo. Nuevamente, se debió a una predisposición colectiva a no atizar la violencia abierta y la intervención de agentes ajenos o secundarios del sistema de representación y mediación política.

El pico de violencia tras la fuga de Morales y García el año pasado tenía como objetivo propiciar su pronto y victorioso retorno, ya sea por reclamo popular o por acción militar, después de generar el vacío de poder ulterior a la renuncia de sus propios relevos.

El fracaso de ese plan ocurrió, entre otros factores, por el hartazgo de entre seis a diez parlamentarios del MAS, y quebró el sentimiento de omnipotencia de quienes estaban acostumbrados a imponer sus dos tercios. Eso, más la sensación de orfandad y confusión de la base partidista del MAS, creó un cierto clima emocional reforzado por el aturdimiento de cobistas y otros dirigentes corporativos, aterrorizados ante la posibilidad de que se les empiece a exigir rendición de cuentas.

Sin duda que el factor decisivo que contribuyó al extraño ceremonial de atenuación de furias —observado en la televisada negociación entre ministros, parlamentarios y dirigentes sindicales— fue la poderosa predisposición mayoritaria de la sociedad a detener los focos de violencia.

Una vez que se aplacó el clima de violencia exacerbada, los miembros del gobierno apagaron las luces y cerraron el teatro. Todas las promesas de aproximación, conciliación y diálogo concluyeron antes de que llegue la Navidad y con la proclamación de la candidatura de Añez Chávez se desnudó la ambición restauradora señorial de una de las fracciones, representativas del poder del agronegocio, que maneja directamente los hilos de este gobierno.

El testimonio de la presidenta del Senado respecto a que la señora Añez no intentó conversar con ella ni una sola vez, explica perfectamente cómo se volvió a montar el conflicto. Supuestamente, el hielo no se quebró ni siquiera para ponerse de acuerdo en la ley de prórroga del mandato a principios de año.

La anécdota puede ser más o menos objetiva, pero ilustra los muy estrechos límites de la capacidad de las dos fracciones políticas minoritarias que permitieron poner en pie y mantener un gobierno provisorio, de legalidad quebradiza, por más de nueve meses. El fracaso de las personas y los grupos condensa esa llamada “cultura política” propia de los representantes (partidarios, sindicales, corporativos, empresariales y varios otros) intemperantes y atrabiliarios que dominan la escena política nacional.

El riesgoso tironeo entre un Parlamento —que se siente cada vez más impetuoso e impune— y un Ejecutivo que derrocha tanta mezquindad como avidez por apropiarse de recursos públicos y con un ánimo inclinado a la amenaza y la querella, armaron la peor combinación posible para enfrentar la pandemia.

## Salud y asaltos a cara descubierta

El número de contagios que reporta el Ministerio de Salud corresponde exclusivamente a esa minoría de personas que presenta síntomas y que pudo ser atendida en un centro sanitario y hacerse una prueba diagnóstica, o a quienes acudieron por su cuenta a conseguir una en algún laboratorio.

Como el gobierno ha desalentado desde un inicio la aplicación de pruebas de laboratorio [^3], y jamás ha tenido un plan de mapeo y seguimiento de contactos, queda fuera de duda que no son ni serán detectados miles de contagios, incluso los tratados en instalaciones hospitalarias. Menos todavía la multitud de quienes se tratan en casa ni de quienes no pueden acceder a tratamiento alguno ni el importante porcentaje de infectados con síntomas leves o asintomáticos.

Respecto a los decesos, la siempre deficiente información pública, sumada a que escasean las pruebas para los que mueren y a la acumulación de entierros clandestinos, revelan que los números oficiales no dan ninguna pista sobre la letalidad real.

En contraste con la desidia y el descuido oficial en las negociaciones políticas más delicadas y un superficial retoque al desvencijado sistema sanitario que heredamos de la gestión masista, son demasiados los funcionarios que muestran un estado de alerta extraordinario y una maravillosa agilidad de manos para escamotear recursos fiscales. La aptitud fiscal para prevenir estos actos y de sancionar a los culpables no ha mejorado ni un milésimo.

La compra de respiradores, valuada en 5 millones de dólares, se eleva hasta ahora a más de 16 millones de dólares sin que se aclaren los sobreprecios denunciados en abril y hace poco [^4].

También se ha disuelto el seguimiento a los graves problemas en la administración de YPFB (contratación de seguros, comidas para campamentos, compra de diésel), así como a un contrato con grandes sobreprecios del Ministerio de Energía [^5]. No hay mayores acciones en el caso de los contratos incestuosos entre filiales de YPFB para incrementar precios [^6], ni en el extraño papel del misterioso y elusivo *embajador tecnológico* (La Razón, 8 de junio de 2020), presuntamente muy cercano a la hija de Jeanine Añez.

La lista es muy larga, y tiene un efecto desmoralizador en la percepción ciudadana, pues se repite el eterno comportamiento de los profesionales de la política, cualquiera sea la bandera que agiten o los relatos con que justifiquen su predisposición a “servir al público”.

## El padre de todos los bloqueos

Si el Ejecutivo y el Legislativo rompieron lanzas con la interpelación al ministro de Defensa —inmediatamente restituido en su cargo después de la censura—, el ascenso anual de jefes militares (trabado y postergado por el Senado) estructuró, junto con la aprobación de créditos externos, la nueva arena de las disputas.

Las hostilidades llegaron al extremo de impedir tanto la difusión del mensaje presidencial en la Asamblea Legislativa, como la intervención de la cabeza del Legislativo en los medios estatales. Esto allanó el camino para el bloqueo de vías, que terminó por desabastecer de medicamentos e insumos vitales, como el oxígeno, a los centros de salud, farmacias y salas de emergencia y terapia intensiva.

La intervención y la digitación del MAS en la preparación y el desarrollo del bloqueo fue públicamente reivindicada por sus cuadros y sus aliados dirigentes de organizaciones sociales. Donde existen distintos puntos de vista, más complementarios que antagónicos entre sí, es en el análisis sobre el grado de participación voluntaria y masiva de campesinos en el bloqueo [^7], lo que en última instancia involucra una valoración del estado de ánimo que predomina en la franja más activa de la militancia y de votantes del MAS.

Las encuestas previas a la cuarentena mostraban que la fidelidad de sus electores prácticamente calcaba las cifras que obtuvo el año pasado [^8]. Estas cifras se mantuvieron básicamente estables al menos hasta julio, según diversos sondeos, ninguno de los cuales se publicó de manera oficial.

El pánico que produce la posibilidad de una victoria masista empuja a los sectores más duros de la derecha a una ofensiva contra el TSE, buscando que la fecha de elecciones vuelva a postergarse. El ataque, comandado ahora por el presidente del Comité pro Santa Cruz, tiene entre sus más firmes adherentes a José Luis Camacho y a la presidenta Añez, como esta lo
dejó claro en su discurso del 6 de agosto [^9].

Pero aplazar nuevamente las elecciones con el propósito oculto de mejorar el reacomodo de las candidaturas más directamente vinculadas al agronegocio es una opción desesperada [^10]. Hasta los menos agudos se dan cuenta de que no existe margen legal (y mucho menos político y social) para mantener el interinato, como lo advierten las intensas señales de que habría una exigencia social ampliamente mayoritaria para su salida.

Produce mayor pánico todavía, aunque pretenda lo contrario, la postura de una transición cívico militar, como especulan en Santa Cruz los grupos más reaccionarios. La ansiedad de estos sectores no se aplaca ni con las insistentes señales de que el desenlace del bloqueo ha multiplicado roces internos entre los grupos corporativos del MAS que lo respaldan y que pusieron la cara para convocar a la movilización fallida y entre quienes se alzan entre la organización política y las hasta ahora leales organizaciones sociales [^11].

La confusión masista se ha incrementado por las denuncias de que su máximo jefe habría incurrido en delitos sexuales, cuya víctima sería una joven con la que se ha exhibido frecuentemente y con la que, según sus acusadores, se relaciona desde que esta era menor de edad. Si la estructura soportó una situación similar en 2016, surge ahora la duda de si podrá hacerlo nuevamente, habida cuenta de su fuga en noviembre y de los desbarajustes internos.

Todas las posibilidades señalan que el debate electoral se atornillará en estos temas, además de otras cuestiones judiciales y acusaciones mutuas de corrupción. Estará ausente la discusión de cómo encarar la reconstrucción del país. Se omitirá también la consideración de un nuevo modelo de desarrollo que sustituya al actual, cuyas fuentes de ingresos se están agotando o, sencillamente, son insuficientes y antagónicas con la necesidad de detener el deterioro y la crisis ambiental.

Bajo las condiciones de enfrentamiento político y social vigente, sin un proyecto que repare tales distancias y choques, continúa afirmándose la tendencia de una gobernabilidad enredada, si es que no insostenible, para cualquier futuro gobierno de nuestro país.

<br>

::: {style="text-align:right; font-weight: bold;"}
Septiembre de 2020
:::


## Notas

[^1]: El New York Times multiplica por cinco los contagios y muertes, pero especialistas en datos desconfían de tales cifras, que carecen de bases de datos. Sin embargo, estiman que los datos oficiales subestiman enormemente las verdaderas cifras. Véase: [https://www.nytimes.com/es/2020/08/22/espanol/america-latina/bolivia-coronavirus.html](https://www.nytimes.com/es/2020/08/22/espanol/america-latina/bolivia-coronavirus.html). El modelo de López y Birbuet ofrece la ventaja de permitir múltiples comparaciones con diversos países, especialmente del continente, y se calcula sobre número de casos por millón de habitantes; véase: [https://rafalopezv.github.io/latam_fallecidos/](https://rafalopezv.github.io/latam_fallecidos/) 

[^2]: Véase: [https://n9.cl/dr4q0](https://n9.cl/dr4q0) 

[^3]: Cuenta también la dificultad mundial que existe hasta ahora para conseguirlas, así como para los reactivos y equipos requeridos.

[^4]: Véase: [https://n9.cl/upwb6](https://n9.cl/upwb6). La presidenta atribuye el problema a su “falta de experiencia” en la adquisición de respiradores; véase: [https://n9.cl/e2avm](https://n9.cl/e2avm)

[^5]: Véase: [https://n9.cl/n59gw](https://n9.cl/n59gw)

[^6]: Véase: [https://n9.cl/9lkv5](https://n9.cl/9lkv5)

[^7]: Véase tres ejemplos de estas diferentes interpretaciones: [https://n9.cl/4nom4](https://n9.cl/4nom4); [https://n9.cl/03wlu](https://n9.cl/03wlu); [https://n9.cl/9o06b](https://n9.cl/9o06b)

[^8]: Según los promedios que brinda la Fundación Friedrich Ebert: [https://n9.cl/p4x6i](https://n9.cl/p4x6i). El diario Página Siete ha presentado la última encuesta pública en la tercera semana de agosto, en la que el MAS y CC aparecen empatados: [https://www.paginasiete.bo/temas/encuesta-1638.html](https://www.paginasiete.bo/temas/encuesta-1638.html)

[^9]: Véase: [http://www.elalteno.com.bo/bolivia/20200807/anez-ataca-al-tribunal-electoral-y-copa-apuesta-por-el-dialogo](http://www.elalteno.com.bo/bolivia/20200807/anez-ataca-al-tribunal-electoral-y-copa-apuesta-por-el-dialogo)

[^10]: El columnista Manfredo Kempff, fiel seguidor de Banzer, se resignó el año pasado a recomendar el voto por CC como el mal menor. Ahora expresa que esa salida no lo convence, pero se queja de la falta de alternativas, ya que aquella que preferiría, la unidad en torno a Tuto Quiroga, no le parece viable, como confiesa en su columna: [https://eldeber.com.bo/opinion/pensando-en-las-candidaturas_198001](https://eldeber.com.bo/opinion/pensando-en-las-candidaturas_198001)

[^11]: Véase: [https://n9.cl/blzo5](https://n9.cl/blzo5); [https://n9.cl/b4mr5](https://n9.cl/b4mr5); [https://n9.cl/arwd6](https://n9.cl/arwd6); [https://www.la-razon.com/nacional/2020/08/31/choquehuanca-quien-comete-estupro-debe-someterse-a-la-ley-y-a-un-tratamiento-psicologico/](https://www.la-razon.com/nacional/2020/08/31/choquehuanca-quien-comete-estupro-debe-someterse-a-la-ley-y-a-un-tratamiento-psicologico/)
