---
lang: es
format: 
  html:
    page-layout: article
---

# Coyuntura de temores y ausencias {.unnumbered}

Los problemas del áspero inicio de año se mantienen en su mayoría, cuando no han empeorado, y en el lapso de abril a julio se ha sumado una avalancha destapes corrupción estatal, pero el balance de fuerzas muestra una apariencia que favorece al Gobierno, en el sentido que ha sorteado algunos de los choques más intensos con sus rivales internos, mientras mantiene a raya a los grupos que intentan aparecer como sus opositores parlamentarios [^1].

La deriva económica del país, sacudida por la irresuelta crisis de iliquidez de dólares, no ha desembocado en una crisis incontrolable, tal cual imaginaron la mayoría de los especialistas del sector, a partir de la rápida persistente escasez de divisas y las drásticas restricciones de retiros para los depositantes en moneda extranjera e importadores legales, inocultables desde marzo. 

Pese a que el deterioro crece en la mayor parte de los indicadores [^2] , la ausencia de una explosión –determinada por una inusual cautela de la reacción popular- es un defensivo importante que frena el ritmo de la desaceleración, y da margen de maniobrabilidad al Gobierno.

En el fondo se observa un abstencionismo político colectivo de gran calado, la ausencia de proyecto alternativo nacional y el encogimiento de la fuerza y alcance de la oposición masista interna, pese a sus agresivas y reiteradas campañas.

## Diques de contención

Una colección de problemas, confrontaciones y quiebras institucionales multifocales, de las características que se ha visto durante estos meses, casi aseguraban, según nuestra experiencia histórica nacional previa, cuestionamientos frontales de la conducción política del país, mucho más, frente un gobierno, ferozmente impugnado por su propio partido y pródigo en desprestigiarse y enredarse cotidianamente.  

Durante los catorce años encabezados por Morales Ayma, situaciones similares terminaban siendo contenidas gracias al vigor de la hegemonía del Movimiento al Socialismo (MAS), sólidamente sustentado por una situación económica que empujó el retroceso de la pobreza y una apertura del ejercicio de derechos y participación de importantes sectores sociales. Esto se extendió hasta el estallido de 2019, cuando se instaló abiertamente una crisis hegemónica que, precisamente a falta de opciones creíbles, permitió el retorno de 2020.

Hoy, ese es un dato del pasado, herido gravemente, desde 2016, por el rechazo que del prorroguismo del expresidente Morales y, ahora, por la retracción económica, la guerrilla despiadada entre los dos aspirantes a ser candidatos de esta fuerza en la siguiente elección nacional, los abusos arbitrariedades y una corrupción implacable. 

El desprestigio y desgaste previo acumulado han alcanzado cumbres imprevistas y difíciles de imaginar, gracias a que la intensidad de la división del MAS permite descubrir y airear trapisondas del manejo del poder que nunca llegaban a conocimiento público. El encono de estas batallas ha llegado al punto de que ha empezado a anunciarse una posible realización de dos congresos orgánicos del MAS, en octubre próximo. Dicho escenario resultaba impensable hasta hace pocas semanas, debido al control, sin fisuras, del aparato orgánico masista que ejercía sector nucleado tras Morales Ayma.

El origen histórico de la coalición social y política que sustenta a la sigla MAS-IPSP, afianzado por su narrativa de instrumento de las organizaciones, sectores y movimientos sociales parecían bloquear indefinidamente cambios sustantivos en su estructura organizativa y cadena de mando.  Pero, la firmeza de tal cimiento da señales de irse desbaratando, a partir de que el ala de Arce Catacora le está ganando de mano a sus contrarios, al copar y alinear a su favor a la que luce en esta fase, como una mayoría de la alta dirigencia de las principales organizaciones sociales. 
La pista que sugiere la posibilidad de que la situación de las cúpulas podría estarse replicando en los demás niveles es que, como se apuntó en boletines previos, no aparecen manifestaciones de cuestionamientos internos significativos y, menos, de una ola inclinada a reclamar democratización, rendición de cuentas, transparencia o renovación dentro las organizaciones sociales; no asoma indicio alguno de recuperación de su independencia frente al estado. 

Hasta aquí, se han identificado dos factores clave, que amortiguan reacciones ante al deterioro de la capacidad adquisitiva de los salarios y calidad de vida de mayoritarios sectores populares, igual que la aparente apatía ante la suma de evidencias (videos, grabaciones de audio, mensajes digitales, extractos bancarios) de una corrupción funcionaria masiva. 

Encabezan la lista de corruptelas conocidas los administradores de justicia, cuando absuelven a jerarcas oficiales, que reciben abultados sobornos, o son extremadamente indulgentes con asesinos condenados, o violadores confesos, que manejan recursos suficientes para retribuir la benevolencia judicial. Compiten por el primer puesto, algunos ministros y legisladores instantáneamente enriquecidos y asiduos practicantes de extorsiones, cohecho, o recepción de sobornos [^3] . 

La sucesión de casos expuestos en los ministerios de Medio Ambiente, Obras Públicas o la polvareda levantada cuando la línea aérea de bandera aparece como transportador de cocaína al extranjero, con respaldo de policías, funcionarios de aeropuerto, igual que la masiva distribución de parcelas para explotar ilegalmente oro, han creado el clima de una “nueva normalidad”.

## Fenómeno viral

La novedad de esta coyuntura es que encima de decadencia del sistema estatal, han saltado a titulares de medios de difusión masiva  y redes digitales una cadena de gravísimas noticias, fuera del ámbito gubernamental,  en casos como los múltiples abusos sexuales y pederastia en la iglesia católica nacional; descalabros empresariales como estafas a depositantes, créditos vinculados (banco FASSIL y un amplio entramado de empresas a su alrededor); de corruptela en el sistema de cooperativas cruceño (COTAS por delante); violencia en colegios de élite (abusos sexuales), a más de una avalancha de feminicidios, igual que violencia y asesinato de menores, o choques violentos entre barrios íntegros que se disputan territorio.  

De esta forma, en estos meses,  la descomposición estatal se presenta como una expresión más de un cuadro de delitos y crímenes que permean a una amplia variedad de asociaciones civiles, relacionadas y representativas de segmentos sociales amplios.

Sería muy difícil medir el grado de desmoralización que tal acumulación de novedades negativas inflige al cuerpo social, pero resulta indiscutible que una de sus manifestaciones es el descenso de la capacidad colectiva de reacción y protesta que, por si misma, deviene en tercer factor que contribuye a que la administración de Arce Catacora, no solo se mantenga a flote en medio del recrudecimiento del oleaje económico, social y político, sino que luzca acumulando ventajas en su disputa por el control del aparato partidario y la definición del candidaturas para 2025 [^4]

Pronósticos y realidades

El denominador común que se encuentra en los tres elementos que atenúan la respuesta social es la prevalencia de un sentimiento de temor en varios planos.

En el económico, los evidentes retrocesos que ocasiona el encarecimiento de importaciones y esa especie de cuasi corralito que viven los ahorristas en dólares [^5] , castigan al público que prefiere refugiarse en la queja, probablemente debido a que el mantenimiento de subvenciones, que el gobierno afirma garantizar,  como la de combustibles, contienen un desencadenamiento global de alza de precios, tan temida por el público, como que una explosión de protestas pueda profundizar el descontrol e incertidumbre económicos. 

El temor ante este tipo escenario, protege al gobierno de remesones mayores, inclusive cuando la cúpula del MAS encarrilada tras Morales Ayma, denuncia que YPFB ha inflado el costo de las importaciones subvencionadas para beneficio de jerarcas oficiales.

El contexto de temores facilita que funcione la propaganda oficial sobre que la explotación de litio puedo sustituir, a breve plazo, la caída de ingresos por la exportación de gas, aun cuando los tratos con empresas chinas y rusa están impugnados -entre otros, por la fracción de Morales- de haber sido manipulados por agentes, directamente ligados a Arce Catacora [^6]. Por ahora, el público se comporta ante estas denuncias, con la inclinación de quien prefiere creer que la explotación (¿e industrialización?) de nuevos recursos pueden resolver la iliquidez y retracción económica en plazos milagrosos.

El conjunto de temores sirve de colchón amortiguador de situaciones habitualmente insostenibles y de parche a la precariedad de gobernabilidad y gobernanza.

## Debilidades obvias y escondidas

No obstante, la benevolencia y tolerancia colectiva ni tiende a ser continuamente flexible, ni equivale a fortaleza afianzada, ya sea de los gobernantes o sus hermanos en disputa. 

El retroceso y la debilidad de los fieles a Morales Ayma se sintetizan en su apuesta integral de pertrecharse en el Chapare y realizar el congreso en sus dominios. El expresidente ha pasado de ser reconocido como una imponente figura en el territorio nacional -y de buena recepción internacional- a un sujeto inseguro, irritado y vulnerable, cuando se encuentra fuera de su territorio y del arropamiento de su séquito. La amplia ofensiva opositora que ha desplegado, mostrando a las fuerzas parlamentarias que se dicen opositoras cómo se ejerce tal condición, no ha logrado hasta ahora, exhibir manifestaciones de acompañamiento social.

Por su lado, la fortaleza del sector gobiernista da señales de precariedad. Un ejemplo, entre varios es su persistencia en atacar a los cocaleros de Yungas, pese que, al mismo tiempo multiplica de intervenciones sobre fábricas de cocaína en Chapare y Carrasco-sin captura de personas culpables- como obvia presión al corazón territorial y social de Morales.

Su juego para conformar las presiones corporativistas se hace cada vez más complicado, tal como lo enseña su tolerancia con los grandes extractores de oro (“cooperativistas” asociados con capitales chinos, brasileños, peruanos), contrastadas con sus exhibiciones de fuerza con otros más pequeños y novatos (caso Madre de Dios). En cualquiera de esos escenarios las agresiones antiambientales se disparan, al igual que con el tráfico y especulación de tierras, o las obras  como las plantas y cultivos para biodiesel y otras.

En la misma línea de aparentar dominio, control y poder, pero desnudando miedo e inconsistencia, se inscribe la prepotencia y abusos, incluyendo la instrumentación de grupos de perfil parapolicial (y apoyo abierto de la Policía), para intentar doblegar a expresiones críticas como la Asamblea de derechos humanos, mientras intenta aparecer “neutral” y distante al conflicto. 

A falta de un cataclismo económico inmediato, la desaceleración mina la economía popular diariamente, mientras la crisis interna del MAS se continúa inflamando, sin tregua y con despilfarro de violencia verbal y simbólica. Pese a ello, los reencuentros de las fracciones, para salvar algún ministro, aprobar legislación de emergencia o, quizás, para repartirse candidatos judiciales, aun caben en esos márgenes.

La administración estatal está sacudida por una imparable cascada de escándalos de corrupción, tendencia que, si no se detiene, convertirá la inestabilidad en crisis de estado. Es la misma dirección a la que conducirá la proliferación de conflictos sectoriales y tensiones inter corporativistas que agrietan la legitimidad y representatividad política. 

Nota: Esta edición, igual que las anteriores, se acompaña de un Anexo informativo al que se accede mediante este vínculo https://n9.cl/kiu93  donde se halla la base informativay documental sobre las que se basan las afirmaciones y apreciaciones del autor.

## Notas

[^1]: Con escasas y notables excepciones, como los más constantes impugnadores de delitos  ambientales del estado

[^2]: Incremento del déficit fiscal, baja liquidez de divisas, deterioro de la balanza comercial, declinación acelerada de la producción de combustibles, entre los más destacados y difundidos

[^3]: A mayor abundancia, durante el cuatrimestre se ha presentado una seguidilla de muertes sospechosas, en casos investigados o por esclarecer(-interventor del banco FASSI, testigo clave del caso ABC, un abogado del gobernador cruceño)

[^4]: Sin embargo, no se debe perder de vista que todo balance de fuerzas es muy provisional, dentro una fase excesivamente fluida y cambiante- Allí radica quizá la única esperanza de los opositores políticos que siguen siendo los invitados de piedra

[^5]: Hasta febrero aproximadamente, un ahorrista que retiraba dólares de su cuenta, podía venderlos en la calle a bs 6.95 en promedio y, si necesitaba volver a comprarlos, a 6.97. Ahora, los bancos le devuelven sus dólares, en moneda nacional a, máximo, 6.92 y puede comprarlos en la calle a 58 puntos de diferencia, (a bs 7.5 en promedio, el mes de julio 2023). Esto apresura el avance de la inflación en más que el admitido por el INE, que mide el incremento del Índice de Precios al Consumidor, con una canasta compuesta de manera mu sesgada, según se ha debatido varias veces. La nueva situación cambiaria empuja el nivel de inflación hacia la diferencia entre las tasa de cambio oficial y la ofrecida en fuentes informales

[^6]: La credibilidad de los allegados a Evo Morales es muy frágil en este campo, tomando en consideración que los más de mil millones que utilizó para “industrializar el litio”, ni siquiera pagan una cuota mínima de amortización de ese capital y, desde luego, no reportan utilidad alguna. El gobierno actual casi no menciona este antecedente, probablemente porque Arce fue el ministro principal en la autorización de los desembolsos 
