---
lang: es
format: 
  html:
    page-layout: article
---

# El fondo campesino y la contraofensiva por la reelección {.unnumbered}

La relación entre el segundo capítulo de la guerra oficial contra ciertas ONG, el informe sobre el Fondo de Desarrollo para los Pueblos Indígena Originario Campesinos (FONDIOC), el voto en favor de estatutos autonómicos y el descenso de los precios del crudo definen los límites un espacio donde convergen las contradicciones y las pugnas de la sociedad.

Después de que lo electoral cedió el primer plano a las crecientes manifestaciones ante una coyuntura de desaceleración económica, desde el centro de ejercicio del poder se adoptan decisiones para diluir el impacto y la importancia de la disminución de ingresos, como condición indispensable para mantener su condición dominante por la mayor cantidad posible de tiempo.

No se trata únicamente de que el descalabro de los precios de los hidrocarburos, como parte del conjunto de materias primas que exportamos, ponga en evidencia la fragilidad e improvisación de las afirmaciones gubernamentales sobre las perspectivas económicas de este y el siguiente año. Se trata también de que estas tendencias ponen en un brete las previsiones adoptadas para coronar la estrategia de reelección continua de las principales autoridades de gobierno.

## Expectativas y realidades económicas

Desde septiembre del año pasado, inclusive, hasta el primer trimestre de este, el ministro de Economía y el vicepresidente del Estado hicieron sus mayores esfuerzos para propagar la idea de que el final del superciclo de precios de materias primas afectaría poco o nada al modelo "productivo social comunitario" [^ano_2015_3-1] que, según el lenguaje propagandístico que utilizan, rige y tiene vigencia en el país.

[^ano_2015_3-1]: La línea argumental descansaba en que la estructura del modelo, "basado en el consumo y la inversión pública", recibiría un impacto "no mayor a 40 o 60 millones de dólares", aunque los precios del barril de crudo descendieran hasta los 30 dólares. En consecuencia, la previsión de crecimiento de 5,9% anual del PIB que consigna el PGN se mantendría intacta. Evidentemente, el consumo se ha incrementado, como lo demuestra el hecho de que entre "2006 y 2013, las ventas de los supermercados de los y los restaurantes se incrementaron casi 700%" (véase: <http://www.rebelion.org/noticia.php?id=202510>). A inicios de septiembre el gobierno ha vuelto a insistir en que creceremos por encima del 5% (véase: <http://www.eldeber.com.bo/economia/economia-crecio-20-primer-semestre.html>)

El avance de la tormenta económica internacional, en la que las turbulencias de la economía china están alcanzando cotas altas que afectan implacablemente a los vendedores de commodities, ha obligado a que el optimismo gubernamental realice un ajuste del 22% a la baja de sus expectativas de crecimiento (del 5,9 al 4,6%).

El presidente del Estado, quien desde el año pasado se mostró más cauteloso que sus voceros económicos, reconoció en su discurso anual ante el Congreso que la reducción de ingresos bordearía los 2.500 millones de dólares [^ano_2015_3-2] ---cifra que ya ha trepado a 3.300 millones de dólares al 7 de septiembre de 2015---, y ha alertado que será necesario "ajustarse los cinturones".

[^ano_2015_3-2]: Véase: <https://n9.cl/58nul>

Por lo pronto, la contracción de los precios internacionales obliga a una disminución de alrededor del 20% en los presupuestos departamentales, municipales y universitarios, con el consiguiente riesgo de que se detonen las demandas de cualquiera de esos sectores. El gobierno está decidido a desplegar esfuerzos para que no se vuelva a presentar una situación como la que tuvo lugar con el conflicto potosino, que es probablemente el último en el que las autoridades puedan exhibir una actitud de tan grande desdén y desparpajo [^ano_2015_3-3].

[^ano_2015_3-3]: A pesar de que más tarde se disculpó por la risa que le causaron al presidente las demandas potosinas (véase: <https://www.la-razon.com/sociedad/2015/08/04/evo-dice-que-causan-risa-las-demandas-de-comcipo/>), la inicial hilaridad oficial ante el pliego regional refleja muy bien el estado de ánimo prevaleciente hasta hace pocas semanas en el staff gubernamental.

Sin embargo, pese a que el desempeño efectivo de la economía se ha distanciado de las optimistas metas oficiales, el país exhibirá un rendimiento claramente superior al resto del continente, manteniendo el vistoso primer puesto que se había pronosticado. Es más, los datos macroeconómicos actuales le permiten demostrar al gobierno que las afirmaciones de sus críticos respecto a que las buenas cifras registradas durante la última década obedecerían únicamente a la elevación de precios de las exportaciones, no son correctas.

## Era de ajustes

Las tesis del "piloto automático" o de la "buena estrella" aplicadas a los resultados económicos del país, efectivamente se desintegran cuando se toma en cuenta que economías mucho más grandes y robustas, como las de Brasil o Argentina, experimentan graves problemas, al igual que la venezolana.

La producción bruta del país apenas ha crecido y, en varios casos, ha retrocedido respecto a sus índices históricos más elevados; es el caso del petróleo, minerales o varios alimentos. Afirmar que el modelo oficial sería una "economía comunitaria" es incongruente, dado el fuerte impulso que han experimentado las relaciones capitalistas.

La adicción del modelo oficial a los recursos provenientes de riquezas naturales no procesadas cobra ahora su factura, lo que se transparenta en la angustiosa búsqueda de nuevas fuentes de tributación, que confronta al fisco con comerciantes mayoristas de carne, cooperativistas y asalariados con sueldos mayores al promedio nacional.

Las contradicciones son todavía mayores cuando, bajo la enorme presión que supone la persistente caída de las reservas probadas de hidrocarburos, el gobierno adopta medidas de estímulo a las transnacionales para que aceleren o intensifiquen la alicaída exploración. Tales alicientes han llevado a levantar zonas de reserva y territorios indígenas y a ofrecer "premios" a gobernaciones, municipios, universidades y otros si invierten en exploraciones que resulten exitosas.

## Ofensiva contra ONG y medios

La desmedida importancia de los ingresos por exportación de hidrocarburos en una economía de corte desarrollista tradicional, y la ineludible necesidad de mantener abastecido al mercado interno a precios relativamente bajos, hacen que el hallazgo de nuevas reservas sea la mayor preocupación estratégica de los gobernantes en el campo económico.

Como, además, estas necesidades de largo aliento se imbrican con su plan de reforma constitucional para la reelección continua, el despliegue de la segunda gran ofensiva contra ONG no alineadas se ha disparado con el mayor ruido posible. Los gobernantes sentían que era necesario para detener en seco cualquier acción que dichas instituciones pudieran estar llevando a cabo que se cruce con sus planes petroleros. Además, eso les permite obtener resultados disuasorios y de intimidación para cualesquier otra que quisiera hacerlo más adelante.

Ya se ha precisado en un análisis anterior que la instintiva desconfianza de este gobierno en particular [^ano_2015_3-4] contra las ONG se relaciona con el hecho de que algunos de sus más notables personeros conocen de primera mano, por experiencia propia, cómo y por qué algunas ONG han sido parte del sistema (informal) de representación política [^ano_2015_3-5]. De hecho, la existencia misma del MAS-IPSP resultaría inexplicable sin el papel de nodrizas asumido por algunas de estas organizaciones en las primeras fases de desarrollo de dicho movimiento político.

[^ano_2015_3-4]: Es bueno recordar que ese recelo se halla ampliamente extendido en una gran cantidad de países; inclusive en varios de los que previamente parecían otorgar carta libre a tales instituciones. La rebelión contra la influencia foránea, la lucha contra el terrorismo, el debilitamiento o el fortalecimiento del Estado son algunos de los argumentos que se ha invocado para justificar esta "epidemia" internacional de suspicacia.

[^ano_2015_3-5]: De allí el despectivo mote de "parapartidos" que ha comenzado a darles el vicepresidente del Estado.

Las capacidades de irradiación ideológica, agitación, propaganda y movilización, además de la especialización en formación, educación y promoción de cuadros de las ONG, son ampliamente conocidas. En gran parte, estas capacidades son el resultado casi natural de que tantas de ellas hayan nacido al impulso de iglesias (especialmente la católica) y que hayan servido de santuario y fuente de empleo a importantes contingentes de militancia izquierdista ---principal, pero no exclusivamente--- en tiempos de dictadura. Una parte sustancial del debate de la reforma constitucional (2006-2008) muestra claras líneas de conexión [^ano_2015_3-6] entre la dirigencia de organizaciones y movimientos sociales con determinadas ONG, o con individuos que las fundaron o que pertenecieron a una o varias de ellas.

[^ano_2015_3-6]: Las múltiples coincidencias entre las Constituciones de Ecuador y Bolivia, por ejemplo, exhiben las conexiones entre dirigentes y organizaciones sociales, campesinas e indígenas principalmente, tanto como de redes de ONG y académicas, que han servido de usina y transporte de contenidos conceptuales muy significativos. En el texto *"El Pacto de Unidad y el Proceso de Construcción de una Propuesta de Constitución Política del Estado"*, sistematizado y compilado por Fernando Garcés y publicado con apoyo de UNITAS, NINA, CEJIS, SENDA y otras (el PDF puede descargarse del sitio web de UNITAS), se encuentra una rica veta de pistas sobre estas relaciones. Además, los asesores de organizaciones sociales casi siempre son o fueron parte de esas organizaciones.

Tales antecedentes se han usado en esta nueva ofensiva [^ano_2015_3-7] para crear un verdadero clima macartista, basado en el supuesto monopolio estatal ya no de la fuerza legítima, sino de la opinión y la acción política. La rudeza del ataque ocasionó críticas entre varios intelectuales, académicos y activistas internacionales tan destacados como Boaventura de Souza Santos y Alberto Acosta, entre otros, obligando a una respuesta vicepresidencial calificada de forzada e insincera [^ano_2015_3-8] por alguno de ellos.

[^ano_2015_3-7]: La anterior ocurrió en 2012 y se acompañó de la publicación de un texto vicepresidencial consagrado al tema.

[^ano_2015_3-8]: El vicepresidente negó su amenaza de expulsar a las ONG "que hicieran política", aunque está registrada en casi todos los medios de difusión. Esta negativa le ganó nuevas observaciones, véase: " 'Poco serio decir que fuimos engañados'. Maristella Svampa responde a García Linera". Véase: <https://pueblosencamino.org/?p=1696>

En esta oportunidad el ataque se desarrolló simultáneamente contra varios periodistas y medios que sufren desde hace años acciones de hostigamiento y desprestigio, o a quienes se les niega participar en la torta publicitaria administrada por el Estado o, más frecuentemente, de ambas. Esto muestra un pico en los niveles de intolerancia, habitualmente bastante elevados.

En una situación en que la economía aporta por ahora más preocupaciones que alegrías, mientras que los plazos y procedimientos para una reforma constitucional no dejan de enredarse, el talante oficial no es de los mejores para aceptar problemas en el espacio del sistema de representación, donde ONG y medios desempeñan tan importante papel.

Desde el punto de vista de quienes quieren y sienten que necesitan extender su control del poder indefinidamente, no basta con haberse asegurado una superioridad electoral tan categórica, ni con haber capturado a casi toda la dirigencia de organizaciones sociales. Creen que es indispensable impedir desde la cuna el surgimiento de focos de inconformidad o protesta.

## El desfonde del FONDIOC

El Fondo campesino, que funcionó hasta agosto de este año, contribuyó decisivamente a remachar lealtades y apoyos de la dirigencia campesina mediante mecanismos clientelistas que se expusieron a la vista pública. Esto, debido en parte a la magnitud de la malversación y el fraude, detectados por algunos periodistas, pero sobre todo a la lucha de facciones dentro del MAS.

La dimensión de los escándalos forzó el cierre y a la refundación inmediata del Fondo campesino, así como la renuncia de la ministra de Desarrollo Rural (figura muy cercana al presidente y muy apreciada por él [^ano_2015_3-9]) debido al informe de la interventora. La reacción del gobierno tiende a asegurar buenas relaciones con los sectores usufructuarios del Fondo y a restaurar la dañada imagen del Ejecutivo, aunque en su afán de hacerlo no haya dudado en profundizar la separación entre campesinos e indígenas comunitarios, anulando la representación de estos últimos en el Fondo reestructurado [^ano_2015_3-10].

[^ano_2015_3-9]: La exministra ya ha sido públicamente exculpada por el jefe de Estado, quien se ha referido a ella como una víctima de una representación excesivamente numerosa de dirigentes en el directorio del Fondo.

[^ano_2015_3-10]: Si el nombre del Fondo reflejara lo que ha hecho o lo que se ha definido para el recientemente creado o refundado, habida cuenta de los criterios empleados para seleccionar a los proyectos y beneficiarios, más que Indígena o Campesino, debería llamarse "Fondo Partidario".

Con estas últimas decisiones, la confrontación entre indígenas y campesinos se ahonda y empeora, después de la prolongada historia de choques por el control y usufructo de tierras categorizadas como TCO, y que se quiere incorporar a la ampliación de la frontera agrícola y al mercado de tierras. La prolongada lucha por el TIPNIS es solamente la más grande y conocida de esas pugnas; también expresa las tensiones en torno a la falta de un auténtico reconocimiento estatal de una verdadera autonomía indígena.

## Estatutos autonómicos y reforma constitucional

Desde el punto de vista del funcionamiento de las autonomías, la importancia que le concede el gobierno a los referendos autonómicos de este mes parece partir del supuesto de que el voto positivo en favor de estatutos elaborados por órganos controlados por su militancia reforzaría su imagen de actor favorable a las autonomías, y le auguraría buenos resultados en el próximo referendo constitucional.

Lo real es que todos esos estatutos, departamentales o indígenas, expresan las significativas restricciones que la Ley Marco de Autonomías ha impuesto no solo a un desenvolvimiento autonómico, sino incluso al grado de descentralización que se había logrado previamente. Por ello, su muy probable aprobación en todos los casos no modificará tales límites, ni la tendencia centralizadora del partido de gobierno. Al mismo tiempo, tampoco mejorará la chance del gobierno de ganar en un referendo destinado esencial, sino únicamente, a autorizar la reelección.

Los verdaderos problemas a los que se enfrenta la obtención de ese objetivo no son ni la oposición política ---casi borrada de la escena--- ni la acción crítica de medios, periodistas u ONG. El primer problema es el control de daños que puede ocasionar la merma de ingresos y recursos económico-financieros; el segundo es la complicada arquitectura de una reforma constitucional, que permita que los cambios ofrecidos, excluyendo la reelección, sean tan atractivos que viabilicen esta última.

La reforma de la justicia es el principal impedimento para desenredar el resto del ovillo, porque el tiempo que reclama parece excesivamente largo frente a las necesidades oficiales de abreviar plazos, antes de que se sigan sumando las estrecheces presupuestarias, y los actores a convocar sean demasiado numerosos e imprevisibles [^ano_2015_3-11].

[^ano_2015_3-11]: Si se atienden las expresiones contradictorias de sus voceros, aparentemente el MAS no termina de decidirse entre presentar una ley de necesidad de reforma exclusivamente consagrada a autorizar la reelección, como lo ha afirmado el primer vicepresidente de los diputados, Víctor Borda, en "Diálogo panamericano" del sábado 5 de septiembre, o "40 otras reformas", según el anuncio del dirigente Hilarión Mamani, titular del CONAMAQ oficialista.

Por ello, lo más probable es que los gobernantes se inclinen por una reforma "compleja" (es decir, con varias reformas), que tiene la ventaja de atender el clamor social de cambios en el aparato de administración de justicia, y puede servir para entreverar con otras la pregunta sobre la reelección, para inducir su aprobación y tratar de garantizarla.

La insistencia vicepresidencial ---seguida entusiastamente por todos los voceros oficiales--- de reemplazar la palabra reelección por "repostulación" no atiende, ciertamente, a un criterio lógico o gramatical, sino al antecedente de que los electores desconfían de las reelecciones continuas, según lo han mostrado al menos tres encuestas nacionales [^ano_2015_3-12].

[^ano_2015_3-12]: A contramano, efectivamente, de la última encargada por el gobierno a la empresa IPSOS, según la cual los encuestados a nivel nacional estarían a favor de la reelección.

En cualquier caso, el conjunto de manifestaciones de voceros gubernamentales y de los dirigentes de la Coordinadora Nacional del Cambio (CONALCAM) traslucen que el oficialismo ya ha decidido acelerar la realización del referendo de aprobación de la reforma de la Constitución, lo que se explica por la aprensión que les generan las consecuencias de una prolongación de la coyuntura de escasez [^ano_2015_3-13].

[^ano_2015_3-13]: Y su influencia en el aumento dentro la coalición de presiones corporativas y fuerzas centrífugas de fuerzas sociales nucleadas dentro y en torno al MAS, como se ha caracterizado en el análisis de coyuntura anterior.

También se ha hecho público que han definido introducir la figura de la doble reelección [^ano_2015_3-14], y que la autorización popular se envolvería, junto con otras cuestiones, en una sola pregunta sobre el referendo popular necesario para aprobar la reforma.

[^ano_2015_3-14]: "La dirigencia explicó que Evo Morales fue elegido en 2009 y en octubre de 2014 fue reelegido, por tanto el 2019 sería elegido y el 2024 debería ser reelegido, de ese modo se cumple el texto constitucional que habla de dos reelecciones continuas, lo que llevaría a Morales a permanecer en la silla presidencial por dos periodos" \[el resaltado es nuestro\] (véase: <https://n9.cl/5mbvt>).

La oposición partidaria ha estado esencialmente ausente, y las pocas oportunidades en que algún representante aislado de sus filas ha logrado viabilizar iniciativas visibles para el público, se producen desinteligencias internas que disuelven la capitalización partidaria o frentista de dichas acciones [^ano_2015_3-15].

[^ano_2015_3-15]: Un ejemplo típico es Rafael Quispe, exdirigente de CONAMAQ y actual diputado de UN, quien da a conocer varias denuncias sobre el Fondo Campesino y que ha empezado a denunciar al jefe de su partido por supuestas amenazas anónimas que le atribuye. La virtual ruptura entre Demócratas y UN es otra expresión de las calamidades sin fin que promueve, impulsa y enfrenta la oposición partidaria.

De hecho, la oposición está tan debilitada que es altamente probable que el MAS gane una nueva elección, incluso si cambia de candidato presidencial. Por ello, se puede arriesgar la hipótesis de que la búsqueda de la reelección puede convertirse, con el transcurso del tiempo, en el camino más peligroso para ese partido, porque si sus planes no funcionan como espera, pondrá en riesgo, más que su futuro electoral, el de su propia vida, pues no habrá conseguido superar la eterna historia de ultradependencia de sus jefes o caudillos.

::: {style="text-align:right; font-weight: bold;"}
Septiembre de 2015
:::

## Notas
