---
lang: es
format: 
  html:
    page-layout: article
---
# Clases medias en debate y la hipótesis de Morales prescindente {.unnumbered}
---

En el espacio continental, la derrota de Correa en el referendo del Ecuador, el apresamiento de Lula [^1], el estrechamiento del cerco judicial sobre figuras clave del kirchnerismo y sobre la misma Cristina Fernández, la insubordinación social que desafía a Ortega en Nicaragua, tanto como el repliegue de seis Estados miembros de UNASUR [^2], expresan la pérdida y el debilitamiento de aliados del régimen en el entorno regional y de la malla de apoyos que lo sustentó en los períodos más duros.

En casa, el apresurado retroceso que se vio obligado a ejecutar el mandatario ante el cuestionamiento a sus políticas, que se pertrechó tras la bandera de impugnación de su nuevo Código Penal, vino acompañada de una caída de la intención de voto por debajo del 30% para Morales por vez primera desde la instalación del régimen. El amaño de las fisuras del bloque social que lo sustentan, y que han llegado hasta su núcleo cocalero, se ensamblan con las “malas vibras” que llegan de fuera de las fronteras.

## Teorías pulverizadas

Inmediatamente después del sofocón oficial a raíz de los resultados de las elecciones judiciales de 2017, la abrogación del nuevo Código Penal ha sido el mayor atolladero político gubernamental desde su fracaso en el referendo constitucional de 2016.

El adverso resultado de la elección de magistrados en diciembre pasado, muy relevante en tanto abierta expresión de censura social, probablemente fue menos doloroso para los gobernantes, no solo por el inmediatismo que prima en su conducta, sino porque no tuvo consecuencias tangibles inmediatas. En cambio, la resistencia de orígenes múltiples, ovillada detrás de la repulsa al Código, los obligó a adoptar la que constituye la más temida y odiada medida para el verticalismo corporativista estatal: tener que retractarse, por intervención directa y de emergencia del propio comandante en jefe del proceso.

Es difícil imaginar peor porrazo para el equipo estratégico encargado de la campaña electoral para las elecciones de dentro de escasos 18 meses. Y mucho más para el ambicioso y todavía encubierto proyecto de poner en pie un nuevo modelo posliberal, que consagraría la permanencia prolongada del Estado corporativo, mediante la implantación de un bipartidismo débil o un monopartidismo fuerte, según la fórmula a que se hizo referencia en el análisis previo [^3].

En un esfuerzo retorcido, a fuerza de complicado, el vice García ha tratado de presentar la caída del Código como resultado de la insurgencia de una “clase media decadente”, atemorizada por la masiva incorporación de nuevos adscritos a dicha franja, gracias al incremento de ingresos provistos por la política del gobierno a unos dos millones de personas, que antes subsistían en la pobreza. Esta masa de recién llegados, con ingresos individuales de “entre 3 a 4 mil Bs por mes”, según el vice, habría conflictuado a la “vieja clase media”, temerosa de tener que compartir prestigio y otros bienes intangibles [^4], lo que la condujo a una asonada contra el gobierno.

La *bajada de línea* vicepresidencial, para orientar y armar a la militancia ante a la incuestionable desmoralización que introdujo en sus filas el abrupto abandono de la hermética defensa del Código, no consiguió ni lo uno ni lo otro. Y es que, además de sus graves omisiones sobre los hechos, rebosa de nudos y lagunas teóricas propias de la improvisación, pues se trata de montar construcciones conceptuales destinadas a imponer una interpretación interesada de la realidad.

El rediseño de las clase medias urbanas en Bolivia es un fenómeno que no se restringe al incremento de ingresos [^5] ni al lapso de una década; tiene varias etapas y períodos. Se trata de una larga historia, con hitos clave a inicios del siglo XX, a partir de los primeros avances vigorosos de la urbanización y la traslocación de la identidad mestiza, heredada de la Colonia a la clase media, vinculada a la aceleración de la expansión de relaciones capitalistas en Bolivia.

La Revolución del 52 establece luego un hito fundamental, pues dinamiza la fuerza y presencia de los campesinos, la clase media por excelencia en formaciones sociales como la nuestra, y la matriz de la que nacen múltiples fracciones sociales, procedentes de la urbanización de familias campesinas.

Las migraciones internas que datan de ese período, con la creación y consolidación de categorías como los comerciantes populares, choferes y cooperativistas, generan nuevos sectores de pequeña burguesía urbana en bolsones territoriales relativamente bien diferenciados y acotados en las mayores urbes. Mientras que el avance territorial de estos grupos a zonas y barrios caracterizados como “residenciales” (es decir ricos, en el lenguaje coloquial del país) de las principales ciudades del país, es uno de los rasgos más destacados en las dos últimas décadas.

Existe la noción según la cual la pequeña burguesía tradicional resiente la disputa por bienes intangibles como el prestigio; supone que estos bienes, incluyendo el poder, serían objetos. Sin embargo, esto es manifiestamente equívoco porque se trata de relaciones sociales, y no aplica la noción de que existen en una cantidad dada y constante y que, por tanto, lo que gana uno lo pierde el otro.

Los protagonistas que tiene en mente el vice cuando describe los ímpetus de consumo y enquistamiento en el poder no se aplican, precisamente, a quienes acaban de superar la pobreza de una manera tibia, frágil e insegura. Se aplican, más bien, a la nueva burocracia que desplazó a la que tradicionalmente solía llenar los cargos estatales altos y medios, así como a los empleados de ONG hoy acorraladas o extintas y a los consultores excluidos de sus nichos habituales de trabajo. Pero tal forcejeo no se ajusta a la descripción de una oleada de pobres en ascenso, ni se disputa principalmente en el campo de bienes intangibles. Es, más bien, la continua pugna por empleos, y se da entre franjas sociales sólidamente decantadas desde antes del “proceso de cambio”.

En plan de afirmar el carácter reaccionario de las movilizaciones que frenaron en seco la aplicación del nuevo Código Penal, la teoría oficial evade escrutar la complejidad de la dinámica de la formación-disolución de clases y fracciones. Pretende reducirla a una visión economicista extrema, y olvida que la movilización de los médicos operó como un punto de concurrencia de múltiples reivindicaciones y sectores atropellados y humillados por la política oficial en anteriores choques, todavía muy frescos en su memoria.

El Código representa y condensa, para la coalición de sujetos sociales que acompañó y dio cuerpo a las protestas de médicos y estudiantes, la dinámica de un Estado que aplasta a oponentes sociales —los de Achacachi, los discapacitados, los del TIPNIS—. Representa también a un país ignorado, con la anulación de facto de los resultados del referendo constitucional por decisión del TCP.

Es el rechazo al carácter antidemocrático de la elección judicial. Esta resistencia que enfrentó al poder político y terminó por imponer la abrogación del Código Penal no depende, ni puede entenderse o explicarse, por la reacción ante uno o algunos de sus artículos, por la sola acción de médicos o transportistas y, menos todavía, por el rechazo al carácter evidentemente progresista de algunas de sus disposiciones.

Los movimientos ciudadanos que llegaron a alinearse detrás de un refundado Comité por la Defensa de la Democracia (CONADE) son lapidados como si se tratara de partidos opositores, cuando estos, en realidad, manifiestan un temor considerable a que, desde ese flanco, les surja una competencia que no saben cómo conjurar. De momento, tal posibilidad es muy remota, pero el solo hecho de que sirva de incubadora a candidaturas ajenas a sus estructuras les resulta muy inquietante. Esa intranquilidad proviene de las evidencias de que las amenazas que se ciernen sobre el MAS los afectan también a ellos.

La imposibilidad de despegue de sus conocidas candidaturas está asociada al hecho de que el éxito oficial sería imposible sin la funcionalidad que exhiben los partidos opositores al régimen, con sus impotentes acciones, la facilidad de entregar un continuo flujo de tránsfugas que no cesan de engordar la bancada oficialista, o las mezquinas disputas internas cuando llega la hora de repartir secretarías y puestos residuales en las directivas camarales.

Este panorama no aparece por ningún lado en la primitiva y sesgada explicación vicepresidencial, que solo ve doctorcitos preocupados de que los que hasta ayer eran pobres les quiten sus puestos en la universidad, en las desharrapadas instituciones sanitarias o en sus clubes sociales. De modo que el gremio conseguiría movilizar a sus depauperados pacientes para, finalmente, aprovecharse de la sensibilidad presidencial. Dicha sensibilidad, ¿abrirá espacio, tal vez, a otro error? [^6], que es como calificó al referendo de 2016.

Claro que el vice se cuida muy bien de enjuiciar las acciones del presidente, porque hacerlo supondría quebrantar los procedimientos que le han garantizado convertirse en casi el único sobreviviente de la vieja guardia de acompañantes que ha capeado todas las crisis y depuraciones en el círculo
íntimo del mandatario.

La intuición política del presidente alcanzó a percibir el carácter profundo del enfrentamiento, algo que su séquito necesita ignorar para poder vender sus alambicadas y cada vez más vacías explicaciones teóricas. De allí que las poses belicistas de “venimos a la guerra y no a caminar sobre flores”, que propala el vice, tuvieron que ser rápida y momentáneamente sustituidas por actitudes más cautas y conciliatorias cuando la conducción máxima percibió que era preferible abrogar el Código antes que arriesgar el control del poder.

## Medidas de remediación

No son muchas las ocasiones en que el régimen se ha visto obligado a dar marcha atrás de manera tan aparatosa como con la abrogación del Código Penal, pero no ha sido la primera. La renuncia a mantener en pie el “gasolinazo” ha sido la inicial, la más importante y duradera. La segunda, la “ley de intangibilidad” del TIPNIS, forzada por la marcha indígena, demostró que algunos retrocesos sirven para tomar impulso y retomar con mayor fuerza, más adelante, las políticas oficiales sacrificadas o, mejor dicho, postergadas.

El reflejo de autoconservación que condujo a abolir el Código tiene toda la apariencia de corresponder a esa segunda categoría, dado que no altera la hoja de ruta definida por el MAS para preservar el control del poder. En ella la aprobación del Código es una pieza importante, aunque no indispensable.

Precisamente como reacción ante la momentánea derrota, desde el gobierno se han multiplicado los esfuerzos e iniciativas para tratar de revertir la reducción de las posibilidades electorales de su candidato y recuperar la credibilidad desgastada por el grueso caudal de evidencias y denuncias de corrupción y por la multiplicación de confrontaciones sociales.

Así, el informe presidencial ante el Congreso, en enero último, reitera la interpretación exitista de los avances ciertos o supuestos que ha logrado el régimen y establece la línea propagandística en la que basará su promoción: “sueño cumplido”. De acuerdo a esa narrativa, es un gobierno popular de ensueño, encabezado por un presidente suprahumano que hará realidad los más profundos anhelos del pueblo. Ya se trate del Bala, el retorno al mar, Rositas o cualquier deseo o reivindicación nunca antes alcanzado, contamos con el personaje que puede lo que ningún otro.

Bajo este esquema escénico se presentaron los alegatos orales en La Haya, reiterando la ventaja que, en términos de imagen, consiguió desde un inicio el gobierno boliviano. Esta ventaja se vio amplificada por la obstinada reiteración de gestos prepotentes, esencialmente antihistóricos, de la parte chilena. Si el gobierno boliviano hubiese mantenido y ampliado las señales de apertura interna con los que constituyó el grupo de apoyo presidencial y de voceros, probablemente hubiese cosechado mayores éxitos de imagen [^7].

Pero la manifiesta electoralización del tema, las enormes incongruencias entre la narrativa con que se sustenta la demanda (cumplimiento de compromisos, justicia, acatamiento de las leyes) y las prácticas internas, sumadas a episodios de inocultable sectarismo (ataques a Carlos Mesa, exclusión de David Choquehuanca, entre otros), limitan su eficacia y verosimilitud.

Por eso mismo, la creencia de algunos fieles de que un fallo favorable de la Corte Internacional blindaría un éxito electoral en octubre de 2019 es propia de un subjetivismo desatado, incapaz de asimilar que los factores que definirán esos resultados son múltiples y que la tendencia declinante que ensombrece actualmente a la candidatura oficial no puede revertirse por uno de ellos. Pero como el esquema de control y manejo del poder no admite dudas [^8], el equipo de campaña no descansa en propalar por todos los canales que un eventual —y muy probable— triunfo de la demanda boliviana ante la CIJ equivaldría a goleada electoral el próximo año. La idea ha calado profundamente en el presidente y también entre los partidos de oposición, que ciertamente no lo reconocen públicamente, pero lo temen reverencialmente.

La política económica se ajusta, como siempre, al mismo esquema, empujando a que el Banco Central y el Ministerio de Economía prevean el 4,7% de crecimiento para este año [^9], para apuntalar una cuasi promesa de aguinaldo extra. En tanto, el despacho de Energía le asegura al jefe de Estado que el informe sobre reservas probables de 100 TCF equivale poco menos que a contar con dinero en el bolsillo, de manera que el presidente ya promete recoger para Tarija regalías del orden de los 3.000 millones de dólares en las siguientes gestiones fiscales.

Pero, además de los cálculos alegres y la multiplicación de ofertas y promesas, el gobierno no descuida afinar y profundizar sus relaciones con las fracciones más importantes del gran capital. Toda la batahola de las protestas empresariales por el incremento salarial y la ley de empresas sociales es genuina, aunque calculadamente exagerada, porque en las últimas semanas el Ejecutivo ha hecho importantes concesiones y compromisos con empresas mineras, mientras regulariza pagos pendientes con las petroleras y da abiertamente luz verde a la producción de agrocombustibles, en tanto que son cada vez más laxos sus controles sobre semillas genéticamente modificadas.

Estas dos últimas medidas ratifican la importancia estratégica que el régimen asigna a la columna vertebral de su propuesta programática de la agenda 2025, referida a la ampliación de la frontera agrícola y a la producción de agroexportables. El segundo pilar, el anhelo de exportar electricidad mediante la construcción y puesta en marcha de megarepresas, está demorado, ya sea por la cuantía del financiamiento o por peleas burocráticas internas (como en el caso Rositas), que fácilmente podrían revelar disputas por tajadas de poder y beneficios que acompañen la asignación y administración de tan grandes contratos.

El completo copamiento de la Central Obrera Boliviana, a través de un forzado y rápido congreso, se ajusta a todo el esquema revisado, y apunta a presentar la imagen de un movimiento popular organizado que se alinea fervorosamente con el régimen. Urgía la depuración de opositores individuales y lastrados por el oportunismo para reparar la portada de unos “movimientos sociales” cohesionados y adheridos sin fisuras al proceso.

## La fortaleza asediada

Si de algo nunca ha dejado estar consciente la cúpula del régimen es de que el debilitamiento de la economía del país acarrearía ansiedad y disputas entre las corporaciones, que son su apoyo social, y divisiones en el aparato político que dirige. Por eso su obsesivo empeño en propagar incansablemente los avances conseguidos, en silenciar o negar sus retrocesos y en estar a la caza de oportunidades para amortiguar los problemas acumulados durante la fase de desaceleración todavía vigente.

Tales recursos, sin embargo, son insuficientes para aplacar el impacto erosivo de la caída de los ingresos por exportaciones, el desperdicio de recursos por corrupción y los errores de gestión, derroche y clientelismo, que amplifican y extienden los efectos adversos de la baja de precios de las materias primas. Es demasiado conocido que los más importantes efectos se expresan en un descenso de las reservas internacionales netas (RIN), en la aceleración del endeudamiento y en el incremento del déficit fiscal (hoy casi idéntico al de los años de crisis de Estado y de colapso del régimen neoliberal).

Los argumentos de la defensa gubernamental mantienen por ahora su eficacia, mientras que los pronósticos económicos catastrofistas apenas influyen en mucho más que algunas franjas de población urbana, que año tras año han mostrado su tendencia a la exageración.

Sin embargo, una deuda desembolsada que está por encima de los 9.500 millones de dólares, la contratada solo con China, que supera los 7.000 millones de dólares [^10], además de otros compromisos ya aprobados, pero aún no desembolsados, suman una carga cada vez más difícil de afrontar, especialmente cuando las expectativas de retorno de gran parte de las inversiones productivas se encuentran muy por debajo de lo programado [^11].

Por ello, a pesar del manifiesto repunte alcista de hidrocarburos y minerales, la principal fortaleza gubernamental confronta amenazas cuya resolución no se vislumbra por lo menos en los próximos dos años. Dichas amenazas están activando los temidos resquebrajamientos de la base social oficial y el incremento de las contradicciones partidarias internas.

La disputa de Achacachi anunció que las confrontaciones anteriores entre campesinos y colonizadores con indígenas se convirtieron en fracturas que afectan también a los campesinos, En lo que va del año, la mayor novedad son las grietas en el núcleo colonizador-cocalero. Así, las disputas generadas por la queja de los Yungas sobre las ventajas de la Ley de la Coca para el Chapare han continuado en escalada; ahora se expresan en choques en el reducto cocalero paceño [^12].

Las pugnas intercorporativas tienen, a su vez, repercusiones en el MAS, atizando las querellas entre facciones; en ellas han ido sucumbiendo casi todas las que se confrontaron con el aparato conducido por el Vice [^13]. Las recientes riñas entre “Ponchos rojos” y la militancia juvenil del MAS muestran la propensión de dichas contradicciones a agudizarse, prolongarse y multiplicarse.

## Momento de inercia y un escenario poco probable

La oposición política (incluyendo a los colectivos ciudadanos) no ha encontrado vías para prolongar la defensa del voto y la soberanía popular, desconocidos por la sentencia del TCP. Nuevamente, las movilizaciones intrínsecamente espontáneas exhiben gran superioridad sobre las planeadas y organizadas por partidos u otras asociaciones políticas, con la desventaja de que la espontaneidad no estructura opciones electorales.

Los vacíos más importantes en la oposición son la falta de congruencia en la defensa de la Constitución, la incapacidad de articular luchas cotidianas y económicas con la resistencia democrática y una ausencia completa de cuestionamiento al programa que representa la reelección de Morales Ayma. Tampoco presentan una visión alternativa de país, conectada a un programa de gobierno que no se restrinja a la reivindicación formal del *Estado de derecho* y a una agenda de ajustes. A falta de un análisis y tratamiento de estas cuestiones, la oposición se limita a confiar en recursos judiciales presentados a instancias internacionales, a intrigar, armar revuelos anecdóticos y barajar candidaturas.

En tales condiciones, prospera el plan de la reelección, pese a la suma de tropiezos y adversidades. Su descarrilamiento sería posible si se lo encomendara a circunstancias imprevisibles y completamente ajenas a la voluntad y la previsión de fuerzas políticas organizadas.

La inercia de la coyuntura, más la voluntarista representación del futuro [^14] y la interpretación caprichosa de los acontecimientos (*wishful thinking*, en inglés), cierra prácticamente toda posibilidad de que los estrategas oficiales lleguen siquiera a considerar —así sea como simple ejercicio intelectual— los resultados y consecuencias que traerían el que Morales Ayma decidiera abstenerse a candidatear en 2019.

Ellos, como la oposición, dan por descontado que eso equivaldría a una derrota segura (“suicidio político”, en palabras del Vice), cuando hay importantes razones para pensar que un Evo Morales *prescindente* (en sentido de quedar alejado u omitido de la elección de 2019) podría más bien ayudar al régimen a resolver las mayores y más premiosas adversidades que está acumulando en su contra.

En esta “imposible” hipótesis de unas elecciones sin Morales, casi toda la narrativa opositora se desmoronaría tan rápido como su débil predisposición a unirse. Incluso en el supuesto de que el MAS se estancara en los niveles de intención de voto que registran las encuestas actuales [^15] (por debajo del 30%), tendría posibilidades en una segunda vuelta presidencial y, con las reglas electorales vigentes para la asignación de bancas, obtendría una representación parlamentaria próxima al 40%. Esta representación sería suficiente para bloquear las más importantes propuestas legislativas de sus contrarios, incluyendo todo tipo de juicios de responsabilidades.

Si a lo anterior se agrega que entre sus activos cuenta con el control de la alta gerencia pública (Contraloría, BCB, empresas estatales, autoridades fiscalizadoras, etcétera, etcétera), el manejo del Órgano Judicial, un enorme aparato de medios masivos de difusión privados y la adhesión fanática de la dirigencia de las mayores organizaciones sociales (cuyos líderes temen ser investigados y sufrir consecuencias que no alcanzarían a los funcionarios con caso de corte), tenemos que incluso estando en la oposición el MAS contaría con una enorme cuota de poder. La suficiente para acogotar a un débil gobierno, carente de programa estratégico y visión de país alternativa, hasta llevarlo a un revocatorio, a partir de la resistencia a las medidas de ajuste (devaluaciones, despidos de la administración pública y otras), de las cuales los partidos opositores no hablan, pero sí los académicos, expertos y analistas vinculados a sus posiciones [^16], cuando se refieren a las *indispensables medidas correctivas* que se están soslayando ahora. En tal escenario, el sacrificio inmediato de la candidatura de Juan Evo Morales Ayma habría servido para habilitarla para, por lo menos, las subsiguientes dos elecciones nacionales.

Pese a su presunta inviabilidad, el análisis de un escenario de elecciones sin Juan Evo Morales Ayma encabezando la fórmula del MAS echa luz sobre varios rincones, tendencias, vericuetos y desenlaces improbables, pero no imposibles, de una coyuntura caracterizada por su fluidez, pese al empeño del régimen y al inercial acompañamiento que le brindan sus competidores institucionales.

::: {style="text-align:right; font-weight: bold;"}
Abril de 2018
:::

## Notas

[^1]: Véase: [https://n9.cl/x9hjm](https://n9.cl/x9hjm) En esta crónica, Eliane Brun analiza el caso de Lula lejos de todo maniqueísmo. 

[^2]: Se trata, en principio, de un repliegue temporal y no una desafiliación definitiva de la mitad de los miembros de UNASUR (Argentina, Brasil, Colombia, Chile, Perú y Paraguay), que objetan la acumulación de problemas irresueltos por la prevaleciente confrontación ideológica (la acefalía de la Secretaría General), como lo señala el Canciller boliviano. Pero la intensificación de estas disputas ideológicas y el debilitamiento del bloque del ALBA hacen que UNASUR, y eventualmente la Comunidad de Estados Latinoamericanos y Caribeños (CELAC), enfrenten una parálisis prolongada e inclusive el riesgo de extinguirse o disolverse. 

[^3]: Véase también Página Siete del 11 de febrero del presente año: [https://n9.cl/c2fbo](https://n9.cl/c2fbo). Se trata del modelo desarrollado por el sociólogo Fernando García Yapur y sugerido por varias intervenciones de voceros oficiales, incluyendo el jefe de Estado.

[^4]: Véase: [https://n9.cl/frqko](https://n9.cl/frqko)

[^5]: Que en ningún caso alcanzan los niveles mencionados por García Linera, quien manipula caprichosamente los datos sobre ingresos y otros para fundamentar sus apreciaciones. Los significativos avances en la disminución de la cantidad de familias pobres y extremadamente pobres, así como en la disminución de los índices de desigualdad que ha alcanzado Bolivia, están entre los más exitosos del continente, pero, tal como en otros países latinoamericanos, son aún frágiles y de relativamente fácil reversibilidad. Véase al respecto Susan Nicolai, Tanvi Bhatkal, Chris Hoy y Thomas Aedy (2016), *Proyecciones sobre el progreso: los Objetivos de Desarrollo Sostenible en América Latina y el Caribe*, Banco Mundial. Quienes superaron la frontera de la pobreza están empleando todo su esfuerzo para no retroceder, y no en la competencia para ascender que describe el Vice.

[^6]: El vice no ha caracterizado la abrogación como un yerro. Simplemente calla, después de que sostuvo que no se modificaría una coma de ese cuerpo legal. Pero cuando trata de distanciarse del referendo —al que califica de fallo (ha llegado a llamarlo “locura”) de cálculo de las organizaciones sociales—, se olvida completamente que esa táctica se basó en su apreciación de que los resultados de las elecciones de 2014 establecían un *piso firme electoral* del 60% para el MAS. Quienes le creyeron se apresuraron a forzar, un año después, el referendo constitucional, buscando explotar la presunta ventaja de contar con ese *piso*.

[^7]: Si, por ejemplo, hubiera convocado a gobernadores y alcaldes a presentar iniciativas propias, para dar un marco local a la presentación boliviana.

[^8]: Dada la dinámica organizativa y de toma de decisiones del MAS y del gobierno, donde todo se subordina a la aprobación del jefe, con muy escaso o ningún debate, y donde, en consecuencia, el destino colectivo depende de imponer al caudillo. La comunicación, en tanto, exige exhibir el máximo nivel de optimismo respecto a realizaciones, resultados y perspectivas. Preservar en alto la moral del encargado de materializar las expectativas de los seguidores pasa, de ser un buen deseo o una simple expresión servil, a convertirse en un imperativo estratégico, aunque los hechos se contradigan con el panorama que se le muestra al conductor.

[^9]: Véase: [https://www.bolivia.com/.../evo-morales-anuncia-que-en-2018-habra-doble-aguinaldo](https://www.bolivia.com/.../evo-morales-anuncia-que-en-2018-habra-doble-aguinaldo) También: [https://n9.cl/0rrvya](https://n9.cl/0rrvya)

[^10]: Véase: [http://radiofides.com/es/2018/02/17/embjador-de-china-la-deuda-de-bolivia-es-mayor-a-los-siete-mil-millones-de-dolares/](http://radiofides.com/es/2018/02/17/embjador-de-china-la-deuda-de-bolivia-es-mayor-a-los-siete-mil-millones-de-dolares/)

[^11]: La planta de urea, que funciona muy por debajo de su capacidad, las secadoras de gas natural subaprovisionadas de materia prima, el ingenio azucarero estatal, que casi carece de caña, son algunos de los principales ejemplos, pero la lista es mucho más larga.

[^12]: La confrontación entre el Estado y los cocaleros yungueños se muestra cada vez más sórdida y enredada porque, para empezar, no es cierto que la hoja producida en La Paz se dedique exclusivamente al consumo legal: aunque en menor proporción que la de Chapare (cuyas cosechas tienen una productividad mayor), una parte apreciable se desvía de los circuitos legales. En consecuencia, las disputas por el control del mercado y los circuitos de comercialización tienen una variedad de agentes e intereses, manipulados tanto por el gobierno, como por los dirigentes a los que intenta descabezar. Está, por otro lado, la abismal ventaja que el Chapare obtiene en materia de inversión pública (planta de urea, aeropuerto Chimoré, infraestructura, servicios, cooperación técnica, etcétera, etcétera) que crispa los ánimos en Yungas 

[^13]: Mientras algunas luchas palaciegas, como las del vice con el excanciller Choquehuanca, son relativamente conocidas y de explicación no muy complicada, otras, como la del enfriamiento del aparentemente insustituible Arce Catacora y sus recientes y constantes esfuerzos de reaparición, son más turbias y herméticas. De todas maneras, el MAS, comparado con otros partidos, muestra una notable capacidad de resguardar su intimidad, pese a la elevada cantidad de bajas políticas que acumulan sus pleitos internos. Las filtraciones y revelaciones importantes son hasta ahora excepcionales.

[^14]: Que, en su versión pesimista, tiene atrapada igualmente a la oposición partidaria, ya que mientras el MAS se empeña en creer que lo realmente bueno está por llegar, esta se inclina por confiar en que la línea de descenso gubernamental es fatal e irreversible. Dicha actitud le impide entender y asumir las situaciones y hechos que aumentan las oportunidades gubernamentales: recuperación del índice de confianza en encuestas, aumento de cotización del gas y minerales, por ejemplo. 

[^15]: Lo que de ninguna manera resulta fatal, ya que con un binomio no digamos electoralmente bueno, sino simplemente no malo, con una oposición dispersa o, peor aún, atomizada, sus posibilidades se inflan.

[^16]: Una columna publicada el 26 de abril último en Página Siete da por hecho que si el MAS es desalojado del gobierno en 2019, primará a tal punto el desconcierto y la división en sus filas, que su derrota definitiva sería inminente. Dicha apreciación no toma en cuenta el gran poder cohesivo que tiene el temor del colectivo de cuadros y dirigentes, partidarios, sindicales y allegados múltiples a que se quiebre la coraza de impunidad que lo protege, ni las gruesas limitaciones de un gobierno de coalición variopinta y ecléctica, que hasta ahora es la única opción visible de recambio.