---
lang: es
format: 
  html:
    page-layout: article
---

# Triunfo y retorno {.unnumbered}

La parsimonia gubernamental para adoptar medidas anticrisis se parece demasiado al estupor que asaltó a una gran parte de la población boliviana, incluyendo muy probablemente a los votantes por el Movimiento al Socialismo (MAS), ante las cifras de su categórico triunfo el 18 de octubre pasado.

No existe un antecedente registrado sobre el paroxismo de sorpresa y desesperación que golpeó a una buena parte de ese 45% de electores que votaron contra el MAS. El efecto del aturdimiento se multiplicó por la significativa demora en las primeras proyecciones del conteo rápido. El público no conseguía asimilar que era la primera vez que asistíamos a elecciones en medio de una pandemia, que bastaba para explicar el retraso que empezó con la apertura de las mesas y que se fue acumulando hasta el envío de datos [^ano_2020_3-1].

[^ano_2020_3-1]: El resultado de la elección se puede encontrar en el constante alto número de supuestos indecisos en prácticamente todas las encuestas, por lo menos de julio en adelante. La conducta beligerante y corrupta del gobierno interino, la consolidación de la candidatura de L. F. Camacho y la ineptitud general de la campaña de CC completan el cuadro.

Vale la pena detenerse en este recuerdo porque, como consecuencia, en las siguientes semanas el país fue sacudido por una ola de negacionismo llevada al paroxismo [^ano_2020_3-2]. Este fenómeno, cada vez más frecuente aquí y en todas partes, obedece a la expansión y al fortalecimiento de la influencia de las plataformas digitales, unánime y equívocamente llamadas "redes sociales", verdaderas sembradoras de desinformación y falsedades.

[^ano_2020_3-2]: Es decir, la incredulidad ante los resultados, pese a la consistencia de los datos y la tendencia a explicarlos con teorías de complot y manipulaciones inverosímiles. El "camachismo" alentó intensamente estas reacciones en plan de ocultar su cuota parte de responsabilidad, y estuvo sustentando ideológicamente las reacciones más golpistas y regresivas. Sin embargo, de ninguna manera cabe atribuirle haber estado solo en esta maniobra.

Bolivia no es inmune a las infodemias, como no lo es al coronavirus, contrariamente a la irónica afirmación de un youtuber promasista a mediados de la primera oleada de la pandemia, y que ha sido ascendido al grado de "héroe popular" por el flamante ministro de Gobierno [^ano_2020_3-3].

[^ano_2020_3-3]: Véase: <https://n9.cl/h02vo>. Tal vez esta actitud proporciona una pista sobre la veracidad de la denuncia contra el nuevo jefe del sistema represivo que sustenta la exsenadora Eva Copa; véase: <https://correodelsur.com/politica/20201124_eva-copa-continua-proceso-por-acoso-en-contra-del-ministro-de-gobierno.html>

Lo verdaderamente importante es que la categórica victoria del MAS ha originado una prolífica serie de teorías conspirativas, de tono y carácter alucinado y alucinante, según las cuales el TSE habría socapado un fraude gigantesco en favor del ganador en esta última elección.

En Santa Cruz ---departamento que, desde la rebelión ciudadana del año pasado, emite frecuentes y crecientes señales de que avanza en encabezar la dinámica política del país--- se ha arraigado de tal manera esta sospecha, que fácilmente puede contribuir al explícito plan de Evo Morales para defenestrar al TSE, facilitándole recuperar su control [^ano_2020_3-4].

[^ano_2020_3-4]: Por ahora, están coaligados en la tarea de desacreditar al TSE desde la ultraderecha hasta sectores progresistas del departamento; véase: <https://n9.cl/apqto>

## El reino de la banalidad

El predominio en la discusión pública de las anécdotas sobre los nombramientos de nuevos altos funcionarios, junto con la adelantada y presurosa campaña electoral por los gobiernos y legislativos de las autonomías, han permitido disimular el enorme desconcierto para afrontar la suma de problemas agregados por la desaceleración económica y la extensión de la epidemia mundial por coronavirus.

La campaña electoral masista y los discursos de apertura de Arce y Choquehuanca en su posesión intentaron crear la impresión de que inaugurarían una gestión caracterizada por iniciativas rápidas y bien definidas. Sin embargo, a un mes de su estreno, las noticias generadas por el Ejecutivo no van mucho más allá de los inevitables nombramientos de nuevos altos funcionarios [^ano_2020_3-5], casi siempre acompañados de un estruendoso zumbido de decenas o centenares de aspirantes que reclaman su espacio en alguna silla de la administración como reconocimiento a su presunta fidelidad o diligencia partidista.

[^ano_2020_3-5]: Véase: <https://n9.cl/dcrg0>

En contrapartida, no asoman por ningún lado planes y medidas para afrontar los problemas de fondo. Aparentemente preocupado por la multiplicación de observaciones sobre este vacío, el ministro de Gobierno ha voceado tres "medidas de reactivación económica": el "bono contra el hambre" (ya aprobado hace meses por la bancada masista saliente); un impuesto a las grandes fortunas y el reintegro en efectivo del impuesto al valor agregado (IVA).

El más importante, pero también de efecto más fugaz, es el bono de mil bolivianos, unánimemente reconocido como necesario, que llegaría a millones de beneficiarios. Este importante monto se inyectaría rápidamente en la economía, con efectos fugaces, pero incontrovertiblemente reactivadores.

El impuesto a la riqueza tiene un horizonte incierto de instrumentación, y su monto ronda lo intrascendente; la devolución del IVA no supera actualmente el carácter de un anuncio, y tiene efectos igualmente limitados.

La prohibición de importar automotores usados ---anunciada como cuarta medida--- no tiene mayor efecto reactivador. Sí tienen, hipotéticamente, un efecto directo sobre el muy golpeado rubro de turismo interno los "permisos especiales" para que funcionarios se tomen vacaciones en estos circuitos. Sin embargo, difícilmente puede utilizarlos quienes no sean altos jerarcas, que suelen estar demasiado ocupados cuidando su puesto y su clientela para tomarse tales licencias.

El 95% de los funcionarios, como el resto de quienes han conseguido preservar su fuente de trabajo o inventarse una, difícilmente pueden pensar en paseos y vacaciones en tiempos de pandemia y empobrecimiento.

A falta de reactivación, se anuncian dos muy correctas medidas en pro de las mujeres: la superación de brechas salariales entre sexos y educación escolar para prevenir la violencia contra las mujeres.

Todas estas disposiciones están muy lejos de encarar con la amplitud y el vigor requeridos el mayor decrecimiento económico experimentado en más de un siglo [^ano_2020_3-6].

[^ano_2020_3-6]: Véase: <https://n9.cl/t61lz>, pp. 13-25. También: <https://n9.cl/nimoq>

A este se suman un muy importante déficit fiscal acumulado y la amenaza de regreso a la pobreza de entre un millón a un millón y medio de habitantes ("la pobreza en la región podría incrementarse hasta 37,3%, mientras que la pobreza extrema a 15,5%", afirma Rolando Ocampo, jefe de Estadísticas de la CEPAL). Además, se calcula una caída de cerca del 40% de los ingresos del país (según la Fundación Jubileo), debido a la disminución de volúmenes y precios de exportaciones, y por el impacto de todos estos problemas en el empleo y la provisión de los servicios básicos (en primer lugar, los servicios sanitarios y la educación).

Las medidas anunciadas son un pálido y difuminado esfuerzo de seguir las recomendaciones de organismos como la CEPAL, que se resumen, textualmente, en:

> *Primera prioridad, atender la crisis sanitaria, en la fase de control de la epidemia, para poder pasar a la fase de reactivación de la economía y reconstrucción con más equidad* [^ano_2020_3-7].<br> <br>Políticas fiscales y monetarias expansivas para contribuir a mitigar los efectos de la pandemia y apoyar la reactivación y la reconstrucción.<br><br> Políticas sociales para atenuar los impactos sobre el empleo, la pobreza y la desigualdad.<br><br> Políticas productivas para evitar la destrucción del tejido productivo y apoyar la reactivación [^ano_2020_3-8].

[^ano_2020_3-7]: *El domingo 29 de noviembre último, el Ministerio de Salud hizo conocer las primeras medidas de prevención, entre las que se incluye el uso de dióxido de cloro y el control de precios en las farmacias, pero no los pagos atrasados ni las masivas adquisiciones de trajes de bioseguridad para el personal de primera línea; tampoco la adquisición de pruebas diagnósticas, o montar el seguimiento y mapeo de contactos. El gobierno de Arce apuesta por campañas de inmunización masivas (gratuitas, ha prometido el ministro del área), probablemente donadas, con vacunas que presentan un alto nivel de incertidumbre en cuanto a eficacia, efectos secundarios y horizonte de inmunización.*

[^ano_2020_3-8]: Véase: <https://n9.cl/48ht0>

Tales pautas, más que un programa especializado, parecen dictados del sentido común, sentido que se muestra completamente esquivo con el gobierno y sus opositores parlamentarios; el atónito silencio de estos últimos acompaña la semiparálisis gubernamental. Con ello tiende a confirmarse que el MAS disfrutará de entrada de una oposición política desmoralizada, desarticulada y desprovista de propuestas e imaginación.

El aturdimiento oficial ha otorgado a la oposición una ventana de oportunidad única para hacer propuestas, plantear iniciativas y exigir acciones. En vez de ello, las coaliciones electorales que supuestamente militan en la oposición se subordinan al ritmo y la agenda del oficialismo, y se dedican, igual que él, a distraer la atención pública, centrando sus mensajes en candidaturas y enjuagues para las elecciones de marzo.

## Miopía estable

La escasa capacidad de comprensión sociohistórica del país que manifiestan las tiendas políticas opositoras se reitera dramáticamente en la esquemática y simplista autocrítica que asume Comunidad Ciudadana ante su fracaso electoral [^ano_2020_3-9]. Lo atribuye principalmente a "factores ajenos", mientras llama eufemísticamente "inadecuada aproximación a lo nacional popular" a su visión señorial, alejada de una comprensión de la gravitación indígena y campesina [^ano_2020_3-10] que caracteriza la realidad boliviana.

[^ano_2020_3-9]: Véase: <https://n9.cl/xdwk2>

[^ano_2020_3-10]: Ni una palabra sobre lo absurdo de una campaña caudillista, centrada en torno a una persona presuntamente parte de una comunidad, ni de su pasividad y carencia de iniciativa y creatividad, pese a que cuenta con la bancada con mayor representación femenina y juvenil.

A los pasivos ya conocidos en materia de conocimiento y sensibilidad social y política estructural de estas tiendas opositoras, se agrega ahora la incomprensión del resultado electoral y, por tanto, de la naturaleza, calidad y límites de la gran votación recibida por el MAS en estas elecciones, en comparación con su triunfo de 2005.

Un dato clave es la diferencia abismal entre los votos con una expectativa de cambio, de inclinación revolucionaria, que ungieron el triunfo del MAS en 2005, y los votos de nítido talante de defensa, conservador y resignado que muestra su votación de 2020. Este hecho no ha sido públicamente analizado por los opositores, aunque sea materia prima fundamental para el diseño de estrategia, tácticas y políticas alternativas.

El temor a una nueva condena a la marginalización política y social, propia del voto masista más duro y leal (principalmente en su núcleo campesino rural andino y en el de los cocaleros), se extiende ahora al resto de los electores del MAS. Lo hace en una relación inversamente proporcional a la estabilidad y antigüedad de su residencia urbana, que puede sumar cerca al 60% del total de ese conjunto [^ano_2020_3-11].

[^ano_2020_3-11]: Estas mis estimaciones se basan en el análisis de cifras proporcionadas en el sitio: <https://n9.cl/j56eg>

La traducción de esta situación es que una buena mayoría de los que han apoyado al binomio Arce-Choquehuanca lo ha hecho por consideraciones prácticas (no ideológicas ni etnonacionalistas), sopesando lo que consideran como la capacidad real del nuevo gobierno de atender las preocupaciones e incertidumbres colectivas.

Esa presunta capacidad será puesta a prueba durante los próximos meses. Y con ella, la fortaleza de la adhesión y confianza de los que, espantados por el comportamiento del gobierno interino y la mediocridad de las otras opciones, prefirieron el mal conocido. Todo ello está sustentado en la expectativa de ver rápidamente resultados tangibles en materia económica, sanitaria y educativa, principalmente.

Esto también limita, en mucho, el espíritu de reformas internas del nuevo gobierno. Estas se han magnificado en noticias y análisis editoriales, basándose casi exclusivamente en declaraciones y en una cierta renovación, sobre todo de parlamentarios oficialistas. Lo único verdaderamente sólido hasta el momento es que se ha incrementado el peso de las dirigencias sindicales y su cuota de participación burocrática [^ano_2020_3-12]. Pero esto, lejos de impulsar una renovación, parece acentuar el corporativismo y el inmovilismo ideológico y conceptual del MAS.

[^ano_2020_3-12]: La singular intensidad de enfrentamientos por copar espacios ha empezado temprano, y puede empeorar rápido y mucho, debido a la influencia que ejercerá sobre ella Evo Morales y los miembros de su séquito, desalojados hoy de puestos protagónicos en el Estado. Estos desajustes internos también se verifican en distintas posiciones en torno a cómo encarar las relaciones con los aparatos represivos (FF. AA., Policía y sistema penal). Esto puede complicar la gestión de los conflictos sociales y abrir espacio, en situaciones de crisis (que tienden a ser frecuentes), a mayores desajustes entre el Ejecutivo y dichas instituciones.

El programa que dicen que proponen aplicar parte de la idea de mantener básicamente intacta la matriz productiva y energética del país. Sin embargo, todo anuncia que los costos de esta decisión (que mantendrá, por ejemplo, las altas e improductivas subvenciones a empresas antieconómicas) empeorará las consecuencias sociales y ambientales que venimos arrastrando de- bido al ineficiente y destructivo modelo desarrollista vigente.

El azoro y la lentitud para formular una oferta anticrisis por el equipo de Luis Arce Catacora puede todavía atribuirse a la falta de tiempo y ensamble del grupo. Parece menos prudente la hipótesis de que se debe principalmente a ataduras ideológicas y a la incapacidad del personal ejecutivo. Sin embargo, esta segunda hipótesis se basa en hechos, por lo que nos permite prever mejor la tendencia central del proceso y su prospectiva.

Las posibilidades de que el gobierno enfrente, desde su arranque, limitaciones genéticas para enfrentar apropiadamente los retos que debe resolver y, en consecuencia, tenga una gobernabilidad hipotecada y quebradiza, se advierten en:

-   Que el programa electoral 2020 del MAS reproduce lo esencial de la Agenda 2025, creada para reelegir a Morales Ayma; esta propuesta no asimila las nuevas condiciones, empeoradas por la pandemia y la concomitancia de otros problemas;
-   Las limitaciones del binomio Arce-Choquehuanca para prevenir y subsanar las contradicciones entre la propuesta y el enfoque tecnocrático del presidente y el discurso metafísico de su vice [^ano_2020_3-13];
-   La omisión completa de propuestas de cambio de matriz productiva, ante el agotamiento o estrangulamiento de las fuentes tradicionales de ingresos del país;
-   La subordinación política y orgánica gubernamental al caudillismo de Morales Ayma;
-   El renovado y mayor peso que tiene en la gestión gubernamental la dirigencia corporativa, principalmente la de origen campesino y colonizador.

[^ano_2020_3-13]: El excanciller perdió una oportunidad excepcional para darle algo de verosimilitud y sustancia a su discurso de posesión, al no haber exhortado a su bancada a retroceder en la modificación de reglamentos parlamentarios, que atenta contra el espíritu de una Constitucional Plurinacional. La esencia de este último término es la comunión, entendimiento y permanente búsqueda de acuerdos en el mosaico de minorías que componemos el pueblo boliviano (más de 36 pueblos originarios, mestizos y combinaciones múltiples), para desterrar la imposición característica del colonialismo.

Como se ve, se trata de pesadas cargas que impiden un camino de rectificación e innovación política e ideológica que supere los ajustes cosméticos introducidos hasta ahora. Con esto se completa el círculo de la estrecha visión propia de la dirigencia política (oficialista y opositora), que deja desguarnecida a la sociedad de alternativas de conducción y guía política.

En cualquier caso, brilla por su ausencia un plan para unir y reconciliar a la sociedad a partir de una identificación realista, profunda y sincera de los problemas a los que nos enfrentamos.

También se nota la falta de un amplio proceso de deliberación colectiva para encarar los graves desafíos que tenemos al frente, en lo económico, sanitario, educativo, económico, democrático y ambiental. Todas las recetas oficialistas y opositoras comparten un carácter cupular, vertical y no participativo.

## Punto a punto y el peso del pasado

En estas circunstancias, las posibilidades de rescatar y poner de pie a organizaciones sociales autónomas frente al Estado son tan o más remotas que hace un año. El triunfo electoral masista premia la subordinación de las dirigencias vigentes y encamina a nuevos dirigentes a imitar sus pasos.

La combinación de ambos factores, junto a un programa de gobierno encadenado a continuar con el modelo de desarrollo vigente y la ausencia de fuerza organizada para resistir sus efectos agravados, dificultará la resistencia social e incrementará el sufrimiento de los más débiles, cuyo número crece aceleradamente.

Mientras la burocracia estatal se prepara para mantener presupuestos que obligan a que paguemos colectivamente el lastre de grandes y fallidas empresas (plantas secadoras de gas, aeropuertos sin tráfico, ingenio azucarero sin caña, obras públicas inútiles o inutilizables) y estipendios a una amplia gana de altos funcionarios, las exportaciones no abastecerán la demanda de divisas para importar, y se multiplicarán los requerimientos para atender la emergencia sanitaria y las nuevas condiciones que requiere la instrucción escolar.

Además, con los presupuestos departamentales, municipales y universitarios estrangulados, la disputa por cada punto porcentual del presupuesto se enardecerá y marcará la tónica de tensiones que tiende a abrirse el próximo año.

Ante la ausencia de medidas para reducir el costo de las importaciones de combustibles, aumentar la exportaciones gasíferas (mediante el uso de fuentes hídricas ya disponibles y no derrochar recursos fiscales en prospecciones inciertas y de lentísima maduración), una plataforma de resistencia y movilización social contra el avance de la enfermedad, el hambre y la pobreza requerirá de mayores partidas educativas, sanitarias y de reactivación y transformación productiva, en vez de los importantes gastos burocráticos e improductivos presupuestados.

Elevar las partidas para educación, servicios sanitarios y socorro a los más golpeados, frente a la pretensión gubernamental de preservar partidas para emprendimientos que no funcionan y plantillas infladas de personal parasitario, podrá ser parte de la pugna predominante en los próximos meses. A ello se sumarán los reclamos departamentales, municipales y universitarios para que los recortes no los asfixien completamente.

Estas demandas resultarán inseparables de la defensa del medioambiente, como reserva estratégica de fuentes de vida y de un modelo alternativo de desarrollo, puesto que se avizora que se mantendrán e intensificarán las políticas avasalladoras de reservas naturales y territorios indígenas. Se busca justificar estas políticas con la ampliación del cultivo de alimentos, cuando la realidad ha demostrado que tales concesiones terminan incrementando la especulación y el tráfico de tierras.

Como una afirmación de lo dicho, la manera en que ha debido despedirse al ministro colonizador que estuvo a la cabeza del Ministerio de Tierras recalca la dificultad que tienen profesionales políticos, oficialistas y opositores para entender estos problemas, que se han mantenido marginales en ese caso de nepotismo y clientelismo.

Nadie planteó que el tema central en ese despacho es que ha encubierto el tráfico de tierras durante los 14 años del régimen masista y sus sucesores interinos entre 2019 y 2020. En consecuencia, el incidente del renunciado ministro debe llevar a un cambio radical de la gestión de este recurso estratégico, bajo personal libre de toda sospecha de reproducir las prácticas depredadoras ejercidas por el MAS y sus aliados empresariales del agronegocio.

Las primeras confrontaciones volverán a plantearse en torno a la prevención y al combate de incendios. Si estas reivindicaciones toman impulso, puede ampliarse la posibilidad de que las hoy muy aisladas demandas de pausa ecológica y prohibición del cambio de uso del suelo se afirmen y se expandan.

La conciliación, la unidad y la prevención de choques entre sectores populares requieren de todo el apoyo que puedan prestar las instituciones sociales no subordinadas y secuestradas estatalmente.

No hay que perder de vista que la propensión a los choques violentos se ha incrementado sin tregua. La base mínima de procesos de diálogo y pacificación es la única referencia democrática vigente, es decir, la plena vigencia de nuestra atropellada y vulnerada Constitución Política, debido a su contenido en materia de derechos y su línea de democracia plural e intercultural.

El vacío de propuestas económicas gubernamentales viene acompañado por una magnificación de las prácticas prebendales y corruptas. Al mismo tiempo, la administración de justicia bate cualquier marca previa de degeneración y subordinación al poder y amparo de la impunidad.

Las propuestas masista y de CC de reformas del Órgano Judicial podrían quedar muy cortas frente a lo que ocurre en esta esfera. Tendrá que verse el alcance y la congruencia del positivo avance que supone haber abierto un espacio de consulta con especialistas, incluyendo a figuras ajenas al gobierno.

## El caudillo insomne

La paradoja actual es que la resistencia popular, incluso la más independiente, puede ser asimilada por la única opción política que buscará capitalizar el debilitamiento gubernamental. Esta posibilidad es la que prepara con su frenético activismo Juan Evo Morales Ayma, a título de fortalecer su partido. Conscientemente o no, acumula fuerzas para presentarse como alternativa a una administración (es decir la de Arce Catacora) que sería acusada de haberse alejado del evismo.

A pesar de su gran influencia en el gobierno, expresada en la cuota de altos cargos que se ha distribuido entre sus seguidores incondicionales [^ano_2020_3-14] y su capacidad de imponer decisiones, así como su control completo de la maquinaria partidista, Morales se esfuerza por simular distancia.

[^ano_2020_3-14]: La elección del exvicepresidente y del ministro represor de la marcha del TIPNIS como acompañantes en su retorno debe leerse como toda una declaración política y un plan de acciones futuras.

La exacerbada pugna corporativista, estimulada por la menor disponibilidad de recursos fiscales, amplía sin tregua su capacidad de arbitrar las disputas internas y manipularlas a su favor. Así, ante el recrudecimiento de los problemas podrá acusar a sus colegas de no saber administrar el poder y podrá autoproponerse como solución, inclusive mediante una elección anticipada.

En una palabra, la suerte del MAS sigue estando en sus manos y no en las de otros, de modo que, como antes, el único factor capaz de afectar este balance es la movilización social espontánea.

::: {style="text-align:right; font-weight: bold;"}
Diciembre de 2020
:::

## Notas
