---
lang: es
format: 
  html:
    page-layout: article
---

# Burguesías estatales y la violencia *in crescendo* {.unnumbered}

El MAS necesita convencerse de que "a quien madruga Dios lo ayuda". Y si eso falla, ¿para qué está el poder? Sin embargo, el lanzamiento de su enésima ofensiva ---adelantar las primarias para la elección de binomios presidenciales--- agita mucho a sus eventuales contendores partidarios, pero no revierte la inexorable declinación de preferencias y aprobación que reportan los estudios de opinión, en un ya dilatado lapso que dura varios meses. En otros términos, de tanto tender emboscadas, se asoma el MAS a la posibilidad de emboscarse a sí mismo.

No descansa ni un instante, y ya prepara la elección del Fiscal General, aumentando las sospechas de que busca a alguien que se preste a blindar a los altos funcionarios del Ejecutivo y allegados, más que a la persona mejor calificada para defender los intereses de la sociedad y el Estado. Para fastidio de los aludidos, eso no impide que disminuya la sucesión y multiplicación de denuncias y señalamientos sobre todo tipo de irregularidades. El patético consuelo oficial parece ser que por cada diez que atañen al partido gobernante, aparecen unos cuantos contrafuncionarios opositores en las parcelas de poder que estos administran. Las informaciones son tan constantes que predisponen a los ciudadanos a asumir que *dondequiera que haya un político profesional es seguro que se encontrará un entuerto* [^ano_2018_2-1].

[^ano_2018_2-1]: Que es la opinión muy mayoritaria que se tiene en las encuestas sobre los partidos políticos.

Destaca también en la coyuntura la información sobre el incremento de superficie cultivada de coca que brinda la oficina especializada de Naciones Unidas, que habitualmente se expresa con suma cautela al respecto [^ano_2018_2-2]. Con tales antecedentes, puede comprenderse cómo y por qué este tema ocupa tan importante y duradera franja de la escena central, disputando titulares en una coyuntura en la que los destapes de corrupción política cunden como hongos en el país y el continente [^ano_2018_2-3].

[^ano_2018_2-2]: Véase el informe completo en: <http://www.unodc.org/documents/bolivia/2017_Bolivia_Informe_Monitoreo_Coca.pdf>

[^ano_2018_2-3]: Es bueno recordar que el impacto electoral de las denuncias sobre tráfico de drogas vinculado al poder es casi nulo, aquí y en cualquier otro país donde se ha intentado usarlas con tales fines.

Lo que sobresale tan pertinazmente es que las preferencias y privilegios estatales hacia los cultivos y actividades paralelas que los acompañan están sólidamente arraigados para el Chapare, en abierta contraposición con la zona yungueña. En esta región se está desarrollando el conflicto de la Asunta [^ano_2018_2-4], que suma bajas humanas (incluyendo el asesinato de un oficial de Policía y por lo menos dos cocaleros al 30 de agosto de 2018), poniendo sal en heridas previas entre los campesinos de esa región y el gobierno masista.

[^ano_2018_2-4]: La Asunta no cabía en la franja etiquetada de "tradicional" en la legislación anterior y, de acuerdo a las estimaciones oficiales, alberga unas 6.600 hectáreas de cocales, que equivalen al 41% de toda el área de producción de Yungas. De estas, al menos 2.000 son completamente ilegales, de acuerdo a las autoridades. La superficie sembrada en la Asunta equivale a cerca de un 80% del área legal que se autoriza al Chapare. Véase: <https://n9.cl/j39s1>

## Gastos y negocios imperiales

En este tiempo, la explosión de reclamos y movimientos ciudadanos o del periodismo de investigación están poniendo al descubierto que muchos (demasiados) gobernantes de nuestros países, y no solo los que ocupan los más altos cargos, erogan gastos y acumulan fortunas abultadas, tan prominentes y dominantes que, con propiedad, se las puede llamar imperiales.

La rapidez y la masividad con que los capitales fluyeron generosos a las arcas estatales, gracias al prolongado ciclo de superprecios de nuestras exportaciones, contribuyó mucho a que, a la sombra de fulgurantes negocios públicos y privados, se amasaran con gran velocidad opíparos patrimonios de contratantes y contratistas de grandes obras. Sin olvidar que múltiples investigaciones que se remontan a épocas previas, cuando los ingresos eran discretos y magros los presupuestos [^ano_2018_2-5], ratifican que la tradición de grandes asaltos a las arcas estatales tiene una larga trayectoria.

[^ano_2018_2-5]: Un ejemplo es el del expresidente nicaragüense Alemán Lacayo (1997-2002), considerado por Transparencia Internacional como uno de los diez mandatarios más corruptos de esta época.

Las investigaciones del "Lava Jato" en Brasil o, antes, las de la Sociedad Química y Minera de Chile, han mostrado en los últimos años que los pactos entre políticos y empresarios superaron hace mucho las barreras entre oficialistas y opositores. Desde cualquier posición o membrete ideológico, los profesionales de la política se han estado arreglando para percibir una cuota de aporte empresarial, especialmente ahora que las participaciones tienen, como se dijo, dimensiones imperiales.

Daniel Ortega (o "Somocita", como cabe llamarlo, atendiendo los antecedentes históricos de Nicaragua [^ano_2018_2-6]) y su consorte han subido las cotas del registro de violencia con que un gobierno, cercado por denuncias y evidencias de corrupción, se resiste a abandonar su posición de privilegio. La sangre que se está derramando en Nicaragua prueba que el uso criminal del poder público, tan ampliamente generalizado en esta fase histórica, se complementa con el ascenso de la represión como mecanismo cada vez más usual de defensa de los grandes privilegios. En los últimos tiempos, la experiencia venezolana es pionera en estas lides.

[^ano_2018_2-6]: Véase: <https://n9.cl/qske7> y también: <https://n9.cl/1cg5r>

El "Lava Jato" brasileño involucra a prácticamente todos los partidos y empresas privadas más grandes de ese país. La investigación de los cuadernos en la Argentina da indicios parecidos. En nuestro país, las sospechas de conexiones público-privadas non sanctas se inclinan nítidamente hacia las empresas chinas, que copan el espacio de las grandes contrataciones para la ejecución de obras públicas [^ano_2018_2-7] durante los años de los superingresos estatales.

[^ano_2018_2-7]: Desde luego que no faltan las excepciones, como la prófuga compañía española encargada de construir el importante proyecto hidroeléctrico de Miguillas, en La Paz.

Que las principales empresas públicas bolivianas hayan manejado 75.000 millones de dólares en menos de una década [^ano_2018_2-8] ---es decir, el 35% de los presupuestos generales correspondientes a ese período---, permite comprender con mayor facilidad la soltura y magnificencia del gasto, canalizado en parte a obras-homenaje, como el palacio presidencial boliviano, con su modesto "cuarto y su camita", que es la manera en que el vice García describe las instalaciones dedicadas al solaz y relax del jefe de Estado [^ano_2018_2-9], y "sin lujo alguno", según asevera el ministro de la Presidencia [^ano_2018_2-10].

[^ano_2018_2-8]: Véase: <https://n9.cl/kdoff>

[^ano_2018_2-9]: Véase: <https://n9.cl/gslvq>

[^ano_2018_2-10]: El sentimiento de sobreabundancia, pese al notable descenso de alto impacto entre 20142017, se expresa en alguna medida en las prácticas displicentes y descuidadas que condujeron a la pérdida de la medalla presidencial en los días de fanfarria y desfiles cívicos.

Los 42 millones de dólares que Bolivia ha aceptado pagar a Quiborax-Non Metallic Minerals, como coronación de un prolongadísimo arbitraje del CIADI del Banco Mundial, puede parecer una cifra discreta comparada con las múltiples denuncias sobre contrataciones directas por varios centenares de millones de dólares del régimen boliviano.

Sin embargo, el caso Quiborax-Non Metallic Minerals merece ser mencionado en este capítulo, porque la amplia información difundida en las semanas del debate deja claro que pudo resolverse con menos del 10% de ese monto, en algunos tramos de las tortuosas negociaciones entre el Estado y la firma (fraudulentamente) chilena. Esta es la versión de la defensa de Carlos Mesa, sobre cuyas espaldas quiere descargar el oficialismo toda la culpa de lo ocurrido.

## Movimientos electorales y movimientos sociales

Precisamente la combinación de movimientos tácticos gubernamentales para diluir sus responsabilidades en el pago de la onerosa multa, combinándolos con la búsqueda de beneficios electorales, sigue dejando abiertas varias interrogantes sobre la correlación interna de fuerzas en la cúpula gubernamental y la manera en que trata de neutralizar la protesta ciudadana, convertida hoy en un auténtico movimiento social que cuestiona la dolosa [^ano_2018_2-11] habilitación del binomio masista.

[^ano_2018_2-11]: Dolosa desde el punto de vista constitucional, porque según el expresidente y hoy principal encargado jurídico del caso marítimo, Eduardo Rodríguez Veltzé, al opinar que debe prevalecer el poder constituyente del pueblo (en este caso, el ejercido en el referendo de febrero 2016). Véase: <https://n9.cl/7rhgq>. Ninguna reforma a la CPE puede aprobarse sin consulta popular. Según la CPE, el TCP carece de facultades para alterar o *corregir* la CPE, como lo ha hecho con el artículo sobre reelección y con otros relacionados y, especialmente, con el 7o, que reconoce el carácter inalienable e imprescriptible de la soberanía del pueblo.

Si el mandato popular expreso de que los actuales mandatarios no deben ser registrados ni inscritos como candidatos ante las autoridades electorales [^ano_2018_2-12] era un fallo irrevocable e inapelable en 2016, reafirmando la prohibición expresa del art. 168 de la CPE, en octubre del año siguiente se convirtió en movilización ante las amenazas gubernamentales de que habría un segundo tiempo, y en movimiento social cuando el TCP emitió su aberrante sentencia por la que usurpa las funciones del soberano y se arroga la capacidad de modificar la CPE y anular el resultado del referendo del 21F [^ano_2018_2-13].

[^ano_2018_2-12]: Esa es la prohibición del texto constitucional, que no se refiere a postulación alguna, ya que dicho término simplemente significa que alguien puede ser *propuesto* como candidato por alguien más.

[^ano_2018_2-13]: Llamo movimientos sociales a las acciones masivas y espontáneas que cuestionan políticas públicas y decisiones estatales o plantean propuestas, derechos o reivindicaciones, por encima ---y muchas veces, completamente al margen--- del sistema de representación política (compuesto principalmente por partidos, asociaciones corporativas como sindicatos, cámaras empresariales y/o todo tipo de estructuras gremiales). Son, pues, muy diferentes de las organizaciones sociales (sindicatos y otro tipo de organizaciones corporativas). Estas últimas son exclusivas de un sector, son jerárquicas, permanentes, verticales, con tendencia a la burocratización y, frecuentemente, al caudillismo. En contrapartida, los movimientos sociales son temporales, poco estructurados, con tendencia a la improvisación y la horizontalidad de sus relaciones internas. A veces son tan amplios y fuertes, que albergan momentáneamente a organizaciones sociales, o inclusive responden inicialmente a su convocatoria, pero pronto la superan y subordinan. Ejemplos de organizaciones sociales: federaciones de fabriles, campesinos, constructores, federaciones y confederaciones de productores o empresarios. Ejemplos de movimientos sociales: Coordinadora del Agua, resistencia civil al "gonismo", resistencia al gasolinazo del MAS, marchas indígenas, resistencia al Código Penal.

Antes de establecer las precisiones de los términos, se estaba analizando la maniobra gubernamental que provoca e impulsa a Carlos Mesa a convertirse en un candidato condicionado y rehén del régimen. El juicio iniciado en su contra sirve tanto para hacer crecer la preferencia hacia su eventual candidatura (por solidaridad ante una víctima), como para frenarla, por desgaste (la corrupción que se proyecta sobre ella) o en seco (anulándola mediante un juicio). Y es que al congelar la fase parlamentaria del juicio que se ha impuesto, luego de que la Fiscalía gatillase el inicio del proceso, este puede revocarse si el jefe del Estado y la cúpula del gobierno y del MAS así lo deciden.

Debe sumarse a lo anterior el adelanto de las elecciones primarias, que tiene la intención de convencer al público de que las elecciones con binomio oficialista ya están en marcha y no se detendrán. En este escenario, la presencia de una candidatura como la de Mesa le da mayor credibilidad al espectáculo electoral, porque los otros contendientes aparecen, de acuerdo a todos los sondeos, descalificados antes de las eliminatorias. Además, como se ha dicho, los juicios que penden sobre las cabezas de todos ellos pueden sacarlos de carrera si es que la jefatura del MAS así lo decide.

El diseño es verosímil, pero no explica los aparentes encontronazos, por ejemplo, entre el apuro de la Fiscalía y el abrupto anuncio de que "Mesa podría estar tranquilo, porque los plazos no dan para condenarlo" (según el expresidente del Senado y, a continuación, según el vice). Tal vez no llegue a dilucidarse pronto si se trata de un guion concebido con anterioridad o de fricciones entre fracciones (la del vice con algún ministro, por ejemplo), pero su efecto no parece garantizar que los resultados de la escenificación sean necesariamente los mejores para el binomio oficial.

## Poder contra poder

La decisión del Legislativo y del Ejecutivo de promulgar la Ley de Organizaciones Políticas (LOP) y de ignorar la enfática y reiterada recomendación del Tribunal Supremo Electoral (TSE) de no convocar a primarias partidarias hasta 2024 se inscribe perfectamente en el recetario previo.

La dirección masista parece convencida de que anticiparlas le asegurará la ansiada inscripción de su fórmula en plazos que ahorren cualquier sorpresa, en caso de que parte de los vocales la rechacen tan cerca a las elecciones como en junio de 2019, que es el mes en el que el TSE se hubiese pronunciado sobre si admitía o no la inscripción del binomio oficial.

Tiene, además, la seguridad de que las primarias de enero de 2019 jaquean a los partidos opositores, que no saben bien cómo enfrentar plazos tan breves para sus farragosas negociaciones en búsqueda de una opción que no reitere sus previas derrotas y humillaciones. Igual o más importante es que no solo las primarias, sino también la LOP, en texto y espíritu, cierran la puerta a la participación de actores como los colectivos y plataformas, que han adquirido un protagonismo tan importante en los últimos años.

Al ejecutar su movimiento táctico, la confianza del régimen exhibe una cota alta, porque se siente dueño de una cómoda mayoría incondicional en el TSE, apuntalada por los dos tercios (o más, por la alta permeabilidad al transfugio de la parte opositora) que controla en el Parlamento [^ano_2018_2-14].

[^ano_2018_2-14]: El anuncio afirma que el TSE considera de "cumplimiento igualmente obligatorio" el resultado del referendo constitucional y la inconstitucional sentencia del TCP, con lo que deja en el aire un enorme signo de interrogación sobre cómo resolverá tan flagrante contradicción.

La imagen de uno o más órganos estatales confrontados con otro se ha destacado en los últimos días invernales del año. Tiene mucho de espejismo, porque, tal como se anotó, la aritmética es inapelablemente favorable al MAS en la ALP y en el TSE. Pero el quid está en que cuando se trata de dinámica política y social, la aritmética es muy importante, pero no siempre decisiva.

La abrogación del Código Penal se lo demostró a los gobernantes, así como la impuesta elección y posesión de los magistrados del MAS en la elección judicial se lo prueba a la ciudadanía, que, con su voto ultramayoritario de repudio, expresó su voluntad de que tal cosa no ocurriera.

Una debilidad de forzar las fechas para elegir binomios partidarios podría ser que, si se hace pública la negativa de una fracción de vocales del TSE de inscribir al binomio oficial, esto pueda convertirse en un inesperado estimulante de la resistencia ciudadana, revitalizando su movilización [^ano_2018_2-15].

[^ano_2018_2-15]: No es fácil en principio que un acto preparatorio electoral ---que puede parecer muy abstracto y ajeno a las preocupaciones cotidianas del público--- genere una eclosión de protestas de las dimensiones y la constancia que provocó otro hecho abstracto, como la aprobación del Código Penal. Podría ocurrir, como sucedió en ese caso, que el repudio a las primarias (tan forzadas) sirva de paraguas para cobijar la insatisfacción de múltiples sectores, debido a ofensas, negación de pedidos o agresiones directas del Ejecutivo contra ellos.

Si impugnar la maniobra de las primarias es un canal para expresar un malestar multisectorial, puede precipitar la salida (renuncia o expulsión) de uno o más vocales de la TSE. Esto desportillaría la imagen del proceso electoral y, eventualmente, aumentaría el número de posibles candidatos alternativos para una ciudadanía que no se afilia con ninguno de los tradicionales y que resiente las dubitaciones y contradicciones del expresidente Mesa sobre su eventual candidatura.

## Colchón y campaña

Uno de los aciertos gubernamentales menos reconocidos y asimilados por sus críticos es la acumulación de ahorro bajo la forma de reservas internacionales netas (RIN) que, a pesar de que han estado mermando lenta y continuamente desde 2014 (por la caída de los precios de nuestras exportaciones), mantienen un nivel expectable [^ano_2018_2-16] que le da una estabilidad notable a nuestra economía, frente a los fuertes bamboleos de las divisas de varios países [^ano_2018_2-17] y el acelerado deterioro de la argentina y la brasileña en América Latina o la turca y la rusa en otras latitudes.

[^ano_2018_2-16]: Véase: <https://n9.cl/ojegt>

[^ano_2018_2-17]: Véase: <https://n9.cl/7w9n8>

Inclusive si se acepta como acertada la explicación de que el haber atesorado las RIN debe atribuirse más a los rudimentarios y complicados sistemas estatales de gasto que a una metódica y estratégica previsión [^ano_2018_2-18], actualmente este "colchón", como parte de la ecléctica política monetarista con toques keynesianos (alta inversión pública y medidas redistributivas), continua rindiendo réditos a los administradores del Estado, especialmente cuando se compara con varios de nuestros vecinos.

[^ano_2018_2-18]: Según Juan Antonio Morales, expresidente del Banco Central de Bolivia, en sus columnas y en entrevista personal.

Se sabe que el gran límite de tales logros es el práctico inmovilismo del patrón de acumulación, así como la marcada ineficiencia para avanzar de manera suficiente y sosteniblemente y con la calidad necesaria en la atención de los servicios esenciales (educación y salud, principalmente). A ello debe sumarse la disminución relativa de capacidades productivas que está determinando una creciente pérdida de seguridad y soberanía alimentaria [^ano_2018_2-19], entre otros efectos altamente perniciosos.

[^ano_2018_2-19]: Véase: <https://n9.cl/fgkl1>

El mayor daño que causa el anclaje de nuestra política económica en la matriz desarrollista y dependiente de riquezas naturales no renovables, es que su completa obsolescencia retrasa cada vez más al país en sus capacidades para responder a desafíos mayores, como el cambio climático, que exigen un nuevo patrón de acumulación, con base a la priorización de uso y cuidado de los recursos renovables y un cambio sustantivo en la infraestructura productiva [^ano_2018_2-20].

[^ano_2018_2-20]: Véase: <https://n9.cl/p4nmy>

La prevalencia de actitudes básicamente pragmáticas y el temor a la innovación y a la incertidumbre que suelen prevalecer como actitudes determinantes del electorado constituyen ventajas de inicio con las que sigue contando el partido de gobierno, como ocurrió previamente.

Lo mismo aplica a las visiones y prácticas con las que la mayoría del electorado asocia a la oposición partidista tradicional, principalmente en el área económica; desde las cámaras empresariales y por la mayor parte de los especialistas conocidos se predican las más conocidas y rechazadas fórmulas de ajuste estructural. El hecho de que los opositores partidarios no cuestionen el patrón de acumulación vigente y carezcan de propuestas alternativas empaña el horizonte del país de forma aparentemente indefinida.

Las medidas económicas que se ofrece en la campaña reforzarán un tipo de discusión completamente favorable al oficialismo, porque las críticas a sus evidentes deficiencias no tienden a volcar electores en su contra, sino al contrario: el innegable malestar ante la descomposición y los abusos puede atenuarse por el temor a cambios traumáticos, al estilo de los impuestos por Macri o Temer.

Ante la ausencia de una auténtica confrontación entre diseños y horizontes económicos y sociales diferentes, el conservadurismo favorable al régimen no solo se sostiene, sino que adormece la capacidad social de reaccionar ante los grandes riesgos que supone la ejecución del programa económico del MAS (Agenda 2025) con su alto nivel de gasto, sus inversiones descomunales e improductivas y su tendencia al endeudamiento.

## Espectro de violencia

El tiempo que transcurre entre la aprobación de la LOP y la inscripción de binomios incrementará las tensiones en todos los frentes, con la posibilidad, en ascenso, de que el uso de la fuerza que impuso el MAS con el golpe contra la Constitución ejecutado por el TCP el año pasado, se reitere y agudice, como lo ejemplifican la tónica con que el régimen afronta los conflictos sociales y el incremento de amenazas y exacciones para los que se atrevan a retarlo [^ano_2018_2-21].

[^ano_2018_2-21]: Los vocales electorales que se atrevan a plantear que la fidelidad a la CPE y que la voluntad soberana expresada democráticamente está por encima de sentencias manipuladas se arriesgan a enfrentarse con una implacable persecución, anunciada públicamente. Véase: <https://n9.cl/es/s/gkid0>.

En la misma situación están los colectivos y activistas del *Bolivia dijo No y Respeto al 21F*, a los que el gobierno y su CONALCAM se proponen confrontar directamente en la calle, durante las movilizaciones convocadas por el Día de la democracia el próximo 10 de octubre [^ano_2018_2-22]. Este medir fuerzas se acompaña con los primeros esfuerzos de replicar las tácticas divisionistas con que el régimen ha doblegado a la disidencia, esta vez la de las organizaciones sociales no subordinadas al gobierno, que han anunciado su intención de constituir una Central Obrera Boliviana (COB) paralela.

[^ano_2018_2-22]: El endurecimiento de los planos señalados se acompaña con la sustitución de altos funcionarios, sospechosos de alguna forma de tibieza, por halcones como los nuevos Canciller y presidente del Senado, que podrían reforzarse con otros que están ahora en la *banca de suplentes*.

La posibilidad de que los choques sean cada vez más físicos y menos simbólicos es la tendencia central que rige durante los últimos meses de este año. La resistencia social espontánea, más conectada a colectivos y plataformas que a partidos [^ano_2018_2-23], experimentará con la mayor crudeza conocida la decisión estructurada, financiada y respaldada por los aparatos estatales de imponer las reglas con las que el régimen quiere enraizarse de manera inextirpable.

[^ano_2018_2-23]: Las mayores vulnerabilidades de estas agrupaciones son su carácter exclusivamente urbano y una completa heterogeneidad ideológica, con cierta tendencia al conservadurismo político entre sus cuadros más conocidos, que suelen ser exdirigentes o exmilitantes mayores de 50 años de edad; los más jóvenes tienden a aparecer solo en los picos de las movilizaciones. Las aún pocas conexiones con sectores indígenas y campesinos es otro flanco a tener en cuenta. La abreviación de plazos electorales disminuye sus posibilidades de condicionar o subordinar las rutinas, prácticas y estilos de los partidos que nuclean a los profesionales de la política.

Por todo ello, en este lapso se podrá verificar lo acertado o erróneo de la aseveración ---también sustentada en estos análisis--- de que las características históricas de la sociedad boliviana y sus tradiciones de lucha popular marcarán una nítida diferencia con las demás experiencias por las que los pueblos de nuestro continente intentan recuperar el pleno ejercicio de sus libertades, derechos y garantías a través de mecanismos democráticos y pacíficos.

::: {style="text-align:right; font-weight: bold;"}
Agosto de 2018
:::

## Notas
