---
lang: es
format: 
  html:
    page-layout: article
---
# Desarrollismo versus pueblos indígenas {.unnumbered}
---

Una marca que mantiene imbatible el MAS es su capacidad de sostener una constante iniciativa política, que destaca en la escena debido a la perpetua reactividad de sus oponentes.

La rutina ha vuelto a repetirse durante los últimos cuatro meses en los que la reiteración, aceleración y amplificación del destape de negocios turbios [^1] que comprometen a altos funcionarios no frena que se introduzcan (o reiteren) propuestas y acciones del oficialismo que mantienen ocupados a quienes difunden noticias y acoquinados a quienes las padecen.

De todas, destaca por sus ecos y proyecciones la nueva ofensiva sobre el Territorio Indígena y Parque Nacional Isiboro Securé (TIPNIS), que ha culminado con la aprobación de una ley que anula los acuerdos que se dieron entre Estado e indígenas con la VIII marcha que llegó a la ciudad de La Paz en 2011, después de la represión que sufrieron en Chaparina.

La “desintangibilización” del TIPNIS tiene la peculiaridad de que no solo se impone en la coyuntura, sino que la conecta con el largo plazo porque resume y representa la propuesta programática, la visión de país y la política masista, al condensar la estrategia contenida en la Agenda 2025 y empalmarla con la habilitación de la candidatura y reelección del actual presidente.

Desmenuzar esta nueva ley permite una excepcional oportunidad de ver y entender los planos temporales y acciones concretas de la visión política hegemónica en Bolivia.

## Del paquetazo eelctoral a la ofensiva estratégica

En el semestre que va desde la aprobación de la Ley General de la coca hasta la de la Ley 969, que “anula la intangibilidad del TIPNIS” [^2], se han acumulado decisiones gubernamentales propias de una gran contraofensiva táctica, orientada a anular y revertir la derrota sufrida un año atrás y despejar la ruta que rehabilite al presidente como candidato en las próximas elecciones nacionales.

Las acciones legislativas y administrativas [^3] que conforman la columna vertebral de esa contraofensiva apuntan a reaglutinar y vigorizar el núcleo central de la base social del MAS, resquebrajado por incumplimientos de compromisos estatales y pugnas internas del partido dominante. En segundo término, buscan afinar la fachada institucional que consumará la maniobra destinada a anular los resultados del referendo constitucional de 2016.

Durante los últimos cinco años, la cúpula gobernante manifestó de diversas formas su inquietud por un sentimiento de deuda con los colonizadores [^4] y por el retraso de uno de sus planes más preciados, al haberse visto obligada a postergar el proyecto de carretera a través del TIPNIS por la marcha indígena de 2012. Esa traumática experiencia fue vivida como un retroceso simbólico y material inaceptable que tenía que revertir más temprano que tarde.

En cuanto a los cooperativistas mineros, las derivaciones del cruento levantamiento con que hace un año pretendieron imponer sus reclamos corporativos necesitaban con urgencia una conciliación y reparación de daños. Así, en aparente compensación por la dureza de su choque con la directiva de FENCOMIN después del asesinato del exviceministro Illanes, el gobierno anuncia que dispondrá de 500 millones de dólares para la prospección de nuevas áreas que otorgar a las cooperativas [^5].

Cooperativistas y colonizadores (cocaleros incluidos) han actuado como mazo y yunque del régimen en batallas decisivas, en las que la capacidad de movilización ha sido el elemento clave. De modo que, al haber facilitado al gobierno proseguir con sus nuevos desafíos, se hacía impostergable atender los principales problemas pendientes con ambos [^6].

En el espacio institucional, la preparación de las elecciones judiciales, ahora reprogramadas para diciembre de este año, exhibió desde su convocatoria la vacuidad de la retórica oficial desplegada por meses. Tanto en la cumbre judicial como en múltiples otras tribunas públicas, se intentó mostrar que, a diferencia de 2011, el procedimiento haría énfasis en los méritos profesionales y académicos y que se superaría el sectarismo, que caracterizó la calificación de candidatos en la experiencia anterior.

El temprano repliegue de la universidad pública paceña (UMSA) del espacio que se otorgó a las universidades para participar de la selección y calificación de aspirantes a candidatos se respaldó en denuncias de parcialidad del proceso. Con esta y otras evidencias, quedó claro que la mayor aspiración oficial sobre estas elecciones es que el nuevo plantel de altos magistrados ayude a olvidar la patética historia de sus predecesores [^7]; asimismo que, en lo posible, los nuevos funcionarios resulten algo más creíbles, dada la gravedad de las decisiones que el Ejecutivo ha dispuesto que asuman.

## El segundo asalto al TIPNIS

La importancia central de la batalla por el TIPNIS parte de la hipótesis de que en esta se concentran las mayores contradicciones del nuevo ciclo estatal: la definitiva cancelación del proyecto de construir un Estado plurinacional. Esto pesará decisivamente sobre la definición de las tendencias que determinarán el rumbo del país durante no menos de una década. Hasta ahora, el desenvolvimiento del debate público sobre el tema ha sufrido una simplificación extrema, dejando de lado explicaciones que abarquen lo que realmente entraña esta prolongada confrontación.

Del lado oficial, se ha tratado de explicar la situación como si se tratara de la resistencia de los “aliados internos del imperialismo”, quienes, bajo un ropaje de ambientalismo colonial, tratan de salvar los intereses de potencias externas que nos habrían impuesto la creación de reservas naturales en su propio beneficio. También estarían los intereses de hacendados (principalmente madereros y ganaderos), que ya no podrían esconder su presencia, ni el vasallaje que al que estarían sometiendo a los pueblos indígenas.

Según este relato, la carretera a construirse permitirá, además, atender las necesidades básicas de esos pueblos y, gracias a la integración de Beni y Cochabamba, logrará un manifiesto avance del desarrollo económico y social de todo el país [^8].

La oposición, especialmente la partidaria, contraataca exhibiendo las flagrantes contradicciones entre las palabras y los hechos gubernamentales en todo lo que se relaciona a su declarada devoción por la Madre Tierra y los pueblos indígenas. Estos reproches se centran en la crítica central: denunciar que el verdadero objetivo de la nueva legislación sobre el TIPNIS sería abrir espacio a nuevos cultivos de coca [^9].

Como un complemento, desde la izquierda —en lo que podría interpretarse como un intento de contrarrestar la postura antiimperialista del gobierno— se pregona que la carretera a través del TIPNIS sería una imposición imperialista, principalmente de Brasil.

Las críticas al extractivismo gubernamental, así como la confrontación entre modelos de desarrollo, han estado presentes desde muy temprano, pero son las que reciben menor atención periodística e informativa.

Lo que prima en el espacio público son las descalificaciones del gobierno al ambientalismo colonial (“cuidadores de árboles para los gringos”) y las acusaciones del predominio de los intereses cocaleros (implicando que, en el fondo, serían “narcotraficantes”) con que responde la oposición partidista, con la esperanza de que su tono moralista le permita cosechar alguna ventaja [^10].

Si existe algún componente con real peso moral que pueda generar corrientes de opinión pública, es el que alerta sobre la saña y violencia con que el oficialismo interviene, divide, persigue y manipula a las organizaciones indígenas (las que representan a los pueblos del TIPNIS, la CIDOB y sus afiliadas, tanto como a la CONAMAQ, organización de los indígenas de tierras altas).

En su vertiente más atrasada, en vez de solidaridad, algunos grupos e individuos convierten su censura en una invocación a la piedad, frecuentemente acompañada de ideas paternalistas y esencialistas.

## La montaña escondida

Los conflictos en torno al bosque de los t’simanes, la represa del Chepete o el TIPNIS nacen y proliferan como resultado del afianzamiento y la depuración del modelo de desarrollo capitalista, que ha terminado por cristalizar como la visión de gobierno [^11]. Este modelo se apoya en una política de colonización (no de cocalización) del TIPNIS en particular y, por lo general, de casi todos los territorios indígenas, así como de las reservas naturales. Esto es parte de la Agenda 2025 (o “agenda patriótica”), que establece el compromiso de ampliar la frontera agrícola como eje central del modelo de desarrollo y de construcción de país. Esa agenda es, además, el principal justificativo del MAS para plantear una nueva reelección presidencial.

Así, el programa para la reelección da por supuesto que ampliar la frontera agrícola fortalecerá automáticamente la seguridad y la soberanía alimentaria, y que el desmonte sería la única manera de lograrlo, eliminando toda consideración sobre el rescate y rehabilitación de las extensas áreas que se han depauperado, erosionado y desertificado por las malas prácticas agrícolas [^12].

Esta política territorial y de redistribución poblacional que se viene realizando por lo menos desde 2008, con el masivo traslado de familias colonizadoras a Pando [^13] y, secundariamente, al Beni (con fines principalmente electorales en ese momento), busca replicar, reforzar y sacar partido del modelo espontáneo de migraciones campesinas internas que primó de 1952 hasta finales del siglo XX. Esta migración campesina desde las tierras altas consolidó el control interno del territorio, modificó la distribución demográfica, la geografía política y la influencia de patrones culturales.

Los colonizadores —ya que no interculturales, que somos todos los habitantes del planeta—, es decir, los campesinos migrantes que buscaban mejorar su producción, ingresos y perspectivas de futuro, jugaron así un rol protagónico en la ampliación y consolidación del mercado interno y favorecieron indirectamente la expansión de la influencia estatal, que se instalaba detrás de los migrantes.

Desde finales del siglo XX, la búsqueda de tierras para la sobrevivencia —que caracterizó a las corrientes colonizadoras iniciales— se ha ido combinando con movimientos orientados a hacerse de tierras para ampliar el mercado de tierras (alquiler y venta), especialmente en regiones aptas para el cultivo de soya y ganadería, como ha venido sucediendo en Santa Cruz durante las dos últimas décadas.

La “conquista” del TIPNIS obedece centralmente a esa lógica [^14], como presunta ruta crítica del desarrollo. Se busca replicar el modelo de ocupación de tierras, en principio por familias desplazadas por la pobreza, que abren espacio a ocupaciones mayores que, a su vez, son la plataforma de lanzamiento del mercado ampliado tierras, previo saqueo y destrucción del bosque y sus recursos.

La ampliación de la frontera agrícola bajo esta modalidad conduce a la depredación de fuentes de vida colectivas (agua, oxígeno, biodiversidad) y, con ello, a cerrarle el paso a un patrón de acumulación diferente, con base en el uso equilibrado de esas fuentes, cada día más escasas y valiosas a nivel del planeta. La que impulsa el gobierno se inclina, más bien, por repetir los intentos de un tipo de desarrollo ensayados infructuosamente desde nuestra declaración de independencia.

El significado profundo y las proyecciones del triunfo gubernamental (Ley 969) permanecen todavía poco visibles, cubiertas por la densa humareda de debates tan vehementes como estériles, que se resisten a asimilar que la corrupción gubernamental radica principalmente en los procesos de contratación de grandes obras públicas, de otorgación de licencias ambientales, en el manejo discrecional de instituciones recaudadoras, en el manejo partidista de la justicia y en la acumulación de rentas y beneficios ilegales para financiar su actividad política y mantener la fidelidad de sus clientelas.

Este fenómeno mundial, que estalla en escándalos como los de Odebrecht, explica mejor el comportamiento de los gobiernos que las teorías conspirativas, que sugieren que se deben a las influencias del “crimen organizado”.

La forma en que interactúan el gobierno y la oposición partidista sobre el TIPNIS muestra que el presunto antagonismo entre ambos es básicamente ficticio, porque unos y otros comparten una visión muy parecida de modernidad, mercado y desarrollo. Sus verdaderas discrepancias en cuanto a modelo económico, forma de distribución del excedente, relaciones internacionales y concepciones sobre lo democrático son insuficientes para distinguirlas en un plazo lo suficientemente largo.

Su cotidiano enfrentamiento por empoderar a los distintos sectores corporativos que representan y por mantener o capturar el poder político puede llegar a extremos violentos, sin por ello convertirlos en representantes de modelos de sociedad antagónicos.

## El colapso del Estado Plurinacional

La política aplicada al TIPNIS, al bosque del pueblo t’simane y la que se proyecta para las tierras comunitarias de origen (TCO) en el área de influencia del Chepete es parte del corporativismo y el estatismo [^15], que han bloqueado definitivamente construir la estatalidad plurinacional, proclamada en nuestra Constitución. La invasión, colonización y expropiación de territorios indígenas en favor de fracciones enriquecidas, especuladoras de tierra y que trafican con su influencia política, cancela la posibilidad de construir un Estado basado en el respeto por los territorios de pueblos indígenas, en la pluralidad económica y democrática, en la construcción y respeto de autonomías (sociales y territoriales), la participación ciudadana y el control social.

La jerarquización de intereses sectoriales propia del corporativismo premia a los afines y penaliza a los adversos, con lo que incrementa la división interna de la sociedad. A tal punto, que los sujetos sociales (campesinos e indígenas) que motorizaron el proceso constituyente y que le dieron contenido y fisonomía a la reforma estatal —hasta el extremo de que el plan estratégico del gobierno se orienta a materializar una contrarreforma agraria que terminaría por aniquilar a los pueblos originario— son definidos en el artículo segundo de la CPE como los sujetos históricos por excelencia.

De acuerdo a declaraciones oficiales sobre los resultados del saneamiento de tierras, a concluirse este año, se atribuyen 38 millones de hectáreas a “campesinos, pequeños propietarios y colonizadores”, 26 millones de ha a las TCO de pueblos indígenas y 17 millones de ha al “sector empresarial”.

El área que corresponde a las TCO viene siendo declarada por la CSUTCB, el presidente Morales y su vice, como excesiva respecto a la población que alberga, e “injusta” si se la compara con la masa campesina que representa de 10 a 15 veces la primera [^16]. Tal enfoque considera idénticas las áreas aptas para a la agricultura y las de los bosques, y refuerza la visión señorial y patronal que ha caracterizado tradicionalmente a las TCO como “tierras vacías”.

## Una fortaleza que transita a debilidad

El modelo que supone que la producción de alimentos (o energía) es antagónica a la investigación y uso de las fuentes de vida (oxígeno, agua apta para el consumo, biodiversidad) es ampliamente dominante entre el espectro de los políticos profesionales (tanto militantes partidarios como dirigentes sociales y sindicales), ya sean oficialistas u opositores, y entre los principales grupos empresariales.

Su visión, apegada a la explotación intensiva de recursos, no llega a comprender que las fuentes de vida son bienes cada vez más escasos y valiosos en el planeta, y que pueden convertirse en la base de una economía diferente a la que venimos ensayando, bajo diversas modalidades de modelos económicos (cuya distinción principal radica en el cambio de relación y predominio entre Estado y mercado) [^17].

Por otro lado, el estatismo corporativo, centralista e inclinado a formas impositivas y crecientemente represivas alcanza a exhibir congruentes actitudes nacionalistas y de insubordinación ante el imperialismo norteamericano, pero carece de recursos ideológicos y políticos para ir más allá de una economía de mercado tradicional y para prevenir que el país se desplace a nuevas órbitas de dependencia y subordinación económica y política [^18].

Es muy posible que el presidente y su estado mayor político todavía no caigan en cuenta de que preservar su política económica —una de sus mayores fortalezas, en tanto que ha conseguido sobrellevar la desaceleración mejor que la mayoría de los países vecinos— se convertirá en una trampa, si insisten en su agresivo y descomunal plan quinquenal de inversiones.

Resulta que la Agenda 2025, prácticamente ya convertida en el Plan general de desarrollo (PGDES), se propone conservar y ampliar la receta que los voceros oficiales suelen llamar “el milagro económico continental”, multiplicando la inversión pública en energía, infraestructura y producción agroindustrial. Esto solo sería posible mediante un endeudamiento masivo, a falta del flujo de capital con el que se contaba durante el ciclo de los superprecios.

Disponer de los 57.000 millones de dólares que se invertirían entre prospección y desarrollo hidrocarburífero y construcción de megarepresas para la exportación de electricidad, implica necesariamente contraer una deuda considerable. Lo mismo vale para la construcción de trenes eléctricos urbanos, la ampliación de la red del teleférico, la compra de nuevos satélites y otras megaobras.

Como ejemplo de lo que supone cumplir el programa de desarrollo de la “agenda patriótica”, su plan eléctrico se apoya en postulados propagandísticos abismalmente alejados de la realidad [^19] y en una completa omisión de las tendencias de generación de energías alternativas. Estos postulados se fortalecen, pese a importantes regresiones, como la política trumpista. La promesa de exportar 11.000 MW de electricidad generada en megarepresas se contrapone al hecho de que en 11 años de gestión no se ha modificado nuestra actual matriz eléctrica basada, en más del 70%, en la quema de gas.

El atraso en construir Miguillas, San José e Ivirizu (represas medianas) —que nos permitiría cambiar la matriz, sustituyendo la generación de menos de 1.000 MW y reforzando así la capacidad exportadora de gas— prueba categóricamente la existencia de fallas fundamentales en la capacidad de planificar y ejecutar, que no hacen sino empeorar cuando se subordinan a la visión electoralista, cada vez menos democrática, del partido dominante.

La única gran inversión futura que parece entusiasmar a inversores, la ferrovía transoceánica a través de Bolivia, ha conseguido adhesiones de países como Uruguay y Paraguay, que son actores secundarios en un proyecto que enlaza el puerto de Santos (Brasil) con Perú, pero no ha obtenido una decisión en firme de Perú y menos de Brasil. Las autoridades peruanas actuales han declarado estar dispuestas a revisar la decisión de los gobiernos de Humala y Dilma Roussef, que excluye el paso por Bolivia [^20], pero sin resultado hasta ahora.

El gobierno federal de Brasil está mucho más dubitativo, pese a que gobernadores de estados vecinos a nuestro país han expresado interés en un rediseño del trazado oficial vigente. En todo caso, medidas internas asumidas por el gobierno boliviano que Brasil considera agresivas contra él —como la aprobación de la Ley de la Coca, por cómo lo afecta el significativo crecimiento del consumo de cocaína— no abren posibilidades para mejorar en breve las debilitadas relaciones diplomáticas entre los dos países.

## Elecciones y democracia

El permanente engarce entre el programa estratégico y la táctica electoralista del MAS corre el riesgo de hacer un cortocircuito en esta coyuntura, por la repetición de un error parecido al cometido en la preparación y lanzamiento del referendo constitucional de 2016, cuando se sobrevaloró la fortaleza propia y se menospreció la de la oposición social.

El reforzamiento del bloque de aliados, comentado al inicio, más una consistente recuperación de los índices de confianza pública del presidente y vice (49% y 43%, respectivamente), la certidumbre de haber aplastado a los representantes indígenas contrarios en el TIPNIS y, finalmente, el implacable avance de la calificación de candidatos para la elección judicial de fin de año, sirvieron para que el entorno presidencial evaluara que era necesario y posible redondear los insumos positivos con una categórica exhibición de fuerza (aprobación de la nueva ley sobre el TIPNIS), para rematar con una elección de magistrados estrechamente controlados, que ayudará en el futuro próximo a anular los resultados del 21F [^21].

La convergencia de conflictos muy diversos (TIPNIS, cocaleros de Yungas y Achacachi, con la teatral reaparición del Mallku), aunados por un común rechazo a la imposición, a que se aplaste adversarios, a la impunidad de militantes propios y aliados, sigue sorprendiendo al gobierno, que comienza a sospechar que incluso si consigue contener estos estallidos con cierta rapidez, le costará un gran capital político, estando tan cerca de una elección de la que ya se sabe perdedor.

Eso no lo arredra en principio, asumiendo que la valoración de fuerzas con que ingresa a ella sea correcta. Sin embargo, la nueva tendencia en que convergen los conflictos da la alerta de que los sectores hastiados con el gobierno rebasan el perímetro de las grandes ciudades y afectan con creciente frecuencia a reductos que consideraba inexpugnables. Aunque esto suceda todavía fragmentariamente, los nuevos choques atacan la imagen presidencial en sus fundamentos y comprometen, en consecuencia, las elecciones judiciales de diciembre e incluso las de 2019.

Así, los nulos y blancos, que ganarán en diciembre, como ya se sabía desde un inicio, pesan mucho más en un sentido plebiscitario sobre la gestión y la figura del presidente, ahora que están tan cercanos los efectos de los conflictos sociales.

La posibilidad de reservar al candidato Morales para una elección ulterior a la de 2019 está prácticamente cerrada, en una situación en la que forzar su candidatura es cada vez más peligroso para el MAS, debido a la resistencia social más que al fortalecimiento de sus rivales.

El carácter esencialmente antidemocrático de una elección, que elevará a la condición de nuevos altos magistrados a candidatos con un apoyo ínfimo en comparación con los votos nulos y blancos, neutraliza su credibilidad. Y, sobre todo, menoscaba profundamente a la del Órgano Electoral, que hasta ahora se siente obligado a administrar esta próxima elección sabiendo cuánto lo debilitará para presidir el gran evento de 2019.

Tratar de afrontar todos estos elementos adversos junto con el acelerado ritmo de inicio y entrega de obras, con estrechar relaciones con los sectores más afectos y con un recrudecimiento de la represión contra protestas y opositores, resulta claramente insuficiente y augura el rebrote de choques cada vez más duros y arriesgados para el gobierno.

::: {style="text-align:right; font-weight: bold;"}
Agosto de 2017
:::

## Notas

[^1]: Una buena proporción de estos episodios se relacionan con el total predominio de contrataciones directas o de la gran discrecionalidad que reciben los máximos ejecutivos para contratar “llave en mano” o EPC (Engineering, Procurement and Construction). Carreteras, plantas hidroeléctricas (Corsan), taladros, planta de polipropileno (la obra más cara en la historia boliviana, pero menos de un tercio de lo que costaría el Chepete) encabezan una larga lista de denuncias sobre las más grandes anormalidades detectadas y denunciadas.

[^2]: El entrecomillado se debe a que se utiliza aquí la nomenclatura que ha predominado en el encuadre periodístico (y que se refiere a la anulación de la intangibilidad) porque, como se desarrolla más adelante, tal denominación se presta a confusiones.

[^3]: Casi simultáneamente al tratamiento de la Ley 266, pueblos indígenas del territorio indígena multiétnico (TIM) —en que conviven los pueblos mojeño, trinitario, yuracaré, movima y t’simane o chimán— protestaron por el incremento de presiones sobre el bosque tsimán, a pesar de que se reconoció como su territorio en 1990. Estas presiones se producen al amparo de resoluciones del INRA, que pretenden convertirlos en familias colonizadoras, cada una con su dotación de 50 hectáreas. De este modo, la mayor parte de las 185.000 hectáreas de ese bosque pasaría a ser “reserva fiscal”, es decir, tierra disponible para distribuir entre nuevos colonizadores. Véase: [http://cejis.org/cinco-pueblos-indigenas-inician-movili-zacion-la-caminata-de-reafirmacion-de-nuestro-derecho-historico-sobre-el-area-del-bos-que-chiman/](http://cejis.org/cinco-pueblos-indigenas-inician-movili-zacion-la-caminata-de-reafirmacion-de-nuestro-derecho-historico-sobre-el-area-del-bos-que-chiman/)

[^4]: Llamados “interculturales” por la CPE, con la fallida intención de desvincular a este importante sector campesino (tradicionalmente familias campesinas pobres migrantes, en búsqueda de nuevas tierras de labranza) de las connotaciones que tiene el término ‘colonialismo’. Los cocaleros son la fracción menos numerosa, pero la más activa políticamente y la más consolidada organizativamente, de esa franja campesina.

[^5]: Véase: [https://notibol.com/noticia/gobierno-invierte—500-millones-para-las-cooperativas-mineras/1170321](https://notibol.com/noticia/gobierno-invierte—500-millones-para-las-cooperativas-mineras/1170321). En 2016 reclamaban por lograr un mejor régimen impositivo que el que tienen, y que se legalicen sus uniones con privadas y transnacionales en las concesiones que se les ha otorgado. Estas concesiones no son necesariamente marginales; la de Colquiri, por ejemplo, contiene una reserva estimada en unos 5.000 millones de dólares a precios de los minerales en 2014.

[^6]: Incluyendo las consecuencias del recrudecimiento de la pelea interna del MAS, entre fines del año pasado e inicios de este, entre los que se incluye el notorio recorte de poder y gravitación de la tendencia del excanciller Choquehuanca.

[^7]: En especial, la manera en que el Legislativo, acaudillado por el Ejecutivo, castigó con el mayor ensañamiento las disidencias y rebeldías de miembros aislados del Tribunal Constitucional, para dejar claro que su precio es el escarnio público de los indisciplinados, hasta el extremo de una práctica muerte civil, que es como el extribuno Cusi describió su experiencia después de haber sido defenestrado de su cargo.

[^8]: El vicepresidente del Estado es el principal responsable de esta línea argumental, comprimida en su folleto Geopolítica de la Amazonía (La Paz: Vicepresidencia de la República, 2013) y ratificada en su discurso oficial del 6 de agosto pasado. Esta narrativa carece de apoyo y referencias factuales que hagan verosímil su explicación de que grandes haciendas ganaderas y explotaciones forestales están instrumentando su oposición a la construcción de caminos, cuando en todas partes estas son sus abanderadas, ya que les son indispensables para mover su producción al mercado. Tampoco aborda la imperiosa necesidad de realizar el esfuerzo más serio y sostenido por salvar bienes escasos (fuentes de agua, oxígeno, biodiversidad) que se encuentran en las áreas que, despiadadamente, se nos habría impuesto por los grandes depredadores ambientales del planeta para inhibir, o simplemente cancelar, nuestras posibilidades de “desarrollarnos”. Desde FOBOMADE se hace una crítica detallada a la visión vicepresidencial: [http://fobomade.org.bo/2017/08/02/sobre-la-geopolitica-vicepresidencial-el-tipnis-y-el-iirsa/](http://fobomade.org.bo/2017/08/02/sobre-la-geopolitica-vicepresidencial-el-tipnis-y-el-iirsa/)

[^9]: Véase, como ejemplo: [http://www.eldeber.com.bo/bolivia/Samuel-cree-que-meta-de-Evo-en-Tipnis-es-mas-coca-20170809-0013.html](http://www.eldeber.com.bo/bolivia/Samuel-cree-que-meta-de-Evo-en-Tipnis-es-mas-coca-20170809-0013.html) El antropólogo Xavier Albó ha expresado una idea parecida. Toranzo subraya este enfoque en [http://www.paginasiete.bo/opinion/carlos-toranzo-roca/2017/8/30/coca-gran-peligro-150190.html](http://www.paginasiete.bo/opinion/carlos-toranzo-roca/2017/8/30/coca-gran-peligro-150190.html). La enorme presión que ejercen los pobladores del Polígono 7, colonizadores y cocaleros, sobre los pueblos indígenas y su persistente demanda de carretera ha llevado a absolutizar el cultivo de coca como presunta causa de los planes gubernamentales sobre el TIPNIS y otros territorios indígenas. Por todo lo anotado, se ha elaborado un anexo que figura al final de este análisis, donde se consigna información relevante sobre el tema.

[^10]: Tal expectativa tiene todas las de perder porque las acusaciones que llueven sobre el régimen desde el primer día de su ascenso no le han hecho la menor mella, ni han impedido que su votación haya subido constantemente en las elecciones nacionales, mientras que no parecen haber jugado ningún papel en su derrota en febrero de 2016. Está claro que llamar cocalero y narcotraficante al presidente y a sus seguidores puede entusiasmar a una cierta franja de electores, pero no cambia en nada el hecho de que, para que cambie el régimen, los nuevos gobernantes necesitarán atraer a una gran parte de los actuales electores del MAS.

[^11]: Escondida bajo discursos anticapitalistas, que derrocha recursos en grandes obras, obsoletas en su concepción y utilidad dentro de la actual realidad mundial. Un neocapitalismo, bravo contra el capitalismo en las palabras y generoso con él en los hechos. No en vano este régimen corresponde al período en que se han construido y prosperado gigantescos malls, shopping centers, galerías y boutiques, y con el consumismo más derrochador, alentado por el ejemplo del Estado, los altos funcionarios y una nueva burguesía burocrática.

[^12]: La acelerada expansión de frontera agrícola de la última década obedece, de lejos, a la ampliación de cultivos industriales de exportación, soya y otras oleaginosas, en tanto que la mayor producción de alimentos no se empareja con la demanda interna (estimulada también por cierto grado de redistribución y disminución de la pobreza), de manera que la importación de alimentos se ha desbocado. Véase: [https://n9.cl/wjxoq](https://n9.cl/wjxoq) y la respuesta oficial sobre este avance de importaciones en [https://n9.cl/li27r](https://n9.cl/li27r)

[^13]: Véase: [https://n9.cl/r3gw6](https://n9.cl/r3gw6)

[^14]: En 2015, el presidente Morales transparentó el fondo del problema al reflexionar en voz alta sobre la naturaleza de las prácticas del sector campesino-colonizador, del que proviene y al que representa. Véase: [https://n9.cl/t2ks2](https://n9.cl/t2ks2)

[^15]: En términos de centralización y concentración de poder, más que en contraposición de lo estatal con lo privado, esfera en la cual no puede acusarse al MAS de ejecutar o propiciar un capitalismo de Estado porque ha encontrado una fórmula que concilia economía estatal y privada, con amplio espacio para esta última, incluyendo a los grandes capitales transnacionales.

[^16]: El presidente Morales intuye que su propia experiencia individual se nutre de una tradición práctica, política e histórica, que asume con naturalidad y sin ningún conflicto personal interno. Véase: [https://n9.cl/t2ks2](https://n9.cl/t2ks2)

[^17]: Quizás lo más inquietante es que el sentido común de nuestra sociedad es consonante con estas nociones debido a la prédica de los partidos nacionalistas de todos los matices, incluyendo a la del MAS y a la mayor parte de las influencias intelectuales y a las propagadas por la asistencia internacional.

[^18]: Por lo pronto, “los flujos de IED [inversión extranjera directa] neta hacia Bolivia disminuyeron en 26,1% respecto a 2015, al haber pasado de $us 555 millones a $us 410 millones, según el último Reporte de Capital Privado Extranjero en Bolivia, publicado por el Banco Central de Bolivia (BCB) en su página web”.

[^19]: Así se ve claramente cuando se contrasta la idea de que Bolivia se convertiría en el núcleo energético continental, “Si se considera que América Latina y el Caribe tienen una capacidad instalada de 349.035 MW/año (OLADE, 2014) y que, considerando todas las fuentes posibles, se alcanza un potencial 662.195 MW/año (ídem), la cantidad que Bolivia produce representa hoy el 0,004% del continente y si efectivamente llegásemos a exportar lo que se propone ENDE ascenderíamos hasta el 0,034, es decir del 4 por mil al 3 por ciento, en cifras correspondientes al año 2015” (Róger Cortéz y Daniel Robison, “Incógnitas tóxicas y verdades ocultas del proyecto Chepete/Bala”, La Paz, octubre de 2016, documento inédito).

[^20]: Sobre los problemas del trazado, véase: [https://n9.cl/i0i97](https://n9.cl/i0i97)

[^21]: Está, además, el tremendo golpe con que el presidente abolló la candidatura más temible que, según las encuestas, tiene al frente, la de Carlos Mesa, al revelar que el expresidente había buscado apoyo oficial para representar a Bolivia en la UNESCO. Véase: [https://n9.cl/71pyb](https://n9.cl/71pyb). La revelación, que afectó notoriamente al expresidente, refuerza la aseveración de Álvaro García, quien lo caracteriza como “pusilánime”, el peor de los pecados de un político, según Maquiavelo, quien recomienda a los gobernantes que no duden en tomar decisiones, que se hagan temer, pero sin llegar jamás al extremo de hacerse odiar.

