---
lang: es
format: 
  html:
    page-layout: article
---
# "Descolonización" de las FF.AA. y redes de extorsión {.unnumbered}
---

A pesar de que en la apertura del año se han declarado dos de las confrontaciones sociales más intensas e importantes de los últimos tiempos —las de cooperativistas y militares de baja graduación—, el gobierno mantiene una nítida ventaja en materia electoral, así como un elevado perfil en el área internacional, con la presentación de la demanda marítima de Bolivia ante la Corte Internacional de Justicia de La Haya y la preparación de la asamblea del Grupo de los 77 y China.

Ha sabido equilibrar su continua tentación de manejar electoralmente el reclamo marítimo con una amplia convocatoria, que ha incluido a expresidentes y excancilleres y a todos los gobernadores, manteniendo así una imagen no sectaria que sigue desequilibrando a la diplomacia y a casi la totalidad de los políticos chilenos, quienes reaccionan homogéneamente con reflejos y discursos indiferenciables de las corrientes ultranacionalistas y ultraconservadoras. Algo parecido a lo que le ocurre al gobierno boliviano cuando se topa con reivindicaciones que se entroncan con el espíritu constituyente, como las que plantean los suboficiales y sargentos.

La reunión del G77 y China le brinda a nuestra representación una oportunidad única de argumentar en pro de la causa que sustentamos en la Haya. Además, el hecho de haber seleccionado a Santa Cruz de la Sierra como sede del acontecimiento contribuye a ratificar el posible triunfo de la candidatura oficialista en un departamento extremadamente sensible ante señales que no proyecten una imagen exclusivamente andina del país.

## Asalariados y uniformados

La armonía y la aparente simplicidad con que parece haberse resuelto la habitualmente accidentada y áspera pugna salarial —que suele copar el centro de la coyuntura los cuatro o cinco primeros meses del año— contrasta con la brusquedad que ha caracterizado la conducción del conflicto con los suboficiales y sargentos de las Fuerzas Armadas, caracterizada por el total predominio de los reflejos cuartelarios, con la destitución, sin juicio previo, de centenares de efectivos y la expulsión de más de una decena de estudiantes de la universidad militar, la Escuela Militar de Ingeniería (EMI).

Si tan feroces sanciones no se retiran en algún momento relativamente próximo, y persiste la impermeabilidad de las autoridades a las demandas de los movilizados, la reacción de los afectados puede alcanzar límites imprevisibles [^1], sin que esto signifique necesariamente que se revoque la relación de fuerzas que favorece completamente a los gobernantes por ahora.

El año pasado concluyó con el inesperado decreto que obligaba al pago de un aguinaldo extra, mientras que este arranca con la determinación de elevar en 10% el salario básico y en 20% el mínimo nacional [^2]. Sin que se conozca hasta hoy una medición confiable del impacto inflacionario del primero, puede anticiparse que sucederá lo mismo con estas otras dos medidas, ya que no existe ninguna predisposición gubernamental para actualizar la metodología de ponderación inflacionaria, que se considera significativamente subestimada, según estudios de la Fundación Jubileo y del CEDLA [^3].

Los incrementos ratifican la decisión gubernamental de mejorar su aceptación entre los asalariados, que es un sector que se ha sentido desfavorecido respecto a otros en su participación en el gran flujo de recursos que han ingresado a la economía del país durante la última década.

El aumento se complementa con una ostentosa aproximación a la dirigencia de la COB y organizaciones afiliadas, como la de los fabriles, con visibles y exitosos resultados. Por ejemplo, frente al conflicto con los suboficiales, varios dirigentes laborales no han vacilado en salir a escena manifestándose a favor de las posiciones del gobierno.

La tregua lograda con los trabajadores y empleados deja pendientes varios problemas con ese sector, que en algunos casos ya se han exteriorizado y en otros permanecen encubiertos [^4]. Sin embargo, ayudará a reducir algunas de las principales tensiones que se han venido acumulando durante los años en que el MAS es responsable de conducir la totalidad de los aparatos estatales.

Tal alivio no terminará de diluir el sentimiento de inequidad diseminado entre todos los sectores que no son parte del bloque de poder [^5], ante las continuas evidencias de que quienes lo componen, como la cúpula de los cooperativistas mineros, obtienen extraordinarias transferencias de excedentes mediante la concesión de riquezas naturales (yacimientos mineros, tierras, recursos forestales, etc.), rebajas o exenciones tributarias, subsidios especiales, traspasos y regalos de maquinaria, equipo e instalaciones. de COMIBOL.

El reciente choque en torno a la nueva ley de minería ha exhibido una vez más la magnitud de las recompensas que se hacen a nombre del conjunto de los cooperativistas, pero que se concentran entre algunos de los dirigentes que copan la representación gremial y política del sector. Estos dirigentes participan en la producción ejerciendo la propiedad práctica y efectiva —ya que no legal— de los yacimientos concedidos [^6].

La pugna en torno a la redacción del proyecto de ley minera ha desnudado contradicciones internas del bloque, magnificadas por la creciente desazón de una parte de los parlamentarios oficialistas que saben que no retornarán a sus curules [^7]. También ha puesto de manifiesto las enormes dificultades del MAS para mejorar la calidad de la gestión de la nueva burocracia que se ha hecho cargo del poder público, a partir del desplazamiento de la que lo monopolizó el medio siglo anterior.

En resumen, las compensaciones salariales alivian las nuevas percepciones sobre desigualdad que pueden arraigarse en las presentes condiciones de aceleración del desarrollo de las relaciones sociales capitalistas, a las que ha dado lugar el avance económico con el que se identifica la actual gestión de gobierno. Se ha institucionalizado la distribución de recursos naturales (y, con ello, el patrimonialismo) como complemento o sustituto de fuentes ingresos de diversos sectores (cooperativistas, campesinos e indígenas, entre otros).

## ¿Bienestar económico, indisposición moral?

El optimismo de los encuestados, visible en la casi totalidad de estudios y sondeos de opinión sobre las expectativas de mejoría de situación económica en el futuro inmediato, es mucho más fácil de medir que las reacciones ante la avalancha de informaciones sobre extorsión, nepotismo, prebendalismo, uso indebido de recursos y bienes estatales que se han instalado como dueños absolutos de la escena noticiosa del año, compitiendo con las novedades cotidianas referidas a la quiebra y entrega total del aparato judicial y de los fiscales a la voluntad del poder político (y económico también).

La mayor parte de los estudios de opinión carecen de preguntas referidas a la materia, y cuando existen, se orientan a interrogar genéricamente sobre confiabilidad institucional o cuestiones afines. Además, es habitual que los encuestados o entrevistados sean elusivos o ambiguos en responder a preguntas frontales sobre temas que, de alguna manera, el público considera riesgosos [^8].

En este cuatrimestre las sospechas se han extendido a los principales representantes del Órgano Ejecutivo, señalados de amparar la concesión irregular de contratos a allegados, incluyendo parientes, por una parte, y a controlar importantes inversiones, no registradas a su nombre, pero manejadas como de su entera propiedad [^9].

Estos escándalos se agregan a una larga cadena, en la que destacan lo ocurrido con la empresa Catler, que le costó la cabeza al segundo jefe del MAS y presidente de YPFB en 2008, la inminente pérdida de las ya pagadas barcazas chinas y el descubrimiento de mallas de extorsión conformadas por los principales asesores jurídicos y altas autoridades del Ministerio de Gobierno, y el denominado “INRA segundo” (o más bien clandestino) que funcionaba en Santa Cruz concediendo tierras discrecionalmente.

La huida del hasta hace poco todopoderoso fiscal del “caso terrorismo” ha impactado seriamente en el gobierno, que teme la caída del complicado andamiaje que le permitió neutralizar a la corriente más radicalizada y violenta de la oposición en el año 2009. Y es que, además de debilitar la credibilidad de la acusación, pone de manifiesto, nuevamente, el fracaso de la reforma judicial y la ausencia de algún cambio en el desempeño de la Policía.

## Nuevos movimientos sociales

La protesta de suboficiales y sargentos subraya la utilidad de distinguir entre movimientos sociales y organizaciones sociales. Estas categorías, que suelen usarse como idénticas por muchos autores, se confunden deliberadamente en el lenguaje de los teóricos gubernamentales para justificar expresiones como “gobierno de los movimientos sociales”.

Nos referimos aquí a los movimientos sociales que serían exclusivamente las manifestaciones de acción directa propias de las limitaciones o fallas del sistema de representación [^10], tan frecuentes entre finales del siglo anterior y 2005 en nuestro país. Con la recomposición del sistema de representación, la cantidad de movimientos sociales ha decaído notablemente, pero el gasolinazo, algunas protestas regionales o las marchas indígenas han demostrado que hay espacio para ellos, pese a la férrea unidad entre el partido de gobierno y la gran mayoría de los dirigentes de organizaciones sociales [^11].

La movilización de militares de baja graduación es un movimiento social característico, en el que destaca la protagónica participación de las esposas. Este movimiento social recupera las bases del proceso constituyente, no solo porque reivindica una aplicación consecuente de la Constitución, sino porque desnuda contradicciones de fondo que enfrenta el Estado, a partir de la congelación de las transformaciones políticas y, especialmente, de la descolonización y aplicación de la pluralidad, convertidas exclusivamente en referencias retóricas o simbólicas.

Cuestiona también, de hecho, la llamada “doctrina militar”, defendida con gran ahínco por los gobernantes y comandantes militares, aunados en un bloque sin fisuras, demostrando que dicho concepto no es más que la completa continuidad conceptual y práctica del aparato estatal represivo, incongruente con el pacifismo y la reconversión integral del Estado que dispone la carta magna.

Sin importar que muchos de los integrantes del sector que hoy día protesta, o todos ellos, seguramente ejerzan en su práctica social cotidiana las conductas verticales y autoritarias (hacia abajo y hacia arriba) que hoy cuestionan y proponen reformar, queda claro que el movimiento recupera la línea democratizante de las movilizaciones populares.

A pesar de que las tendencias predominantes apuntan hacia la desactivación y sometimiento de la movilización, esta tiene los componentes necesarios para impactar y dejar huella. Si, inesperadamente, el movimiento encuentra la ruta para no ser desarticulado, el tiempo que se tarde en atender sus demandas afectará la estructura estatal, tanto más seriamente cuanto más se demore en ello. Por lo pronto, es posiblemente la única movilización que puede mellar el puntaje electoral del oficialismo porque la represión a sus componentes toca fibras de amplios sectores populares, principalmente campesinos y migrantes del campo [^12].

## Acciones opositoras y escenariois prospectivos

Los partidos que compiten con el MAS se están esforzando en superar la inocuidad que ha caracterizado sus acciones. De esa manera, UN ha anotado dos importantes denuncias (la defraudación de impuestos en exportaciones de amalgamas y residuos de oro y el contrato de catering de BoA), al mismo tiempo que ha consolidado su presencia hegemónica en el Frente Amplio (FA), al imponer la realización de la consulta para elegir candidato, porque el suyo no tiene adversario viable entre los otros componentes de la coalición.

La convergencia del MDS (ex Verdes de Santa Cruz), sus aliados benianos y el MSM, se ha ganado, sin duda alguna, el sitio que corresponde al hecho más novedoso del panorama electoral, al haber aproximado a corrientes de orígenes ideológicos prácticamente antagónicos, aunque de extracción social muy similar: clase media urbana. Lo inesperado de esta convergencia no se traduce hasta ahora en un potenciamiento electoral, ya que los últimos sondeos muestran una intención de voto casi constante, que mantiene la ventaja del oficialismo por encima de la que equivale a sumar a sus tres inmediatos seguidores (FA, MDS y MSM).

La posibilidad de que la aproximación entre el MDS y el MSM cristalice en un acuerdo electoral tiene como consecuencia que la aparentemente descartada unidad opositora pueda volver a debatirse. Sin embargo, de momento no terminan de aclararse los términos en que podría viabilizarse, especialmente en lo que hace a las candidaturas que la presidirían, ni se manifiestan señales que demuestren que la concurrencia de todos garantice un incremento perceptible de la intención de voto.

Las acciones más resonantes de la oposición no han llegado al punto de alterar la relación de fuerzas vigente; el que esto ocurra sigue dependiendo de la evolución de los conflictos sociales. De allí que —pese a la acumulación de frentes de confrontación y desgaste— la tendencia central del proceso siga apuntando a un triunfo del oficialismo el 12 de octubre.

<br>

::: {style="text-align:right; font-weight: bold;"}
Abril de 2013
:::


## Notas

[^1]: De hecho, uno de los principales voceros del movimiento amenazó con volarse con una carga de explosivos en la puerta del Ministerio de Defensa. Aunque tal advertencia parece tener un sentido propagandístico antes que práctico, no debe perderse de vista de que la pérdida de empleo somete a las personas a los más altos niveles conocidos de estrés; en consecuencia, condiciona las formas más extremas de respuesta a la tensión. Recuérdese lo que ocurrió años atrás con el trabajador minero que cumplió su amenaza de volarse en las instalaciones del Congreso. Kristofer J. Fenlason y Terry A. Beehr (“Social support and occupational stress: Effects of talking to others”, Journal of Organisational Behaviour, 15, pp. 157-175, 1994) analizan las reacciones ante la pérdida del empleo.

[^2]: Véase: [https://n9.cl/4zqy7](https://n9.cl/4zqy7)

[^3]: Las discrepancias sobre la inflación se presentan en un contexto de crecimiento del PIB boliviano que podría llegar a finales de este año al 5,5%, ubicándose segundo en la región, tan solo detrás del de Panamá, cuya proyección es del 7%. Véase: [https://n9.cl/7n1iu](https://n9.cl/7n1iu)

[^4]: Uno de los problemas propios de esta gestión gubernamental, y que afecta a decenas de miles de empleados de la administración pública, es el de los “consultores en línea”, que representan a cerca de la mitad de quienes trabajan en el Estado, según cifras proporcionadas por el Defensor del Pueblo. Estos “consultores” carecen de cualquier beneficio social y trabajan frecuentemente en condiciones de notable abuso en cuanto a régimen horario e indefensión ante abusos de toda índole. Véase: [http://www.defensoria.gob.bo/sp/noticias_proc.asp?Seleccion=813](http://www.defensoria.gob.bo/sp/noticias_proc.asp?Seleccion=813). Otro problema de estos “consultores”, especialmente durante el primer año de experiencia, son las obligaciones tributarias y las sanciones que enfrentan en esa materia, debido a su total inexperiencia en manejarlas cuando obtienen un NIT.

[^5]: Colonizadores, comerciantes y cooperativistas son los tres principales componentes del nuevo bloque; los cocaleros, con prácticas económicas y sociales que conjugan las de colonizadores y comerciantes, ocupan un lugar central, en alianza con académicos y políticos profesionales que componen la burguesía burocrática estatal. La consolidación de estos sectores se acompaña con la exclusión de otros, como los indígenas.

[^6]: El gobierno ha concedido 372.278 hectáreas a los cooperativistas (véase: [http://www.defensoria.gob.bo/sp/noticias_proc.asp?Seleccion=813](http://www.defensoria.gob.bo/sp/noticias_proc.asp?Seleccion=813)) en los últimos siete años, además de millones de dólares en instalaciones, equipos y maquinarias de COMIBOL. También ha priorizado el predominio de las actividades extractivas y ha oficializado su antagonismo con los “ecologistas”, como los denomina en sus discursos de condena el presidente del Estado, al subordinar el uso del agua a las necesidades de las actividades mineras.

[^7]: Por la experiencia de 2010, ya saben que la rotación de puestos, propia de la democracia comunitaria, no se aplica a los cargos de presidente, vicepresidente y ministros, pero, en compensación, afecta a la casi totalidad de ls parlamentarios del partido de gobierno. Este comportamiento también es un mecanismo para preservar la lealtad de nuevos dirigentes de organizaciones sociales, quienes han adquirido la idea de que su paso por el Legislativo es parte de sus derechos naturales y de la “indianización” y “descolonización” del Estado, al menos como la concibe el vicepresidente (véase: Álvaro García Linera, El oenegismo: Enfermedad infantil del derechismo (O cómo la “reconducción” del Proceso de Cambio es la restauración neoliberal), La Paz: Vicepresidencia del Estado Plurinacional de Bolivia, 2012).

[^8]: Es bien conocida la proverbial cautela de los bolivianos respecto a diversas cuestiones, entre las que destacan las preferencias electorales. Esto resta precisión a los resultados de sondeos referidos a esas cuestiones.

[^9]: La concesión por invitación directa del servicio de refrigerios para la aerolínea bandera, en el primer caso, y el manejo de una extensa red de medios masivos de difusión, a la que se refiere el texto Control remoto, del periodista Raúl Peñaranda (La Paz, 2014), en el segundo. Los tres o cuatro millones de dólares del contrato de BoA son, en cualquier caso, una minucia frente a otros de altísimos montos, como el teleférico La Paz-El Alto, y aún mayores, como el fracasado convenio con la empresa Hydrochina para la construcción de la represa Rositas en el Río Grande ([http://www.eldeber.com.bo/oferta-electrica-crece-peroproyecto-rositas-se-demora-/140413214212](http://www.eldeber.com.bo/oferta-electrica-crece-peroproyecto-rositas-se-demora-/140413214212))

[^10]: Entendiendo como tales no solo a los partidos y otras organizaciones políticas habilitadas legalmente para presentar candidaturas a puestos públicos electivos, sino también a sindicatos, asociaciones de productores, comités cívicos y todo tipo de organización gremial y corporativa.

[^11]: Las organizaciones sociales son permanentes, necesariamente sectoriales, jerárquicas, más o menos burocratizadas, en contraste con los movimientos sociales, necesariamente efímeros, eventualmente multisectoriales, horizontales y poco o nada burocratizados (Roger Cortéz, El sistema de representación en Bolivia, Santa Cruz: UAGRM, 2011)

[^12]: El “caso Macororó”, de 2003, que mostró al ministro de Defensa Teodovic, del gobierno de Gonzalo Sánchez de Lozada, “regalando” la fuerza de trabajo de conscriptos a empresarios agroexportadores, dio la campanada final de la caída del ancien régime al proyectar una imagen de regresión total de los cambios de 1952, con los hijos de campesinos reducidos nuevamente a las prácticas serviles de antes de la Revolución.




