---
lang: es
format: 
  html:
    page-layout: article
---
# La búsqueda oficial de victoria en el referendo {.unnumbered}
---

Si bien terminó imponiéndose la convocatoria a un referendo “simple”, en el que se decidirá únicamente por una nueva reelección, contradiciendo lo previsto en el anterior análisis, la evolución de los hechos que condujeron al MAS a escoger esa modalidad y no la de una reforma “ómnibus” [^1] no ha sido para nada sencilla, y presagia complejos nuevos escenarios.

Los tres planos principales que condicionan la futura disposición de fuerzas que empieza a dejarse sentir son: el curso desfavorable que se mantiene y refuerza como tendencia principal de la situación económica internacional y, especialmente, la baja de precios de los commodities; la restructuración de la disposición de fuerzas en el espacio continental y regional y, finalmente, el mantenimiento de un estado de crispación y confrontación de las escenas política y social en nuestro país.

## Un vecindario agitado

Las novedades que han traído las elecciones de Argentina y Venezuela se repiten tanto y concitan tal cantidad de comentarios y previsiones, que es fácil perder de vista que nuestro subcontinente y el Cono Sur muy pocas veces han sido escenarios apacibles.

El denominador común múltiple en este tercer quinquenio del nuevo milenio se define por las dificultades que atraviesan prácticamente todos los gobiernos que decidieron aprovechar, con diferente éxito y profundidad, el espacio que dejó el repliegue hegemónico estadounidense en estas latitudes.

Brasil, Argentina, Paraguay y los principales participantes del bloque del ALBA adoptaron durante estos años políticas y rumbos que se zafaron ostensiblemente del libreto predominante en los años de la Guerra Fría, de las guerras de “baja intensidad” y de los “ajustes estructurales”.

Los gobiernos nacional populares [^2], que le dieron su sello particular a estos últimos años en América Latina, presentan ciertos rasgos comunes, aparte de cierta afinidad en política externa: una inclinación keynesiana, nacionalista y desarrollista [^3] de sus políticas económicas y una indiscutible mayor proximidad y permeabilidad a organizaciones, movimientos y sectores populares, campesinos y de trabajadores, en comparación con todos los gobiernos de la primera fase de la recuperación democrática.

La década de precios altos de las materias primas alentó el arraigo y la proyección de estos regímenes, pero prácticamente todos, con distintos matices y ritmo, están experimentando dificultades a partir del viraje del mercado mundial. La merma de ingresos se acompaña, también de manera bastante uniforme, con el descubrimiento o puesta en evidencia de gigantescos casos de corrupción, prebendalismo y clientelismo sistemático; además, en países como Bolivia o Ecuador, de persecución a organizaciones y sujetos críticos, incremento de tendencias represivas, cooptación de organizaciones sociales y otros rasgos afines.

“Mensalao” (escándalo de las mensualidades, sobornos pagados a los diputados para su apoyo a proyectos del Poder Ejecutivo) y “Lava Jato” (lavado de dinero que implica a grupos mafiosos, políticos y empresas) son nombres que se ha dado en el Brasil a gigantescas operaciones de investigación que están transparentando la colusión entre políticos (tanto de la coalición oficial como de sus adversarios) y ejecutivos de empresas estatales y privadas; solo en el caso de “Lava Jato” han costado no menos de 6.000 millones de dólares.

El enriquecimiento de la familia presidencial y muchos altos funcionarios en Argentina, así como de la “boliburguesía” venezolana, la concentración de poder y riqueza de la familia presidencial en Nicaragua, y muchos otros casos en todos los gobiernos calificados de “izquierdistas”, “socialistas”, “progresistas” o “populistas”, configuran el panorama que está llevando a los grupos conservadores a plantearse la supuesta apertura de un período de restauración [^4] “neoliberal”.

Sin embargo, tal como en el caso de la crisis económica, que se desarrolla en formas tan disparejas [^5], la situación política de cada uno de los países es sui generis y, en la mayor parte de los casos, autónoma la una de la otra [^6]. De allí que el entusiasmo y la homogeneidad de los pronósticos que se hacen a partir de la caída del kirchnerismo y la derrota legislativa del gobierno chavista revelan más la impaciencia de los grupos dominantes de antaño por recuperar el poder, que el descubrimiento del mecanismo de una nueva oscilación histórica.

La salida de los Kirchner y la seria derrota del gobierno de Maduro en las elecciones parlamentarias aumentan las posibilidades de cambios gubernamentales en Brasil, Ecuador y Bolivia. Si esto llega a ocurrir, obedecerá a manifiestos errores de los gobiernos que enfrentan tal amenaza [^7], pero de ninguna manera cabe esperar que se retorne a la situación anterior.

Los gobiernos que puedan reemplazar a los que están en capilla se encontrarán con al menos dos profundos cambios, que hacen poco viable el sueño de restauración conservadora convencional. El primero es que está en pleno desarrollo una multipolaridad política que sustituye la presencia de EE. UU. como potencia exclusiva y excluyente. El segundo radica en la fuerza y arraigo del empoderamiento social que ha ocurrido en estos últimos años.

Es en América Latina donde los Estados Unidos han visto su mayor repliegue de los últimos años, cediendo espacio económico y político a nuevos actores, como China, y las posibilidades de que pueda recuperar su anterior posición son más que remotas.

Respecto a los movimientos populares de la región, los gobiernos de Venezuela, Bolivia, Ecuador y Nicaragua han hecho todos los esfuerzos por domesticarlos y someterlos [^8], con serias consecuencias para su autonomía, organicidad, fortaleza, unidad y democratización interna. Pese al enorme pasivo que eso representa, los intentos por desmontar y eliminar las conquistas y avances conseguidos encontrarán una resistencia cualitativamente superior a la del pasado y, en general, a una significativa maduración de la capacidad colectiva de identificar, reclamar y sostener el mantenimiento de derechos reconocidos a lo largo de este último siglo.

## Realidades económicas y era de reajustes

Los índices y tendencias económicos adversos se han seguido empeorando durante este año, en la misma medida en que las posibilidades de recuperación parecen cada vez más lejanas. La pérdida acumulada por la disminución del precio de nuestros productos de exportación supera las previsiones más pesimistas [^9], y a los problemas del deterioro de los términos de intercambio comercial están a punto de agregarse nuevas complicaciones, como el alza de tipos de interés que prepara la Reserva Federal estadounidense [^10].

Sin embargo, mientras más enredado se presenta el panorama, más optimistas y desafiantes son las declaraciones de los voceros económicos bolivianos, al pregonar que “estamos blindados” ante la crisis y que tienen fórmulas confiables y duraderas para sortearla o abortarla.

El mensaje oficial se atrinchera detrás de la información de que el desempeño económico de Bolivia es mejor que el de los otros países sudamericanos y en una defensa cerrada de las virtudes de su modelo, presuntamente basado en la “fortaleza del mercado interno” y la inversión pública.

Indiscutiblemente, más allá de la gravedad de las malas noticias y el entrecruzamiento de argumentos teóricos, el gobierno ha conseguido nuevamente sorprender con su capacidad de iniciativa al anunciar la concesión de créditos chinos por un monto inicial de 7.500 millones de dólares, que incluso subirían a 10.000 millones, con lo que podría ejecutar un ambicioso plan de obras de infraestructura caminera, energética e inversiones en otros campos (gran parte bajo la modalidad “llave en mano”, utilizada con tanta frecuencia que tiende a convertirse en la norma).

Lo que no ha empezado siquiera a discutirse es la necesidad, pertinencia y sostenibilidad de varias de las obras programadas porque, tal como con la carretera por el TIPNIS y varios otros proyectos multimillonarios, no se han dado a conocer los estudios y el respaldo conceptual, económico, ambiental y científico con que se ejecutarían.

De hecho, la ejecución de grandes proyectos urbanos, como los trenes de Santa Cruz de la Sierra y Cochabamba, o la multiplicación de ramales del teleférico en La Paz y El Alto (que en conjunto se acercan a un costo de 1.500 millones de dólares), abren más interrogantes de los que resuelven, debido a su elevado costo y a su escaso impacto en la solución de los problemas de fondo de las principales urbes.

Otros, como el conjunto del plan nuclear (2.000 millones de dólares), incluyendo en primer plano la construcción de una minicentral nuclear de generación eléctrica, se siguen propagandeando como presunta base de la conversión de Bolivia en una “potencia energética regional” [^11], aunque sin poner sobre la mesa los estudios de costo-beneficio y disponibilidad de mercados. En cualquier caso, obedecen a una lógica que marcha a contramano de priorizar las inversiones en energías limpias y carentes de los riesgos que tiene la atómica [^12].

De cualquier manera, el gobierno afirma ahora que nuestra economía crecerá no al 5,9%, como anunció a principios de año, pero sí al 5,01%, con lo que se pagará el aguinaldo extra, que tiene una importancia crucial para la estrategia de campaña favorable a la reforma constitucional, en la que se decidirá la habilitación de Morales para una nueva reelección.

Mediante el gasto de reservas internacionales (RIN), un endeudamiento externo acelerado y a gran escala, el incremento de la presión tributaria y la penalización a los contribuyentes tradicionales, el gobierno apuesta a fondo por mostrar una economía invulnerable a las convulsiones externas. Lo ha conseguido en gran parte este año, pero es más que dudoso que pueda sostener esa burbuja por mucho más tiempo.

Los enunciados de industrialización han quedado reducidos a realizaciones vistosas [^13], pero definitivamente menores y completamente insuficientes para lograr una transformación de la matriz productiva y del patrón
de acumulación.

La dificultad más grande que ha enfrentado y enfrenta el manejo de la economía del país, con los éxitos y limitaciones que muestra hasta hoy, es su completa funcionalidad a la visión de campaña electoral continua, practicada por el MAS durante la década que conduce el Estado.

Si esa lógica no cambia, las contradicciones y dificultades económicas tenderán a proliferar y, con ellas, las presiones para que este gobierno o el que lo suceda ingrese en una lógica de recortes y ajustes (devaluaciones incluidas) en desmedro de los trabajadores y los sectores populares.

## La campaña del referendo

Bien vistas las cosas, puede decirse que quien conduce las campañas, tanto por el Sí como por el No a la reelección, es el gobierno. La primera, obedeciendo a una decisión consciente y deliberada, y la campaña negativa, por defecto, con base a las omisiones, errores y enredos de la administración.

No existe ninguna conducción partidaria o social de la tendencia, hasta ahora mayoritaria, por bloquear la reforma constitucional que, a la medida de sus deseos, ha diseñado la conducción masista, y que será puesta a prueba la tercera semana de febrero de 2016. Lo que hacen los partidos opositores, los disidentes masistas y algunos dirigentes sociales arrepentidos o nunca sometidos al partido gubernamental es tratar de amplificar y reiterar la oposición de los grupos sociales que se confrontaron al MAS desde el comienzo, o a la desilusión de aquellos que lo estuvieron apoyando.

Desde el uso del eufemismo “repostulación”, para amortiguar el reflejo negativo con que reacciona la mayoría ante la idea de la reelección, hasta una evidente aceleración de arrestos y trámites judiciales del caso de corrupción del Fondo Campesino —como parte de la campaña—, el gobierno continúa ensayando infructuosamente diversas fórmulas para volcar la tendencia que se refleja en sondeos desde inicios de año hasta el último 6
de diciembre [^14]:.

Los mensajes y acciones ensayados para favorecer su opción intentan adecuarse a la información que recogen los estrategas, sin cambiar un sólido eje que convoca a votar por la estabilidad y la continuidad, por lo sabido y conocido. El viraje a este registro, típicamente conservador, no se ha iniciado en esa campaña; es la consecuencia necesaria de un vuelco, primero al centro, que se advierte desde las elecciones regionales de 2010 (el lema de campaña “Vamos bien” del año pasado lo retrata fielmente).

La base y el atractivo de este relato radican principalmente en la capacidad del gobierno de seguir controlando las principales variables económicas y de moderar los apetitos y las pugnas de los grupos corporativos que lo sustentan. Pero incluso si consigue tales objetivos hasta el referendo, todavía enfrenta el riesgo de que eso no alcance para asegurar la victoria que le permita habilitar una vez más como candidatos para 2019 a la dupla que conduce el Estado, el gobierno y el partido hegemónico.

## Escenarios prospectivos

En el caso de que los esfuerzos no le alcancen al gobierno para un triunfo del Sí, el MAS todavía tiene posibilidades de ganar las elecciones de 2019, aunque, ciertamente, afrontando riesgos y complicaciones que no ha conocido previamente. Una manera de hacerlo es presentando enrocados a sus actuales candidatos (Morales a la vice y García a la cabeza), fórmula que no está prohibida en nuestra Constitución. La otra es entregando la posta a nuevos candidatos, de la mayor lealtad y docilidad posibles (un poco al estilo Cámpora-Perón en la Argentina de 1973).

El orgullo y el amor propio del supremo conductor político serían la primera y más evidente traba de la primera solución, y el riesgo de desatar una pugna interna, eventualmente incontrolable, el de las dos señaladas.

Pero, incluso si triunfa el Sí por un estrecho margen, las condiciones que se avecinan no le dan al MAS la certeza de que pueda volver a imponerse en 2019. Y es que, por todo lo señalado hasta aquí, va tomando forma, como tendencia central de la coyuntura, que de esas elecciones nazca un gobierno débil, ya sea continuista o de fuerzas opositoras.

Si es del actual oficialismo, estará muy socavado por su errores y contradicciones internas; si es de algún partido o coalición opositora, porque los oficialistas de hoy mantendrán el control de muchos puestos gerenciales clave del Estado, incluyendo posiblemente el aparato judicial y el Ministerio Público, encabezados por las más grandes organizaciones sociales. Desde luego que este curso se alteraría seriamente si el empecinamiento oficial por mantener y profundizar yerros lleva al desarrollo de escenarios de desastre [^15].

En el fondo, dado que el gobierno se ha inclinado por dar una respuesta economicista a todos los problemas, incluyendo los políticos y los estratégicos [^16], todo dependería de la suerte del modelo ensayado por la conducción de esta área. Hasta ahora, como se ha apuntado reiteradamente, ha sorteado los principales escollos y ha vadeado los sombríos pronósticos opositores, pero es cada vez más inverosímil que pueda mantener dicho desempeño a largo plazo con el desmoronamiento de los precios del gas [^17] y el deterioro de aquellos de los minerales (que podrían tener un porvenir menos negativo, igual que los alimentos).

Aunque la oposición carece de propuestas, estrategia de triunfo o solidez organizativa, este gobierno, igual que cualquier otro, necesitará consultar y acordar un plan para enfrentar las dificultades que ya han comenzado. Incluso puede verse ahora que el uso de reservas y el endeudamiento masivo para mantener la inversión pública serán insuficientes para preservar (y menos para mejorar) la cantidad y calidad del empleo, la capacidad adquisitiva de los salarios y el cumplimiento de todos los compromisos adquiridos en forma de bonos y subvenciones. Mucho menos se podrá mantener los privilegios de los dirigentes corporativos y de grupos como cooperativistas, cocaleros o colonizadores.

La situación social y política puede deteriorarse con extrema rapidez, si no se produce una rápida y consistente modificación de los hábitos de las autoridades de imponerse a como dé lugar y confrontar continuamente a sus críticos, para pactar, más bien, una plataforma conjunta de medidas de emergencia, de reprogramación y reestructuración de la inversión pública. Esta debería incluir pasos serios y verificables para transparentar las adquisiciones y contratos, así como la correspondiente rendición de cuentas en todos los casos.

La reforma de la administración de justicia y de la Policía, el relanzamiento de las autonomías y la descentralización, la recuperación de la independencia sindical y la democratización de los sindicatos y organizaciones sociales son otros temas que deben estar presentes en la búsqueda de acuerdos. De otro modo, cada uno de estos asuntos puede originar movimientos sociales espontáneos y rebeldes que busquen soluciones por la acción directa.

Es muy difícil que se produzca semejante viraje, no solo por la reticencia gubernamental, sino porque esa modificación sería interpretada por sus adversarios como una debilidad y, en su intento de explotarla, podrían esterilizarla fácilmente.

Pero si no se consigue imprimir un cambio significativo en esa dirección, todos los escenarios tenderían a privilegiar la exacerbación de los choques y a incrementar el costo y el sufrimiento para todos los actores, excluyendo, quizá, a los más privilegiados.

::: {style="text-align:right; font-weight: bold;"}
Diciembre de 2015
:::
 
## Notas

[^1]: Es decir, varias reformas en una sola consulta, como lo anunciaron voceros de la Coordinadora Nacional del Cambio (CONALCAM). Esta es la asociación de corporaciones y organizaciones sociales que, con base a la convocatoria de las principales confederaciones campesinas del país, respaldan a la gestión del gobierno actual. Los principales cambios a consultarse, si esa era la opción escogida, se referirían a la administración de justicia, que ha quedado ahora postergada, con el consiguiente crecimiento del descontento colectivo; también la retardación de la puesta en vigencia de un plan que permita al Ejecutivo reforzar su control sobre los operadores del Órgano Judicial, disminuyendo la visibilidad que hoy tiene esa sujeción.

[^2]: Descripción menos cargada ideológicamente que la de populista, usada más como adjetivo (des)calificativo que como categoría de análisis, excepto en el caso de autores que, como Laclau, se declaran teóricos del populismo e intentan emplear el término de un modo no peyorativo.

[^3]: Autores como el uruguayo Eduardo Gudynas prefieren caracterizarlos como extractivistas, aludiendo a su estructural incapacidad de superar la dependencia de la explotación y comercialización de materias primas (de modo prácticamente idéntico a los gobiernos conservadores o liberales que desplazaron).

[^4]: “Así, entre 2000 y 2015, mucha agua corrió bajo el puente. Frente a ello, vale la pena preguntarse si la tirantez entre transformación y restauración en este cambio de época no ha ido desembocando en un fin de ciclo, que bien podría caracterizarse como revolución pasiva —como afirma M. Modonesi (2012)—, categoría de análisis histórico que, asociada al transformismo y al cesarismo democrático, expresaría la reconstitución de las relaciones sociales en un nuevo orden de dominación jerárquico. Triste y lamentable final sería entonces el de nuestros gobiernos progresistas, que tanta energía colectiva y expectativa política conllevaron, lo cual incluye por supuesto no solo las experiencias populistas, en sus diferentes matices, sino las otras, como las del PT brasileño, que en el segundo mandato de Dilma Rousseff atraviesa hoy su hora más aciaga, marcada por la corrupción, el ajuste económico y el olvido de las promesas de transformación social” (Maristella Svampa en: [https://n9.cl/nq9uu](https://n9.cl/nq9uu))

[^5]: Como la venezolana, que se ha precipitado a una situación próxima a la quiebra, la ecuatoriana, mucho más controlada, la brasileña con características principalmente recesivas, o la boliviana, que continua exhibiendo cifras alabadas por los organismos financieros internacionales.

[^6]: En nuestro caso, dicha autonomía es menor, dada nuestra dependencia de las economías de Brasil y Argentina, que son nuestros principales socios comerciales y los compradores de nuestra principal exportación, el gas natural.

[^7]: La temprana defenestración de los gobiernos de Zelada, en Honduras, y de Lugo, en Paraguay, se diferencia de lo que está pasando ahora no solo por la participación militar, junto a una ostensible digitación estadounidense en esos hechos, sino por la debilidad y la escasa organicidad del movimiento popular en dichos países. 

[^8]: La relación entre el peronismo y los sindicatos en Argentina es muy anterior al kirchnerismo, y se rige por una dinámica muy diferenciada del resto de los países aquí mencionados.

[^9]: La reducción de los ingresos por hidrocarburos y minerales alcanzará los 34.173 millones de bolivianos (más de 4.900 millones de dólares) antes de que concluya el año. Véase:[www.paginasiete.bo/.../exportaciones-caen-317-superan-prevision-oficia-78951.html](www.paginasiete.bo/.../exportaciones-caen-317-superan-prevision-oficia-78951.html)

[^10]: Véase: [http://economia.elpais.com/economia/2015/12/06/actualidad/1449400109_854218.html](http://economia.elpais.com/economia/2015/12/06/actualidad/1449400109_854218.html)

[^11]: La construcción de varias represas también presenta importantes cuestionamientos de carácter ambiental, mientras que la viabilidad de la venta de electricidad a la Argentina, en caso de que se construya las generadoras, entra en una fase de incógnita con el arribo de un nuevo gobierno a ese país. Prácticamente ningún proyecto de generación cuenta con estudios del costo de las líneas transmisoras a los posibles compradores internacionales.

[^12]: La resistencia a la construcción de un centro de investigación nuclear en la zona de Mallasilla, en La Paz, ha mostrado el recelo ciudadano a aceptar sin explicaciones los planes del gobierno en este rubro. También ha puesto nuevamente de manifiesto la propensión que este tiene de enfrentar grupos y sectores para manipularlos en beneficio del cumplimiento de sus designios.

[^13]: Las plantas de recuperación de líquidos del gas natural y la inconclusa petroquímica para obtener urea en el Chapare son las principales. El progreso de la industrialización del litio está más que demorado, y sin una clara perspectiva de evolución, mientras que la puesta en marcha de metalúrgicas como la de Karachipampa presenta hasta ahora más problemas que soluciones.

[^14]: En todas, excepto en la encargada por el gobierno y ejecutada por la empresa peruana IPSOS, el No lleva una ventaja aproximada de 10 puntos porcentuales, que varían según la amplitud y la localización de la muestra seleccionada.

[^15]: Como ejemplo e hipótesis, basta observar el deterioro actual del Órgano Judicial, plagado de redes de extorsión, igual que la Policía, a lo que se añade la política benevolente con que el Ejecutivo se relaciona con las Fuerzas Armadas. Si no se enmiendan y rectifican, pueden dar sustento a grandes sobresaltos institucionales, que podrían desembocar en una nueva crisis estatal.

[^16]: Con esta denominación aludo a las trabas y deserciones observadas en la inconclusa reforma y descolonización del Estado, la transformación de la matriz productiva y el patrón de acumulación, así como a la apenas iniciada renovación ética e intelectual.

[^17]: Este energético se ha abaratado más que el petróleo debido a la consolidación de enormes reservas mundiales de gas esquisto. Por esta razón, la renegociación de precios con nuestros compradores tiende a carecer del resguardo que le proporcionaba el estar vinculado al del petróleo, y con muy pocas probabilidades de mejorar sustancialmente, por lo menos en el próximo quinquenio.