---
lang: es
format: 
  html:
    page-layout: article
---

# Escenarios endógenos y externos ante una estrategia de poder {.unnumbered}

El caudal y el contenido noticioso masivo que casi han monopolizado la atención de redes digitales y medios de difusión masiva convencionales [^1] coinciden tan ajustadamente con la estrategia que el último boletín asigna al comportamiento de la conducción del MAS [^2], que inducen a suponer que tal estrategia avanza holgadamente, pese a los contrastes que ha sufrido en el espacio internacional.

Y si fuese verdad que existió alguna resistencia dentro del gobierno a plegarse y subordinarse a esa estrategia —como varias veces lo ha denunciado Juan Evo Morales—, ese contratiempo también parece completamente superado.

De modo que las “tomas de distancia” de Arce Catacora y Choquehuanca [^3] o de cualquier otra figura destacada de los órganos estatales frente a Morales quedan reducidas a gestos aislados, muy ocasionales, mientras que la maquinaria estatal en su conjunto ha trabajado y prestado sus recursos para reivindicar a Morales como el faro y el guía supremo, indiscutible e insustituible y, en ese sentido, como el ineludible presidente del próximo gobierno, cualquiera sea la fecha en que se lo elija.

## Espada o mazo

La primera tarea del equipo de campaña presidencial de Morales Ayma ha sido la reparación y el control de daños causados por los brotes de división o insubordinación interna del MAS, partiendo del manejo del aparato de Estado y, muy especialmente, de su segmento judicial.

Esto le ha permitido la plena recuperación del control de la administración de justicia, de cuya operativa, entresijos e intimidades tienen gran conocimiento y manejo un grupo de abogados. Estos —que son parte del núcleo de la burguesía burocrática de Estado conformada en torno a Morales desde el inicio de su régimen— han utilizado a todo su personal y a sus cómplices en el Ministerio Público y la judicatura para desbaratar cualquier proceso iniciado contra dirigentes y punteros operativos del MAS y llevar adelante una contraofensiva para perseguir, enjuiciar y encarcelar a sus oponentes.

La rutina de acusación, hostigamiento judicial continuo, detención “provisional” y extorsión, acompañada por el indispensable escamoteo de derechos y garantías, ha sido intensamente practicada casi desde el inicio de la gestión evista. El método actual aplica mayor celeridad en los procedimientos e intensifica el acoso; además, traslada estas prácticas al seno del Legislativo.

En el Legislativo, la bancada del MAS, derrochando bronca y diligencia, usa todo tipo de recursos y “procesos” internos para tratar de neutralizar el único éxito tangible de la oposición partidista en los últimos años, que consiste en haber superado por 15 votos (disminuidos ahora a 11) el límite que separa al oficialismo del control de los dos tercios en diputados [^4].

El acobardamiento que de por sí produce la maquinaria judicial boliviana, sujeta al mandato de los jefes masistas [^5], se combina con el todavía vigente azoro que produjo el 55% masista de diciembre de 2020 en la oposición partidista, y que no se ha revertido ni con el retroceso del MAS en las elecciones autonómicas. Esto se debe a que las organizaciones políticas convencionales no forjaron tales triunfos ni participaron en ellos [^6]; más bien, fueron gestados en buena parte por disidentes del oficialismos o activistas ajenos al partidismo.

Jeanine Añez ha sido seleccionada con fruición por la cabeza y operadores masistas para ser inclementemente castigada [^7], entre otras cosas porque su actitud, al haberse quedado en el país —e incluso haber participado como candidata en las elecciones para la Gobernación del Beni—, contrasta demasiado notoriamente la de Morales Ayma, García Linera, Quintana, Arce Z., Arce Catacora, etcétera, etcétera, quienes, ante una situación de riesgo, optaron por la fuga.

Esta diferencia de actitud es suficiente para sacar a flote el sadismo más primitivo de estos dirigentes y su raigal misoginia, que trata de disfrazarse de presión para que los opositores accedan a respaldar el juicio de responsabilidades contra Añez siempre y cuando, desde luego, no se aplique el mismo procedimiento a Morales Ayma por haber incitado a la violencia masiva contra los habitantes de las mayores ciudades y otros delitos concomitantes.

La ventaja que conserva el MAS en todo este frente es que el partidismo opositor ha sido incapaz de zafarse de la antinomia fraude-golpe, al debatir el problema bajo los términos de los estrategas de Morales Ayma.

El examen objetivo de los acontecimientos prueba que el MAS ejecutó un golpe de Estado en noviembre de 2017, y que llevó adelante un largo proceso de fraude durante los años en que subordinó, restó independencia y manipuló a su antojo al Órgano Electoral y a todos los tribunales electorales.

La oposición ni siquiera entiende que, al hablar de “golpe”, el MAS se refiere a una situación completamente ajena a las definiciones académicas y se pertrecha, casi exclusivamente, en el poroso informe de la OEA, referido a un horizonte temporal excesivamente estrecho. Por eso no le ha quedado otra que depender de factores externos (la opinión consultiva de la CIDH y el informe del GIEI [^8]).

## Guerra anunciada

Al mismo tiempo que se desarrolla la confrontación sobre la interpretación y reinterpretación de la renuncia y evasión de Morales Ayma y el alto mando masista, la estrategia de esa conducción avanza firmemente en la guerra territorial que se libra principalmente en Santa Cruz y Beni.

La disputa por la tierra y el territorio, experimentada por los pueblos indígenas de esos departamentos como resistencia a un agresivo proceso de neocolonización protagonizado por colonizadores campesinos (detrás del que se esconde el agronegocio transnacional), registra al menos una controvertida muerte [^9], mientras se acumulan lesionados y heridos.

Allí, en estrecha alianza y coordinación con sus socios económicos (y enemigos políticos jurados), el bloque agroindustrial-financiero, con los colonizadores como avanzadilla social y algunas colonias menonitas como apoyo con su maquinaria, continúan posesionándose de nuevas tierras que desmontan, con quemas o sin ellas. Es un avance implacable sobre reservas naturales, territorios indígenas y parques nacionales, para incorporarlas al mercado de tierras, con la omisión o con la directa complicidad de las autoridades del Instituto Nacional de Reforma Agraria (INRA) y el ministerio responsable del ramo [^10].

La alianza económica que se menciona en el párrafo anterior se refiere al acuerdo explícito entre las cámaras empresariales y el MAS sobre la ampliación de la frontera agrícola (en los hechos, la expansión del mercado de tierras) que, de acuerdo a la Agenda Patriótica del MAS, debe alcanzar 13 millones de hectáreas.

Ese avance, aunado al supuestamente inevitable uso de semillas transgénicas y su paquete tecnológico de agrotóxicos, defendido compacta y fieramente bajo el camuflaje verbal de “uso de biotecnología” por la CAO, la CAINCO y la rama de la Confederación de Colonizadores [^11] que constituyen pequeños y medianos productores de oleaginosas (la otra la conforman los cocaleros del Chapare).

Esta alianza económica es tan profunda y explícita, que empresarios del agronegocio acudieron directa y públicamente al cuartel general de Morales Ayma en el Chapare, a pedirle que abogue por ellos ante el gabinete de Luis Arce Catacora [^12].

El simultáneo enfrentamiento político de los aliados, expresado en los choques entre el gobierno central y la Gobernación de Santa Cruz; Demócratas y afines vs. el MAS; bancadas de uno y otro bloque; el gobierno interino de Añez persiguiendo masistas, no anula ni aplaca el entendimiento económico entre ellos. Para más señas, este entendimiento entraña una comunión estratégica, pues coincide en la visión desarrollista (por tanto, capitalista) tradicional que viene ensayando el país desde el siglo anterior. Su discrepancia central en este punto es la importancia que cada uno atribuye a la acción económica del Estado y a las medidas “redistributivas”.

Cuando Morales reivindica los procesos de ocupación de tierras ejecutados por los colonizadores, enuncia, en cualquier caso, un criterio unánime en el MAS, que incluye completa y férreamente al vicepresidente Choquehuanca [^13] y, desde luego, al gobierno actual.

La contradicción entre ambas esferas induce a que actores protagonistas, como los pueblos indígenas —arraigados fundamentalmente en sus TCO—, no terminen de desentrañar el problema. Es el caso de un dirigente chiquitano clave [^14], que percibe la ocupación territorial realizada por los colonizadores principalmente como manifestación política para ganar espacios electorales para el MAS, coincidiendo con la explicación empresarial, la de la coalición Creemos, e, indirectamente, con la de Evo Morales Ayma.

Tanto el gobernador como los empresarios se enfocan en la explicación de los objetivos políticos de la colonización, mientras que el MAS la aborda como tema de derechos [^15]. Ambos coinciden en omitir cualquier alusión al fundamental sentido económico (ampliación y participación en el mercado de tierras), en la más típica operación ideológica de ocultamiento de una contradicción.

Este manejo ideológico segmenta la realidad, desarticula la relación entre el agronegocio y el muy rápido deterioro medioambiental de Santa Cruz y el Beni, compartimenta esa situación respecto del avance meteórico de plantaciones de coca y, en general, se niega a ver la carrera acelerada con que el tren del cambio climático nos está atropellando. En los Andes la minería, especialmente la aurífera, juega su propio destacadísimo papel.

La XI marcha indígena que busca llegar a Santa Cruz de la Sierra, con su consigna “Por los derechos humanos y contra los avasallamientos”, parece estarse enredando en la trampa ideológica del MAS y el agronegocio, tanto por no haber buscado hasta ahora también la movilización de los indígenas de tierras altas (ribereños del río Beni, Urus, CONAMAQ, por ejemplo), como por no rescatar las cuestiones centrales de la defensa de tierra, territorio, agua, y de la Constitución, que debemos, en primer lugar, a las marchas y orientaciones de los pueblos indígenas en los años noventa del siglo pasado, con los que se abrió el proceso constituyente.

Si la actual orientación de la marcha se consolida, a su arribo será recibida por el Comité Cívico cruceño y Creemos (¡!), facilitando el encubrimiento de la complicidad estatal-empresarial en la depredación masiva de la naturaleza, las quemas, el exterminio de la biodiversidad, y la consagración de los megaproyectos que hipotecan económica y políticamente al país, preservando el agónico modelo de desarrollo y el patrón de acumulación vigentes [^16].

## Contrapunto entre pandemia y economía

El discurso oficial sobre lo que se habría logrado hasta hoy en términos de recuperación económica se apoya, por una parte, en atribuir toda la responsabilidad del retroceso económico a la conducción del gobierno provisional y, en segundo lugar, en un optimismo relumbrante que se resume en su pronóstico de que, en menos de dos años, se habrá superado “el entuerto del gobierno neoliberal”.

El dúo compuesto por Arce Catacora y su hombre de confianza en la cartera de Economía omite completamente cualquier reconocimiento de que la declinación económica del país arranca con la curva de descenso de los exportables —en especial del gas natural— hace casi siete años, mientras subestima el impacto de la pandemia y, principalmente, no reconoce las fuertes señales de la decadencia del modelo de desarrollo y patrón de acumulación [^17].

Este denso silencio oculta la obstinación de preservar empresas públicas que generan pérdidas continuas y que requieren masivas transfusiones de recursos [^18], solo justificables para mantener una imagen y fuentes de empleos para la amplia clientela del oficialismo, frenando la recuperación económica y bloqueando las posibilidades de transitar a un modelo alternativo de desarrollo.

Como parte de esta conducta se inscriben la casi totalidad de las medidas adoptadas por YPFB para esconder o tratar de ocultar y retrasar, desesperada y vanamente, el eclipse de los ingresos provenientes de la exportación de gas. Estos se ven cada vez más estrangulados por, en primer lugar, los grandes cambios del mercado mundial del energético (EE. UU. convertido en primer exportador de petróleo y gas; Argentina con enormes reservas de gas en plena expansión); en segundo, por la negligencia interna en la búsqueda y desarrollo de reservas y, en tercer lugar, por la quema de gas internamente como principal fuente de generación eléctrica.

En un contexto de aceleración de los efectos del calentamiento y el cambio climático, con presiones en ascenso para disminuir el uso de combustibles fósiles, se achican las posibilidades de inversiones externas en el gas natural boliviano, mientras que YPFB, con insuficientes recursos financieros y un pesado rezago tecnológico, no tiene reales posibilidades de alterar esa realidad.

El hecho de que ocupemos un octavo lugar en el ranking sudamericano de la pandemia, con unos 4.200 infectados por cada 100.000 habitantes, comparados con los más de 11.000 de Argentina (véase anexo), ayuda a comprender que, pese a la lentitud o inexistencia de respuestas claras para paliar los daños económicos, no se produzcan explosiones sociales de gran magnitud y la población todavía tolere que el gobierno ponga el acento en el juego político del “fraude-golpe”.

No existe forma de prever si dicha tendencia se mantendrá ante una cuarta ola epidemiológica, porque según el ranking de contagios (morbilidad) que figura en el anexo, nuestro país, con su debilísimo sistema sanitario, exhibe una situación más benévola que aquellos con sistemas fuertes (Uruguay, Chile o Cuba, por ejemplo) [^19], mientras que la mortalidad se mantiene oculta tras un gran subrregistro.

Con tales reservas respecto a la confiabilidad de los datos disponibles, queda fuera de discusión que la relación entre pandemia y economía será en todo lado el factor de ajuste más importante en la relación sociedad-Estado y gobernabilidad y, desde luego, también en nuestro país [^20].

## La reforma condenada

Que el aparato judicial sea la espada/garrote de la estrategia masista y su plan de reinstalar a Morales a la cabeza del país ha profundizado hasta extremos insondables el hundimiento de la administración de justicia.

La rápida conversión de los juicios que existían contra funcionarios del MAS por procesos contra los de la administración interina es tan aplastante y obscena, que el informe del GIEI destaca que la subordinación del aparato judicial es un problema mayúsculo y una amenaza de primer grado para la democracia boliviana.

Profesionales bien intencionados, académicos y algunos cuadros partidarios han estado produciendo iniciativas para comenzar la frustrada reforma anunciada a inicios de este gobierno. Sin embargo, ahora ha quedado convertida en una piltrafa, porque si todo se resume a un ajuste a ejecutarse en tres meses, concentrándose en el procedimiento penal —como ha anunciado el reversible en sus argumentos ministro de Justicia—, queda claro que el MAS no piensa ceder un control que es piedra angular del conjunto de sus planes y diseños.

Las propuestas de reforma se concentran mayormente en cambiar la elección popular de magistrados por otros procedimientos, como si en las elecciones judiciales no hubiese quedado claro que los votantes rechazaron el sectarismo y el utilitarismo de la selección parlamentaria de candidatos a jueces. Tanto aquí como en EE. UU., por mencionar otro caso, está demostrado que la influencia partidista del Legislativo se inclina por manipular y someter a jueces y fiscales.

Cualquier muestra de no subordinación de árbitros y jueces desata tempestades verbales de Morales Ayma, quien ha descalificado a la CIDH y al GIEI. A la primera, por no haber avalado la elección indefinida, y al segundo, por haber encontrado violaciones de derechos también en su gobierno.

Los fiscales son el segundo gran tema de preocupación de los reformadores. Sin embargo, prácticamente no se menciona que para comenzar a quebrar la ausencia de autonomía de la administración de justicia debe empezarse con la renuncia de los miembros del TCP, que fue el ariete para quebrantar el orden constitucional y negar la soberanía popular.

Su papel es tan decisivo que, de otra manera, es muy difícil imaginar el inicio de un cambio sustantivo. Sin esta resultará muy difícil que los cambios políticos transcurran pacíficamente; mucho menos cuando los choques violentos mantienen en su vanguardia a dirigentes y cuadros partidarios de primera línea [^21], como ya ocurrió en noviembre de 2019.

La compacta decisión del MAS de mantener inalterado el control sobre el Ministerio Público y el Órgano Judicial se complementa con la sostenida ofensiva sobre las Fuerzas Armadas (FF. AA.), contradiciendo la tradición del régimen de los 14 años de prodigarse en concesiones y halagos. Además de la necesidad de convertir el “golpe” en un “golpe militar”, la táctica que despliega el equipo de campaña de Morales hacia las FF. AA. genera incógnitas sobre sus motivaciones y eventuales consecuencias.

## Voces del subconsciente y del subsuelo

Este análisis parte haciendo un recuento de los elementos que ayudan a mantener y avanzar en el objetivo “Evo presidente” (cuanto antes mejor y a cualquier costo). Esto se verifica completamente en el espacio de la escena política [^22].

En ese espacio también destaca el agobio de algunas de las nuevas autoridades, hostigadas física y judicialmente, o el aparente apaciguamiento de la alcaldesa de El Alto, que busca refugio en los brazos del gobierno ante los problemas que confronta, aliviando así el riesgo que significa una fractura de la base aymara del MAS.

Pero incluso en ese espacio, ciertas palabras y gestos dan pistas de que las cosas no transcurren tan plácidamente para esa estrategia. Véanse al respecto, en el anexo, actuaciones y exageraciones del exministro Quintana proclamando una línea estilo Robin Hood [^23] o promesas de cubrir de besos a la comunidad LGTBI, propias de un campañista desesperado en la búsqueda de ofrendas y dádivas que debe distribuir ante un público escéptico o frío. Ahí también cabe anotarse la recomendación de García Linera de que se deben preparar nuevas nacionalizaciones.

Esa suerte de lapsus se correlacionan con la incertidumbre y la ansiedad de una gran mayoría [^24] (cuatro quintos, según los encuestadores) que no percibe soluciones en curso, que teme por sus ingresos y empleos y que se siente vulnerable ante la enfermedad y la muerte. Para ellos el Estado, manejado por quien sea, se parece cada vez más a una asociación delictiva que persigue codiciosamente los fines de quienes lo componen y de sus más cercanos socios.

::: {style="text-align:right; font-weight: bold;"}
Agosto de 2021
:::

## Notas

[^1]: En tal sentido, el anexo de referencias de noticias de las últimas páginas no refleja la densidad, la intensidad y el espacio de redes y medios, sino el respaldo de afirmaciones aquí contenidas, igual que fuentes relevantes sobre temas aquí analizados y que sirven de apoyo a investigadores de las instituciones que acceden a estos análisis.

[^2]: Señalando que el MAS apuesta todas sus cartas a la reelección de Morales Ayma, recauchutando su imagen con base a la táctica de imponer su visión de que fue una víctima de un golpe de Estado, al mismo tiempo que arrincona mediante la represión judicial a sus opositores políticos.

[^3]: Es bastante obvio que estos personajes no se sienten cómodos en el papel que Morales Ayma y su equipo los obligan a jugar. Al mismo tiempo, sin embargo, queda perfectamente claro que carecen del valor, la fuerza y la experiencia para convertir sus críticas o rezongos en algo más que una anécdota. Por lo demás, carecen de un horizonte de formulaciones y criterios propios que los diferencie de la corriente principal del MAS, para sustentar cualquier disidencia seria.

[^4]: Véase: [https://www.paginasiete.bo/nacional/2021/9/1/denuncian-que-el-mas-hostiga-procesa-ofrece-dinero-por-dos-tercios-en-alp-306723.html](https://www.paginasiete.bo/nacional/2021/9/1/denuncian-que-el-mas-hostiga-procesa-ofrece-dinero-por-dos-tercios-en-alp-306723.html)

[^5]: Decididos a aparentar como sea que ellos no se acobardaron cuando huyeron o se refugiaron en embajadas, frente a las movilizaciones nacionales que cuestionaron el prorroguismo en 2019. Esto, además, es parte central de la estrategia de reconstrucción de la imagen de Juan Evo.

[^6]: El miedo desatado por la ofensiva persecutoria oficial no se limita a los dirigentes y cuadros opositores. Afecta, con toda probabilidad, a ejecutivos y técnicos de ONG, ya sea que hayan o no padecido las ofensivas previas, como se aprecia en el trabajo cotidiano de muchas de ellas, que habrían optado por una marcada despolitización, según testimonios de personal de campo. La irrupción de UNITAS con una publicación criticando el comportamiento del gobierno es una notable excepción.

[^7]: Las dos desventajas principales de la señora Añez ante toda la violencia judicial y simbólica con que la asedia el MAS son el descubrimiento de la catadura de sus principales asesores (Murillo con sus negocios o el exministro de Defensa con sus planes tipo Bahía de Cochinos), y el hecho de que ella, en su papel de representante —pero no parte integrante— de la gran burguesía transnacionalizada del agronegocio, carece de la fuerza para contrarrestar la persecución.

[^8]: La Corte Interamericana de Derechos Humanos (CIDH), que se pronunció sobre el supuesto carácter de “derecho humano” de la reelección indefinida y continua, y el Grupo Independiente de Expertos Internacionales (GIEI), que analizó las denuncias de abusos cometidos en 2019. Ambos temas se tratan más adelante en este boletín; el enlace de los textos completos de ambos documentos figura en el anexo de referencias de noticias.

[^9]: Véase: [https://www.la-razon.com/nacional/2021/08/01/del-castillo-niega-que-indigena-chiquitano-haya-muerto-por-golpiza-de-interculturales/](https://www.la-razon.com/nacional/2021/08/01/del-castillo-niega-que-indigena-chiquitano-haya-muerto-por-golpiza-de-interculturales/); [https://gacetadelsur.com/2021/08/03/familia-desmiente-que-el-indigena-chiquitano-lino-pena-haya-muerto-por-covid-19/](https://gacetadelsur.com/2021/08/03/familia-desmiente-que-el-indigena-chiquitano-lino-pena-haya-muerto-por-covid-19/)

[^10]: El anexo contiene algunas referencias documentales sobre el conflicto; el estudio de la Fundación Tierra tiene la explicación más detallada y minuciosa.

[^11]: “Interculturales”, según la denominación política introducida en la CPE.

[^12]: Véase: [https://www.la-razon.com/nacional/2021/04/30/morales-se-reune-con-empresarios-crucenos-para-tratar-la-reactivacion-economica/](https://www.la-razon.com/nacional/2021/04/30/morales-se-reune-con-empresarios-crucenos-para-tratar-la-reactivacion-economica/) ; [https://eldeber.com.bo/economia/agro-ofrece-sumar-us-2000-millones-en-exportaciones-y-duplicar-los-empleos_232706](https://eldeber.com.bo/economia/agro-ofrece-sumar-us-2000-millones-en-exportaciones-y-duplicar-los-empleos_232706)

[^13]: Véase: https://www.la-razon.com/nacional/2021/05/12/choquehuanca-a-interculturalesvan-a-decir-lo-que-piensan-y-sienten-sin-la-cabeza-agachada/

[^14]: Véase: https://eldeber.com.bo/economia/lazaro-tacoo-laberan-muchos-no-quieren-lastierras-para-cultivar-las-quieren-para-traficar_239448

[^15]:  *La mayoría* —es decir, los campesinos— *tiene más derechos que la minoría* —es decir los indígenas—, afirmaba hace años, en su folleto “Oenegismo...” el exvice García Linera.

[^16]: El ejemplo característico de estas megaobras es el del Chepete-Bala, reactivado el mes de agosto último. Su costo socioambiental, económico y político es impagable, pues prácticamente termina de liquidar la cuenca del río Beni para generar electricidad cuyo único cliente posible, Brasil, no la ha demandado jamás por consideraciones geopolíticas, como ha sido ocurrido con el tren transoceánico, pese a la presión y patrocinio de Alemania, China y otras potencias. Los boletines del año 2017 se han ocupado de este proyecto. Véase: [https://www.paginasiete.bo/opinion/roger-cortez-hurtado/2021/8/31/destruccion-como-politica-de-estado-306603.html](https://www.paginasiete.bo/opinion/roger-cortez-hurtado/2021/8/31/destruccion-como-politica-de-estado-306603.html)

[^17]: Tomando en cuenta esos elementos, se advierte que cuando el Ministerio de Economía se congratula por nuestra recuperación omite completamente compararla con las de nuestros vecinos que, casi en todos los casos, nos superan ampliamente.

[^18]: [Véase: https://www.paginasiete.bo/economia/2021/9/3/autorizan-al-bcb-prestar-economia-bs-15607-mm-500-mm-iran-empresas-publicas-306985.html](Véase: https://www.paginasiete.bo/economia/2021/9/3/autorizan-al-bcb-prestar-economia-bs-15607-mm-500-mm-iran-empresas-publicas-306985.html). Véase más enlaces sobre el tema en el anexo.

[^19]: Queda muy claro que una de las más importantes muestras de la debilidad de nuestro sistema de prestaciones de salud es un pésimo sistema de registro de contagios y muertes, por lo que nuestras estadísticas no son de fiar.

[^20]: Véase: [https://repositorio.cepal.org/bitstream/handle/11362/47043/5/S2100379_es.pdf](https://repositorio.cepal.org/bitstream/handle/11362/47043/5/S2100379_es.pdf)

[^21]: Véase: https://www.paginasiete.bo/nacional/2021/8/5/gustavo-torrico-comanda-gruposde-choque-del-mas-en-la-paz-303126.html

[^22]: Llamo así a la palestra simbólica donde los actores y voceros políticos actúan bajo los faros, cámaras y micrófonos que proporcionan las redes digitales (sociales) y los medios de difusión masiva, y donde se contrastan sus discursos y narrativas.

[^23]: La promesa de vaciar los bolsillos de los ricos para beneficio de los pobres pasa por alto que la base fuerte dura y sólida del MAS se apuntala en nuevas burguesías a las que se ha abierto vías de acumulación de capital mediante el tráfico de tierras, yacimientos minerales, contrabando y todo tipo de negocios irregulares o ilícitos.

[^24]: Véase: [https://eldeber.com.bo/edicion-impresa/el-74-de-los-bolivianos-opina-que-los-gobernantes-favorecen-a-unos-pocos_236823](https://eldeber.com.bo/edicion-impresa/el-74-de-los-bolivianos-opina-que-los-gobernantes-favorecen-a-unos-pocos_236823)
