---
lang: es
format: 
  html:
    page-layout: article
---
# Recrudece el plan para atropellar la soberanía popular {.unnumbered}
---

La ilusión que nos asalta frecuentemente en sentido de que la agitación interna siempre supera a la externa se ha visto notablemente resentida en estos primeros meses del año, en los que las turbulencias foráneas llegaron al extremo de sugerir, en algún momento, que retornaba el espectro de la guerra nuclear. La combinación y contraposición de la personalidad del nuevo presidente estadounidense con la del risueño emperador norcoreano creó esa imagen, aunque el análisis de los hechos deja claro que, por ahora, se trata antes que nada de una febril competencia simbólica.

En cambio, el simbolismo ha cedido en estas tierras harto trecho a manifestaciones muy materiales, que se acumulan en: i) la intensificación de la ofensiva gubernamental para garantizar la posibilidad de inscribir a su único candidato presidencial en la justa de 2019; ii) una nueva ofensiva estatal intimidatoria y iii) la agregación de casos de corrupción y grandes fallas administrativas.

En el cuatrimestre destaca por encima de todo que, por una vez, la disidencia y el descontento les ganaron a las fuerzas gubernamentales en la calle, en la jornada para recordar el referendo constitucional del año pasado (el 21F, como se lo llama ahora).

## Tumultos boreales y convulsiones australes

El nuevo y ostentoso mandatario de EE. UU. no termina de cumplir con los principales objetivos que prometió, bloqueado por los guardavallas institucionales y los recursos de contención del propio sistema interno de poder. Hasta aquí no ha encontrado una vía para canalizar sus propuestas más provocativas —el muro con México y la abrogación de la reforma sanitaria—, y ha requerido un bombardeo sobre Siria para acallar la avalancha de denuncias de los nexos de su entorno íntimo con el presidente ruso. Eso sí, no se ha detenido en desmontar los siempre pobres e insuficientes compromisos de su país para enfrentar el cambio climático, acelerando las exploraciones petroleras y la extracción de carbón y disminuyendo impuestos a los más ricos.

Steve Bannon, todavía asesor principal de Trump —igual que unos cuantos analistas dados al sensacionalismo y a las conclusiones fáciles [^1]—, está comprobando que la globalización no se acaba con el anuncio de revisión ni con la abolición de acuerdos comerciales.
Lo que aún está por dilucidarse es cuán posibles son los abruptos cambios en política internacional que pretende introducir la nueva administración en casos como el de Irán, que, dado lo inestable del tablero del Medio Oriente, pueden desencadenar desastres profundos y duraderos, como la masiva emigración de los que huyen de las guerras.

Esto confirma que la fase experimental del ascenso del nuevo jefe de Estado, caracterizado por su marcada inestabilidad, puede prolongarse, creando situaciones imprevistas, incluso cuando hasta ahora la fortaleza del sistema ha prevalecido sobre los impulsos de Trump. De cualquier manera, el gobierno estadounidense cuenta con la ventaja de una situación económica en despliegue, más estable que la de los europeos.

La supuesta oleada de triunfos de los neoconservadores eurófobos [^2] se ha frenado con su derrota en Holanda y el ya anunciado fracaso de Le Pen en la segunda ronda electoral francesa. Pero eso no compensa el profundo malestar que viven los ciudadanos de la Unión Europea, acentuado después de la salida británica [^3], por los elevados niveles de incertidumbre y lentitud y lo errático de su recuperación económica.

Aun así, este año muestra una tendencia lerda pero sostenida a la recuperación de precios de los commodities, con excepción del petróleo (con alto impacto en economías como la nuestra), que no termina de equilibrarse pese al inédito acuerdo de los productores OPEP con los no asociados, suscrito a finales de 2016.

Nuestro continente está sacudido por la dureza del enfrentamiento interno en Venezuela, en una supuesta agonía de larga duración, escenificada dramáticamente por los medios de difusión desde hace más de dos años y por la explosión de ondas de corrupción estatal que afectan a casi todos los países. Lo de Brasil [^4], con el caso Odebrecht, que compromete a todos los partidos, desde el PT hasta la derecha extrema, es un símbolo de cómo los políticos profesionales, cualquiera sea su ideología, han extremado sus prácticas para saquear los bienes públicos y estafar a los ciudadanos.

El triunfo de Lenin Moreno en Ecuador rompe la uniformidad del giro electoral, pero no la tendencia a que se eclipse a los gobiernos que prevalecieron en la escena sudamericana. La experiencia de Macri y Temer muestra también, simultáneamente, que el giro hacia políticas “neoliberales” tiene que afrontar la resistencia de sociedades mucho más empoderadas y conscientes de sus derechos que aquellas en que se pudo aplicar los lineamientos del consenso de Washington a finales del siglo pasado.

## Los costos no importan

Nadie ha puesto en duda la fortaleza de la decisión del MAS boliviano para revocar los resultados de la consulta popular sobre la reelección en 2016 y, durante los últimos meses, el partido oficial no ha hecho más que confirmar lo tonto que hubiese sido ponerlo en duda.

Más bien, ha querido reforzar el mensaje de que su decisión es inquebrantable y que los que la resistan puedan resultar lesionados, si es que no reducidos a añicos. Así ha de leerse que haya metido fuelle a los juicios ya instaurados contra políticos y dirigentes opositores, o la apresurada expulsión del Centro de Documentación e Investigación del Desarrollo (CEDIB) de su sede provisional en Cochabamba. El rector de la universidad estatal de ese distrito, amigo muy cercano del régimen, consiguió en pocos días intimidar de tal manera a los investigadores, que estos prefirieron quedar casi a la intemperie ante el inminente riesgo de violencia [^5].

El despliegue de fuerza siempre se ha complementado con el de un enorme flujo propagandístico estatal (y con los viajes del presidente), que hace un año había costado 5.300.000.000 Bs (cinco mil trescientos millones de bolivianos, unos 750 millones de dólares), durante el quinquenio previo [^6]. De modo que, considerando la intensificación de campañas favorables a la reelección y descalificadoras del triunfo del No el año pasado, la cifra, conservadoramente actualizada para este año, sobrepasará los 900 millones de dólares para el periodo que viene desde 2011.

La considerable dificultad de siquiera acercarse a estos montos para poder competir —principalmente en anuncios y transmisiones de radio, TV y, cada vez más intensamente, en presencia en las redes sociales virtuales—, se equilibró en esta ocasión con un enorme despliegue callejero para conmemorar la celebración de los resultados del 21F.

La superioridad de la concurrencia popular a los actos de reafirmación del No se verificó incuestionablemente en La Paz y otras ciudades, mientras que la de Santa Cruz de la Sierra resultó un fiasco, debido a que la convocatoria no se unificó y hubo actos dispersos. La ventaja de contar con la participación obligada de empleados públicos no fue suficiente para que el MAS reedite la convocatoria aplastante que ha mantenido por años en sus
actos; en esta ocasión debió resignarse a un segundo lugar.

Una característica notable de esa jornada de movilizaciones es que fue convocada y protagonizada por colectivos ciudadanos, en tanto que los partidos opositores que aportaron efectivamente con asistentes permanecieron en un discreto segundo plano. Se trata de una señal adicional que apuntala la necesidad de un cambio fundamental en el sistema de representación política [^7].

La preocupación oficial por este hecho no mella su plan inicial, y solo fortalece —como ya ocurría previamente— su predisposición a favorecer las cuatro alternativas no electivas del menú que maneja para desconocer el referendo del 21 de febrero.

## La artillería económica

A pesar de la ya anotada dificultad de recuperación de los precios del petróleo, la política económica oficial sigue ostentando las mejores marcas continentales [^8], incluso cuando es vista con los criterios más conservadores de los organismos internacionales, como la CEPAL [^9], que pronostica un crecimiento del PIB del 3,8%, casi un punto por debajo de la expectativa del ministro Arze. El ministro se arriesga a sostener que se llegaría al 4,7%, encendiendo explícitamente las expectativas sobre el pago del segundo aguinaldo al concluir la gestión.

Es ostensible el esfuerzo gubernamental por mantener el buen récord de cifras, que lo ha llevado a endeudarse por la vía de una nueva emisión de bonos (deuda soberana) de 1.000 millones de dólares, principalmente para alivianar la rápida caída de reservas, según interpreta el expresidente del BCB Juan Antonio Morales, a costa de pagar intereses de unos 45 millones de dólares anuales.

Mantener una buena imagen de su manejo de las finanzas públicas (cuando Venezuela se hunde en la superinflación, Argentina no acaba de recuperarse y Brasil sigue estancado) es, en términos prácticos, crucial para los planes de reelegirse [^10]. También es un poderoso mensaje político, porque le permite mofarse de las previsiones opositoras que, cada año, tienden a cargar las tintas sobre los escollos que tendrá que sortear la política económica gubernamental.

El párrafo siguiente, de autoría de Gonzalo Chávez, uno de los analistas económicos críticos más conocidos, se inscribe en la línea de tales advertencias:

> *Para mantener el producto en torno del 4% al año a futuro, la política económica de corto plazo tiene muy pocos grados de libertad. Debe escoger entre rezar para que vuelvan a subir los precios de las materias primas o quemar ahorros interno y externo para mantener la burbuja de consumo. ¿Por qué después de 11 años de gobierno y haber gastado 60.000 millones de dólares extras (medio Plan Marshall a precios de hoy) no tenemos ninguna fuente adicional de ingresos externos que no sean los recursos naturales? Las exportaciones cayeron en torno de 4.000 millones de dólares y no hay ningún sector alternativo que puede darnos ni 50 millones de dólares. Pero como vivimos al día y lo que interesa es la política antes que la economía, se fuerza el modelo primario exportador, aunque esto signifique sacrificar el futuro. Claro, el pretexto de la conspiración del imperio siempre está disponible para ocultar errores internos de la fiesta del rentismo. Tal vez el ajuste del país a la realidad económica lo tendrá que hacer otro gobierno (véase: [http://chavezbol.blogspot.com/2017/04/cebando-el-carburador.html](http://chavezbol.blogspot.com/2017/04/cebando-el-carburador.html)).*

Además de la importancia electoral de mantener cifras de buen desempeño, está la necesidad de contar con una base para realizar las monumentales inversiones de la “agenda patriótica” (57.000 millones de dólares solo en energía, de los cuales 27.000 irían a megarepresas). La tendencia declinante del crecimiento de estos dos últimos años, la desaceleración general y el crecimiento del déficit fiscal (que ronda el 7%) no contribuyen a garantizar las enormes deudas que se necesitará contraer para ejecutar el programa planeado hasta el año 2025.

Para una apropiada valoración de la actual disposición de fuerzas y preferencias, debe anotarse que la actitud ante el desempeño del gobierno y la confianza que suscita han dejado de declinar, según lo muestran los primeros sondeos del año.

## Foto, democracia y silencio

La inesperada aparición de un manifiesto firmado y acompañado de la fotografía de los seis dirigentes opositores más publicitados [^11] ha dado pie a un espectáculo noticioso durante semanas, debido a su carácter sorpresivo y, sobre todo, a la campaña propagandística del vicepresidente, quien desafió a todos los signatarios a un debate, para luego condicionar el reto hasta eludirlo completamente.

La primera aparición conjunta y solidaria de los representantes partidarios se ha referido exclusivamente a cuestiones políticas (violaciones democráticas, persecución judicial a opositores, planes de reelección y cuestiones afines), pero no contiene una sola mención crítica al programa de gobierno, con su masivo plan de inversiones y la alta intensidad de acciones lesivas al ambiente que entraña (ampliación de la frontera agrícola, concesiones de tierras, megarepresas).

Se verifica de este modo que el gobierno mantiene la iniciativa y puede seguir alimentando la corriente central del debate público en torno a la reelección de su candidato, contando con respuestas puramente reactivas.

La ausencia de discusión desde las filas de los partidos opositores, así como del planteamiento de un modelo alternativo de desarrollo al que actualmente se ejecuta y preconiza, deja esa responsabilidad a individuos y organizaciones de la sociedad civil, con gran menoscabo de sus posibilidades de llegar al conocimiento del público en general [^12].

Las escaramuzas tácticas próximas —como la realización de nuevas elecciones judiciales— no brindan esperanza alguna de negociación fructífera entre las fuerzas parlamentarias, porque los esporádicos gestos oficiales de apertura no modifican cuestiones de fondo relacionadas con su determinación de preservar el control sobre el conjunto de los poderes estatales, pues esto les garantiza habilitar a su candidato y ganar las elecciones de 2019 [^13].

De tal modo, el avance inicial —es decir, que la oposición dejara de identificar la propia elección de los altos magistrados como el fondo del problema y considerara la selección de candidatos como el tema crucial— queda en punto cero [^14].
Como sinopsis, puede afirmarse que el tensionamiento de contradicciones continúa dando la fisonomía a la coyuntura de este cuatrimestre, y se perfila como tendencia central del proceso. En la oposición partidaria se advierte que el inicio de acciones conjuntas es el nuevo mecanismo para incrementar su eficiencia política y mejorar su entrenamiento en algunas acciones de fiscalización parlamentaria; sin embargo, mantiene una ausencia completa en el cuestionamiento estratégico y programático.

Sin vestigios de tregua en el horizonte, las protestas espontáneas y los movimientos sociales (entendidos como explosiones de insatisfacción, sin conducción política orgánica) siguen siendo los adversarios más probables y eficaces de un régimen cuyo perfil se reduce cada vez más al de un ente que proclama la estabilidad, la continuidad y la permanencia como sus mejores atributos, mientras exhibe una completa falta de capacidad para enmendar un giro cada vez más represivo y enfangado en la corrupción.

::: {style="text-align:right; font-weight: bold;"}
Mayo de 2017
:::

## Notas

[^1]: El vicepresidente de Bolivia se ha mostrado como uno de los más entusiastas voceros de esa interpretación, basada en el llamado fenómeno “populista” de los países avanzados. Véase: [https://n9.cl/vtg3s](https://n9.cl/vtg3s). Sin embargo, la globalización no es una conjura, un capricho ideológico, un gran pacto comercial internacional o la suma de todos ellos. Es la fase actual de desarrollo del capitalismo en todos sus planos y niveles: económico, cultural, político e ideológico. Se sustenta en los cambios tecnológicos aportados por la informática, las telecomunicaciones y la caída de las murallas mercantiles que aún sostenía la vigencia de un bloque soviético hasta los años ochenta. En esa misma época, China ya se había inscrito como nave principal de la globalización, en su condición de fábrica planetaria y reina de las inversiones transnacionales.  

[^2]: En el otro lado del espectro, se ha enfriado el impulso de formaciones como PODEMOS, en España, al influjo, probablemente de experiencias como las de Syriza, en Grecia, y del recrudecimiento de temores en el electorado al momento de decidirse por alternativas desconocidas. Habrá que ver si en Francia el salto de Melenchon sigue el mismo curso, una vez que perdió el acceso al ballotage.

[^3]: La gran cuestión que abre la consumación del Brexit no radica en los duros espasmos de la ruptura, que pueden extenderse por largo tiempo, sino en un balance más prolongado, en el que habrá que ver si el aislacionismo británico termina por encoger a esa potencia que, por sí misma y con sus aliados más próximos (nacidos de su mismo vientre: EE. UU., Canadá, Australia, etc.) ocupó gran parte del protagonismo de los siglos previos.

[^4]: Se manejan con mayor discreción situaciones como las de Perú, donde los tratos con Odebrecht arrojan sombras no solo sobre ex presidentes, sino sobre el actual mandatario, Pedro Pablo Kuzcynski.

[^5]: Este antecedente consagra el hecho de que las ONG dedicadas a cuestiones indígenas y al medioambiente son las más expuestas al severo escrutinio estatal, dispuesto a borrar a cualquiera que parezca sospechosa de contradecirlo. El expresidente de la Asamblea Constituyente del Ecuador ha analizado la persecución al CEDIB como una típica muestra de la regresión de los gobiernos “progresistas” del área (véase: [https://n9.cl/wx2zp](https://n9.cl/wx2zp)).

[^6]: Véase: [https://n9.cl/6z5p5](https://n9.cl/6z5p5)

[^7]: Que, tal como se ha señalado y argumentado en análisis previos, incluye a partidos, sindicatos, organizaciones sociales, ONG políticamente activas, medios masivos de difusión y otras instancias que, en la experiencia social boliviana concreta, intervienen como centros de emisión ideológica, formación y organización política.

[^8]: Igualada por Paraguay y superada solamente por República Dominicana y Panamá.

[^9]: Véase: [https://n9.cl/5l7n50](https://n9.cl/5l7n50)

[^10]: El duro rechazo popular para abrir la reelección en Paraguay (respaldada también de la bancada del expresidente Lugo) aparentemente no ha sido del mayor agrado del gobierno boliviano, advertido hace muchos meses por encuestas de que, en general, tampoco el público de nuestro país ve con los mejores ojos la prolongación indefinida de los gobiernos. De allí nace precisamente la idea de hablar de “repostulación”, buscando endulzar el término.

[^11]: Véase: [https://n9.cl/b4hv5r](https://n9.cl/b4hv5r)

[^12]: El seguimiento de una de las iniciativas gubernamentales, el tren bioceánico, muestra la enorme dificultad de materializar las gigantescas obras que conforman ese programa. Aunque desde hace más de un año los voceros oficiales anuncian un inminente avance, hasta ahora solo se ha conseguido la adhesión de Uruguay y Paraguay, pero no la de Brasil, que es quien tiene la real capacidad de decisión. El antagonismo entre el gobierno de Temer y el de Bolivia genera un escenario totalmente privilegiado de negociación para Brasil. Eso explica el inconsulto cambio de diseño del tren bioceánico, que ya pactó con Perú, y que excluye su paso por Bolivia. Decisiones internas bolivianas, como la aprobación de la Ley de la Coca, son consideradas por Brasil como auténticas agresiones (porque ante una presunta mayor oferta de coca y cocaína, esperan un alza correlativa de crímenes y violencia en su territorio) que entraban aún más las negociaciones. De ese modo, se alejan las posibilidades de que la gran agenda estratégica del gobierno boliviano pueda concretarse.

[^13]: Por ejemplo, conceder mayor participación al sistema universitario (vía CEUB) en la preselección de candidatos para las elecciones judiciales, pero manteniendo otras observaciones que llevan al exmagistrado del Tribunal Supremo de Justicia, Iván Lima, a considerar que los 21 millones de dólares que costará la elección judicial serán un desperdicio. Véase: [https://www.facebook.com/Ivanlimamagne/posts/10212604351646445](https://www.facebook.com/Ivanlimamagne/posts/10212604351646445)

[^14]: En las condiciones actuales de la coyuntura política y social, va cobrando cuerpo la discusión de si Bolivia puede reproducir en los próximos meses una dinámica parecida a la que se observa hoy en Venezuela, producto de la obstinación del régimen por desconocer los avances de sus contrarios y mantener un control cerrado de todas las fuentes y recursos de poder. Se trata, con seguridad, de una especulación fundamentalmente vacía, no solo por las históricas diferencias abismales entre ambas formaciones sociales, sino por las características que identifican a los sujetos sociales colectivos que definen en Bolivia la coyuntura y la construcción histórica del país. 