---
lang: es
format: 
  html:
    page-layout: article
---

# Censo, violencia y peleas intestinas {.unnumbered}

El segundo tercio del año ha transcurrido ostentando un primer plano en el que destaca un serpenteante discurrir de las desinteligencias internas del Movimiento al Socialismo (MAS), los logros económicos gubernamentales, principalmente en materia de comercio internacional y diversas disputas en torno a propiedad de la tierra y la coca, en las que se verifica el ascenso y multiplicación de episodios violentos. La decisión oficial de postergar el Censo, despunta como nuevo espacio de confrontación, en un contexto donde la continua descomposición de la Policía y la administración de Justicia, van de la mano con señales cada vez más potentes de que el Gobierno desiste de emprender la indispensable reforma de estas instituciones.

## Agridulce economía

Después de 16 años que el MAS conduce la política económica (restando el paréntesis entre fines de 2019 a 2020) puede verse que los análisis económicos adversos, con un enfoque catastrofista predominante, han terminado siéndole útiles, porque no alcanzan a entender y menos a explicar el comportamiento general de la economía del país, lo que favorece el exitismo oficial y el sostenimiento de ilusiones sociales.

Este cuadro se refuerza con el beneficio que recibe el campo gubernamental en este momento con las informaciones sobre la balanza comercial, anunciados por el presidente: “Volvemos a romper récords en materia económica (..). Hasta julio de 2022, el valor de nuestras exportaciones llegó a \$us8.275 millones, la cifra más alta en los últimos 30 años”.

Los datos del Instituto Nacional de Estadísticas (INE) señalan además que las importaciones a julio presentan un incremento de 41%, es decir 6.988 millones de dólares, cifra mayor en 2.031 millones a la registrada en igual período de 2021”. Los empresarios observan que el incremento se debe, casi por entero, a incrementos internacionales de precio y no a volúmenes exportados, que están estáticos o declinantes, como el gas.

Hay excepciones como el explosivo incremento de exportaciones de oro, con su casi nulo aporte impositivo y tremendo costo ambiental; mientras que lo más positivo de la situación es el ascenso de productos no tradicionales.

La cara oscura y las mayores amenazas que contrapesan lo anterior, se resumen en la avalancha del costo de importación de combustibles (las importaciones de estos productos aumentaron un 147,5%, hasta los 2.274,5 millones de dólares, cifra superior en 1.355 millones de dólares a los 919 millones de dólares registrados de enero a julio de 2021); el crecimiento acelerado de la deuda que, entre los 12 mil millones de dólares de la externa, más la interna de 38 mil millones de \$us, suponen un 80% del PIB; la magnitud del déficit fiscal arrastrado por cerca de una década. Estos problemas son tan complicados como que el 80% de los precarios empleos e ingresos de las familias bolivianas provienen de la economía “sumergida” [^ano_2022_2-1].

[^ano_2022_2-1]: Todas las cifras y datos están respaldadas en el anexo informativo digital que acompaña al boletín.

Una visión de conjunto del campo económico trasluce que las informaciones favorables no alcanzan a contrarrestar la desaceleración, altamente influida por una situación mundial caracterizada por impulsos inflacionarios, escasez de alimentos y combustibles y un alto nivel de incertidumbre derivada de la guerra entre Rusia y Ucrania, tanto como por el incremento de tensiones entre China y EEUU.

Más allá de lo coyuntural, está el declive general de las variantes y parches al modelo desarrollista, basado en la extracción de recursos naturales y el industrialismo arcaico que trata de subsanarlo, cual venimos ensayando por casi ocho décadas.

En los últimos meses se ha hecho patente que tres de los mayores proyectos industrializadores de la administración de Arce Catacora, reiteran o empeoran las fallas y problemas de previos megaproyectos masistas. El de una nueva planta de fertilizantes, con el doble de costo que tuvo la de Bulo Bulo, no está respaldado por estudios técnicos indispensables y parece sencillamente inviable por la languideciente producción de gas y capacidad financiera del país. Mientras que los de una planta de producción de biodiesel y otras de reciclamiento de aceites usados enfrentan serias observaciones técnicas y ambientales (la de biodiesel), incluyendo conflictos de intereses y dudosas escalas de precios y de beneficios esperados.

En todos los casos la opacidad e insuficiencia de la información que publican las fuentes oficiales, incrementan la susceptibilidad ante la apertura de grandes oportunidades para nuevas tramas de corrupción. Esta percepción resulta fuertemente alentada por nuevas noticias de salarios suntuosos para burócratas sindicales, igual que para gerentes de empresas como la planta de urea o la todavía no funcionante Gestora de pensiones.

## Mas dentelladas que sana sana

Con todas sus contradicciones e incógnitas del futuro a mediano, e incluso a corto plazo, el desempeño económico ha fortalecido la aceptación y aprobación del presidente, provocando un visible desagrado de las corrientes más cercanas a Evo Morales Ayma.

Aparentemente esta franja de dirigentes y operadores políticos teme que Arce C. incumpla su promesa de no buscar la reelección y pueda imponerse como candidato, si las elecciones nacionales se realizan como está previsto en 2025.

Los varios intentos de la dirigencia del MAS por presentar una imagen cohesionada no han conseguido en ningún momento apaciguar el brote de enfrentamientos y ataques mutuos. El más exitoso, que hubo pudo congregar a Morales, Choquehuanca y Arce en una reunión conjunta, y logró un apaciguamiento, no exento de turbulencias, que duró pocas semanas que ha vuelto a quebrarse aparatosamente en Cotoca, en un acto proselitista el 29 de agosto. Al final del encuentro, Morales Ayma denunció públicamente, el robo de su celular y otros dos aparatos de “su asistente”, sugiriendo que el ministro de Gobierno también presente en la reunión, sería responsable, al menos por omisión.

La reignición de las brasas que se habían estado sofocando, reitera que el expresidente no soporta la resistencia de Arce a deshacerse del titular de la cartera de Gobierno, quien al lado de los responsables de los despachos de Justicia y Economía conforma el más estrecho círculo de confianza del mandatario.

El área más sensible donde explotan los choques y rencillas de Morales con el ministro de Gobierno es la Policía, atravesada por escándalos que muestran la complicidad de altos jefes y oficiales con bandas de delincuentes, lo que es explotado alternadamente por los bandos enfrentados del MAS, que promueven denuncias o destapes de corrupción de un jefe, o un grupo de ellos, acusando a sus rivales, masistas como ellos, de beneficiarse con los tratos ilícitos que salen a la luz pública.

El hecho de que Arce mantenga a sus dos ministros más cuestionados (Gobierno y Justicia) en sus puestos, acorta la vitalidad y duración de las treguas y exaspera al bando pro evista, que interpreta la obstinación y desplantes del presidente como actos de insubordinación y deslealtad del Gobierno actual frente a la autoridad de Morales que, a su entender, tendría que ser inalienable e imprescriptible.

Los choques partidistas ensanchan el potencial de poder de los dirigentes de organizaciones sociales, al darles la oportunidad de intervenir como árbitros o agentes dirimidores; pero, como se apuntó en el boletín anterior, las cúpulas mayores temen y vacilan intervenir directamente. En cambio, en instancias intermedias, como la directiva de los Ponchos Rojos, organización campesina arraigada en el altiplano norte, o en regiones de Santa Cruz, donde aumentan los problemas entre colonizadores y campesinos establecidos en esas zona, se observa una fuerte tendencia a tratar de explotar la ocasión que ofrece la coyuntura.

## Tierra y coca

La producción de coca y las movilizaciones de este sector social -especialmente al de Chapare- que le permitieron compactar el núcleo hegemónico del bloque social popular impulsor del proceso constituyente, están ahora en el centro de un conflicto radicado en los Yungas de La Paz, desde que se aprobó la Ley general de la coca en 2017.

La molestia que produjo el aumento del nivel autorizado de producción en Chapare derivó en discrepancias internas en Yungas, con la división de las bases de la Asociación Departamental de Productores de Coca de La Paz(ADEPCOCA) entre un grupo minoritario, francamente apegado al oficialismo, y las directivas que optan por una posición sindical independiente.

Desde ese momento los no alineados han sufrido embates en tres frente; 1) el control del mercado legal, así definido por la ley de la coca; 2) el estímulo gubernamental a la división organizativa de ADEPCOCA, patrocinando al sector disidente y 3) la represión, tanto a dirigentes no alineados con el oficialismo, como a las bases que defienden, en La Paz, el mercado, construido con los fondos sindicales de ADEPCOCA.

El control del mercado de la coca proveniente de Yungas es el corazón de la disputa, en un contexto de factores que presionan a la baja los precios de coca. Los tres países andinos que están a la cabeza de la producción de hoja de coca son Colombia, que alcanzó en 2021 una superficie de 143.000 hectáreas, Perú supera las 61.000 y Bolivia que ha superado largamente las 22.000 que fija la ley como tope y se encontraría, según EEUU entre 39.700 Has, mientras NNNU señala 29.400.

Tradicionalmente la hoja de coca boliviana ha cotizado a precios al menos 3 veces mayor a la colombiana y peruana, pero el gran avance de superficie y productividad genera una superproducción y contrabando que está deprimiendo los precios, factor que estimula la violencia de los choques entre los cocaleros de Yungas.

La misma tendencia, agravada por la formación de comandos civiles armados, e inclusive milicias, ha aparecido en disputas por tierra en Santa Cruz, particularmente en la provincia Guarayos y -sin reporte de grupos armados hasta ahora- en la región chiquitana. En la localidad de Pailitas, unas 200 personas armadas hicieron huir a los policías el 31 de julio.

Estas luchas tienen como objetivo principal participar y ampliar el mercado ilegal y altamente especulativo de tierras que no deja de ensancharse continuamente.

## Las reformas canceladas

La completa degradación policial y la importante afectación de las FFAA por la manipulación a gran escala ejercida por el Ejecutivo, estrecha los márgenes de control estatal efectivo y su capacidad de garantizar seguridad, ensanchando así los espacios de proliferación de choques violentos de civiles y la formación de grupos paramilitares y parapoliciales.

La conducción de los ministros clave, de Gobierno y Justicia, cierra las posibilidades de las transformaciones requeridas en la Policía y el Órgano judicial. El de Gobierno es hostigado por el ala evista del MAS que lo señala como encubridor de narcotraficantes y, en ese papel, de alentar jefes y grupos internos de la institución coludidos con los criminales.

El de Justicia, no ha avanzado en llevar adelante cambios urgentes propuestos por los expertos de la Corte Interamericana de Derechos Humanos y está comprometido en acciones de instrumentación de fallos favorables al régimen, con el precio de cerra los ojos ante el impetuoso avance de la corrupción de jueces y fiscales, al mismo tiempo que acaba de designar a 500 nuevos jueces con el mismo criterio y mecanismos que mantienen la partidización del aparato judicial y su permeabilidad completa ante los poderes políticos y económicos.

En este momento los problemas de la esfera política y judicial, marcan la tónica dominante. La oxigenación del Gobiernos por algunas cifras macroeconómicas es muy frágil y puede deteriorarse por las áreas adversas como la precariedad de las Reservas Internacionales y el endurecimiento de las condiciones y costos del endeudamiento.

Si a ello se agrega el incremento de la crispación política interna del MAS y los choques frontales con la oposición política, por cuestiones como la decisión oficial de imponer una demora del Censo Nacional, la consolidación política del Gobierno de Arce se ve más vulnerable todavía.

En esas condiciones, cualquier otro contratiempo, de la índole de nuevos choque entre sectores sociales, o protestas de las mismas bases del MAS (gremiales ante nueva legislación, por ejemplo), o contratiempos económicos, serán pruebas decisivas para verificar si el MAS puede realmente contener las peleas internas, como un reflejo de sobrevivencia, o si estas se desbordan y aceleran escenarios caóticos.

La posibilidad de que algún actor o sector oficial busque un rumbo diferente, ya sea sondeando caminos de aproximación con críticos, disidentes u opositores, o proponiendo una reconducción del modelo económico no asoma por ningún lado.

## Notas
