---
lang: es
format: 
  html:
    page-layout: article
---
# Cumbre de la hegemonía del MAS {.unnumbered}
---

Este segundo análisis de coyuntura del año se realiza en dos entregas: la actual y una segunda, que se elaborará después de realizadas las elecciones nacionales del 12 de octubre. De modo que en esta ocasión lo electoral merecerá una mención secundaria porque dicho asunto será abordado de forma exclusiva en la siguiente entrega

## El sistema de represemtación política

La inminencia de las elecciones concentra la atención colectiva en los partidos, predisponiendo a que se olvide la importancia de otros componentes del sistema de representación [^1]:. Sin embargo, en esta oportunidad el empeño exhibido por el gobierno para reclutar o consolidar el respaldo de diversas organizaciones sociales ha vuelto a poner de manifiesto su importancia como parte del funcionamiento del sistema.

La importancia que se le ha otorgado desde el bando oficial a la formalización de su alianza con la Central Obrera Boliviana (COB) ratifica la preocupación que le causaba la proliferación de señales sobre la sensación de discriminación que han estado experimentando varios sectores asalariados. Una de las causas es la distribución del excedente; la otra, el sesgo de las autoridades hacia grupos como los cooperativistas cuando sectores asalariados entran en conflicto con ellos.

El acuerdo suscrito con la COB y la cuota parlamentaria que le otorga busca reforzar el incremento salarial extraordinario, que significa repetir el pago del doble aguinaldo, para restañar heridas y mejorar la performance de votos que se busca entre los trabajadores que venden su fuerza de trabajo.

Tan o más importante es que el partido de gobierno busca cerrar, con el convenio político con la COB, el control que ostenta sobre las principales organizaciones sociales del país. Aunque nunca dejó de ejercer una considerable influencia sobre la mayor confederación sindical, la relación se había desgastado, y en algún momento llegó a ser manifiestamente tensa. Este es un pasivo que los estrategas de la reelección no querían arrastrar, pese a que, con toda probabilidad, están advertidos de que ni en sus épocas de mayor gloria la COB alcanzó a tener el predicamento necesario para ser un factor de peso sobre la decisión de voto de sus afiliados.

Después de haber reducido implacablemente las disidencias entre los indígenas, por ejemplo, mediante la persecución o la simple división, se ha apostado al valor simbólico de contar con el respaldo de la que en algún momento fuera la organización unitaria de los trabajadores.

Si se complementan las observaciones previas con las extraordinarias dificultades que encuentran todos los partidos y coaliciones de oposición para siquiera alcanzar presencia y organicidad efectivas en todo el territorio nacional —a lo que hay que agregar sus muy limitadas chances electorales, amén de la disminución de ONG críticas y el manejo de un enorme aparataje mediático—, vemos perfilarse una línea de horizonte en que el MAS, como partido dominante en lo electoral, hegemónico en lo ideológico y conductor de las direcciones de la mayoría de organizaciones sociales, consigue copar casi en su totalidad los canales del sistema de representación.

Esta situación incrementa en lo inmediato su capacidad de maniobra y control. Pero a la larga, y en cuanto se le presenten coyunturas desfavorables, se convierte en una importante vulnerabilidad, puesto que expone y amplifica las debilidades de una estructura construida principalmente con base a concesiones y licencias de corte corporativo, prebendal y clientelar. Este tipo de agregación de intereses se agrieta con relativa facilidad y predispone a la proliferación de manifestaciones de indisciplina.

## Señales de escasez

Es en la dimensión económica donde resulta más probable que se registren choques entre los muchos y heterogéneos intereses, ahora coaligados bajo la conducción gubernamental. Por lo tanto, ese el espacio en el que, de preferencia, se expresarán las posibilidades de nuevos giros y apertura del
abanico político.

Desde hace por lo menos tres años los organismos financieros internacionales vienen pronosticando descensos y frenazos en los países emergentes, que efectivamente se han cumplido, aunque por lo general con efectos menos intensos que los anunciados.

Se han ratificado, de manera unánime [^2], iguales presagios para el próximo año, con el agregado de que la tendencia a la baja del precio del petróleo y derivados se ha consolidado, pese a todas las turbulencias originadas en Oriente Medio y el conflicto de Ucrania. Esto tiende a impactar frontalmente a economías ultradependientes de la exportación de hidrocarburos. A ello se suma, en nuestro caso, el que ha traído la baja de cotizaciones de minerales.

Los problemas de las economías de Brasil y Argentina [^3] nos tocan muy de cerca debido a los múltiples vasos comunicantes que mantenemos con esos países.

Por estas razones, no cabe duda de que las turbulencias económicas constituirán el máximo reto para el plan de nueva reelección, eventualmente indefinida, que concentra la energía de las acciones gubernamentales a partir de su certeza de conseguir un triunfo rotundo en el torneo del 12 de octubre.

## Apertura de oportunidades

El desarrollo de la campaña electoral ha dado lugar a que cuestiones postergadas de la reforma intelectual y moral —que han sido parte significativa del proceso constituyente— recuperen actualidad e impulso. Tal es el caso de la lucha para contrarrestar y erradicar la violencia contra las mujeres (al alza en gran parte de América Latina), que ha saltado al primer plano como arma de agresión electoral. El carácter instrumental y altamente oportunista con que lo emplean los contendientes partidarios limita objetivamente la posibilidad de conseguir cambios drásticos a corto plazo.

Sin embargo, no debe subestimarse, y menos desperdiciarse, la sensibilización y relevancia que ha adquirido la cuestión, abriendo espacio a iniciativas que, desde la sociedad civil, incrementan la demanda de que los compromisos estatales para atender esta situación superen la superficialidad y el descuido actuales.

Lo mismo puede decirse de un tema muy vinculado al anterior: la explosión ampliada de los problemas que confronta la administración de justicia. El gobierno aborda el problema no exactamente priorizando la profunda insatisfacción social sobre esta cuestión, sino como una oportunidad para ajustar y blindar su completo control sobre el Órgano Judicial, el Ministerio Público y el Tribunal Constitucional. Debido a que las demandas sociales se contraponen francamente a dicho enfoque oficial, se pueden vislumbrar significativas oportunidades si se atienden, canalizan y apoyan tales expectativas sociales.

## Las fronteras de la consolidación hegemónica

La inminencia del triunfo oficialista, y la incapacidad esencial de sus contendores para enfrentarlo, subraya el auge de la potencia política e ideológica del MAS, que rebasa el plano de la conducción del gobierno y del Estado y se afirma en el espacio de las prácticas, creencias y comportamientos colectivos.

La ausencia de proyectos alternativos consagra la hegemonía [^4] del partido dominante, tanto respecto a la convergencia, unidad y representación efectiva de los intereses estratégicos del bloque dominante, cuanto a su capacidad de aparentar la representación del conjunto de la sociedad, incluyendo la de los sectores subalternos y oprimidos.

Pero, puesto que dicha hegemonía se ha montado sobre una narrativa y un lenguaje forjados en auténticas luchas populares, seguir representándolas, al mismo tiempo que se transgrede cotidianamente sus contenidos en diversos ámbitos [^5]:, lleva a que el ascenso hegemónico se vea socavado por incongruencias tan marcadas que configuran una temprana decadencia de la fortaleza y la moral del aparato político que ha sabido capitalizar la movilización y las expectativas populares.

Eso hace que sus planes para prolongar (de ser posible, indefinidamente) su ejercicio y control del poder pasen a ser su flanco más vulnerable en los siguientes meses.

::: {style="text-align:right; font-weight: bold;"}
Septiembre de 2014
:::

## Notas

[^1]: En un análisis anterior se ha desarrollado la idea de que dicho sistema involucra, en el caso boliviano, a diversas organizaciones corporativas, sindicales y sociales, además de algunas ONG, medios de difusión masiva y otros

[^2]: Véase: [https://n9.cl/xy6z3](https://n9.cl/xy6z3); también: [https://n9.cl/2u3lv](https://n9.cl/2u3lv); y, de la CEPAL, [https://n9.cl/i3av6](https://n9.cl/i3av6)

[^3]: Esta última, con muy altos niveles de incertidumbre por la rapidez de la evolución inflacionaria, la crisis de pago con los fondos buitre y la imprevisibilidad del resultado de la elección general del año próximo. El inesperado ascenso de Marina Silva en el Brasil también introduce algunos interrogantes para nuestra relación con ese país.

[^4]: Se emplea aquí la noción de hegemonía como “consenso activo”, es decir, la creencia de que cierta dominación es no solo inevitable, sino también necesaria e, incluso, deseable. Tal acepción es antagónica al uso del término 'hegemonía' como equivalente a 'imposición'.

[^5]: Participación y control social, transformación productiva, descentralización, autonomía, autogobierno y desarrollo armónico con la naturaleza, para citar algunos de los vacíos y mayores contradicciones en la transformación iniciada.