---
lang: es
format: 
  html:
    page-layout: article
---

# Pugnas sociales en era de pandemias {.unnumbered}

La ceguera es una manifestación, no descrita, ni atribuida en estudios, tratados o partes médicos, al SARS-CoV-2 (nombre oficial del virus causante de la pandemia de Covid-19). Sí lo son: la fiebre, la tos seca, la fatiga, la dificultad respiratoria, la pérdida de los sentidos del olfato y del gusto y, menos frecuentemente, algunas molestias gastrointestinales.

Sin embargo, todo lo que ignoramos sobre el virus ---pueden ser sus mutaciones genéticas, el conjunto de su acción sobre el organismo humano, en especial sobre el sistema inmunitario, los patrones y tendencias epidemiológicas que lo caracterizan--- está prácticamente sumergido en la mayor oscuridad, incluso para los especialistas más avanzados y experimentados [^ano_2020_1-1]. En consecuencia, esas lagunas o mares desconocidos funcionan como una verdadera venda que obstruye nuestra visión, incrementa nuestra ansiedad y nos lleva muchas veces a actuar a ciegas, individual y colectivamente.

[^ano_2020_1-1]: Véase: <https://n9.cl/iyw9a>; <https://n9.cl/e7x9g>; <https://n9.cl/pm2yc>; <https://n9.cl/k4dh3>; <http://ddi.sutd.edu.sg/>; <https://n9.cl/kfkpd>; <https://n9.cl/qrjmd>

Nuestro país, que ostenta el dudoso mérito de estar entre los países del continente que realizan menos pruebas diagnósticas y casi ningún seguimiento de contactos, está ingresando en una nueva fase de enfrentar la crisis sanitaria con los ojos literalmente cerrados [^ano_2020_1-2].

[^ano_2020_1-2]: Véase: <https://n9.cl/ap0ac>. Esta deficiencia se debe, en parte, a la escasez de test y reactivos de laboratorio, pero también a un denso y obtuso burocratismo estatal.

## Ingresos que caen

Los apresurados y a veces terroríficos vaticinios que emiten filósofos, analistas, expertos y augures de todo pelaje, ya sea en tono ultraoptmista, anunciando que el mundo cambiará positivamente y el coronavirus sofocará al capitalismo, o, en el otro extremo, que nos hundiremos en un lóbrego pozo de desocupación, hambre y salvajismo [^ano_2020_1-3], se basan en intuiciones, estados de revelación metafísica o deducciones, pero casi nunca en hechos verificables.

[^ano_2020_1-3]: Véase: <http://tiempodecrisis.org/wp-content/uploads/2020/03/Sopa-de-Wuhan-ASPO.pdf>; <https://n9.cl/5l8yi>; <https://n9.cl/q8wzp>

En realidad, es difícil encontrar visiones prospectivas convincentes y fundamentadas, o siquiera en pistas que sugieran lo que depara el futuro, ante tantas incógnitas no resueltas que ha traído la pandemia.

Entre lo que sí sabemos con suficiente certeza figura la dramática caída de disponibilidad de recursos para la mayor parte de los actores y sujetos sociales nacionales [^ano_2020_1-4]. La recuperación de la actividad comercial y de las importaciones ---frenadas en seco por las cuarentenas en el nuestro y en varios otros países y, más importante, la todavía no cuantificada mella en la producción de bienes y servicios--- lastrarán aún más su recuperación.

[^ano_2020_1-4]: Es decir, más del 70% de nuestra población, que sobrevive inventando y realizando actividades económicas usualmente calificadas de "informales".

En otras palabras, el temido retorno a la pobreza de las familias e individuos que la superaron en la década de los superprecios de las materias primas se ha adelantado y masificado en nuestro continente, así como en todos los países que alcanzaron éxitos en reducir la pobreza al inicio de este siglo [^ano_2020_1-5].

[^ano_2020_1-5]: Véase: <https://www.sandiegouniontribune.com/en-espanol/noticias/story/2020-04-09/pandemia-puede-arrojar-a-500-millones-a-la-pobreza>; <https://n9.cl/83hp1>

El propio Estado ya está experimentando el estrangulamiento de recursos externos, debido al inédito derrumbe de los precios del petróleo y sus derivados, así como de minerales y otros commodities. Su recuperación durante los siguientes meses es incierta [^ano_2020_1-6]. En consecuencia, la estrechez en las transferencias que oxigenan las arcas de gobernaciones, municipios y universidades [^ano_2020_1-7] se mantiene, y se agudizará al menos por varios meses.

[^ano_2020_1-6]: Véase: <https://cnnespanol.cnn.com/2020/04/30/puede-que-el-mundo-nunca-recupere-su-sed-de-petroleo/>

[^ano_2020_1-7]: Véase: <https://www.la-razon.com/economia/2020/04/21/cepal-baja-proyeccion-crecimiento-bolivia-3-covid-19/>

A lo afirmado se agregará el costo de las medidas destinadas a contener la pandemia. Una fracción de ellas proviene de las erogaciones para pagar los salarios de todos los servidores públicos, incluyendo la frondosa alta burocracia, durante el período de cuasi parálisis en el funcionamiento de la mayoría de las instituciones públicas.

Los ahorros mencionados por la cartera de Economía y por el Banco Central, debido al importante recorte de volúmenes y precios de productos, como combustibles y otros rubros, difícilmente equilibrarán las erogaciones. Por ello, manejar el incremento de un déficit fuertemente impulsado por la situación será una variable adicional a los problemas.

Lo que queda muy claro es que la mayor parte de la población económicamente activa, incluyendo las empresas formales, privadas y públicas, lidiarán con adversidades importantes, cuyo horizonte de resolución se encuentra por ahora sumergido en la penumbra.

Las tensiones que implica lo anterior, desde este momento de forzada inacción de la mayor parte de la sociedad, se combinarán en la fase de reapertura y flexibilización con un estado de ánimo colectivo en el que se mezclen el temor ante la incertidumbre con vetas de frustración, malhumor y rabia. Todo ello puede empujar a la desesperación a diversos colectivos y sectores.

## Planes de ractivación y pugna política

En diciembre de 2019 se caracterizó, en el boletín de análisis correspondiente, al gobierno interino como representativo de los socios económicos del régimen masista y, más concretamente, de los vinculados al agronegocio y a la financiera [^ano_2020_1-8].

[^ano_2020_1-8]: Véase: <https://n9.cl/q0wtk>; <https://n9.cl/dqb0h>; <https://n9.cl/xx6tk>; <https://n9.cl/j36hm>; <https://n9.cl/938mr>; <https://n9.cl/823ie>; <https://n9.cl/jnluw>; <https://n9.cl/bcxnr>; <https://n9.cl/n985a>; <https://n9.cl/bz960>

El programa de reactivación económica presentado por los ministerios de Economía y de Desarrollo Productivo corrobora esa caracterización ya que, salvo las indispensables medidas de apoyo y alivio de emergencia, calca el pliego petitorio de la Confederación Agropecuaria de Oriente (CAO) y de la de Industria y Comercio (CAINCO). Estas afirman que será posible poner en pie la economía nacional incrementando los estímulos a la agroindustria tradicional y a los productos ganaderos exportables, e incrementando el área dedicada a biocombustibles.

Esta demanda empresarial ha sido inmediatamente ratificada y respalda por los antiguos colonizadores (hoy pequeños y medianos soyeros) que ocupan tierras bajas del este y parte del Norte Integrado en Santa Cruz [^ano_2020_1-9] y que, junto con los colonizadores cocaleros del Chapare, componen el núcleo hegemónico del MAS.

[^ano_2020_1-9]: Véase: <https://n9.cl/eba8q>

La magnitud y la premura de los requerimientos de estos grupos económicos queda patente en la cifra que exigen les provea el Estado para remontar la emergencia y la crisis. Sus demandas sectoriales sobrepasan el total de recursos que el gobierno de Añez ha programado para dar apoyo a todos los sectores empresariales del país, entre grandes, pequeños y medianos, y cualquiera sea el rubro en que se desempeñen [^ano_2020_1-10].

[^ano_2020_1-10]: Véase: <https://n9.cl/oyiyl>

Pero no se trata solamente del manejo de reivindicaciones y propuestas de planes, sino de que la temprana expansión de focos de calor en el oriente boliviano, embriones de grandes incendios, auguran que una gran quema, como la del año pasado, está en vías de ocurrir [^ano_2020_1-11], ante la completa indiferencia e inacción estatal, demostrando la implacable angurria de estos intereses.

[^ano_2020_1-11]: Véase: <https://n9.cl/ncloh>; <https://n9.cl/xafno>; <https://n9.cl/1tkh7>

Los planes de expansión de la frontera agrícola para transgénicos y biocombustibles, y posiciones como de la propia presidente, quien avaló el plan del uso del suelo (PLUS) del gobernador masista del Beni, desoyendo los reiterados reclamos indígenas [^ano_2020_1-12], no dejan duda sobre el origen e intenciones del gobierno interino.

[^ano_2020_1-12]: Véase: <https://n9.cl/abtck>

Su política mantiene intacta la amenaza que heredamos del MAS sobre las tierras fiscales, las reservas naturales, los parques nacionales y los territorios indígenas. Y es que los incendios abren las puertas a los avasallamientos, que preceden al intenso tráfico de estas tierras. Este comercio es el mecanismo con el que los grandes exportadores subsidian la pobre productividad de los cultivos industriales, propia del modelo agropecuario vigente en nuestro país.

La promesa de que semejante esquema productivo nos permitirá recuperarnos y avanzar a la prosperidad olvida maliciosamente que las economías de nuestros vecinos Brasil y Argentina han llevado a su extremo el modelo de la agroindustria de exportación, el monocultivo, los transgénicos y los agrotóxicos, y que la fortaleza de estos dos países se manifiesta cada día más claramente erigida sobre pies de barro y afligida por el retorno masivo de la pobreza y la inseguridad.

En el espacio de la disputa abierta por el poder político, que en este momento concentra exclusivamente la atención de individuos y grupos profesionalizados en esa actividad, el manejo de las masivas cantidades de recursos públicos, propio de una situación de emergencia, parece operar como un potente estímulo adicional de los apetitos del MAS, aparentemente desesperado por preservar la significativa ventaja que hasta marzo le atribuía la mayor parte de los sondeos sobre intención de voto.

Bajo el supuesto de que mantendría esa preeminencia, o de que la está ensanchando por los errores del gobierno, ha lanzado una ofensiva propagandística y de desacato de los confinamientos sanitarios, tratando de forzar que se concrete una fecha próxima para la realización de elecciones [^ano_2020_1-13].

[^ano_2020_1-13]: Esta situación cada vez más favorable al MAS no se ha detenido desde diciembre de 2019. Es impermeable a las nuevas y graves denuncias sobre ilegalidades cometidas por el anterior régimen, incluyendo la muy debilitada situación en que quedó el sistema nacional de salud pública, a pesar de las ostentosas campañas sobre el seguro único de salud y la inauguración de varias obras hospitalarias que resultaron inútiles o quedaron inservibles muy rápidamente. En el siguiente enlace se observa un resumen de los resultados de cinco encuestas de intención de voto llevadas a cabo entre febrero y marzo pasado: [https://estotambiensucede.net/index.php/2020/03/12/fundacion-ebert-difunde-proyeccionesde-bolivia-electoral/](https://estotambiensucede.net/index.php/2020/03/12/fundacion-ebert-difunde-proyecciones-de-bolivia-electoral/). La empresa Ciesmori ha realizado un par de muestreos durante la cuarentena, según los cuales la ventaja se estaría volcando a favor de Añez.

Si en diciembre se vislumbraba que el MAS podía ganar la primera vuelta, pero no en primera vuelta, con las cifras de las encuestas de hace dos meses y la deriva de la coyuntura, esa última posibilidad empieza a tomar fuerza.

La ofensiva presente del MAS resulta estimulada por las acciones del gobierno provisional, cuya actitud parece basarse en el aparente supuesto ---seguramente errado--- de que las medidas de emergencia sanitaria y las ayudas económicas a diversos sectores incrementarían su chance de ganar las próximas elecciones [^ano_2020_1-14].

[^ano_2020_1-14]: Si se mantiene la última posición oficial, expresada por su ministro de Salud en sentido de que no cabe sino resignarse ante las muertes y el avance de los contagios hasta alcanzar la inmunidad de rebaño, enfrentamos el riesgo de que el descontrol sanitario que ahora se observa en Beni se convierta en tendencia dominante.

La manifiesta tendencia gubernamental a mantener la judicialización de la política, junto con una actitud proclive al verticalismo y la represión antes que al diálogo y los acuerdos, son también mecanismos con que se alienta el fortalecimiento del MAS.

La pugna entre la presión masista por adelantar las elecciones y la resistencia gubernamental ante ella no da señales de encontrar eco en la población, que se muestra más bien indiferente ante este ruidoso tironeo.

La reconquista del manejo de dos tercios de votos en la Asamblea Legislativa por el MAS, que ya se manifestó con la censura al ministro de Defensa, es un indudable resultado de la manera descuidada y altanera con que el gobierno ha tratado a los legisladores masistas, con quienes le fue posible iniciar la pacificación del país y aprobar leyes clave como la de convocatoria a elecciones. La preservación de una relación abierta y de consulta pudo cerrarle el paso al objetivo del MAS de reconquistar el control de su bancada, pero el gobierno interino abandonó esa tarea.

Gracias a ello se amplifica la debilidad institucional del gobierno provisional, puesta casi exclusivamente en las manos del Tribunal Constitucional (TCP) [^ano_2020_1-15] y las FF. AA., al mismo tiempo que se observa una recuperada, pero aun volátil, unidad del MAS.

[^ano_2020_1-15]: Se desconocen los términos del armisticio entre los miembros del TCP, elegidos con el patrocinio del MAS, y el actual Ejecutivo, aparentemente muy satisfecho con que ese organismo no objetara la legalidad de la actual presidencia. El actual gobierno ni siquiera se ha esforzado en reclamar que culminen las demandas para anular la anticonstitucional sentencia que habilitó la última candidatura de Morales Ayma.

Por vez primera después de un prolongado paréntesis, el candidato de Comunidad Ciudadana (CC) está intentando una acción política que busca recuperar iniciativa, al situarse explícitamente al margen de la confrontación entre el MAS y el grupo gobernante que forjó y lanzó la candidatura de Añez, implicando que se trata de una pugna mezquina y de alto riesgo colectivo en la situación en la que se desenvuelve la pandemia en el país y en ausencia de un acuerdo político.

La sola promulgación de la ley que fija fecha tope para las elecciones, en la amplificada situación de autonomía relativa de los aparatos de Estado, no garantiza su cumplimiento. Si no se producen cambios, podría terminar convirtiéndose en una muestra de impotencia y no en el gesto de fuerza que pretende el MAS.

Cuando se desconoce el número de personas infectadas con el coronavirus ---ya que sin pruebas ni seguimiento de contactos las estimaciones oficiales tienen un margen excesivo de error---, no son fantasiosas las hipótesis y modelaciones que advierten que los casos activos (incluyendo una probable mayoría de asintomáticos) multiplican holgadamente la cifra oficial de contagios [^ano_2020_1-16].

[^ano_2020_1-16]: Dos modelos que advierten la posibilidad de una mayor cantidad de contagios se encuentran en: <https://n9.cl/k4dh3>; <https://n9.cl/ve9i1>

Además, desconociendo si los pacientes recuperados tienen inmunidad temporal o permanente; ignorando si pueden ser ciertas las hipótesis, basadas en reincidencias y autopsias, de que este coronavirus en particular diezma las células inmunitarias, nadie puede garantizar las consecuencias del indispensable e inevitable levantamiento de las cuarentenas.

## Enfrentando la adeversidad y la incertidumbre

La lucha frontal y prioritaria por la salud y un vigoroso y eficiente sistema sanitario público [^ano_2020_1-17] que la resguarde es hoy parte medular de una plataforma unitaria de la sociedad civil. Esta necesita propuestas para cambiar las matrices productiva y energética como un camino obligatorio para encarar la recuperación económica.

[^ano_2020_1-17]: El cobro de tarifas exorbitantes y especulativas por clínicas privadas hace imperativo adoptar medidas similares a las que tomó el gobierno de Irlanda, al obligar a los centros privados a ponerse bajo el mando y normas del sistema público sanitario.

Para dicha recuperación hay que tener en cuenta que, si bien la deuda externa era impagable en la década de 1980, hoy nos encaminamos aceleradamente a una situación en que pagarla resultará material y moralmente insoportable e insostenible.

Se necesita construir nuevas bases económicas a partir de incrementa la producción de alimentos, de abandonar las técnicas depredadoras de tierras, aguas, bosques y biodiversidad que ahora predominan; de cimentar una industria de turismo que duplique o triplique el flujo de visitantes (cerca de un millón el año 2019) [^ano_2020_1-18] , y de sustituir las exportaciones de gas y minerales. En suma, un viraje a formas de bioeconomía (economía verde y naranja) ocupan un lugar fundamental en la reconstrucción de la economía y las relaciones sociales.

[^ano_2020_1-18]: Este turismo debe alejarse de los moldes y operadores tradicionales de turismo (golpeados frontalmente por la pandemia). Esto supone garantizar la intangibilidad de reservas naturales, parques nacionales y territorios indígenas, con absoluta prohibición de quemas y desmontes, porque el principal atractivo que tenemos para ofrecer al mundo es una naturaleza preservada y culturas capaces de sostener un equilibrio con ella.

Estas búsquedas se darán mediante el rescate de las formas de actuación social directa. Las dificultades económicas se convertirán en impulsos de reactivación de exigencias de descentralización y fortalecimiento de autonomías regionales y sociales. Sin embargo, una seria desventaja para conseguirlo es que la renovación y democratización de las organizaciones sociales secuestradas y descompuestas por el régimen masista no da señales de resolverse en un futuro cercano.

El descontento de médicos y personal sanitario debido al incumplimiento constante de compromisos de pago de salarios, de dotación de trajes e implementos de bioseguridad, de incremento de pruebas y mapeo de contactos, así como la multiplicación de contagios entre el personal de primera línea (incluyendo a policías y militares), tiende a abrir paso a una situación de descontrol gubernamental. Esta se vería empeorada por la apuesta del gobierno de mezclar la gestión con la promoción de la candidatura de la presidenta. La demanda de declinación de dicha candidatura tomará impulso al compás de los desaciertos oficiales y, especialmente, de sus impactos en el manejo de la crisis sanitaria.

La coyuntura tiende a caldearse bajo el impulso de la ofensiva masista en los frentes parlamentario y callejero. A ello se añade la cada vez más rápida sucesión de señales de corrupción (ENTEL, YPFB, el manejo de nombramientos para altos cargos), abusos de poder y reticencia al diálogo.

El gobierno interino se inclina a exhibir un estilo y recursos similares a los de sus predecesores, con la importante diferencia de que carece de la legitimidad, la organización y la tolerancia social de la que disfrutó el régimen previo.

Todo lo anterior refuerza y multiplica las amenazas de proliferación de escenarios de enfrentamiento social y político. Prácticamente cualquier go- bierno (incluyendo ciertamente uno del MAS) que sea elegido y mantenga la misma visión, modelo económico social y prácticas del régimen masista y del actual, tendrá un horizonte de vida que, generosamente, no superará los dos años.

En todo el mundo se alzan voces que reclaman virajes de fondo en la ma- nera deconstruir la sociedad y de relacionarnos con la naturaleza y los demás seres vivos. La reactivación económica debería servir para abrir espacio a modelos alternativos de desarrollo y eludir las amenazas de descargar la crisis sobre las espaldas de los abandonados y desprotegidos habituales [^ano_2020_1-19].

[^ano_2020_1-19]: Véase, por ejemplo: <https://n9.cl/tzlie>; <https://n9.cl/6on2u>

Los combates por no quedar condenados a la sobrevivencia desesperada y por no ser nuevamente las víctimas de ajustes concebidos bajo las fórmu- las y esquemas tradicionales y arcaicos, necesitarán combinarse con accio- nes frontales y decisivas para enfrentar el cambio climático y dejar atrás los patrones sociales, universalmente prevalecientes, que han originado y están disparando la gran crisis global que atravesamos y la posibilidad de que esta se repita periódicamente.

::: {style="text-align:right; font-weight: bold;"}
Mayo de 2020
:::

## Notas
